# Translations template for cinder.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the cinder project.
#
# Translators:
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011
# Zbyněk Schwarz <zbynek.schwarz@gmail.com>, 2015
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: cinder VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2019-01-11 16:51+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-04-12 06:05+0000\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language: cs\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 4.3.3\n"
"Language-Team: Czech\n"

#, python-format
msgid "\t%s"
msgstr "\t%s"

#, python-format
msgid ""
"\n"
"OpenStack Cinder version: %(version)s\n"
msgstr ""
"\n"
"OpenStack Cinder verze: %(version)s\n"

#, python-format
msgid " but size is now %d"
msgstr "ale velikost je nyní %d"

msgid " or "
msgstr "nebo"

#, python-format
msgid ""
"%(driver)s manage_existing cannot manage a volume connected to hosts. Please "
"disconnect this volume from existing hosts before importing"
msgstr ""
"%(driver)s nelze spravovat existující svazek připojený k hostitelům. Před "
"importem ho prosím odpojte od existujících hostitelů."

#, python-format
msgid ""
"%(err)s\n"
"result: %(res)s."
msgstr ""
"%(err)s\n"
"výsledek: %(res)s."

#, python-format
msgid "%(exception)s: %(explanation)s"
msgstr "%(exception)s: %(explanation)s"

#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"%(fun)s: selhalo s nečekaným výstupem příkazového řádku.\n"
"Příkaz: %(cmd)s\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s"

#, python-format
msgid "%(host)-25s\t%(availability_zone)-15s"
msgstr "%(host)-25s\t%(availability_zone)-15s"

#, python-format
msgid "%(host)-25s\t%(zone)-15s"
msgstr "%(host)-25s\t%(zone)-15s"

#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""
"%(message)s\n"
"Kód stavu: %(_status)s\n"
"Tělo: %(_body)s"

#, python-format
msgid ""
"%(msg_type)s: creating NetworkPortal: ensure port %(port)d on ip %(ip)s is "
"not in use by another service."
msgstr ""
"%(msg_type)s: vytváření síťového portálu: ujistěte se, že port %(port)d na "
"ip adrese %(ip)s nepoužívá jiná služba."

#, python-format
msgid ""
"%(op)s: backup %(bck_id)s, volume %(vol_id)s failed. Backup object has "
"unexpected mode. Image or file backups supported, actual mode is "
"%(vol_mode)s."
msgstr ""
"%(op)s: záloha %(bck_id)s svazku %(vol_id)s selhala. Objekt zálohy má "
"neočekávaný režim. Podporovány jsou zálohy obrazu nebo souborů, současný "
"režim je %(vol_mode)s."

#, python-format
msgid "%(service)s Service is not %(status)s on storage appliance: %(host)s"
msgstr ""
"Služba %(service)s není ve stavu %(status)s v zařízení úložiště: %(host)s"

#, python-format
msgid ""
"%(worker_name)s value of %(workers)d is invalid, must be greater than 0."
msgstr ""
"Hodnota %(worker_name)s ve %(workers)d je neplatná, musí být větší než 0."

#, python-format
msgid ""
"%s cannot be accessed. Verify that GPFS is active and file system is mounted."
msgstr ""
"Nelze získat přístup k %s. Ověřte, zda GPFS je aktivní a že systém souborů "
"je připojen."

#, python-format
msgid "%s cannot be resized using clone operation as it contains no blocks."
msgstr ""
"nelze změnit velikost %s pomocí operace klonování, protože neobsahuje žádné "
"bloky."

#, python-format
msgid ""
"%s cannot be resized using clone operation as it is hosted on compressed "
"volume"
msgstr ""
"nelze změnit velikost %s pomocí operace klonování, protože je umístěn na "
"komprimovaném svazku"

#, python-format
msgid "%s configuration option is not set."
msgstr "Konfigurační volba %s není nastavena."

#, python-format
msgid "%s is not a directory."
msgstr "%s není adresář."

#, python-format
msgid "%s is not installed"
msgstr "%s není nainstlaováno"

#, python-format
msgid "%s is not installed."
msgstr "%s není nainstalováno."

#, python-format
msgid "%s is not set"
msgstr "%s není nastaveno"

#, python-format
msgid "%s is not set."
msgstr "%s není nastaveno."

#, python-format
msgid "%s must be a valid raw or qcow2 image."
msgstr "%s musí být platný obraz raw nebo qcow2."

#, python-format
msgid "%s must be an absolute path."
msgstr "%s musí být absolutní cesta."

#, python-format
msgid "%s not set in cinder.conf"
msgstr "%s není nastaveno v cinder.conf"

#, python-format
msgid "%s not set."
msgstr "%s není nastaveno."

#, python-format
msgid ""
"'%(prot)s' is invalid for flashsystem_connection_protocol in config file. "
"valid value(s) are %(enabled)s."
msgstr ""
"'%(prot)s' v souboru nastavení je neplatný pro protokol připojení k "
"flashsystem. Platné hodnoty jsou %(enabled)s."

msgid "'active' must be present when writing snap_info."
msgstr "při zápisu informací o snímku musí být přítomno 'active'."

msgid "'consistencygroup_id' must be specified"
msgstr "'consistencygroup_id' musí být zadáno"

msgid "'qemu-img info' parsing failed."
msgstr "zpracování 'qemu-img info' selhalo."

#, python-format
msgid ""
"(Command: %(cmd)s) (Return Code: %(exit_code)s) (Stdout: %(stdout)s) "
"(Stderr: %(stderr)s)"
msgstr ""
"(Příkaz: %(cmd)s) (Návratový kód: %(exit_code)s) (Standardní výstup: "
"%(stdout)s) (Chybový výstup: %(stderr)s)"

msgid "A valid secondary target MUST be specified in order to failover."
msgstr "Pro zavedení záložního systému MUSÍ být zadán platný druhotní cíl."

msgid "A volume ID or share was not specified."
msgstr "Nezadáno ID svazku nebo sdílení."

#, python-format
msgid ""
"API Version String %(version)s is of invalid format. Must be of format "
"MajorNum.MinorNum."
msgstr ""
"Řetězec verze API %(version)s je v neplatném formátu- Musí být ve formátu "
"Hlavní číslo verze a Vedlejší číslo verze"

#, python-format
msgid "API response: %s"
msgstr "Odpověď API: %s"

#, python-format
msgid "API version %(version)s is not supported on this method."
msgstr "API s verzí %(version)s není v této metodě podporován."

msgid ""
"About to delete child projects having non-zero quota. This should not be "
"performed"
msgstr ""
"Chystáte se smazat podřazené projekty mající nenulovou kvótu. Toto by nemělo "
"být prováděno"

msgid "Access list not available for public volume types."
msgstr "Seznam přístupu není dostupný pro veřejné typy svazku."

msgid "Activate or deactivate QoS error."
msgstr "Chyba při aktivaci nebo deaktivaci QoS."

msgid "Activate snapshot error."
msgstr "Chyba při aktivaci snímku."

msgid "Add FC port to host error."
msgstr "Chyba při přidávání FC portu k hostiteli."

msgid "Add fc initiator to array error."
msgstr "Chyba při přidávání zavaděče fc do pole."

msgid "Add initiator to array error."
msgstr "Chyba při přidávání zavaděče do pole."

msgid "Add lun to cache error."
msgstr "Chyba při přidávání lun do mezipaměti."

msgid "Add lun to partition error."
msgstr "Chyba při přidávání lun do oddílu."

msgid "Add mapping view error."
msgstr "Chyba při přidávání zobrazení mapování."

msgid "Add new host error."
msgstr "Chyba při přidávání nového hostitele."

#, python-format
msgid ""
"All the specified storage pools to be managed do not exist. Please check "
"your configuration. Non-existent pools: %s"
msgstr ""
"Žádné ze zadaných zásob úložiště, které mají být spravovány, neexistují. "
"Prosím zkontrolujte své nastavení. Neexistující zásoby: %s"

msgid "An error has occurred during backup operation"
msgstr "Během operace zálohování nastala chyba"

#, python-format
msgid ""
"An error occurred during the LUNcopy operation. LUNcopy name: "
"%(luncopyname)s. LUNcopy status: %(luncopystatus)s. LUNcopy state: "
"%(luncopystate)s."
msgstr ""
"Při operaci kopírování LUN došlo k chybě. Název operace: %(luncopyname)s. "
"Status: %(luncopystatus)s. Stav: %(luncopystate)s."

#, python-format
msgid "An error occurred while reading volume \"%s\"."
msgstr "Při čtení svazku \"%s\" nastal problém."

#, python-format
msgid "An error occurred while writing to volume \"%s\"."
msgstr "Při zápisu do svazku \"%s\" nastal problém."

msgid "An unknown exception occurred."
msgstr "Vyskytla se neočekávaná výjimka."

msgid ""
"An user with a token scoped to a subproject is not allowed to see the quota "
"of its parents."
msgstr ""
"Uživatel s příznakem z podprojektu nemá povoleno zobrazit kvótu nadřazených "
"projektů."

#, python-format
msgid "Array does not exist or is offline. Current status of array is %s."
msgstr "Pole neexistuje nebo je offline. Současný stav pole je %s."

msgid "Associate host to hostgroup error."
msgstr "Chyba při přidružování hostitele ke skupině hostitele."

msgid "Associate host to mapping view error."
msgstr "Chyba při přidružování hostitele k zobrazení mapování."

msgid "Associate initiator to host error."
msgstr "Chyba při přidružování zavaděče k hostiteli."

msgid "Associate lun to lungroup error."
msgstr "Chyba při přidružování lun ke skupině lun."

msgid "Associate lungroup to mapping view error."
msgstr "Chyba při přidružování skupiny lun k zobrazení mapování."

msgid "Associate portgroup to mapping view error."
msgstr "Chyba při přidružování skupiny portu k zobrazení mapování."

msgid "At least one valid iSCSI IP address must be set."
msgstr "Musí být nastavena alespoň jedna platná IP adresa iSCSI."

#, python-format
msgid "Attempt to transfer %s with invalid auth key."
msgstr "Pokus o přenos %s s neplatným ověřovacím klíčem."

#, python-format
msgid "Availability zone '%(s_az)s' is invalid."
msgstr "Zóna dostupnosti '%(s_az)s' je neplatná."

msgid "Available categories:"
msgstr "Dostupné kategorie:"

#, python-format
msgid "Backend doesn't exist (%(backend)s)"
msgstr "Podpůrná vrstva neexistuje (%(backend)s)"

msgid "Backend storage did not configure fiber channel target."
msgstr "Úložiště podpůrné vrstvy nenastavilo cíl fiber channel."

msgid "Backing up an in-use volume must use the force flag."
msgstr "Při zálohování používaného svazku je zapotřebí použít příznak force."

#, python-format
msgid "Backup %(backup_id)s could not be found."
msgstr "Záloha %(backup_id)s nemohla být nalezena."

msgid "Backup RBD operation failed"
msgstr "Záložní operace RBD selhala"

msgid "Backup already exists in database."
msgstr "Záloha již existuje v databázi."

msgid "Backup id required"
msgstr "ID zálohy je vyžadováno"

msgid "Backup operation of an encrypted volume failed."
msgstr "Záložní operace zašifrovaného svazku selhala."

#, python-format
msgid ""
"Backup service %(configured_service)s does not support verify. Backup id "
"%(id)s is not verified. Skipping verify."
msgstr ""
"Zálohovací služba %(configured_service)s nepodporuje ověřování. Záloha s id "
"%(id)s není ověřena. Ověřování přeskočeno."

#, python-format
msgid ""
"Backup service %(service)s does not support verify. Backup id %(id)s is not "
"verified. Skipping reset."
msgstr ""
"Zálohovací služba %(service)s nepodporuje ověřování. Záloha s id %(id)s není "
"ověřena. Resetování přeskočeno."

#, python-format
msgid "Backup should only have one snapshot but instead has %s"
msgstr "Záloha by měla mít pouze jeden snímek ale místo toho má %s"

msgid "Backup status must be available"
msgstr "Stav zálohy musí být dostupný"

#, python-format
msgid "Backup status must be available and not %s."
msgstr "Stav zálohy musí být dostupný a ne %s."

msgid "Backup status must be available or error"
msgstr "Stav zálohy musí být dostupný nebo chybný"

msgid "Backup to be restored has invalid size"
msgstr "Obnovovaná záloha má neplatnou velikost"

#, python-format
msgid "Bad key(s) in quota set: %s"
msgstr "Špatné klíče v sadě kvót: %s"

#, python-format
msgid ""
"Bad or unexpected response from the storage volume backend API: %(data)s"
msgstr ""
"Špatná nebo neočekávaná odpověď od API podpůrné vrstvy úložiště svazků: "
"%(data)s"

msgid "Bad response from Datera API"
msgstr "Špatná odpověď od API Datera"

msgid "Bad response from SolidFire API"
msgstr "Špatná odpověď od SolidFire API"

#, python-format
msgid "Bad response from XMS, %s"
msgstr "Špatná odpověď od XMS, %s"

msgid "Binary"
msgstr "Binární soubor"

msgid "Blank components"
msgstr "Prázdné součásti"

#, python-format
msgid "Brocade Fibre Channel Zoning CLI error: %(reason)s"
msgstr "Chyba vyhrazování CLI Brocade Fibre Channel: %(reason)s"

#, python-format
msgid "Brocade Fibre Channel Zoning HTTP error: %(reason)s"
msgstr "Chyba vyhrazování HTTP Brocade Fibre Channel: %(reason)s"

msgid "CHAP secret should be 12-16 bytes."
msgstr "Soukromý klíč CHAP by měl mít alespoň 12-16 bajtů."

#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"Výstup výjimky rozhraní příkazového řádku:\n"
"příkaz: %(cmd)s\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s."

#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"Výstup výjimky rozhraní příkazového řádku:\n"
"příkaz: %(cmd)s\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s."

msgid ""
"CMMVC6071E The VDisk-to-host mapping was not created because the VDisk is "
"already mapped to a host.\n"
"\""
msgstr ""
"CMMVC6071E, mapování virtuálního disku na hostitele nebylo vytvořeno protože "
"disk k hostiteli již je namapován.\n"
"\""

#, python-format
msgid "CPG (%s) doesn't exist on array"
msgstr "Společná skupiny poskytování (%s) neexistuje v poli"

msgid "Cache name is None, please set smartcache:cachename in key."
msgstr ""
"Název mezipaměti je None, prosím nastavte  smartcache:cachename v klíči."

#, python-format
msgid "Cache volume %s does not have required properties"
msgstr "Svazek mezipaměti %s nemá požadované vlastnosti"

msgid "Can not add FC port to host."
msgstr "Nelze přidat FC port k hostiteli."

#, python-format
msgid "Can not find cache id by cache name %(name)s."
msgstr "Nelze najít id mezipaměti podle jejího názvu %(name)s."

#, python-format
msgid "Can not find partition id by name %(name)s."
msgstr "Nelze najít id oddílu podle názvu %(name)s."

#, python-format
msgid "Can not translate %s to integer."
msgstr "Nelze převést %s na celé číslo."

msgid "Can't decode backup record."
msgstr "Nelze rozšifrovat záznam zálohy."

#, python-format
msgid "Can't find cache name on the array, cache name is: %(name)s."
msgstr "Nelze v poli najít název mezipaměti, její název je: %(name)s."

#, python-format
msgid "Can't find partition name on the array, partition name is: %(name)s."
msgstr "Nelze v poli najít název oddílu, jeho název je: %(name)s."

msgid "Can't find the same host id from arrays."
msgstr "V polích nelze najít stejné id hostitele ."

#, python-format
msgid "Can't get volume id. Volume name: %s."
msgstr "Nelze získat id svazku. Název svazku: %s."

msgid "Can't parse backup record."
msgstr "Nelze zpracovat záznam zálohy."

#, python-format
msgid "Cannot create directory %s."
msgstr "Nelze vytvořit adresář %s."

msgid "Cannot create encryption specs. Volume type in use."
msgstr "Nelze vytvořit specifikace šifrování. Typ svazku se používá."

#, python-format
msgid ""
"Cannot create image of disk format: %s. Only vmdk disk format is accepted."
msgstr ""
"Nelze vytvořit obraz formátu disku: %s. Je přijímán pouze formát disku vmdk."

#, python-format
msgid "Cannot create volume of size %s: not multiple of 8GB."
msgstr "Nelze vytvořit svazek o velikosti %s: není násobkem 8GB."

#, python-format
msgid "Cannot create volume_type with name %(name)s and specs %(extra_specs)s"
msgstr ""
"Nelze vytvořit typ svazku s názvem %(name)s a specifikacemi %(extra_specs)s"

#, python-format
msgid ""
"Cannot delete cache volume: %(cachevol_name)s. It was updated at "
"%(updated_at)s and currently has %(numclones)d volume instances."
msgstr ""
"Nelze smazat svazek mezipaměti: %(cachevol_name)s. Byl aktualizována "
"%(updated_at)s a v současnosti má %(numclones)d instancí svazku."

#, python-format
msgid ""
"Cannot delete cache volume: %(cachevol_name)s. It was updated at "
"%(updated_at)s and currently has %(numclones)s volume instances."
msgstr ""
"Nelze smazat svazek mezipaměti: %(cachevol_name)s. Byl aktualizována "
"%(updated_at)s a v současnosti má %(numclones)s instancí svazku."

msgid "Cannot delete encryption specs. Volume type in use."
msgstr "Nelze smazat specifikace šifrování. Typ svazku se používá."

msgid "Cannot find migration task."
msgstr "Nelze najít úkol pro přesun."

msgid "Cannot ping DRBDmanage backend"
msgstr "Nelze zjistit spojení s podpůrnou vrstvou DRBDmanage"

#, python-format
msgid ""
"Cannot provide both 'cgsnapshot_id' and 'source_cgid' to create consistency "
"group %(name)s from source."
msgstr ""
"Při vytváření skupiny jednotnosti %(name)s ze zdroje nelze zadávat  "
"'cgsnapshot_id' a 'source_cgid' najednou."

msgid "Cannot register resource"
msgstr "Nelze registrovat zdroj"

msgid "Cannot register resources"
msgstr "Nelze registrovat zdroje"

#, python-format
msgid "Cannot retype from HPE3PARDriver to %s."
msgstr "Nelze přetypovat z HPE3PARDriver na %s."

msgid "Cannot retype from one 3PAR array to another."
msgstr "Nelze přetypovat z jednoho pole 3PAR na jiné."

msgid "Cannot retype to a CPG in a different domain."
msgstr "Nelze přetypovat do společné skupiny poskytování v jiné doméně."

msgid "Cannot retype to a snap CPG in a different domain."
msgstr "Nelze přetypovat do snímku společné skupiny poskytování v jiné doméně."

msgid "Cannot specify both protection domain name and protection domain id."
msgstr "Nelze zadat název a id ochranné domény najednou."

msgid "Cannot specify both storage pool name and storage pool id."
msgstr "Nelze zadat název a id zásoby úložiště najednou."

msgid "Cannot update encryption specs. Volume type in use."
msgstr "Nelze aktualizovat specifikace šifrování. Typ svazku se používá."

#, python-format
msgid "Cannot update volume_type %(id)s"
msgstr "Nelze aktualizovat typ svazku %(id)s"

#, python-format
msgid "CgSnapshot %(cgsnapshot_id)s could not be found."
msgstr "Snímek skupiny jednotnosti %(cgsnapshot_id)s nemohl být nalezen."

msgid "Change hostlun id error."
msgstr "Chyba při změně id hostitele lun."

msgid "Change lun priority error."
msgstr "Chyba při získávání priority lun."

msgid "Change lun smarttier policy error."
msgstr "Chyba při změny chytré vrstvy zásady lun."

#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: %(unders)s"
msgstr ""
"Změna by využití změnila na méně než 0 pro následující zdroje: %(unders)s"

msgid "Check access permissions for the ZFS share assigned to this driver."
msgstr ""
"Zkontrolujte oprávnění k přístupu pro sdílení ZFS přidělené k tomuto "
"ovladači."

msgid "Check hostgroup associate error."
msgstr "Chyba při kontrole přidružení skupiny hostitele."

msgid "Check initiator added to array error."
msgstr "Chyba při kontrole přidání zavaděče do pole."

msgid "Check initiator associated to host error."
msgstr "Chyba při kontrole přidružení zavaděče k hostiteli."

msgid "Check lungroup associate error."
msgstr "Chyba při kontrole přidružení skupiny lun."

msgid "Check portgroup associate error."
msgstr "Chyba při kontrole přidružení skupiny portu."

msgid ""
"Check the state of the http service. Also ensure that the https port number "
"is the same as the one specified in cinder.conf."
msgstr ""
"Zkontrolujte stav služby http. Také se ujistěte, že číslo portu https je "
"stejné jako port zadaný v cinder.conf."

msgid "Chunk size is not multiple of block size for creating hash."
msgstr ""
"Velikost kusu není násobkem velikosti bloku z kterého je možné vytvořit "
"kontrolní součet."

#, python-format
msgid "Cisco Fibre Channel Zoning CLI error: %(reason)s"
msgstr "Chyba vyhrazování CLI Cisco Fibre Channel: %(reason)s"

#, python-format
msgid ""
"Clone type '%(clone_type)s' is invalid; valid values are: '%(full_clone)s' "
"and '%(linked_clone)s'."
msgstr ""
"Typ klonu '%(clone_type)s' je neplatný; platné hodnoty jsou: "
"'%(full_clone)s' a '%(linked_clone)s'."

msgid ""
"Cluster is not formatted. You should probably perform \"dog cluster format\"."
msgstr ""
"Cluster není zformátován. Pravděpodobně byste měli provést příkaz \"dog "
"cluster format\"."

#, python-format
msgid "CommandLineHelper._wait_for_condition: %s timeout."
msgstr ""
"Pomocník příkazového řádku: Čekání na podmínku: Vypršel časový limit %s."

msgid "Compression Enabler is not installed. Can not create compressed volume."
msgstr ""
"Povolovač komprimace není nainstalován. Nelze vytvořit komprimovaný svazek."

#, python-format
msgid "Compute cluster: %(cluster)s not found."
msgstr "Výpočetní cluster: %(cluster)s nenalezen."

msgid "Condition has no field."
msgstr "Podmínka nemá žádné pole."

#, python-format
msgid "Configuration value %s is not set."
msgstr "Konfigurační volba %s není nastavena."

#, python-format
msgid ""
"Conflicting QoS specifications in volume type %s: when QoS spec is "
"associated to volume type, legacy \"netapp:qos_policy_group\" is not allowed "
"in the volume type extra specs."
msgstr ""
"Konfliktní specifikace QoS pro typ svazku %s: Když je specifiakce přidružena "
"k typu svazku legacy, \"netapp:qos_policy_group\" není povolena v "
"dodatečných specifikací typu svazku."

#, python-format
msgid "Connection to glance failed: %(reason)s"
msgstr "Připojení ke glance selhalo: %(reason)s"

#, python-format
msgid "Connection to swift failed: %(reason)s"
msgstr "Připojení k swift selhalo: %(reason)s"

#, python-format
msgid "Connector does not provide: %s"
msgstr "Konektor nepodporuje: %s"

#, python-format
msgid "Connector doesn't have required information: %(missing)s"
msgstr "Konektor nemá požadované informace: %(missing)s"

#, python-format
msgid "ConsistencyGroup %(consistencygroup_id)s could not be found."
msgstr "Skupina jednotnosti %(consistencygroup_id)s nemohla být nalezena."

msgid "Container"
msgstr "Kontejner"

msgid "Container size smaller than required file size."
msgstr "Velikost kontejneru je menší než požadovaná velikost souboru."

#, python-format
msgid "Converted to %(f1)s, but format is now %(f2)s"
msgstr "Převedeno na %(f1)s, ale formát je nyní %(f2)s"

#, python-format
msgid "Converted to %(vol_format)s, but format is now %(file_format)s"
msgstr "Převedeno na %(vol_format)s, ale formát je nyní %(file_format)s"

#, python-format
msgid "Converted to raw, but format is now %s"
msgstr "Převedeno na prosté, ale formát je nyní %s"

#, python-format
msgid "Converted to raw, but format is now %s."
msgstr "Převedeno na prostý, ale formát je nyní %s."

msgid "Coordinator uninitialized."
msgstr "Koordinátor nezaveden."

#, python-format
msgid ""
"Copy volume task failed: convert_to_base_volume: id=%(id)s, status="
"%(status)s."
msgstr ""
"Úkol kopírování svazku selhal: převedení na základní svazek: Id=%(id)s, stav="
"%(status)s."

#, python-format
msgid "Copying metadata from %(src_type)s %(src_id)s to %(vol_id)s."
msgstr "Kopírování popisných dat z %(src_type)s %(src_id)s do %(vol_id)s."

msgid ""
"Could not determine which Keystone endpoint to use. This can either be set "
"in the service catalog or with the cinder.conf config option "
"'backup_swift_auth_url'."
msgstr ""
"Nelze zjistit, který koncový bod Keystone použít. Ten může být nastaven buď "
"v katalogu služby nebo pomocí volby 'backup_swift_auth_url' v souboru cinder."
"conf."

msgid ""
"Could not determine which Swift endpoint to use. This can either be set in "
"the service catalog or with the cinder.conf config option 'backup_swift_url'."
msgstr ""
"Nelze zjistit, který koncový bod Swift použít. Ten může být nastaven buď v "
"katalogu služby nebo pomocí volby 'backup_swift_url' v souboru cinder.conf."

#, python-format
msgid "Could not find GPFS cluster id: %s."
msgstr "Nelze najít id clusteru GPFS: %s."

#, python-format
msgid "Could not find GPFS file system device: %s."
msgstr "Nelze najít zařízení systému souborů GPFS: %s."

#, python-format
msgid "Could not find config at %(path)s"
msgstr "Nelze najít nastavení v %(path)s"

#, python-format
msgid "Could not find iSCSI export for volume %s"
msgstr "Nelze najít export iSCSI pro svazek %s"

#, python-format
msgid "Could not find key in output of command %(cmd)s: %(out)s."
msgstr "Ve výstupu příkazu %(cmd)s nelze najít klíč: %(out)s."

#, python-format
msgid "Could not find parameter %(param)s"
msgstr "Nelze najít parametr %(param)s"

#, python-format
msgid "Could not find target %s"
msgstr "Nelze najít cíl %s"

msgid "Could not get system name."
msgstr "Nelze získat název systému."

#, python-format
msgid "Could not save configuration to %(file_path)s: %(exc)s"
msgstr "Nelze uložit nastavení do %(file_path)s: %(exc)s"

msgid "Create QoS policy error."
msgstr "Chyba při vytváření zásady QoS."

#, python-format
msgid ""
"Create backup aborted, expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"Vytvoření zálohy zrušeno, očekávaný stav zálohy je %(expected_status)s ale "
"zjištěný stav je %(actual_status)s."

#, python-format
msgid ""
"Create backup aborted, expected volume status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"Vytvoření zálohy zrušeno, očekávaný stav svazku je %(expected_status)s ale "
"zjištěný stav je %(actual_status)s."

msgid "Create hostgroup error."
msgstr "Chyba při vytváření skupiny hostitele."

#, python-format
msgid "Create hypermetro error. %s."
msgstr "Chyba při vytváření hypermetra. %s"

msgid "Create lun migration error."
msgstr "Chyba při vytváření přesunu lun."

msgid "Create luncopy error."
msgstr "Chyba při vytváření kopie lun."

msgid "Create lungroup error."
msgstr "Chyba při vytváření skupiny lun."

msgid "Create manager volume flow failed."
msgstr "Vytvoření postupu správce svazku selhalo."

msgid "Create snapshot error."
msgstr "Chyba při vytváření snímku."

#, python-format
msgid "Create volume error. Because %s."
msgstr "Chyba při vytváření svazku: Protože %s."

msgid "Create volume failed."
msgstr "Vytvoření svazku selhalo."

#, python-format
msgid ""
"Creating and activating zone set failed: (Zone set=%(cfg_name)s error="
"%(err)s)."
msgstr ""
"Vytvoření a aktivování sady zóny selhalo: (Sada zóny=%(cfg_name)s chyba="
"%(err)s)."

#, python-format
msgid ""
"Creating and activating zone set failed: (Zone set=%(zoneset)s error="
"%(err)s)."
msgstr ""
"Vytvoření a aktivování sady zóny selhalo: (Sada zóny=%(zoneset)s chyba="
"%(err)s)."

msgid ""
"DRBDmanage driver setup error: some required libraries (dbus, drbdmanage.*) "
"not found."
msgstr ""
"Chyba nastavení ovladače DRBDmanage: nenalezeny některé požadované knihovny "
"(dbus, drbdmanage.*)."

#, python-format
msgid "DRBDmanage expected one resource (\"%(res)s\"), got %(n)d"
msgstr "DRBDmanage očekával jeden zdroj (\"%(res)s\"), obdrženo %(n)d"

#, python-format
msgid ""
"Dedup is a valid provisioning type, but requires WSAPI version "
"'%(dedup_version)s' version '%(version)s' is installed."
msgstr ""
"Dedup je platný typ poskytování, ale vyžaduje WSAPI verze "
"'%(dedup_version)s', je nainstalována verze '%(version)s'."

#, python-format
msgid ""
"Default quota for resource: %(res)s is set by the default quota flag: quota_"
"%(res)s, it is now deprecated. Please use the default quota class for "
"default quota."
msgstr ""
"Výchozí kvóta pro zdroj: %(res)s je nastavena příznakem výchozí kvóty: quota_"
"%(res)s, je nyní zastaralé. Pro výchozí kvótu prosím použijte třídu výchozí "
"kvóty."

msgid "Default volume type can not be found."
msgstr "Výchozí typ svazku nenalezen."

msgid "Delete LUNcopy error."
msgstr "Chyba při mazání kopírování LUN."

msgid "Delete QoS policy error."
msgstr "Chyba při mazání zásady QoS."

msgid "Delete associated lun from lungroup error."
msgstr "Chyba při mazání přidružené lun ze skupiny lun."

#, python-format
msgid ""
"Delete backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"Smazání zálohy zrušeno, v současnosti nastavená služba záloh "
"[%(configured_service)s] není stejnou službou použitou k vytvoření této "
"zálohy [%(backup_service)s]."

msgid "Delete hostgroup error."
msgstr "Chyba při mazání skupiny hostitele."

msgid "Delete hostgroup from mapping view error."
msgstr "Chyba při mazání skupiny hostitele ze zobrazení mapování."

msgid "Delete lun error."
msgstr "Chyba při mazání lun."

msgid "Delete lun migration error."
msgstr "Chyba při mazání přesunu lun."

msgid "Delete lungroup error."
msgstr "Chyba při mazání skupiny lun."

msgid "Delete lungroup from mapping view error."
msgstr "Chyba při mazání skupiny lun ze zobrazení mapování."

msgid "Delete mapping view error."
msgstr "Chyba při mazání zobrazení mapování."

msgid "Delete portgroup from mapping view error."
msgstr "Chyba při mazání skupiny portu ze zobrazení mapování."

msgid "Delete snapshot error."
msgstr "Chyba při mazání snímku."

#, python-format
msgid "Delete snapshot of volume not supported in state: %s."
msgstr "Smazání snímku svazku není podporováno ve stavu: %s."

#, python-format
msgid ""
"Delete_backup aborted, expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"Smazání zálohy zrušeno, očekávaný stav zálohy je %(expected_status)s ale "
"zjištěný stav je %(actual_status)s."

msgid "Deleting volume from database and skipping rpc."
msgstr "Odpojování svazku od databáze a přeskakování rpc."

#, python-format
msgid "Deleting zones failed: (command=%(cmd)s error=%(err)s)."
msgstr "Mazání zón selhalo: (příkaz=%(cmd)s chyba=%(err)s)."

msgid "Dell API 2.1 or later required for Consistency Group support"
msgstr ""
"Pro podporu skupin jednotnosti je vyžadována API Dell verze 2.1 a vyšší."

#, python-format
msgid "Destination has migration_status %(stat)s, expected %(exp)s."
msgstr "Cíl má stav přesunu %(stat)s, očekáváno %(exp)s."

msgid "Destination volume not mid-migration."
msgstr "Cílový svazek není uprostřed přesunu."

msgid ""
"Detach volume failed: More than one attachment, but no attachment_id "
"provided."
msgstr ""
"Odpojení svazku selhalo. Více než jedno připojení, ale nezadáno žádné "
"attachment_id."

msgid "Detach volume from instance and then try again."
msgstr "Odpojte svazek od instance a zkuste to znovu."

#, python-format
msgid "Detected more than one volume with name %(vol_name)s"
msgstr "Zjištěn více než jeden svazek s názvem %(vol_name)s"

#, python-format
msgid "Did not find expected column in %(fun)s: %(hdr)s."
msgstr "Nenalezen očekávaný sloupec v %(fun)s: %(hdr)s."

#, python-format
msgid "Did not find the expected key %(key)s in %(fun)s: %(raw)s."
msgstr "Očekávaný klíč %(key)s nenalezen v %(fun)s: %(raw)s."

#, python-format
msgid "Domain with name %s wasn't found."
msgstr "Doména s názvem %s nebyla nalezena."

#, python-format
msgid ""
"Downlevel GPFS Cluster Detected.  GPFS Clone feature not enabled in cluster "
"daemon level %(cur)s - must be at least at level %(min)s."
msgstr ""
"Zjištěn cluster GPFS nižší úrovně. Funkce klonování GPFS není povolena v "
"daemonu clusteru na úrovni %(cur)s - úroveň musí být alespoň %(min)s."

#, python-format
msgid "Driver initialize connection failed (error: %(err)s)."
msgstr "Zavedení připojení ovladačem selhalo (chyba: %(err)s)."

msgid "Driver must implement initialize_connection"
msgstr "Ovladač musí zavést initialize_connection"

#, python-format
msgid ""
"Driver successfully decoded imported backup data, but there are missing "
"fields (%s)."
msgstr ""
"Ovladač úspěšně rozšifroval data importované zálohy, ale některá pole chybí "
"(%s)."

#, python-format
msgid ""
"EMC VNX Cinder Driver CLI exception: %(cmd)s (Return Code: %(rc)s) (Output: "
"%(out)s)."
msgstr ""
"Výjimka CLI ovladače EMC VNX Cinder: %(cmd)s (Návratový kód: %(rc)s) "
"(Výstup: %(out)s)."

#, python-format
msgid ""
"Either 'cgsnapshot_id' or 'source_cgid' must be provided to create "
"consistency group %(name)s from source."
msgstr ""
"Pro vytvoření skupiny jednotnosti %(name)s ze zdroje musí být zadán buď "
"'cgsnapshot_id' nebo 'source_cgid'."

#, python-format
msgid ""
"Either SLO: %(slo)s or workload %(workload)s is invalid. Examine previous "
"error statement for valid values."
msgstr ""
"SLO: %(slo)s nebo vytížení %(workload)s jsou neplatné. Prozkoumejte "
"předchozí chybový výpis pro platné hodnoty."

msgid "Enables QoS."
msgstr "Povolí QoS."

msgid "Enables compression."
msgstr "Povolí komprimaci."

msgid "Enables replication."
msgstr "Povolí replikaci."

msgid "Ensure that configfs is mounted at /sys/kernel/config."
msgstr "Ujistěte se, že configfs je připojen k /sys/kernel/config."

#, python-format
msgid ""
"Error Adding Initiator: %(initiator)s on groupInitiatorGroup: "
"%(initiatorgroup)s Return code: %(ret.status)d Message: %(ret.data)s ."
msgstr ""
"Chyba při přidávání zavaděče: %(initiator)s ve skupině zavaděče: "
"%(initiatorgroup)s. Návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Adding to TargetGroup: %(targetgroup)s withIQN: %(iqn)sReturn code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při přidávání do cílové skupiny: %(targetgroup)s mající IQN: %(iqn)s. "
"Návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Cloning Snapshot: %(snapshot)s on Volume: %(lun)s of Pool: %(pool)s "
"Project: %(project)s  Clone project: %(clone_proj)s Return code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při klonování snímku: %(snapshot)s ve svazku %(lun)s ze zásoby "
"%(pool)s, projekt %(project)s, klon projektu: %(clone_proj)s, návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Creating Initiator: %(initiator)s on Alias: %(alias)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"Chyba při vytváření zavaděče: %(initiator)s s přezdívkou: %(alias)s. "
"Návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Creating Project: %(project)s on Pool: %(pool)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"Chyba při vytváření projektu: %(project)s v zásobě %(pool)s. Návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Creating Property: %(property)s Type: %(type)s Description: "
"%(description)s Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při vytváření vlastnosti: %(property)s, typ: %(type)s, popis: "
"%(description)s, návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Creating Share: %(name)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"Chyba při vytváření sdílení: %(name)s, návratový kód: %(ret.status)d, "
"zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Creating Snapshot: %(snapshot)s onVolume: %(lun)s to Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při vytváření snímku: %(snapshot)s ve svazku %(lun)s do zásoby "
"%(pool)s, projekt %(project)s, návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error Creating Snapshot: %(snapshot)s onshare: %(share)s to Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při vytváření snímku: %(snapshot)s ve sdílení %(share)s do zásoby "
"%(pool)s, projekt %(project)s, návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error Creating Target: %(alias)sReturn code: %(ret.status)d Message: "
"%(ret.data)s ."
msgstr ""
"Chyba při vytváření cíle: %(alias)s. Návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error Creating TargetGroup: %(targetgroup)s withIQN: %(iqn)sReturn code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"Chyba při vytváření cílové skupiny: %(targetgroup)s mající IQN: %(iqn)s. "
"Návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Creating Volume: %(lun)s Size: %(size)s Return code: %(ret.status)d "
"Message: %(ret.data)s."
msgstr ""
"Chyba při vytváření svazku: %(lun)s, velikost: %(size)s, návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Deleting Snapshot: %(snapshot)s on Share: %(share)s to Pool: %(pool)s "
"Project: %(project)s Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při mazání snímku: %(snapshot)s ve sdílení %(share)s do zásoby "
"%(pool)s, projekt %(project)s, návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error Deleting Snapshot: %(snapshot)s on Volume: %(lun)s to Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při mazání snímku: %(snapshot)s ve svazku %(lun)s do zásoby %(pool)s, "
"projekt %(project)s, návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Deleting Volume: %(lun)s from Pool: %(pool)s, Project: %(project)s. "
"Return code: %(ret.status)d, Message: %(ret.data)s."
msgstr ""
"Chyba při mazání svazku: %(lun)s ze zásoby %(pool)s, projekt %(project)s, "
"návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Deleting project: %(project)s on pool: %(pool)s Return code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při mazání projektu: %(project)s v zásobě %(pool)s. Návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Deleting replication action: %(id)s Return code: %(ret.status)d "
"Message: %(ret.data)s."
msgstr ""
"Chyba při odstraňování provedení replikace: %(id)s. Návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Getting Initiators: InitiatorGroup: %(initiatorgroup)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"Chyba při získávání zavaděčů: Skupina zavaděče: %(initiatorgroup)s. "
"Návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Getting Project Stats: Pool: %(pool)s Project: %(project)s Return "
"code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při získávání statistik projektu: Zásoba %(pool)s, projekt "
"%(project)s, návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Getting Share: %(share)s on Pool: %(pool)s Project: %(project)s Return "
"code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při získávání sdílení: %(share)s v zásobě %(pool)s, projekt "
"%(project)s, návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Getting Target: %(alias)sReturn code: %(ret.status)d Message: "
"%(ret.data)s ."
msgstr ""
"Chyba při získávání cíle: %(alias)s. Návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error Getting Volume: %(lun)s on Pool: %(pool)s Project: %(project)s Return "
"code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při získávání svazku: %(lun)s v zásobě %(pool)s, projekt %(project)s, "
"návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Setting props Props: %(props)s on Volume: %(lun)s of Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při nastavování vlastností: %(props)s ve svazku %(lun)s v zásobě "
"%(pool)s, projekt %(project)s, návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error Verifying Initiator: %(iqn)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"Chyba při ověřování zavaděče: %(iqn)s. Návratový kód: %(ret.status)d, "
"zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Verifying Pool: %(pool)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"Chyba při ověřování zásoby: %(pool)s: Návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error Verifying Project: %(project)s on Pool: %(pool)s Return code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při ověřování projektu: %(project)s v zásobě %(pool)s. Návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Verifying Service: %(service)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"Chyba při ověřování služby: Služba: %(service)s, návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error Verifying Target: %(alias)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"Chyba při ověřování cíle: %(alias)s. Návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error Verifying share: %(share)s on Project: %(project)s and Pool: %(pool)s "
"Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"Chyba při ověřování sdílení: %(share)s v projektu %(project)s a zásobě "
"%(pool)s. Návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

msgid "Error connecting to ceph cluster."
msgstr "Chyba při připojování ke clusteru ceph."

#, python-format
msgid "Error connecting via ssh: %s"
msgstr "Chyba při připojování pomocí ssh: %s"

#, python-format
msgid "Error creating volume: %s."
msgstr "Chyba při vytváření svazku: %s."

msgid "Error deleting replay profile."
msgstr "Chyba při mazání profilu rychlého načtení."

#, python-format
msgid "Error deleting volume %(vol)s: %(err)s."
msgstr "Chyba při mazání svazku %(vol)s: %(err)s."

#, python-format
msgid "Error during evaluator parsing: %(reason)s"
msgstr "Chyba během zpracování hodnotitele: %(reason)s"

#, python-format
msgid ""
"Error editing share: %(share)s on Pool: %(pool)s Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"Chyba při úpravě sdílení: %(share)s v zásobě: %(pool)s. Návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error enabling iSER for NetworkPortal: please ensure that RDMA is supported "
"on your iSCSI port %(port)d on ip %(ip)s."
msgstr ""
"Chyba při povolování iSER pro síťový portál: ujistěte se prosím, že RDMA je "
"podporováno pro port %(port)d vašeho iSCSI na ip adrese %(ip)s."

#, python-format
msgid "Error encountered during cleanup of a failed attach: %(ex)s"
msgstr "Během čištění selhaného připojení se vyskytla chyba: %(ex)s"

#, python-format
msgid "Error executing command via ssh: %s"
msgstr "Chyba při provádění příkazu pomocí ssh: %s"

#, python-format
msgid "Error extending volume %(vol)s: %(err)s."
msgstr "Chyba při rozšiřování svazku %(vol)s: %(err)s."

#, python-format
msgid "Error extending volume: %(reason)s"
msgstr "Chyba při rozšiřování svazku: %(reason)s"

#, python-format
msgid "Error finding %(name)s."
msgstr "Chyba při hledání %(name)s."

msgid ""
"Error getting appliance version details. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"Chyba při získávání podrobností o verzi zařízení. Návratový kód: %(ret."
"status)d, zpráva: %(ret.data)s."

#, python-format
msgid "Error getting domain id from name %(name)s: %(id)s."
msgstr "Chyba při získávání id domény z názvu %(name)s: %(id)s."

msgid "Error getting initiator groups."
msgstr "Chyba při získávání skupin zavaděče."

#, python-format
msgid "Error getting pool id from name %(pool_name)s: %(err_msg)s."
msgstr "Chyba při získávání id zásoby z názvu %(pool_name)s: %(err_msg)s."

#, python-format
msgid ""
"Error getting replication action: %(id)s. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"Chyba při získávání provádění replikace: %(id)s. Návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

msgid ""
"Error getting replication source details. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"Chyba při získávání podrobností o zdroji replikace. Návratový kód: %(ret."
"status)d, zpráva: %(ret.data)s."

msgid ""
"Error getting replication target details. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"Chyba při získávání podrobností o cíli replikace. Návratový kód: %(ret."
"status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error getting version: svc: %(svc)s.Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"Chyba při získávání verze: svc: %(svc)s. Návratový kód: %(ret.status)d, "
"zpráva: %(ret.data)s."

#, python-format
msgid "Error in SolidFire API response: data=%(data)s"
msgstr "Chyba v odpovědi SolidFire API: data=%(data)s"

#, python-format
msgid ""
"Error modifying Service: %(service)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"Chyba při změně služby: %(service)s, návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error moving volume: %(vol)s from source project: %(src)s to target project: "
"%(tgt)s Return code: %(ret.status)d Message: %(ret.data)s ."
msgstr ""
"Chyba při přesunování svazku: %(vol)s ze zdrojového projektu %(src)s do "
"cílového %(tgt)s. Návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

msgid "Error not a KeyError."
msgstr "Chyba není chyba klíče."

msgid "Error not a TypeError."
msgstr "Chyba není chyba typu."

#, python-format
msgid "Error renaming volume %(vol)s: %(err)s."
msgstr "Chyba při přejmenování svazku %(vol)s: %(err)s."

#, python-format
msgid "Error response: %s"
msgstr "Chybová odpověď: %s"

msgid "Error retrieving volume size"
msgstr "Chyba při získávání velikosti svazku"

#, python-format
msgid ""
"Error sending replication update for action id: %(id)s . Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"Chyba při odesílání aktualizace replikace pro činnost s id: %(id)s. "
"Návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error sending replication update. Returned error: %(err)s. Action: %(id)s."
msgstr ""
"Chyba při odesílání aktualizace replikace. Předaná chyba: %(err)s. Činnost: "
"%(id)s."

#, python-format
msgid ""
"Error setting replication inheritance to %(set)s for volume: %(vol)s project "
"%(project)s Return code: %(ret.status)d Message: %(ret.data)s ."
msgstr ""
"Chyba při nastavování dědění replikace na %(set)s pro svazek: %(vol)s, "
"projekt %(project)s. Návratový kód: %(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid ""
"Error severing the package: %(package)s from source: %(src)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"Chyba při oddělování balíčku: %(package)s od zdroje: %(src)s. Návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

#, python-format
msgid "Error while checking transaction status: %s"
msgstr "Chyba při kontrole stavu přenosu: %s"

#, python-format
msgid "Error while getting data via ssh: (command=%(cmd)s error=%(err)s)."
msgstr "Chyba při získávání dat pomocí ssh: (příkaz=%(cmd)s chyba=%(err)s)."

#, python-format
msgid "Error while requesting %(service)s API."
msgstr "Chyba při žádání API %(service)s."

#, python-format
msgid "Error while running zoning CLI: (command=%(cmd)s error=%(err)s)."
msgstr ""
"Chyba při spouštění rozhraní příkazového řádku pro zónu:  (příkaz=%(cmd)s "
"chyba=%(err)s)."

msgid "Exceeded the limit of snapshots per volume"
msgstr "Překročeno omezení snímků na svazek"

#, python-format
msgid "Exception in _select_ds_for_volume: %s."
msgstr "Výjimka ve výběru diskového prostoru pro svazek: %s."

#, python-format
msgid "Exception: %s"
msgstr "Výjimka: %s"

#, python-format
msgid "Expected integer for node_count, svcinfo lsiogrp returned: %(node)s."
msgstr "U počtu uzlů očekáváno číslo, svcinfo lsiogrp předalo: %(node)s."

#, python-format
msgid "Expected no output from CLI command %(cmd)s, got %(out)s."
msgstr ""
"Od příkazu %(cmd)s v příkazovém řádku neočekáván žádný výstup, předáno "
"%(out)s."

#, python-format
msgid ""
"Expected single vdisk returned from lsvdisk when filtering on vdisk_UID.  "
"%(count)s were returned."
msgstr ""
"Při filtrování pomocí UID virtuálního disku bylo očekáváno vrácení jednoho "
"disku z lsvdisk. Bylo předáno %(count)s."

#, python-format
msgid "Expected volume size was %d"
msgstr "Očekávaná velikost snímku byla %d"

#, python-format
msgid ""
"Export backup aborted, expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"Exportování zálohy zrušeno, očekávaný stav svazku je %(expected_status)s ale "
"zjištěný stav je %(actual_status)s."

#, python-format
msgid ""
"Export record aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"Exportování záznamu zrušeno, v současnosti nastavená služba záloh "
"[%(configured_service)s] není stejnou službou použitou k vytvoření této "
"zálohy [%(backup_service)s]."

msgid "Extend volume error."
msgstr "Chyba při rozšiřování svazku"

msgid "Extend volume not implemented"
msgstr "Rozšíření svazku není zavedeno"

msgid "FC is the protocol but wwpns are not supplied by OpenStack."
msgstr "FC je protokol, ale OpenStack nedodává wwpn."

#, python-format
msgid "Faield to unassign %(volume)s"
msgstr "Nelze zrušit přidělení %(volume)s"

#, python-format
msgid "Fail to create cache volume %(volume)s. Error: %(err)s"
msgstr "Nelze vytvořit svazek mezipaměti %(volume)s. Chyba: %(err)s"

#, python-format
msgid "Failed adding connection for fabric=%(fabric)s: Error: %(err)s"
msgstr "Nelze přidat připojení pro fabric=%(fabric)s: Chyba: %(err)s"

#, python-format
msgid "Failed creating snapshot for volume %(volname)s: %(response)s."
msgstr "Nelze vytvořit snímek ze svazku %(volname)s: %(response)s."

#, python-format
msgid "Failed getting details for pool %s."
msgstr "Nelze získat podrobnosti zásoby %s."

#, python-format
msgid "Failed removing connection for fabric=%(fabric)s: Error: %(err)s"
msgstr "Nelze odstranit připojení pro fabric=%(fabric)s: Chyba: %(err)s"

#, python-format
msgid "Failed to Extend Volume %(volname)s"
msgstr "Nelze rozšířit svazek %(volname)s"

#, python-format
msgid "Failed to Login to 3PAR (%(url)s) because %(err)s"
msgstr "Nelze se přihlásit do 3PAR (%(url)s) kvůli %(err)s"

msgid "Failed to access active zoning configuration."
msgstr "Nelze získat přístup k aktivním nastavení zónování."

#, python-format
msgid "Failed to access zoneset status:%s"
msgstr "Nelze získat přístup ke stavu sady zóny: %s"

msgid "Failed to add zoning configuration."
msgstr "Nelze přidat nastavení zónování."

#, python-format
msgid "Failed to associate qos_specs: %(specs_id)s with type %(type_id)s."
msgstr "Nelze asociovat specifikace qos: %(specs_id)s s typem %(type_id)s."

#, python-format
msgid "Failed to attach iSCSI target for volume %(volume_id)s."
msgstr "Nelze připojit cílové iSCSI pro svazek %(volume_id)s."

#, python-format
msgid "Failed to backup volume metadata - %s"
msgstr "Nelze zálohovat popisná data svazku - %s"

#, python-format
msgid ""
"Failed to backup volume metadata - Metadata backup object 'backup.%s.meta' "
"already exists"
msgstr ""
"Nelze zálohovat popisná data svazku - objekt zálohy popisných dat 'backup.%s."
"meta' již existuje"

#, python-format
msgid "Failed to clone volume from snapshot %s."
msgstr "Nelze klonovat svazek ze snímku %s."

#, python-format
msgid "Failed to connect to %(vendor_name)s Array %(host)s: %(err)s"
msgstr "Nelze se připojit k %(vendor_name)s Pole %(host)s: %(err)s"

#, python-format
msgid "Failed to connect to sheep daemon. addr: %(addr)s, port: %(port)s"
msgstr "Nelze se připojit k daemonu sheep. Adresa: %(addr)s, port: %(port)s"

#, python-format
msgid "Failed to copy image to volume: %(reason)s"
msgstr "Nelze zkopírovat obraz do svazku: %(reason)s"

#, python-format
msgid "Failed to copy metadata to volume: %(reason)s"
msgstr "Nelze zkopírovat popisná data do svazku: %(reason)s"

msgid "Failed to copy volume, destination device unavailable."
msgstr "Nelze zkopírovat svazek, cílové zařízení je nedostupné."

msgid "Failed to copy volume, source device unavailable."
msgstr "Nelze zkopírovat svazek, zdrojové zařízení je nedostupné."

#, python-format
msgid "Failed to create IG, %s"
msgstr "Nelze vytvořit IG, %s"

#, python-format
msgid "Failed to create Volume Group: %(vg_name)s"
msgstr "Nelze vytvořit skupinu svazku: %(vg_name)s"

msgid "Failed to create api volume flow."
msgstr "Nelze vytvořit postup api svazku."

#, python-format
msgid "Failed to create cg snapshot %(id)s due to %(reason)s."
msgstr ""
"Vytvoření snímku skupiny jednotnosti %(id)s selhalo z důvodu %(reason)s."

#, python-format
msgid "Failed to create consistency group %(id)s due to %(reason)s."
msgstr "Vytvoření skupiny jednotnosti %(id)s selhalo z důvodu %(reason)s."

#, python-format
msgid "Failed to create consistency group %(id)s:%(ret)s."
msgstr "Nelze vytvořit skupinu jednotnosti %(id)s:%(ret)s."

#, python-format
msgid "Failed to create consistency group: %(cgid)s. Error: %(excmsg)s."
msgstr "Nelze vytvořit skupinu jednotnosti: %(cgid)s. Chyba: %(excmsg)s."

#, python-format
msgid ""
"Failed to create host: %(name)s. Please check if it exists on the array."
msgstr "Nelze vytvořit hostitele: %(name)s. Zkontrolujte zda existuje v poli."

#, python-format
msgid "Failed to create hostgroup: %(name)s. Check if it exists on the array."
msgstr ""
"Nelze vytvořit skupinu hostitele: %(name)s. Zkontrolujte zda existuje v poli."

#, python-format
msgid "Failed to create iscsi target for volume %(volume_id)s."
msgstr "Nelze vytvořit cílové iscsi pro svazek %(volume_id)s."

msgid "Failed to create manage existing flow."
msgstr "Nelze vytvořit správu existujícího postupu."

msgid "Failed to create manage_existing flow."
msgstr "Nelze vytvořit postup pro správu existujících."

#, python-format
msgid "Failed to create metadata for volume: %(reason)s"
msgstr "Nelze vytvořit popisná data pro svazek: %(reason)s"

#, python-format
msgid "Failed to create qos_specs: %(name)s with specs %(qos_specs)s."
msgstr ""
"Nelze vytvořit specifikace qos: %(name)s se specifikacemi %(qos_specs)s."

msgid "Failed to create scheduler manager volume flow"
msgstr "Nelze vytvořit postup správce plánovače svazku"

#, python-format
msgid "Failed to create snapshot %s"
msgstr "Nelze vytvořit snímek %s"

#, python-format
msgid "Failed to create snapshot for volume %s."
msgstr "Nelze vytvořit snímek pro svazek %s."

#, python-format
msgid "Failed to create thin pool, error message was: %s"
msgstr "Nelze vytvořit mělkou zásobu, chybová zpráva byla: %s"

#, python-format
msgid "Failed to create volume %s"
msgstr "Nelze vytvořit svazek %s"

#, python-format
msgid "Failed to delete cgsnapshot %(id)s due to %(reason)s."
msgstr "Smazání snímku skupiny jednotnosti %(id)s selhalo z důvodu %(reason)s."

#, python-format
msgid "Failed to delete consistency group %(id)s due to %(reason)s."
msgstr "Smazání skupiny jednotnosti %(id)s selhalo z důvodu %(reason)s."

#, python-format
msgid ""
"Failed to delete fileset for consistency group %(cgname)s. Error: %(excmsg)s."
msgstr ""
"Nelze smazat sadu souborů ze skupinu jednotnosti %(cgname)s. Chyba: "
"%(excmsg)s."

#, python-format
msgid "Failed to delete snapshot %s"
msgstr "Nelze smazat snímek %s"

#, python-format
msgid "Failed to detach iSCSI target for volume %(volume_id)s."
msgstr "Nelze odpojit cílové iSCSI pro svazek %(volume_id)s."

msgid "Failed to disassociate qos specs."
msgstr "Nelze odloučit specifikace qos."

#, python-format
msgid "Failed to disassociate qos_specs: %(specs_id)s with type %(type_id)s."
msgstr "Nelze odloučit specifikace qos: %(specs_id)s s typem %(type_id)s."

#, python-format
msgid "Failed to export for volume: %(reason)s"
msgstr "Nelze exportovat pro svazek: %(reason)s"

msgid "Failed to find Storage Center"
msgstr "Nelze najít centrum úložiště"

msgid "Failed to find a vdisk copy in the expected pool."
msgstr "V zadané zásobě nelze najít kopii virtuálního disku."

msgid "Failed to find account for volume."
msgstr "Nelze najít účet pro svazek."

#, python-format
msgid "Failed to find fileset for path %(path)s, command output: %(cmdout)s."
msgstr ""
"Nelze najít sadu souborů pro cestu %(path)s, výstup příkazu: %(cmdout)s."

#, python-format
msgid "Failed to find host %s."
msgstr "Nelze najít hostitele %s."

#, python-format
msgid "Failed to get LUN target details for the LUN %s"
msgstr "Nelze získat podrobnosti cíle LUN pro LUN %s"

#, python-format
msgid "Failed to get LUN target list for the LUN %s"
msgstr "Nelze získat seznam cílů LUN pro LUN %s"

#, python-format
msgid "Failed to get all associations of qos specs %s"
msgstr "Nelze získat všechna přidružení specifikací qos %s"

#, python-format
msgid "Failed to get code level (%s)."
msgstr "Nelze získat úroveň kódu (%s)."

#, python-format
msgid "Failed to get domain because CPG (%s) doesn't exist on array."
msgstr ""
"Nelze získat doménu protože společná skupiny poskytování (%s) neexistuje v "
"poli."

msgid "Failed to get model update from clone"
msgstr "Nelze získat aktualizaci modelu z klona"

msgid "Failed to get name server info."
msgstr "Nelze získat informace o jmenném serveru."

msgid "Failed to get show fcns database info."
msgstr "Nelze získat zobrazení informací o databázi fcns."

#, python-format
msgid "Failed to get size of volume %s"
msgstr "Nelze získat velikost svazku %s"

#, python-format
msgid "Failed to get snapshot for volume %s."
msgstr "Nelze získat snímek pro svazek %s."

#, python-format
msgid "Failed to get target IQN for the LUN %s"
msgstr "Nelze získat cílové IQN pro LUN %s"

#, python-format
msgid "Failed to get target portal for the LUN %s"
msgstr "Nelze získat cílový portál LUN pro LUN %s"

msgid "Failed to get targets"
msgstr "Nelze získat cíle"

msgid "Failed to identify volume backend."
msgstr "Nelze zjistit podpůrnou vrstvu svazku."

#, python-format
msgid "Failed to link fileset for the share %(cgname)s. Error: %(excmsg)s."
msgstr "Nelze propojit sadu souborů se sdílením %(cgname)s. Chyba: %(excmsg)s."

#, python-format
msgid "Failed to log on %s Array (invalid login?)."
msgstr "Nelze se přihlásit k %s Pole (neplatné přihlášení?)."

#, python-format
msgid "Failed to login for user %s."
msgstr "Nelze se přihlásit jako uživatel %s."

msgid "Failed to login with all rest URLs."
msgstr "Nelze se přihlásit pomocí jakékoliv z REST URL."

#, python-format
msgid ""
"Failed to make a request to Datera cluster endpoint due to the following "
"reason: %s"
msgstr ""
"Nelze zažádat pro koncový bod clusteru Datera z následujícího důvodu: %s"

msgid "Failed to manage api volume flow."
msgstr "Nelze spravovat postup api svazku."

#, python-format
msgid ""
"Failed to manage existing %(type)s %(name)s, because reported size %(size)s "
"was not a floating-point number."
msgstr ""
"Nelze spravovat existující %(type)s %(name)s, protože nahlášená velikost "
"%(size)s není číslo s plovoucí desetinnou čárkou."

#, python-format
msgid ""
"Failed to manage existing volume %(name)s, because of error in getting "
"volume size."
msgstr ""
"Nelze spravovat existující svazek %(name)s, protože při získávání velikosti "
"svazku došlo k chybě."

#, python-format
msgid ""
"Failed to manage existing volume %(name)s, because rename operation failed: "
"Error msg: %(msg)s."
msgstr ""
"Nelze spravovat existující svazek %(name)s, protože operace pro přejmenování "
"selhala: Chybová zpráva: %(msg)s."

#, python-format
msgid ""
"Failed to manage existing volume %(name)s, because reported size %(size)s "
"was not a floating-point number."
msgstr ""
"Nelze spravovat existující svazek %(name)s, protože nahlášená velikost "
"%(size)s není číslo s plovoucí desetinnou čárkou."

#, python-format
msgid "Failed to manage volume %s."
msgstr "Nelze spravovat svazek %s."

#, python-format
msgid "Failed to move volume %s."
msgstr "Nelze přesunout svazek %s."

#, python-format
msgid ""
"Failed to parse CLI output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"Nelze zpracovat výstup rozhraní příkazového řádku:\n"
"příkaz: %(cmd)s\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s."

msgid ""
"Failed to parse the configuration option 'keystone_catalog_info', must be in "
"the form <service_type>:<service_name>:<endpoint_type>"
msgstr ""
"Nelze zpracovat volbu nastavení 'keystone_catalog_info', musí být ve formátu "
"<typ služby>:<název služby>:<typ koncového bodu>"

msgid ""
"Failed to parse the configuration option 'swift_catalog_info', must be in "
"the form <service_type>:<service_name>:<endpoint_type>"
msgstr ""
"Nelze zpracovat volbu nastavení 'swift_catalog_info', musí být ve formátu "
"<typ služby>:<název služby>:<typ koncového bodu>"

#, python-format
msgid "Failed to remove export for volume %(volume)s: %(reason)s"
msgstr "Nelze odstranit exportování svazku %(volume)s: %(reason)s"

#, python-format
msgid "Failed to remove iscsi target for volume %(volume_id)s."
msgstr "Nelze odstranit cílové iscsi pro svazek %(volume_id)s."

#, python-format
msgid ""
"Failed to rename logical volume %(name)s, error message was: %(err_msg)s"
msgstr ""
"Nelze přejmenovat logický svazek  %(name)s, chybová zpráva byla: %(err_msg)s"

#, python-format
msgid "Failed to retrieve active zoning configuration %s"
msgstr "Nelze získat aktivní nastavení zónování %s"

#, python-format
msgid "Failed to set QoS for existing volume %(name)s, Error msg: %(msg)s."
msgstr ""
"Nelze nastavit Qos pro existující svazek %(name)s, chybová zpráva: %(msg)s."

msgid "Failed to set attribute 'Incoming user' for SCST target."
msgstr "Nelze nastavit vlastnost 'Incoming user' pro cíl SCST."

#, python-format
msgid ""
"Failed to set permissions for the consistency group %(cgname)s. Error: "
"%(excmsg)s."
msgstr ""
"Nelze nastavit oprávnění pro skupinu jednotnosti %(cgname)s. Chyba: "
"%(excmsg)s."

#, python-format
msgid ""
"Failed to unlink fileset for consistency group %(cgname)s. Error: %(excmsg)s."
msgstr ""
"Nelze odpojit sadu souborů pro skupinu jednotnosti %(cgname)s. Chyba: "
"%(excmsg)s."

#, python-format
msgid "Failed to update metadata for volume: %(reason)s"
msgstr "Nelze aktualizovat popisná data svazku: %(reason)s"

msgid "Failed to update or delete zoning configuration"
msgstr "Nelze aktualizovat nebo smazat nastavení zónování"

#, python-format
msgid "Failed to update qos_specs: %(specs_id)s with specs %(qos_specs)s."
msgstr ""
"Nelze aktualizovat specifikace qos: %(specs_id)s se specifikacemi "
"%(qos_specs)s."

msgid "Failed to update quota usage while retyping volume."
msgstr "Nelze aktualizovat využití kvóty při přetypování svazku."

#, python-format
msgid ""
"Failed updating volume %(vol_id)s metadata using the provided %(src_type)s "
"%(src_id)s metadata"
msgstr ""
"Nelze aktualizovat popisná data svazku %(vol_id)s pomocí zadaných dat "
"%(src_type)s %(src_id)s"

#, python-format
msgid "Failure getting LUN info for %s."
msgstr "Nelze získat informace LUN pro %s."

#, python-format
msgid "Failure moving new cloned LUN to %s."
msgstr "Nelze přesunout nově klonovaný LUN do %s."

#, python-format
msgid "Failure staging LUN %s to tmp."
msgstr "Nelze zařadit LUN %s do tmp."

#, python-format
msgid "Fexvisor failed to add volume %(id)s due to %(reason)s."
msgstr "Flexvisor nemohl přidat svazek %(id)s, z důvodu %(reason)s."

#, python-format
msgid ""
"Fexvisor failed to join the volume %(vol)s in the group %(group)s due to "
"%(ret)s."
msgstr ""
"Flexvisor nemohl připojit svazek %(vol)s ve skupině %(group)s z důvodu "
"%(ret)s."

#, python-format
msgid ""
"Fexvisor failed to remove the volume %(vol)s in the group %(group)s due to "
"%(ret)s."
msgstr ""
"Flexvisor nemohl odstranit svazek %(vol)s ve skupině %(group)s z důvodu "
"%(ret)s."

#, python-format
msgid "Fexvisor failed to remove volume %(id)s due to %(reason)s."
msgstr "Flexvisor nemohl odstranit svazek %(id)s, z důvodu %(reason)s."

#, python-format
msgid "Fibre Channel SAN Lookup failure: %(reason)s"
msgstr "Selhání vyhledávání SAN Fibre Channel: %(reason)s"

#, python-format
msgid "Fibre Channel Zone operation failed: %(reason)s"
msgstr "Selhání zóny operací Fibre Channel: %(reason)s"

#, python-format
msgid "Fibre Channel connection control failure: %(reason)s"
msgstr "Selhání kontroly připojení Fibre Channel: %(reason)s"

#, python-format
msgid "File %(file_path)s could not be found."
msgstr "Soubor %(file_path)s nemohl být nalezen."

#, python-format
msgid "File already exists at %s."
msgstr "Soubor s nastavením již existuje v %s."

#, python-format
msgid "File already exists at: %s"
msgstr "Soubor již existuje v: %s"

msgid "Find host in hostgroup error."
msgstr "Chyba při hledání hostitele ve skupině hostitele."

msgid "Find host lun id error."
msgstr "Chyba při hledání id hostitele lun."

msgid "Find lun group from mapping view error."
msgstr "Chyba při hledání skupiny lun v zobrazení mapování."

msgid "Find mapping view error."
msgstr "Chyba při hledání zobrazení mapování."

msgid "Find portgroup error."
msgstr "Chyba při hledání skupiny portu."

msgid "Find portgroup from mapping view error."
msgstr "Chyba při hledání skupiny portu v zobrazení mapování."

#, python-format
msgid ""
"Flash Cache Policy requires WSAPI version '%(fcache_version)s' version "
"'%(version)s' is installed."
msgstr ""
"Zásada mezipaměti Flash vyžaduje WSAPI verze '%(fcache_version)s', je "
"nainstalována verze '%(version)s'."

#, python-format
msgid "Flexvisor assign volume failed.:%(id)s:%(status)s."
msgstr "Flexvisor nemohl přidělit svazek.:%(id)s:%(status)s."

#, python-format
msgid "Flexvisor assign volume failed:%(id)s:%(status)s."
msgstr "Flexvisor nemohl přidělit svazek:%(id)s:%(status)s."

#, python-format
msgid ""
"Flexvisor could not find volume %(id)s snapshot in the group %(vgid)s "
"snapshot %(vgsid)s."
msgstr ""
"Flexvisor nemohl najít snímek svazku %(id)s ve snímku %(vgsid)s skupiny "
"%(vgid)s."

#, python-format
msgid "Flexvisor create volume failed.:%(volumeid)s:%(status)s."
msgstr "Vytvoření svazku pomocí Flexvisor selhalo:%(volumeid)s:%(status)s."

#, python-format
msgid "Flexvisor failed deleting volume %(id)s: %(status)s."
msgstr "Flexvisor selhal při mazání svazku %(id)s: %(status)s."

#, python-format
msgid "Flexvisor failed to add volume %(id)s to group %(cgid)s."
msgstr "Flexvisor nemohl přidat svazek %(id)s do skupiny %(cgid)s."

#, python-format
msgid ""
"Flexvisor failed to assign volume %(id)s due to unable to query status by "
"event id."
msgstr ""
"Flexvisor nemohl přidělit svazek %(id)s, protože se nešlo dotázat na stav "
"pomocí id události."

#, python-format
msgid "Flexvisor failed to assign volume %(id)s: %(status)s."
msgstr "Flexvisor nemohl přidělit svazek %(id)s: %(status)s."

#, python-format
msgid "Flexvisor failed to assign volume %(volume)s iqn %(iqn)s."
msgstr "Flexvisor nemohl přidělit svazek %(volume)s iqn %(iqn)s."

#, python-format
msgid "Flexvisor failed to clone volume %(id)s: %(status)s."
msgstr "Flexvisor nemohl klonovat svazek %(id)s: %(status)s."

#, python-format
msgid "Flexvisor failed to clone volume (failed to get event) %(id)s."
msgstr "Flexvisor nemohl klonovat svazek (nelze získat událost) %(id)s."

#, python-format
msgid "Flexvisor failed to create snapshot for volume %(id)s: %(status)s."
msgstr "Flexvisor nemohl vytvořit snímek svazku %(id)s: %(status)s."

#, python-format
msgid ""
"Flexvisor failed to create snapshot for volume (failed to get event) %(id)s."
msgstr "Flexvisor nemohl vytvořit snímek svazku (nelze získat událost) %(id)s."

#, python-format
msgid "Flexvisor failed to create volume %(id)s in the group %(vgid)s."
msgstr "Flexvisor nemohl vytvořit svazek %(id)s ve skupině %(vgid)s."

#, python-format
msgid "Flexvisor failed to create volume %(volume)s: %(status)s."
msgstr "Flexvisor nemohl vytvořit svazek %(volume)s: %(status)s."

#, python-format
msgid "Flexvisor failed to create volume (get event) %s."
msgstr "Flexvisor nemohl vytvořit svazek (získání události) %s."

#, python-format
msgid "Flexvisor failed to create volume from snapshot %(id)s: %(status)s."
msgstr "Flexvisor nemohl vytvořit svazek ze snímku %(id)s: %(status)s."

#, python-format
msgid "Flexvisor failed to create volume from snapshot %(id)s:%(status)s."
msgstr "Flexvisor nemohl vytvořit svazek ze snímku %(id)s: %(status)s."

#, python-format
msgid ""
"Flexvisor failed to create volume from snapshot (failed to get event) %(id)s."
msgstr ""
"Flexvisor nemohl vytvořit svazek ze snímku (nelze získat událost) %(id)s."

#, python-format
msgid "Flexvisor failed to delete snapshot %(id)s: %(status)s."
msgstr "Flexvisor nemohl smazat snímek %(id)s: %(status)s."

#, python-format
msgid "Flexvisor failed to delete snapshot (failed to get event) %(id)s."
msgstr "Flexvisor nemohl smazat svazek (nelze získat událost) %(id)s."

#, python-format
msgid "Flexvisor failed to delete volume %(id)s: %(status)s."
msgstr "Flexvisor nemohl smazat svazek %(id)s: %(status)s."

#, python-format
msgid "Flexvisor failed to extend volume %(id)s: %(status)s."
msgstr "Flexvisor nemohl rozšířit svazek %(id)s: %(status)s."

#, python-format
msgid "Flexvisor failed to extend volume %(id)s:%(status)s."
msgstr "Flexvisor nemohl rozšířit svazek %(id)s:%(status)s."

#, python-format
msgid "Flexvisor failed to extend volume (failed to get event) %(id)s."
msgstr "Flexvisor nemohl rozšířit svazek (nelze získat událost) %(id)s."

#, python-format
msgid "Flexvisor failed to get pool info %(id)s: %(status)s."
msgstr "Flexvisor nemohl získat informace o zásobě %(id)s: %(status)s."

#, python-format
msgid ""
"Flexvisor failed to get snapshot id of volume %(id)s from group %(vgid)s."
msgstr "Flexvisor nemohl získat id snímku svazku %(id)s ze skupiny %(vgid)s."

#, python-format
msgid "Flexvisor failed to remove volume %(id)s from group %(cgid)s."
msgstr "Flexvisor nemohl odstranit svazek %(id)s ze skupiny %(cgid)s."

#, python-format
msgid "Flexvisor failed to spawn volume from snapshot %(id)s:%(status)s."
msgstr "Flexvisor nemohl spustit svazek ze snímku %(id)s: %(status)s."

#, python-format
msgid ""
"Flexvisor failed to spawn volume from snapshot (failed to get event) %(id)s."
msgstr ""
"Flexvisor nemohl spustit svazek ze snímku (nelze získat událost) %(id)s."

#, python-format
msgid "Flexvisor failed to unassign volume %(id)s: %(status)s."
msgstr "Flexvisor nemohl zrušit přidělení svazku %(id)s: %(status)s."

#, python-format
msgid "Flexvisor failed to unassign volume (get event) %(id)s."
msgstr "Flexvisor nemohl zrušit přidělení svazku (získání události) %(id)s."

#, python-format
msgid "Flexvisor failed to unassign volume:%(id)s:%(status)s."
msgstr "Flexvisor nemohl zrušit přidělení svazku:%(id)s:%(status)s."

#, python-format
msgid "Flexvisor unable to find the source volume %(id)s info."
msgstr "Flexvisor nemohl najít informace o zdrojovém svazku %(id)s."

#, python-format
msgid "Flexvisor unassign volume failed:%(id)s:%(status)s."
msgstr "Zrušení přidělení svazku pomocí Flexvisor selhalo:%(id)s:%(status)s."

#, python-format
msgid "Flexvisor volume %(id)s failed to join group %(vgid)s."
msgstr "Svazek Flexvisor %(id)s nemohl být připojen ke skupině %(vgid)s."

#, python-format
msgid "GPFS is not running, state: %s."
msgstr "GPFS neběží, stav: %s."

msgid "Get FC ports from array error."
msgstr "Chyba při získávání portů FC z pole."

msgid "Get FC target wwpn error."
msgstr "Chyba při získávání cílového FC wwpn."

msgid "Get LUNcopy information error."
msgstr "Chyba při získávání informací o kopírování LUN."

msgid "Get QoS id by lun id error."
msgstr "Chyba při získávání id QoS pomocí id lun."

msgid "Get QoS information error."
msgstr "Chyba při získávání informací o QoS."

msgid "Get QoS policy error."
msgstr "Chyba při získávání zásad QoS."

msgid "Get cache by name error."
msgstr "Chyba při získávání mezipaměti pomocí názvu."

msgid "Get connected free FC wwn error."
msgstr "Chyba při připojování volného FC wwn."

msgid "Get host initiators info failed."
msgstr "Získávání informací o zavaděčích hostitele selhalo."

msgid "Get hostgroup information error."
msgstr "Chyba při získávání informací o skupině hostitele."

msgid ""
"Get iSCSI port info error, please check the target IP configured in huawei "
"conf file."
msgstr ""
"Chyba při získávání informací o portu iSCSI, prosím zkontrolujte cílovou IP "
"zadanou v souboru s nastavením huawei."

msgid "Get iSCSI port information error."
msgstr "Chyba při získávání informací o portu iSCSI."

msgid "Get iSCSI target port error."
msgstr "Chyba při získávání portu cíle iSCSI."

msgid "Get lun migration task error."
msgstr "Chyba při získávání úkolu o přesunu lun."

msgid "Get lungroup id by lun id error."
msgstr "Chyba při získávání id skupiny lun pomocí id lun."

msgid "Get lungroup information error."
msgstr "Chyba při získávání informací o skupině lun."

msgid "Get partition by name error."
msgstr "Chyba při získávání oddílu podle názvu."

msgid "Get partition by partition id error."
msgstr "Chyba při získávání oddílu pomocí id oddílu."

msgid "Get smartcache by cache id error."
msgstr "Chyba při získávání chytré mezipaměti pomocí id mezipaměti."

msgid "Get snapshot id error."
msgstr "Chyba při získávání id snímku."

msgid "Get target IP error."
msgstr "Chyba při získávání cílové IP adresy."

msgid "Get volume by name error."
msgstr "Chyba při získávání svazku podle názvu."

msgid "Get volume error."
msgstr "Chyba při získávání svazku."

#, python-format
msgid ""
"Glance metadata cannot be updated, key %(key)s exists for volume id "
"%(volume_id)s"
msgstr ""
"Popisná data glance nemohou být aktualizována, klíč %(key)s existuje pro "
"svazek s id %(volume_id)s"

#, python-format
msgid "Glance metadata for volume/snapshot %(id)s cannot be found."
msgstr "Popisná data Glance pro svazek/snímek %(id)s nemohla být nalezena."

#, python-format
msgid "Google Cloud Storage api failure: %(reason)s"
msgstr "Selhání api úložiště Google Cloud: %(reason)s"

#, python-format
msgid "Google Cloud Storage connection failure: %(reason)s"
msgstr "Chyba v připojení k úložišti Google Cloud: %(reason)s"

#, python-format
msgid "Google Cloud Storage oauth2 failure: %(reason)s"
msgstr "Chyba v ověření oauth2 v úložišti Google Cloud: %(reason)s"

#, python-format
msgid "Got bad path information from DRBDmanage! (%s)"
msgstr "Získány špatné informace o cestě z DRBDmanage! (%s)"

msgid "HPELeftHand url not found"
msgstr "HPELeftHand URL nenalezena"

#, python-format
msgid ""
"Hash block size has changed since the last backup. New hash block size: "
"%(new)s. Old hash block size: %(old)s. Do a full backup."
msgstr ""
"Velikost bloku kontrolního součtu byla od poslední zálohy změněna, Nová "
"velikost bloku kontrolního součtu: %(new)s. Stará velikost bloku kontrolního "
"součtu: %(old)s. Proveďte úplnou zálohu."

#, python-format
msgid "Hint \"%s\" not supported."
msgstr "Nápověda \"%s\" není podporována."

msgid "Host"
msgstr "Hostitel"

#, python-format
msgid "Host %(host)s could not be found."
msgstr "Hostitel %(host)s nemohl být nalezen."

#, python-format
msgid "Host %s has no FC initiators"
msgstr "Hostitel %s nemá žádné zavaděče FC"

#, python-format
msgid "Host not found. Failed to remove %(service)s on %(host)s."
msgstr "Hostitel nenalezen. Nelze odstranit %(service)s na %(host)s."

msgid "ID"
msgstr "ID"

msgid ""
"If compression is set to True, rsize must also be set (not equal to -1)."
msgstr ""
"Je-li komprese nastavena na True, pak rsize musí být také nastaveno (nesmí "
"se rovnat -1)."

msgid "If nofmtdisk is set to True, rsize must also be set to -1."
msgstr ""
"Je-li notfmtdisk nastaveno na True, pak rsize musí být také nastaveno na "
"hodnotu -1."

#, python-format
msgid ""
"Illegal value '%(prot)s' specified for flashsystem_connection_protocol: "
"valid value(s) are %(enabled)s."
msgstr ""
"V protokolu připojení k flashsystem byla nalezena neplatná hodnota "
"'%(prot)s': platné hodnoty jsou %(enabled)s."

msgid "Illegal value specified for smarttier: set to either 0, 1, 2, or 3."
msgstr ""
"Zadána neplatná hodnota pro chytrou vrstvu: nastavte buď na 0, 1, 2, či 3."

msgid ""
"Illegal value specified for storwize_svc_vol_grainsize: set to either 32, "
"64, 128, or 256."
msgstr ""
"Zadána neplatná hodnota pro storwize_svc_vol_grainsize: nastavte buď na 32, "
"64, 128, nebo 256."

msgid ""
"Illegal value specified for thin: Can not set thin and thick at the same "
"time."
msgstr ""
"Zadána neplatná hodnota pro hloubku: Nelze zadat najednou thin i thick."

#, python-format
msgid "Image %(image_id)s could not be found."
msgstr "Obraz %(image_id)s nemohl být nalezen."

#, python-format
msgid "Image %(image_id)s is not active."
msgstr "Obraz %(image_id)s není aktivní."

#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr "Obraz %(image_id)s je nepřijatelný: %(reason)s"

msgid "Image location not present."
msgstr "Umístění obrazu není přítomno."

#, python-format
msgid ""
"Image virtual size is %(image_size)dGB and doesn't fit in a volume of size "
"%(volume_size)dGB."
msgstr ""
"Virtuální velikost obrazu je %(image_size)dGB, a proto se nevejde do svazku "
"s velikostí %(volume_size)dGB."

msgid ""
"ImageBusy error raised while deleting rbd volume. This may have been caused "
"by a connection from a client that has crashed and, if so, may be resolved "
"by retrying the delete after 30 seconds has elapsed."
msgstr ""
"Při mazání svazku rbd nastala chyba Obraz je zaneprázdněn. To může být "
"způsobeno připojením od klienta, které bylo přerušeno a, pokud tomu tak je, "
"může být vyřešeno novým pokus o smazání po vypršení 30 vteřin."

msgid "Incremental backups exist for this backup."
msgstr "Pro tuto zálohu existují přírůstkové zálohy."

msgid "Input volumes or snapshots are invalid."
msgstr "Vstupní svazky nebo snímky jsou neplatné."

msgid "Input volumes or source volumes are invalid."
msgstr "Vstupní nebo zdrojové svazky jsou neplatné."

#, python-format
msgid "Instance %(uuid)s could not be found."
msgstr "Instance %(uuid)s nemohla být nalezena."

#, python-format
msgid "Invalid 3PAR Domain: %(err)s"
msgstr "Neplatná doména 3PAR: %(err)s"

msgid "Invalid ALUA value. ALUA value must be 1 or 0."
msgstr "Neplatná hodnota ALUA. Hodnota musí být 1 nebo 0."

msgid "Invalid Ceph args provided for backup rbd operation"
msgstr "Zadány neplatné argumenty Ceph pro záložní operaci rbd"

#, python-format
msgid "Invalid CgSnapshot: %(reason)s"
msgstr "Neplatný snímek skupiny jednotnosti: %(reason)s"

#, python-format
msgid "Invalid ConsistencyGroup: %(reason)s"
msgstr "Neplatná skupina jednotnosti: %(reason)s"

#, python-format
msgid ""
"Invalid HPELeftHand API version found: %(found)s. Version %(minimum)s or "
"greater required for manage/unmanage support."
msgstr ""
"Nalezena neplatná verze API HPELeftHand: %(found)s. Pro podporu spravování "
"je vyžadována verze %(minimum)s nebo vyšší."

#, python-format
msgid "Invalid IP address format: '%s'"
msgstr "Neplatný formát IP adresy: '%s'"

#, python-format
msgid ""
"Invalid QoS specification detected while getting QoS policy for volume %s"
msgstr ""
"Při získávání zásady QoS pro svazek %s byla zjištěna neplatná specifikace QoS"

#, python-format
msgid ""
"Invalid Virtuozzo Storage share specification: %r. Must be: [MDS1[,"
"MDS2],...:/]<CLUSTER NAME>[:PASSWORD]."
msgstr ""
"Neplatná specifikace sdílení úložiště Virtuozzo: %r. Musí být [MDS1[,"
"MDS2],...:/]<NÁZEV CLUSTERU>[:HESLO]."

#, python-format
msgid "Invalid XtremIO version %(cur)s, version %(min)s or up is required"
msgstr "Neplatná verze XtremIO %(cur)s, je vyžadována verze %(min)s nebo vyšší"

msgid "Invalid argument - negative seek offset."
msgstr "Neplatný argument - záporná odchylka hledání."

#, python-format
msgid "Invalid argument - whence=%s not supported."
msgstr "Neplatný argument - whence=%s není podporováno."

#, python-format
msgid "Invalid attaching mode '%(mode)s' for volume %(volume_id)s."
msgstr "Neplatný režim připojení  '%(mode)s' pro svazek %(volume_id)s."

#, python-format
msgid "Invalid auth key: %(reason)s"
msgstr "Neplatný ověřovací klíč: %(reason)s"

#, python-format
msgid "Invalid backup: %(reason)s"
msgstr "Neplatná záloha: %(reason)s"

#, python-format
msgid "Invalid connection initialization response of volume %(name)s"
msgstr "Neplatná odpověď zavedení připojení od svazku %(name)s"

#, python-format
msgid ""
"Invalid connection initialization response of volume %(name)s: %(output)s"
msgstr "Neplatná odpověď zavedení připojení od svazku %(name)s: %(output)s"

#, python-format
msgid "Invalid content type %(content_type)s."
msgstr "Neplatný typ obsahu %(content_type)s."

#, python-format
msgid "Invalid directory: %s"
msgstr "Neplatný adresář: %s"

#, python-format
msgid "Invalid disk adapter type: %(invalid_type)s."
msgstr "Neplatný typ adaptéru disku: %(invalid_type)s."

#, python-format
msgid "Invalid disk backing: %s."
msgstr "Neplatné zálohování disku: %s"

#, python-format
msgid "Invalid disk type: %(disk_type)s."
msgstr "Neplatný typ disku: %(disk_type)s."

#, python-format
msgid "Invalid disk type: %s."
msgstr "Neplatný typ disku: %s"

#, python-format
msgid "Invalid host: %(reason)s"
msgstr "Neplatný hostitel: %(reason)s"

#, python-format
msgid ""
"Invalid hpe3parclient version found (%(found)s). Version %(minimum)s or "
"greater required. Run \"pip install --upgrade python-3parclient\" to upgrade "
"the hpe3parclient."
msgstr ""
"Nalezena neplatná verze hpe3parclient (%(found)s). Je vyžadována verze "
"%(minimum)s a vyšší. Spusťte \"pip install --upgrade python-3parclient\" pro "
"aktualizaci klienta."

#, python-format
msgid ""
"Invalid hpelefthandclient version found (%(found)s). Version %(minimum)s or "
"greater required. Run 'pip install --upgrade python-lefthandclient' to "
"upgrade the hpelefthandclient."
msgstr ""
"Nalezena neplatná verze hpelefthandclient (%(found)s). Je vyžadována verze "
"%(minimum)s a vyšší. Spusťte \"pip install --upgrade python-lefthandclient\" "
"pro aktualizaci klienta."

#, python-format
msgid "Invalid image href %(image_href)s."
msgstr "Neplatný href %(image_href)s obrazu."

msgid "Invalid image identifier or unable to access requested image."
msgstr ""
"Neplatný identifikátor obrazu nrbo nelze získat přístup k požadovanému "
"obrazu."

msgid "Invalid imageRef provided."
msgstr "Zadáno neplatné imageRef."

msgid "Invalid input"
msgstr "Neplatný vstup"

#, python-format
msgid "Invalid input received: %(reason)s"
msgstr "Obdržen neplatný vstup: %(reason)s"

#, python-format
msgid "Invalid is_public filter [%s]"
msgstr "Neplatný filtr is_public [%s]"

#, python-format
msgid "Invalid metadata size: %(reason)s"
msgstr "Neplatná velikost popisných dat: %(reason)s"

#, python-format
msgid "Invalid metadata: %(reason)s"
msgstr "Neplatná popisná data: %(reason)s"

#, python-format
msgid "Invalid mount point base: %s"
msgstr "Neplatná základna bodu připojení: %s"

#, python-format
msgid "Invalid mount point base: %s."
msgstr "Neplatná základna bodu připojení: %s."

#, python-format
msgid "Invalid new snapCPG name for retype.  new_snap_cpg='%s'."
msgstr ""
"Neplatný nový název snímku společné skupiny poskytování pro přetypování.  "
"Nový název='%s'."

#, python-format
msgid "Invalid qos specs: %(reason)s"
msgstr "Neplatné specifikace qos: %(reason)s"

#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr "Neplatné vypršení rezervace %(expire)s."

msgid "Invalid service catalog json."
msgstr "Neplatný json katalog služeb"

msgid "Invalid sheepdog cluster status."
msgstr "Neplatný stav clusteru sheepdog."

#, python-format
msgid "Invalid snapshot: %(reason)s"
msgstr "Neplatný snímek: %(reason)s"

#, python-format
msgid "Invalid status: '%s'"
msgstr "Neplatný stav: '%s'"

#, python-format
msgid "Invalid storage pool %s requested.  Retype failed."
msgstr "Zažádáno o neplatnou zásobu úložiště %s. Přetypování selhalo."

#, python-format
msgid "Invalid storage pool %s specificed."
msgstr "Zadána neplatná zásoba úložiště %s."

#, python-format
msgid "Invalid update setting: '%s'"
msgstr "Neplatné nastavení aktualizace: '%s'"

#, python-format
msgid "Invalid value '%s' for force."
msgstr "Neplatná hodnota '%s' pro vynucení."

msgid "Invalid value for 'scheduler_max_attempts', must be >=1"
msgstr "Neplatná hodnota pro 'scheduler_max_attempts', musí být >=1"

msgid "Invalid value for NetApp configuration option netapp_host_type."
msgstr "Neplatná hodnota pro volbu nastavení NetApp netapp_host_type."

msgid "Invalid value for NetApp configuration option netapp_lun_ostype."
msgstr "Neplatná hodnota pro volbu nastavení NetApp netapp_lun_ostype."

#, python-format
msgid "Invalid value for age, %(age)s"
msgstr "Neplatná hodnota pro věk, %(age)s"

#, python-format
msgid ""
"Invalid volume size provided for create request: %s (size argument must be "
"an integer (or string representation of an integer) and greater than zero)."
msgstr ""
"Zadána neplatná velikost svazku při žádosti o vytvoření: %s (argument "
"velikosti musí být celé číslo (nebo celé číslo zadané pomocí řetězce) a "
"větší než nula)."

#, python-format
msgid "Invalid volume type: %(reason)s"
msgstr "Neplatný typ svazku: %(reason)s"

#, python-format
msgid "Invalid volume: %(reason)s"
msgstr "Neplatný svazek: %(reason)s"

#, python-format
msgid "Invalid volume_type passed: %s."
msgstr "Předán neplatný typ svazku: %s."

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type is not compatible; either "
"match source volume, or omit type argument)."
msgstr ""
"Zadán neplatný typ svazku: %s (požadovaný typ není kompatibilní; buď se musí "
"shodovat se zdrojovým svazkem, nebo vynechejte argument zadávající typ)."

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type is not compatible; "
"recommend omitting the type argument)."
msgstr ""
"Zadán neplatný typ svazku: %s (požadovaný typ není kompatibilní; doporučuje "
"se vynechat argument zadávající typ)"

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type must be supported by this "
"consistency group)."
msgstr ""
"Zadán neplatný typ svazku: %s (požadovaný typ musí být podporován touto "
"skupinou jednotnosti)."

#, python-format
msgid "Invalid wwpns format %(wwpns)s"
msgstr "Neplatný formát wwpns %(wwpns)s"

msgid "Issue encountered waiting for job."
msgstr "Při čekání na úkol se vyskytl problém."

msgid "Issue encountered waiting for synchronization."
msgstr "Při čekání na synchronizaci se vyskytl problém."

msgid ""
"Issuing a fail-over failed because replication is not properly configured."
msgstr ""
"Vyvolání zavedení záložního systému, protože replikace není správně "
"nastavena."

#, python-format
msgid "KeyError: %s"
msgstr "Chyba klíče: %s"

#, python-format
msgid "LUN not found with given ref %s."
msgstr "LUN nenalezena pomocí zadaného odkazu %s."

msgid "LeftHand cluster not found"
msgstr "Cluster LeftHand nebyl nalezen"

#, python-format
msgid "Linked clone of source volume not supported in state: %s."
msgstr "Propojený klon zdrojového svazku není podporován ve stavu: %s."

msgid "Lock acquisition failed."
msgstr "Získání zámku selhalo."

msgid "Logout session error."
msgstr "Chyba odhlášení sezení."

msgid ""
"Lookup service not configured. Config option for fc_san_lookup_service needs "
"to specify a concrete implementation of the lookup service."
msgstr ""
"Služba vyhledávání není nastavena. Volba nastavení fc_san_lookup_service "
"musí udávat konkrétní zavedení této služby."

msgid "Lun migration error."
msgstr "Chyba při přesunu Lun."

#, python-format
msgid "Malformed fcns output string: %s"
msgstr "Poškozený řetězec výstupu fcns: %s"

#, python-format
msgid "Malformed message body: %(reason)s"
msgstr "Poškozené tělo zprávy: %(reason)s"

#, python-format
msgid "Malformed nameserver string: %s"
msgstr "Poškozený řetězec jmenného serveru: %s"

msgid "Malformed request body"
msgstr "Poškozené tělo požadavku"

msgid "Malformed request body."
msgstr "Poškozené tělo požadavku."

msgid "Malformed request url"
msgstr "Poškozená url požadavku"

#, python-format
msgid "Malformed response to command %(cmd)s: %(reason)s"
msgstr "Poškozená odpověď na příkaz %(cmd)s: %(reason)s"

#, python-format
msgid "Malformed show fcns database string: %s"
msgstr "Poškozené zobrazení řetězce databáze fcns: %s"

#, python-format
msgid ""
"Malformed zone configuration: (switch=%(switch)s zone_config="
"%(zone_config)s)."
msgstr ""
"Poškozené nastavení zóny: (rozbočovač=%(switch)s nastavení zóny="
"%(zone_config)s)."

#, python-format
msgid "Malformed zone status: (switch=%(switch)s zone_config=%(zone_config)s)."
msgstr ""
"Poškozený stav zóny: (rozbočovač=%(switch)s nastavení zóny=%(zone_config)s)."

msgid "Manage existing get size requires 'id'."
msgstr "Správa existujícího získání velikosti vyžaduje 'id'."

msgid "Manage existing snapshot not implemented."
msgstr "Správa existujícího snímku není zavedena."

#, python-format
msgid ""
"Manage existing volume failed due to invalid backend reference "
"%(existing_ref)s: %(reason)s"
msgstr ""
"Správa existujícího svazku selhala kvůli neplatnému odkazu na podpůrnou "
"vrstvu %(existing_ref)s: %(reason)s"

#, python-format
msgid "Manage existing volume failed due to volume type mismatch: %(reason)s"
msgstr ""
"Správa existujícího svazku selhala kvůli neshodě s typem svazku: %(reason)s"

msgid "Manage existing volume not implemented."
msgstr "Správa existujícího svazku není zavedena."

msgid "Manage existing volume requires 'source-id'."
msgstr "Správa existujícího svazku vyžaduje 'source-id'."

#, python-format
msgid "Maximum number of backups allowed (%(allowed)d) exceeded"
msgstr "Překročen maximální povolený počet záloh (%(allowed)d)"

#, python-format
msgid "Maximum number of snapshots allowed (%(allowed)d) exceeded"
msgstr "Překročen maximální povolený počet snímků (%(allowed)d)"

#, python-format
msgid ""
"Maximum number of volumes allowed (%(allowed)d) exceeded for quota "
"'%(name)s'."
msgstr ""
"Maximální povolený počet svazků (%(allowed)d) překračuje kvótu '%(name)s'."

#, python-format
msgid "May specify only one of %s"
msgstr "Lze zadat pouze jedno z %s"

msgid "Metadata backup already exists for this volume"
msgstr "Záloha popisných dat je pro tento svazek již vytvořena"

#, python-format
msgid "Metadata backup object '%s' already exists"
msgstr "Object zálohy popisných dat '%s' již existuje"

msgid "Metadata restore failed due to incompatible version"
msgstr "Obnovení popisných dat selhalo kvůli nekompatibilní verzi"

msgid "Metadata restore failed due to incompatible version."
msgstr "Obnovení popisných dat selhalo kvůli nekompatibilní verzi."

msgid ""
"Missing 'purestorage' python module, ensure the library is installed and "
"available."
msgstr ""
"Chybí python modul 'purestorage', ujistěte se, že knihovna je nainstalovaná "
"a dostupná."

msgid "Missing Fibre Channel SAN configuration param - fc_fabric_names"
msgstr "Chybí parametr nastavení Fibre Channel SAN - fc_fabric_names"

msgid "Missing request body."
msgstr "Chybí tělo žádosti."

#, python-format
msgid "Missing required element '%s' in request body."
msgstr "V těle žádosti chybí povinný prvek '%s'."

#, python-format
msgid "Multiple copies of volume %s found."
msgstr "Nalezeno mnoho kopií svazku %s."

#, python-format
msgid "Multiple matches found for '%s', use an ID to be more specific."
msgstr "Nalezeno mnoho shod pro '%s', použijte ID pro zpřesnění hledání."

msgid "Multiple profiles found."
msgstr "Nalezeno mnoho profilů."

msgid "Must implement a fallback schedule"
msgstr "Je nutné zavést záložní plán"

msgid "Must implement schedule_create_volume"
msgstr "Je nutné zavést schedule_create_volume"

msgid "Must implement schedule_get_pools"
msgstr "Je nutné zavést schedule_get_pools"

msgid "Must pass wwpn or host to lsfabric."
msgstr "lsfabric je nutné předat wwpn nebo host."

msgid ""
"Must specify 'status', 'attach_status' or 'migration_status' for update."
msgstr ""
"Pro aktualizaci musíte zadat 'status', 'attach_status' nebo "
"'migration_status'."

#, python-format
msgid "Must specify a valid persona %(valid)s,value '%(persona)s' is invalid."
msgstr ""
"Musíte zadat platnou persónu %(valid)s, hodnota '%(persona)s' není platná."

#, python-format
msgid ""
"Must specify a valid provisioning type %(valid)s, value '%(prov)s' is "
"invalid."
msgstr ""
"Musíte zadat platný typ poskytování %(valid)s, hodnota '%(prov)s' je "
"neplatná."

msgid "Must specify an ExtensionManager class"
msgstr "Musí být určena třída ExtensionManager"

msgid "Must specify storage pools. Option: sio_storage_pools."
msgstr "Musíte zadat zásoby úložiště. Volba: sio_storage_pools."

msgid "Must supply a positive value for age"
msgstr "Věk musí být zadán pomocí kladné hodnoty"

#, python-format
msgid ""
"NAS config '%(name)s=%(value)s' invalid. Must be 'auto', 'true', or 'false'"
msgstr ""
"Nastavení NAS '%(name)s=%(value)s' je neplatné. Musí být buď 'auto', 'true', "
"nebo 'false'"

#, python-format
msgid "NFS config file at %(config)s doesn't exist"
msgstr "Soubor s nastavením NFS v %(config)s neexistuje"

#, python-format
msgid "NFS file %s not discovered."
msgstr "Soubor NFS %s nebyl nalezen."

msgid "NFS file could not be discovered."
msgstr "Soubor NFS nemohl být nalezen."

msgid "NaElement name cannot be null."
msgstr "Název NaElement nemůže být prázdný."

msgid "Name"
msgstr "Název"

msgid ""
"Name, description, add_volumes, and remove_volumes can not be all empty in "
"the request body."
msgstr ""
"V těle žádosti nemohou být název, popis, přidání svazků, či odebrání svazků "
"všechny prázdné."

msgid "Need non-zero volume size"
msgstr "Je třeba zadat nenulovou velikost svazku"

msgid "NetApp Cinder Driver exception."
msgstr "Výjimka ovladače NetApp Cinder."

#, python-format
msgid ""
"New size for extend must be greater than current size. (current: %(size)s, "
"extended: %(new_size)s)."
msgstr ""
"Nová velikost pro rozšíření musí být větší než současná. (současná: "
"%(size)s, rozšířená: %(new_size)s)."

msgid "New volume type not specified in request_spec."
msgstr "Nový typ svazku nebyl zadán ve specifikaci žádosti."

msgid "Nimble Cinder Driver exception"
msgstr "Výjimka ovladače Nimble Cinder"

msgid "No active iSCSI portals with supplied iSCSI IPs"
msgstr "Žádné aktivní portály iSCSI zadané pomocí IP iSCSI"

msgid "No backups available to do an incremental backup."
msgstr "Žádná záloha pro provedení přírůstkové zálohy."

#, python-format
msgid "No cloned LUN named %s found on the filer"
msgstr "Ve správci souborů nebyl nalezen klonovaný LUN s názvem %s"

msgid "No config node found."
msgstr "Nenalezen žádný uzel nastavení."

#, python-format
msgid "No element by given name %s."
msgstr "Žádný prvek podle zadaného názvu %s."

#, python-format
msgid "No file found with %s as backing file."
msgstr "V  %s nenalezen žádný záložní soubor."

msgid "No iSCSI-enabled ports on target array."
msgstr "V cílovém poli není žádný port umožňující iSCSI."

#, python-format
msgid "No initiator group found for initiator %s"
msgstr "Pro zavaděče %s nebyla nalezena žádná skupina zavaděče"

#, python-format
msgid "No interface found on cluster for ip %s"
msgstr "V clusteru s ip adresou %s nenalezeno žádné rozhraní."

msgid "No ip address found."
msgstr "Žádná ip adresa nenalezena."

msgid "No mounted NFS shares found"
msgstr "Nenalezena žádná připojená sdílení NFS"

msgid "No mounted SMBFS shares found."
msgstr "Nenalezena žádná připojená sdílení SMBFS"

msgid "No mounted Virtuozzo Storage shares found"
msgstr "Nenalezena žádné připojená sdílení Virtuozzo"

msgid "No mounted shares found"
msgstr "Nenalezena žádná připojená sdílení"

#, python-format
msgid "No node found in I/O group %(gid)s for volume %(vol)s."
msgstr ""
"Ve skupině vstupu/výstupu %(gid)s nenalezen žádný uzel pro svazek %(vol)s."

msgid ""
"No pools are available for provisioning volumes. Ensure that the "
"configuration option netapp_pool_name_search_pattern is set correctly."
msgstr ""
"Pro poskytující svazky nejsou dostupné žádné zásoby. Ujistěte se, že volba "
"netapp_pool_name_search_pattern je nastavena správně."

#, python-format
msgid "No snap found with %s as backing file."
msgstr "Nenalezen žádný snímek kde %s je záložní soubor."

#, python-format
msgid "No such QoS spec %(specs_id)s."
msgstr "Žádné takové specifikace QoS: %(specs_id)s."

msgid "No suitable discovery ip found"
msgstr "Nenalezena žádná vhodná zjišťovací ip adresa"

#, python-format
msgid "No support to restore backup version %s"
msgstr "Pro obnovení zálohy verze %s není žádná podpora"

#, python-format
msgid "No target id found for volume %(volume_id)s."
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#, python-format
msgid ""
"No volume on cluster with vserver %(vserver)s and junction path %(junction)s "
msgstr ""
"Žádný svazek v clusteru na virtuálním serveru %(vserver)s a cestě spojení "
"%(junction)s"

msgid "Not a valid value for NaElement."
msgstr "Neplatná hodnota pro NaElement."

msgid "Not an rbd snapshot"
msgstr "Není snímkem rbd"

#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr "Nemáte oprávnění k obrazu %(image_id)s."

msgid "Not authorized."
msgstr "Není povoleno."

#, python-format
msgid "Not enough space on backend (%(backend)s)"
msgstr "Na podpůrné vrstvě je nedostatek místa (%(backend)s)"

msgid "Not enough storage space in the ZFS share to perform this operation."
msgstr ""
"Ve sdílení ZFS není dostatek úložného prostoru k provedení této operace."

msgid "Not stored in rbd"
msgstr "Neuloženo v rbd"

msgid "Nova returned \"error\" status while creating snapshot."
msgstr "Při vytváření snímku Nova vrátila stav \"error\"."

msgid "Object Count"
msgstr "Počet objektů"

msgid "Object is not a NetApp LUN."
msgstr "Objekt není NetApp LUN."

#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""
"Pouze %(value)s požadavky %(verb)s mohou být provedeny pro %(uri)s každých "
"%(unit_string)s."

msgid "Only one limit can be set in a QoS spec."
msgstr "Ve specifikaci QoS lze nastavit pouze jednu mez."

msgid ""
"Only users with token scoped to immediate parents or root projects are "
"allowed to see its children quotas."
msgstr ""
"Pouze uživatelé mající příznak z nadřazených nebo kořenových projektů mají "
"povoleno zobrazit kvóty podřazených projektů"

msgid "Only volumes managed by OpenStack can be unmanaged."
msgstr "Zrušit správu lze pouze u svazků, jenž spravuje OpenStack."

#, python-format
msgid "Operation failed with status=%(status)s. Full dump: %(data)s"
msgstr "Operace selhala se stavem=%(status)s. Úplný výpis: %(data)s"

#, python-format
msgid "Operation not supported: %(operation)s."
msgstr "Operace není podporována: %(operation)s."

msgid "Option gpfs_images_dir is not set correctly."
msgstr "Volba gpfs_images_dir není správně nastavena."

msgid "Option gpfs_mount_point_base is not set correctly."
msgstr "Volba gpfs_mount_point_base není správně nastavena."

#, python-format
msgid "Originating %(res)s %(prop)s must be one of '%(vals)s' values"
msgstr "Původní %(res)s %(prop)s musí mít jednu z hodnot '%(vals)s'"

#, python-format
msgid "ParseException: %s"
msgstr "Chyba zpracování: %s"

msgid "Partition name is None, please set smartpartition:partitionname in key."
msgstr ""
"Název oddílu je None, prosím nastavte smartpartition:partitionname v klíči."

msgid ""
"Password or SSH private key is required for authentication: set either "
"san_password or san_private_key option."
msgstr ""
"Heslo nebo soukromý klíč SSH jsou vyžadovány pro ověření: nastavte volbu "
"san_password nebo san_private_key."

msgid "Path to REST server's certificate must be specified."
msgstr "Cesta k certifikátu serveru REST musí být zadána."

#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr "Zásada nedovoluje, aby bylo %(action)s provedeno."

msgid "Pool is not available in the volume host field."
msgstr "Zásoba není dostupná v poli hostitel svazku."

msgid "Pool is not available in the volume host fields."
msgstr "Zásoba není dostupná v polích hostitele svazku."

#, python-format
msgid "Pool with name %(pool_name)s wasn't found in domain %(domain_id)s."
msgstr "Zásoba s názvem %(pool_name)s nebyla nalezena v doméně %(domain_id)s."

msgid "Project ID"
msgstr "ID projektu"

#, python-format
msgid "Project quotas are not properly setup for nested quotas: %(reason)s."
msgstr "Kvóty projekty nejsou pro vnořené kvóty správně nastaveny: %(reason)s."

#, python-format
msgid ""
"Protocol %(storage_protocol)s is not supported for storage family "
"%(storage_family)s."
msgstr ""
"Protokol %(storage_protocol)s není podporován u úložišť druhu "
"%(storage_family)s."

msgid "Provided backup record is missing an id"
msgstr "Zadanému záznamu zálohy chybí id"

#, python-format
msgid ""
"Provided snapshot status %(provided)s not allowed for snapshot with status "
"%(current)s."
msgstr ""
"Zadaný stav snímku %(provided)s není povolen pro snímek se stavem "
"%(current)s."

#, python-format
msgid "Pure Storage Cinder driver failure: %(reason)s"
msgstr "Selhání ovladače Pure Storage Cinder: %(reason)s"

#, python-format
msgid "QoS Specs %(specs_id)s already exists."
msgstr "Specifikace QoS %(specs_id)s již existuje."

#, python-format
msgid "QoS Specs %(specs_id)s is still associated with entities."
msgstr "Specifikace QoS %(specs_id)s je stále přidružena k entitám."

#, python-format
msgid "QoS spec %(specs_id)s has no spec with key %(specs_key)s."
msgstr ""
"Specifikace QoS %(specs_id)s nemají specifikace s klíčem %(specs_key)s."

msgid "Qos specs still in use."
msgstr "Specifikace QoS se stále používá."

msgid "Query resource pool error."
msgstr "Chyba při dotazování zásoby zdroje."

#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr "Třída kvóty %(class_name)s nemohla být nalezena."

msgid "Quota could not be found"
msgstr "Kvóta nemohla být nalezena."

#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr "Kvóta překročena pro zdroje: %(overs)s"

#, python-format
msgid "Quota exceeded: code=%(code)s"
msgstr "Kvóta překročena: kód=%(code)s"

#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr "Kvóta pro projekt %(project_id)s nemohla být nalezena."

#, python-format
msgid ""
"Quota limit invalid for project '%(proj)s' for resource '%(res)s': limit of "
"%(limit)d is less than in-use value of %(used)d"
msgstr ""
"Limit kvóty je pro zdroj '%(res)s' projektu '%(proj)s neplatný: limit "
"%(limit)d je menší než použitá hodnota %(used)d"

#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr "Rezervace kvóty %(uuid)s nemohla být nalezena."

#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr "Využití kvóty pro projekt %(project_id)s nemohla být nalezena."

#, python-format
msgid "RBD diff op failed - (ret=%(ret)s stderr=%(stderr)s)"
msgstr ""
"RBD operace porovnání selhala - (ret=%(ret)s chybový výstup=%(stderr)s)"

#, python-format
msgid "REST %(proxy_ver)s hpelefthandclient %(rest_ver)s"
msgstr "REST %(proxy_ver)s, hpelefthandclient %(rest_ver)s"

#, python-format
msgid "Received error string: %s"
msgstr "Obdržen chybový řetězec: %s"

msgid "Reference must be for an unmanaged snapshot."
msgstr "Odkaz musí být pro nespravovaný snímek."

msgid "Reference must be for an unmanaged virtual volume."
msgstr "Odkaz musí být pro nespravovaný virtuální svazek."

msgid "Reference must be the volume name of an unmanaged virtual volume."
msgstr "Odkaz musí být název nespravovaného virtuálního svazku."

msgid "Reference must contain source-id or source-name key."
msgstr "Odkaz musí obsahovat zdrojové id, nebo klíč mající názem zdroje."

msgid "Reference must contain source-id or source-name."
msgstr "Odkaz musí obsahovat id nebo název zdroje."

msgid "Reference must contain source-name element."
msgstr "Odkaz musí obsahovat prvek source-name."

msgid "Reference must contain source-name or source-id."
msgstr "Odkaz musí obsahovat source-name nebo source-id."

msgid "Reference must contain source-name."
msgstr "Odkaz musí obsahovat název zdroje."

#, python-format
msgid ""
"Refusing to migrate volume ID: %(id)s. Please check your configuration "
"because source and destination are the same Volume Group: %(name)s."
msgstr ""
"Přesun svazku s ID: %(id)s zamítnut. Prosím zkontrolujte své nastavené "
"protože zdroj a cíl jsou ve stejné skupině svazku: %(name)s."

msgid "Remove CHAP error."
msgstr "Chyba při odstraňování CHAP."

msgid "Remove fc from host error."
msgstr "Chyba při odstraňování fc z hostitele."

msgid "Remove host from array error."
msgstr "Chyba při odstraňování hostitele z pole."

msgid "Remove host from hostgroup error."
msgstr "Chyba při odstraňování hostitele ze skupiny hostitele."

msgid "Remove iscsi from host error."
msgstr "Chyba při odstraňování iscsi z hostitele."

msgid "Remove lun from cache error."
msgstr "Chyba při odstraňování lun z mezipaměti."

msgid "Remove lun from partition error."
msgstr "Chyba při odstraňování lun z oddílu."

msgid "Remove volume export failed."
msgstr "Odstranění exportu svazku selhalo."

msgid "Rename lun on array error."
msgstr "Chyba při přejmenování lun v poli."

msgid "Request body and URI mismatch"
msgstr "Neshoda s tělem požadavku a URI"

msgid "Request body contains too many items"
msgstr "Tělo požadavku obsahuje příliš mnoho položek"

#, python-format
msgid "Request to Datera cluster returned bad status: %(status)s | %(reason)s"
msgstr ""
"Požadavek pro cluster Datera vrátil špatný stav: %(status)s | %(reason)s"

#, python-format
msgid ""
"Requested backup exceeds allowed Backup gigabytes quota. Requested "
"%(requested)sG, quota is %(quota)sG and %(consumed)sG has been consumed."
msgstr ""
"Požadovaná záloha překračuje povolenou kvótu gigabajtů zálohy.  Požadováno "
"%(requested)sG, kvóta je %(quota)sG a bylo spotřebováno %(consumed)sG."

#, python-format
msgid ""
"Requested volume or snapshot exceeds allowed %(name)s quota. Requested "
"%(requested)sG, quota is %(quota)sG and %(consumed)sG has been consumed."
msgstr ""
"Požadovaný svazek nebo snímek překračuje povolenou kvótu %(name)s. "
"Požadováno %(requested)sG, kvóta je %(quota)sG a bylo spotřebováno "
"%(consumed)sG."

msgid "Required configuration not found"
msgstr "Požadované nastavení nenalezeno."

#, python-format
msgid ""
"Reset backup status aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"Resetování stavu zálohy zrušeno, v současnosti nastavená služba záloh "
"[%(configured_service)s] není stejnou službou použitou k vytvoření této "
"zálohy [%(backup_service)s]."

#, python-format
msgid "Resizing clone %s failed."
msgstr "Změna velikosti klonu %s selhala."

msgid "Resizing image file failed."
msgstr "Změna velikosti obrazu selhala."

msgid "Resource could not be found."
msgstr "Zdroj nemohl být nalezen."

msgid "Resource not ready."
msgstr "Zdroj není připraven."

#, python-format
msgid ""
"Restore backup aborted, expected volume status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"Obnovení zálohy zrušeno, očekávaný stav svazku je %(expected_status)s ale "
"zjištěný stav je %(actual_status)s."

#, python-format
msgid ""
"Restore backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"Obnovení zálohy zrušeno, v současnosti nastavená služba záloh "
"[%(configured_service)s] není stejnou službou použitou k vytvoření této "
"zálohy [%(backup_service)s]."

#, python-format
msgid ""
"Restore backup aborted: expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"Obnovení zálohy zrušeno, očekávaný stav zálohy je %(expected_status)s ale "
"zjištěný stav je %(actual_status)s."

#, python-format
msgid "Retry count exceeded for command: %s"
msgstr "Počet pokusů překročen pro příkaz: %s"

msgid "Retryable SolidFire Exception encountered"
msgstr "Zjištěna opakovatelná výjimka SolidFire"

msgid "Retype requires migration but is not allowed."
msgstr "Přetypování vyžaduje přesun ale ten není povolen."

#, python-format
msgid ""
"Running Cinder with a VMware vCenter version less than %s is not allowed."
msgstr ""
"Spouštět Cinder pomocí VMware vCenter s verzí starší než %s není povoleno."

#, python-format
msgid "SMBFS config file at %(config)s doesn't exist."
msgstr "Soubor s nastavením SMBFS %(config)s neexistuje."

msgid "SMBFS config file not set (smbfs_shares_config)."
msgstr "Soubor s nastavením SMBFS není zadán "

#, python-format
msgid "SSH Command failed after '%(total_attempts)r' attempts : '%(command)s'"
msgstr "Příkaz SSH selhal po '%(total_attempts)r' pokusech : '%(command)s'"

#, python-format
msgid "SSH command injection detected: %(command)s"
msgstr "Zjištěno vložení příkazů SSH: %(command)s"

#, python-format
msgid "SSH connection failed for %(fabric)s with error: %(err)s"
msgstr "SSH připojení selhalo v %(fabric)s s chybou: %(err)s"

#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr "Filtr hostitelů plánovače %(filter_name)s nemohl být nalezen."

#, python-format
msgid "Scheduler Host Weigher %(weigher_name)s could not be found."
msgstr "Váha plánovače hostitele %(weigher_name)s nemohla být nalezena."

#, python-format
msgid "Service %(service)s on host %(host)s removed."
msgstr "Služba %(service)s odstraněna na hostiteli %(host)s."

#, python-format
msgid "Service %(service_id)s could not be found."
msgstr "Služba %(service_id)s nemohla být nalezena."

msgid "Service is unavailable at this time."
msgstr "Služba je v tuto chvíli nedostupná."

msgid "Sets thin provisioning."
msgstr "Nastaví mělké poskytování."

#, python-format
msgid "Sheepdog I/O Error, command was: \"%s\"."
msgstr "Chyba vstupu/výstupu Sheepdog, příkaz byl: \"%s\"."

msgid ""
"Show operations can only be made to projects in the same hierarchy of the "
"project in which users are scoped to."
msgstr ""
"Zobrazení operací lze pouze u projektů ve stejné hierarchii jako projekt do "
"kterého jsou uživatelé zařazeni."

msgid "Size"
msgstr "Velikost"

#, python-format
msgid "Size for volume: %s not found, cannot secure delete."
msgstr "Velikost pro svazek: %s nenalezeno, nelze bezpečně smazat."

#, python-format
msgid ""
"Size of specified image %(image_size)sGB is larger than volume size "
"%(volume_size)sGB."
msgstr ""
"Velikost zadaného obrazu %(image_size)sGB je větší než velikost svazku "
"%(volume_size)sGB."

#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr "Snímek %(snapshot_id)s nemohl být nalezen."

#, python-format
msgid "Snapshot %(snapshot_id)s has no metadata with key %(metadata_key)s."
msgstr ""
"Snímek %(snapshot_id)s nemá žádná popisná data mající klíč %(metadata_key)s."

#, python-format
msgid "Snapshot '%s' doesn't exist on array."
msgstr "Snímek '%s' neexistuje v poli."

msgid "Snapshot cannot be created while volume is migrating."
msgstr "Snímek nemůže být vytvořen při přesunu svazku."

msgid "Snapshot of secondary replica is not allowed."
msgstr "Snímek druhotné repliky není povolen."

#, python-format
msgid "Snapshot of volume not supported in state: %s."
msgstr "Snímek svazku není podporován ve stavu: %s."

#, python-format
msgid "Snapshot res \"%s\" that is not deployed anywhere?"
msgstr "Zdroj snímku \"%s\" který není nikde zaveden?"

#, python-format
msgid "Snapshot status %(cur)s not allowed for update_snapshot_status"
msgstr "Stav snímku %(cur)s není povolen při aktualizaci stavu snímku"

#, python-format
msgid ""
"Snapshot to be backed up must be available, but the current status is \"%s\"."
msgstr "Zálohovaný snímek musí být dostupný, ale jeho stav je nyní \"%s\"."

msgid "SolidFire Cinder Driver exception"
msgstr "Výjimka ovladače SolidFire Cinder"

msgid "Sort direction array size exceeds sort key array size."
msgstr "Pole směru řazení překračuje velikost pole klíče řazení."

msgid "Source host details not found."
msgstr "Podrobnosti zdrojového hostitele nenalezeny."

msgid "Source volume device ID is required."
msgstr "ID zařízení zdrojového svazku je vyžadováno."

msgid "Source volume not mid-migration."
msgstr "Zdrojový svazek není uprostřed přesunu."

msgid "Specify a password or private_key"
msgstr "Zadejte heslo nebo soukromý klíč"

msgid "Specify san_password or san_private_key"
msgstr "Zadejte san_password nebo san_private_key"

msgid "Start LUNcopy error."
msgstr "Chyba při spuštění kopírování LUN."

msgid "State"
msgstr "Stav"

#, python-format
msgid "State of node is wrong. Current state is %s."
msgstr "Špatný stav uzlu. Současný stav je %s."

msgid "Status"
msgstr "Stav"

msgid "Stop snapshot error."
msgstr "Chyba při zastavování snímku."

#, python-format
msgid "Storage family %s is not supported."
msgstr "Druhy úložiště %s nejsou podporovány."

#, python-format
msgid "Storage profile: %(storage_profile)s not found."
msgstr "Profil úložiště: %(storage_profile)s nenalezen."

msgid "System does not support compression."
msgstr "Systém nepodporuje kompresi."

msgid "System is busy, retry operation."
msgstr "Systém je zaneprázdněn, zopakujte operaci."

msgid "Target volume type is still in use."
msgstr "Cílový typ svazku se stále používá."

msgid "Terminate connection failed"
msgstr "Ukončení připojení selhalo"

msgid "Terminate connection unable to connect to backend."
msgstr "Nelze se připojit k podpůrné vrstvě pro ukončení připojení."

#, python-format
msgid "Terminate volume connection failed: %(err)s"
msgstr "Ukončení připojení svazku selhalo: %(err)s"

msgid ""
"The 'sort_key' and 'sort_dir' parameters are deprecated and cannot be used "
"with the 'sort' parameter."
msgstr ""
"Parametry 'sort_key' a 'sort_dir' jsou zastaralé a nemohou být použity s "
"parametrem 'sort'."

#, python-format
msgid ""
"The GPFS filesystem %(fs)s is not at the required release level.  Current "
"level is %(cur)s, must be at least %(min)s."
msgstr ""
"Systém souborů GPFS %(fs)s není na požadované úrovni vydání. Současná úroveň "
"je %(cur)s, musí být alespoň %(min)s."

#, python-format
msgid ""
"The WebDAV request failed. Reason: %(msg)s, Return code/reason: %(code)s, "
"Source Volume: %(src)s, Destination Volume: %(dst)s, Method: %(method)s."
msgstr ""
"Požadavek WebDAV selhal. Důvod: %(msg)s, návratový kód/důvod: %(code)s, "
"zdrojový svazek: %(src)s, cílový svazek: %(dst)s. metoda %(method)s."

msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using 'cinder-manage db sync' before running this "
"command."
msgstr ""
"Chyba výše naznačuje, že databáze nebyla vytvořena.\n"
"Prosím vytvořte ji pomocí 'cinder-manage db sync' před zadáním tohoto "
"příkazu."

msgid "The copy should be primary or secondary"
msgstr "Kopie by měla být primární nebo sekundární"

msgid "The decorated method must accept either a volume or a snapshot object"
msgstr "Dekorovaná metoda musí přijímat buď objekt svazku nebo objekt snímku "

#, python-format
msgid "The device in the path %(path)s is unavailable: %(reason)s"
msgstr "Zařízení na cestě %(path)s není dostupné: %(reason)s"

#, python-format
msgid "The end time (%(end)s) must be after the start time (%(start)s)."
msgstr "Doba konce (%(end)s) musí být po době začátku (%(start)s)."

#, python-format
msgid "The failed-over volume could not be deleted: %s"
msgstr "Záložní svazek nelze smazat: %s."

msgid "The method update_migrated_volume is not implemented."
msgstr "Metoda update_migrated_volume není zavedena."

msgid "The parent backup must be available for incremental backup."
msgstr "Pro provedení přírůstkové zálohy musí být dostupná nadřazená záloha."

#, python-format
msgid "The provided snapshot '%s' is not a snapshot of the provided volume."
msgstr "Zadaný snímek '%s' není snímek zadaného svazku."

msgid ""
"The replication mode was not configured correctly in the volume type "
"extra_specs. If replication:mode is periodic, replication:sync_period must "
"also be specified and be between 300 and 31622400 seconds."
msgstr ""
"Režim replikace nebyl v dodatečných specifikacích svazku správně nastaven. "
"Pokud je režim periodic, musí být také zadáno replication:sync_period a mít "
"zvolen interval mající hodnotu od 300 až 31622400 vteřin."

msgid "The results are invalid."
msgstr "Výsledky jsou neplatné."

msgid "The snapshot cannot be created when the volume is in maintenance mode."
msgstr "Snímek nelze vytvořit, zatímco svazek je v režimu údržby."

msgid "The source volume for this WebDAV operation not found."
msgstr "Zdrojový svazek nebyl nalezen pro tuto operaci WebDAV."

#, python-format
msgid ""
"The source volume type '%(src)s' is different than the destination volume "
"type '%(dest)s'."
msgstr "Typ zdrojového svazku '%(src)s' je jiný než cílový typ '%(dest)s'."

#, python-format
msgid "The source volume type '%s' is not available."
msgstr "Typ zdrojového svazku '%s' není dostupný."

msgid "The specified vdisk is mapped to a host."
msgstr "Zadaný virtuální disk je mapován k hostiteli."

#, python-format
msgid ""
"The type of metadata: %(metadata_type)s for volume/snapshot %(id)s is "
"invalid."
msgstr ""
"Typ popisných dat: %(metadata_type)s pro svazek/snímek %(id)s je neplatný."

msgid "The volume cannot accept transfer in maintenance mode."
msgstr "Svazek nemůže v režimu údržby přijímat přenosy v režimu údržby."

msgid "The volume cannot be attached in maintenance mode."
msgstr "Svazek nemůže být během údržby připojen."

msgid "The volume cannot be detached in maintenance mode."
msgstr "Svazek nemůže být během údržby odpojen."

msgid "The volume cannot be updated during maintenance."
msgstr "Svazek nemůže být během údržby spravován."

msgid "The volume connection cannot be initialized in maintenance mode."
msgstr "Připojení ke svazku nemůže být zavedeno v režimu údržby."

msgid "The volume driver requires the iSCSI initiator name in the connector."
msgstr "Ovladač svazku vyžaduje název zavaděče iSCSI v konektoru."

msgid ""
"The volume is currently busy on the 3PAR and cannot be deleted at this time. "
"You can try again later."
msgstr ""
"Svazek je v současnosti zaneprázdněn v 3PAR a nemůže být nyní smazán. Prosím "
"zkuste to znovu později."

msgid "There are no valid ESX hosts."
msgstr "Žádní platní hostitelé ESX."

msgid "There are no valid datastores."
msgstr "Žádná platná datová úložiště."

msgid "There is no metadata in DB object."
msgstr "V objektu DB nejsou žádná popisná data."

#, python-format
msgid "There is no share which can host %(volume_size)sG"
msgstr "Neexistuje sdílení schopné hostit %(volume_size)sG"

#, python-format
msgid "There is no share which can host %(volume_size)sG."
msgstr "Neexistuje sdílení schopné hostit %(volume_size)sG."

msgid "There is no virtual disk device."
msgstr "Neexistuje žádné zařízení virtuálního disku."

#, python-format
msgid "There was an error adding the volume to the remote copy group: %s."
msgstr "Při přidávání svazku do skupiny vzdálené kopie se vyskytla chyba: %s."

#, python-format
msgid "There was an error creating the cgsnapshot: %s"
msgstr "Při vytváření snímku skupiny jednotnosti nastala chyba: %s"

#, python-format
msgid "There was an error creating the remote copy group: %s."
msgstr "Při vytváření skupiny vzdálené kopie se vyskytla chyba: %s"

#, python-format
msgid ""
"There was an error setting the sync period for the remote copy group: %s."
msgstr ""
"Při nastavování doby synchronizace skupiny vzdálené kopie se vyskytla chyba: "
"%s"

#, python-format
msgid ""
"There was an error setting up a remote copy group on the 3PAR arrays: "
"('%s'). The volume will not be recognized as replication type."
msgstr ""
"Při nastavování skupiny vzdálené kopie na polích 3PAR se vyskytla chyba: "
"('%s'). Svazek nebude rozpoznán jako mající typ pocházející od replikace."

#, python-format
msgid "There was an error starting remote copy: %s."
msgstr "Při spouštění vzdálené kopie se vyskytla chyba: %s"

#, python-format
msgid "There's no NFS config file configured (%s)"
msgstr "Není zadán žádný soubor s nastavením NFS (%s)"

#, python-format
msgid ""
"There's no Quobyte volume configured (%s). Example: quobyte://<DIR host>/"
"<volume name>"
msgstr ""
"Není nastaven žádný svazek Quobyte (%s). Příklad: quobyte://<adresář "
"hostitele>/<název svazku>"

msgid "Thin provisioning not supported on this version of LVM."
msgstr "Mělké poskytování není podporováno v této verzi LVM."

msgid "This request was rate-limited."
msgstr "Tento požadavek má omezené množství."

#, python-format
msgid ""
"This system platform (%s) is not supported. This driver supports only Win32 "
"platforms."
msgstr ""
"Tato systémová platforma (%s) není podporována. Tento ovladač podporuje "
"pouze platformy Win32."

#, python-format
msgid "Timed out while waiting for Nova update for creation of snapshot %s."
msgstr "Při čekání na aktualizaci od Nova při vytváření snímku %s vypršel čas."

#, python-format
msgid ""
"Timed out while waiting for Nova update for deletion of snapshot %(id)s."
msgstr ""
"Při čekání na aktualizaci od Nova při mazání snímku %(id)s vypršel čas."

#, python-format
msgid "Timeout while requesting %(service)s API."
msgstr "Při žádání o API %(service)s vypršel časový limit."

#, python-format
msgid "Transfer %(transfer_id)s could not be found."
msgstr "Přenos %(transfer_id)s nemohl být nalezen."

#, python-format
msgid ""
"Trying to import backup metadata from id %(meta_id)s into backup %(id)s."
msgstr ""
"Pokus o importování popisných dta zálohy z id %(meta_id)s do zálohy %(id)s."

#, python-format
msgid ""
"Tune volume task stopped before it was done: volume_name=%(volume_name)s, "
"task-status=%(status)s."
msgstr ""
"Úkol ladění svazku zastaven pře jeho dokončením: název svazku="
"%(volume_name)s, stav úkoolu=%(status)s."

#, python-format
msgid ""
"Type %(type_id)s is already associated with another qos specs: "
"%(qos_specs_id)s"
msgstr ""
"Typ %(type_id)s již je přidružen k jiné specifikaci qos: %(qos_specs_id)s"

msgid "Type access modification is not applicable to public volume type."
msgstr "Změna typu přístupu se nevztahuje k veřejnému typu svazku."

msgid "Type cannot be converted into NaElement."
msgstr "Typ nemůže být převeden na NaElement."

#, python-format
msgid "TypeError: %s"
msgstr "Chyba typu: %s"

#, python-format
msgid "UUIDs %s are in both add and remove volume list."
msgstr "UUID %s jsou zároveň v seznamu přidání i odstranění svazků."

msgid "Unable to access the backend storage via file handle."
msgstr ""
"Nelze získat přístup k  podpůrné vrstvě úložiště pomocí obslužné rutiny "
"souboru."

#, python-format
msgid "Unable to access the backend storage via the path %(path)s."
msgstr "Nelze získat přístup k podpůrné vrstvě úložiště pomocí cesty %(path)s."

msgid "Unable to connect or find connection to host"
msgstr "Nelze se připojit nebo nalézt připojení k hostiteli"

msgid "Unable to create lock. Coordination backend not started."
msgstr "Nelze vytvořit zámek. Podpůrná vrstva koordinátora nebyla spuštěna."

#, python-format
msgid "Unable to delete snapshot %(id)s, status: %(status)s."
msgstr "Nelze smazat snímek %(id)s, stav: %(status)s."

msgid ""
"Unable to detach volume. Volume status must be 'in-use' and attach_status "
"must be 'attached' to detach."
msgstr ""
"Nelze odpojit svazek. Pro odpojení musí být stav svazku 'in-use' a stav "
"připojení musí být 'attached'."

#, python-format
msgid "Unable to determine snapshot name in Purity for snapshot %(id)s."
msgstr "Nelze zjistit název snímku v Purity pro snímek %(id)s."

msgid "Unable to determine system id."
msgstr "Nelze zjistit id systému."

msgid "Unable to determine system name."
msgstr "Nelze zjistit název systému."

#, python-format
msgid ""
"Unable to do manage snapshot operations with Purity REST API version "
"%(api_version)s, requires %(required_versions)s."
msgstr ""
"Nelze provést operace správy snímku pomocí Purity REST API verze "
"%(api_version)s, vyžaduje %(required_versions)s."

#, python-format
msgid "Unable to extend volume %s"
msgstr "Nelze rozšířit svazek %s"

msgid "Unable to fetch connection information from backend."
msgstr "Nelze získat informace o připojení z podpůrné vrstvy."

#, python-format
msgid "Unable to fetch connection information from backend: %(err)s"
msgstr "Nelze získat informace o připojení z podpůrné vrstvy: %(err)s"

#, python-format
msgid "Unable to find Purity ref with name=%s"
msgstr "Nelze najít odkaz na Purity s názvem=%s"

#, python-format
msgid "Unable to find Volume Group: %(vg_name)s"
msgstr "Nelze najít skupinu svazku: %(vg_name)s"

msgid "Unable to find iSCSI mappings."
msgstr "Nelze najít mapování iSCSI."

#, python-format
msgid "Unable to find ssh_hosts_key_file: %s"
msgstr "Nelze najít soubor klíčů hostitelů ssh: %s"

#, python-format
msgid "Unable to find volume %s"
msgstr "Nelze najít svazek %s"

#, python-format
msgid "Unable to get a block device for file '%s'"
msgstr "Nelze získat blokové zařízení pro soubor '%s'"

#, python-format
msgid ""
"Unable to get configuration information necessary to create a volume: "
"%(errorMessage)s."
msgstr ""
"Nelze získat informace o nastavení potřebné k vytvoření svazku: "
"%(errorMessage)s."

#, python-format
msgid "Unable to get stats for backend_name: %s"
msgstr "Nelze získat statistiky s podpůrné vrstvy s názvem: %s"

#, python-format
msgid "Unable to locate account %(account_name)s on Solidfire device"
msgstr "Nelze nalézt účet %(account_name)s na zařízení Solidfire"

#, python-format
msgid "Unable to locate an SVM that is managing the IP address '%s'"
msgstr "Nelze nalézt SVM které spravuje IP adresu '%s'"

#, python-format
msgid ""
"Unable to manage existing volume. Volume %(volume_ref)s already managed."
msgstr ""
"Nelze spravovat existující svazek. Svazek %(volume_ref)s již je spravován."

#, python-format
msgid "Unable to manage volume %s"
msgstr "Nelze spravovat svazek %s"

msgid "Unable to map volume"
msgstr "Nelze mapovat svazek"

msgid "Unable to map volume."
msgstr "Nelze mapovat svazek."

msgid "Unable to parse attributes."
msgstr "Nelze zpracovat vlastnosti."

msgid ""
"Unable to re-use a host that is not managed by Cinder with "
"use_chap_auth=True,"
msgstr ""
"Nelze znovu použít hostitele, kterého nespravuje Cinder, pomocí "
"use_chap_auth=True."

msgid "Unable to re-use host with unknown CHAP credentials configured."
msgstr ""
"Nelze znovu použít hostitele, pokud má nastaveno neznámé ověřovací údaje "
"CHAP."

#, python-format
msgid "Unable to rename volume %(existing)s to %(newname)s"
msgstr "Nelze přejmenovat svazek %(existing)s na %(newname)s"

#, python-format
msgid ""
"Unable to retype:  A copy of volume %s exists. Retyping would exceed the "
"limit of 2 copies."
msgstr ""
"Nezle přetypovat: Kopie svazku %s již existuje, Přetypování by překročilo "
"omezení 2 kopií."

#, python-format
msgid ""
"Unable to retype: Current action needs volume-copy, it is not allowed when "
"new type is replication. Volume = %s"
msgstr ""
"Nezle přetypovat: Současná činnost vyžaduje kopii svazku, není povoleno, "
"pokud je nový typ replikace. Svazek = %s"

msgid "Unable to terminate volume connection from backend."
msgstr "Nelze ukončit připojení svazku v podpůrné vrstvě."

#, python-format
msgid "Unable to terminate volume connection: %(err)s"
msgstr "Nelze ukončit připojení k ovladači: %(err)s"

msgid "Unacceptable parameters."
msgstr "Nepřijatelné parametry."

#, python-format
msgid ""
"Unexecpted mapping status %(status)s for mapping %(id)s. Attributes: "
"%(attr)s."
msgstr "Neočekávaný stav mapování %(status)s pro %(id)s. Vlastnosti: %(attr)s."

#, python-format
msgid ""
"Unexpected CLI response: header/row mismatch. header: %(header)s, row: "
"%(row)s."
msgstr ""
"Neočekávaná odpověď rozhraní příkazového řádku: neshoda hlavičky/řádku. "
"Hlavička: %(header)s, řádek: %(row)s."

msgid "Unexpected response from Nimble API"
msgstr "Neočekávaná odpověď od Nimble API"

msgid "Unexpected status code"
msgstr "Neočekávaný kód stavu"

msgid "Unknown NFS exception"
msgstr "Neznámá výjimka NFS"

msgid "Unknown RemoteFS exception"
msgstr "Neznámá výjimka RemoteFS"

msgid "Unknown SMBFS exception."
msgstr "Neznámá výjimka SMBFS."

msgid "Unknown Virtuozzo Storage exception"
msgstr "Neznámá výjimka úložiště Virtuozzo"

msgid "Unknown action"
msgstr "Neznámá činnost"

#, python-format
msgid "Unknown or unsupported command %(cmd)s"
msgstr "Neznámý nebo nepodporovaný příkaz %(cmd)s"

#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr "Neznámý zdroj kvóty %(unknown)s."

msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Neznámý směr řazení, musí být 'desc' nebo 'asc'"

msgid "Unknown sort direction, must be 'desc' or 'asc'."
msgstr "Neznámý směr řazení, musí být buď 'desc' nebo 'asc'."

msgid "Unmanage volume not implemented."
msgstr "Zrušení správy svazku není zavedeno."

#, python-format
msgid "Unrecognized QOS keyword: \"%s\""
msgstr "Nerozpoznané klíčové slovo QoS: \"%s\""

#, python-format
msgid "Unrecognized backing format: %s"
msgstr "Nerozpoznaný formát zálohy: %s"

#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr "Nerozpoznaná hodnota read_deleted '%s'"

msgid "Unsupported Content-Type"
msgstr "Nepodporovaný Content-Type"

#, python-format
msgid "Unsupported backup metadata version (%s)"
msgstr "Nepodporovaná verze zálohy popisných dat (%s)"

msgid "Unsupported backup metadata version requested"
msgstr "Zažádána nepodporovaná verze popisných dat zálohy"

msgid "Unsupported backup verify driver"
msgstr "Nepodporovaný ovladač ověření zálohy"

#, python-format
msgid ""
"Unsupported firmware on switch %s. Make sure switch is running firmware v6.4 "
"or higher"
msgstr ""
"Nepodporovaný frimware na rozbočovači %s. Ujistěte se, že na rozbočovači je "
"nainstalována verze 6.4 nebo vyšší."

#, python-format
msgid "Unsupported volume format: %s "
msgstr "Nepodporovaný formát svazku: %s"

msgid "Update QoS policy error."
msgstr "Chyba při aktualizování zásady QoS."

msgid ""
"Update and delete quota operations can only be made by an admin of immediate "
"parent or by the CLOUD admin."
msgstr ""
"Operace aktualizace a smazání kvóty může provést pouze správce přímého "
"nadřazeného nebo správce Cloudu."

msgid ""
"Update and delete quota operations can only be made to projects in the same "
"hierarchy of the project in which users are scoped to."
msgstr ""
"Operace aktualizace a smazání kvóty mohou být provedeny pouze v projektech "
"ve stejné hierarchii jako projekt do kterého jsou uživatelé zařazeni."

msgid "Updated At"
msgstr "Aktualizováno"

msgid "Upload to glance of attached volume is not supported."
msgstr "Nahrávání na glance připojeného svazku není podporováno."

msgid "Use ALUA to associate initiator to host error."
msgstr "Chyba při použití ALUA k přidružení zavaděče k hostiteli."

msgid ""
"Use CHAP to associate initiator to host error. Please check the CHAP "
"username and password."
msgstr ""
"Chyba při použití CHAP k přidružení zavaděče k hostiteli. Zkontrolujte "
"prosím uživatelské jméno a heslo CHAP."

msgid "User ID"
msgstr "ID uživatele"

msgid "User does not have admin privileges"
msgstr "Uživatel nemá správcovská oprávnění"

msgid "User not authorized to perform WebDAV operations."
msgstr "Uživatel nemá oprávnění provádět operace WebDAV."

#, python-format
msgid "VV Set %s does not exist."
msgstr "Sada virtuálních svazků %s neexistuje."

#, python-format
msgid "Valid consumer of QoS specs are: %s"
msgstr "Platní spotřebitelé specifikace QoS jsou: %s"

#, python-format
msgid "Validate volume connection failed (error: %(err)s)."
msgstr "Ověření připojení svazku selhalo (chyba: %(err)s)."

#, python-format
msgid ""
"Value \"%(value)s\" is not valid for configuration option \"%(option)s\""
msgstr "Hodnota \"%(value)s\" není platná pro volbu nastavení \"%(option)s\""

#, python-format
msgid "ValueError: %s"
msgstr "Chyba hodnoty: %s"

#, python-format
msgid "Vdisk %(name)s not involved in mapping %(src)s -> %(tgt)s."
msgstr "Virtuální disk %(name)s není součástí mapování %(src)s -> %(tgt)s."

#, python-format
msgid ""
"Version %(req_ver)s is not supported by the API. Minimum is %(min_ver)s and "
"maximum is %(max_ver)s."
msgstr ""
"Verze  %(req_ver)s není API podporována. Minimální verze je %(min_ver)s a "
"maximální %(max_ver)s."

#, python-format
msgid "VersionedObject %s cannot retrieve object by id."
msgstr "Objekt s verzí %s nemůže získat objekt podle id."

#, python-format
msgid "VersionedObject %s does not support conditional update."
msgstr "Objekt s verzí %s nepodporuje podmíněné aktualizace."

#, python-format
msgid "Virtual volume '%s' doesn't exist on array."
msgstr "Virtuální svazek '%s' neexistuje v poli."

#, python-format
msgid "Volume %(deviceID)s not found."
msgstr "Svazek %(deviceID)s nenalezen."

#, python-format
msgid "Volume %(name)s was created in VNX, but in %(state)s state."
msgstr "Svazek %(name)s byl vytvořen ve VNX, ale je ve stavu %(state)s."

#, python-format
msgid "Volume %(vol)s could not be created in pool %(pool)s."
msgstr "Svazek %(vol)s nemohl být vytvořen v zásobě %(pool)s."

#, python-format
msgid ""
"Volume %(vol_id)s status must be available to update readonly flag, but "
"current status is: %(vol_status)s."
msgstr ""
"Stav svazku %(vol_id)s musí být dostupný pro aktualizaci příznaku pouze pro "
"čtení, ale současný stav: %(vol_status)s."

#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr "Svazek %(volume_id)s nemohl být nalezen."

#, python-format
msgid ""
"Volume %(volume_id)s has no administration metadata with key "
"%(metadata_key)s."
msgstr ""
"Svazek %(volume_id)s nemá žádná popisná data správy mající klíč "
"%(metadata_key)s."

#, python-format
msgid "Volume %(volume_id)s has no metadata with key %(metadata_key)s."
msgstr "Svazek %(volume_id)s nemá žádná metadata s klíčem %(metadata_key)s."

#, python-format
msgid "Volume %(volume_id)s is still attached, detach volume first."
msgstr "Svazek %(volume_id)s je stále připojen, nejdříve odpojte svazek."

#, python-format
msgid "Volume %(volume_id)s replication error: %(reason)s"
msgstr "Chyba replikace svazku %(volume_id)s: %(reason)s"

#, python-format
msgid "Volume %s could not be created from source volume."
msgstr "Svazek %s nemohl být vytvořen ze zdrojového svazku."

#, python-format
msgid "Volume %s could not be created on shares."
msgstr "Svazek %s nemohl být vytvořen ve sdílení."

#, python-format
msgid "Volume %s could not be created."
msgstr "Svazek %s nemohl být vytvořen."

#, python-format
msgid "Volume %s does not have provider_location specified, skipping."
msgstr "Svazek %s nemá zadáno umístění poskytovatele, je přeskočen."

#, python-format
msgid "Volume %s doesn't exist on array."
msgstr "Svazek %s neexistuje v poli."

#, python-format
msgid ""
"Volume %s is online. Set volume to offline for managing using OpenStack."
msgstr ""
"Svazek %s je online. Pro správu pomocí OpenStack ho nastavte na offline."

#, python-format
msgid "Volume %s must not be part of a consistency group."
msgstr "Svazek %s nesmí být součástí skupiny jednotnosti."

#, python-format
msgid "Volume %s not found."
msgstr "Svazek %s nenalezen."

#, python-format
msgid "Volume %s: Error trying to extend volume"
msgstr "Svazek %s: Chyba při pokusu o rozšíření svazku"

#, python-format
msgid "Volume (%s) already exists on array"
msgstr "Svazek (%s) již existuje v poli"

#, python-format
msgid "Volume (%s) already exists on array."
msgstr "Svazek (%s) již existuje v poli."

#, python-format
msgid "Volume Group %s does not exist"
msgstr "Skupina svazku %s neexistuje"

#, python-format
msgid "Volume Type %(id)s already exists."
msgstr "Typ svazku %(id)s již existuje."

#, python-format
msgid ""
"Volume Type %(volume_type_id)s deletion is not allowed with volumes present "
"with the type."
msgstr ""
"Smazání typu svazku %(volume_type_id)s není povoleno, když existují svazky s "
"tímto typem."

#, python-format
msgid ""
"Volume Type %(volume_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""
"Typ svazku %(volume_type_id)s nemá žádné dodatečné parametry s klíčem "
"%(extra_specs_key)s."

msgid "Volume Type id must not be None."
msgstr "ID typu svazku nesmí být None."

msgid "Volume by this name already exists"
msgstr "Svazek s tímto názvem již existuje"

msgid "Volume create failed while extracting volume ref."
msgstr "Vytvoření svazku selhalo při extrahování odkazu svazku."

#, python-format
msgid "Volume device file path %s does not exist."
msgstr "Cesta k souboru zařízení svazku %s neexistuje."

#, python-format
msgid "Volume device not found at %(device)s."
msgstr "Zařízení svazku nenalezeno na %(device)s."

#, python-format
msgid "Volume driver %s not initialized."
msgstr "Ovladač svazku %s není zaveden."

msgid "Volume driver not ready."
msgstr "Ovladač svazku není připraven."

#, python-format
msgid "Volume driver reported an error: %(message)s"
msgstr "Ovladač svazku nahlásil chybu: %(message)s"

#, python-format
msgid "Volume is attached to a server.  (%s)"
msgstr "Svazek je připojen k serveru. (%s)"

msgid "Volume is in-use."
msgstr "Svazek se používá."

msgid "Volume is not available."
msgstr "Svazek není dostupný."

msgid "Volume is not local to this node."
msgstr "Svazek není pro tento uzel místním."

msgid ""
"Volume metadata backup requested but this driver does not yet support this "
"feature."
msgstr ""
"Zažádáno o zálohu popisných dat svazku, ale tento ovladač tuto funkci zatím "
"nepodporuje."

#, python-format
msgid "Volume migration failed: %(reason)s"
msgstr "Přesunutí svazku selhalo: %(reason)s"

msgid "Volume must be in the same availability zone as the snapshot"
msgstr "Svazek musí být ve stejné zóně dostupnosti jako snímek"

msgid "Volume must be in the same availability zone as the source volume"
msgstr "Svazek musí být ve stejné zóně dostupnosti jako zdrojový svazek"

msgid "Volume must not be replicated."
msgstr "Svazek nesmí být replikován."

msgid "Volume must not have snapshots."
msgstr "Svazek nesmí mít snímky."

#, python-format
msgid "Volume not found for instance %(instance_id)s."
msgstr "Svazek není nalezen v instanci %(instance_id)s."

msgid "Volume not found on configured storage backend."
msgstr "Svazek nebyl nalezen na nastavené podpůrné vrstvě úložiště."

msgid "Volume not found."
msgstr "Svazek nenalezen."

msgid "Volume not yet assigned to host."
msgstr "Svazek ještě není přidělen k hostiteli."

msgid "Volume reference must contain source-name element."
msgstr "Odkaz na svazek musí obsahovat prvek source-name."

#, python-format
msgid "Volume replication for %(volume_id)s could not be found."
msgstr "Replikace svazku %(volume_id)s nemohla být nalezena."

msgid "Volume should have agent-type set as None."
msgstr "Svazek by měl mít typ agenta nastaven na None."

#, python-format
msgid ""
"Volume size %(volume_size)sGB cannot be smaller than the image minDisk size "
"%(min_disk)sGB."
msgstr ""
"Velikost svazku %(volume_size)sGB nemůže být menší než minimální velikost "
"disku v obrazu %(min_disk)sGB."

#, python-format
msgid "Volume size '%(size)s' must be an integer and greater than 0"
msgstr "Velikost svazku '%(size)s' musí být celé číslo a větší než 0"

#, python-format
msgid ""
"Volume size '%(size)s'GB cannot be smaller than original volume size  "
"%(source_size)sGB. They must be >= original volume size."
msgstr ""
"Velikost svazku'%(size)s'GB nemůže být menší než původní velikost svazku "
"%(source_size)sGB. Musí být >= původní velikosti svazku."

#, python-format
msgid ""
"Volume size '%(size)s'GB cannot be smaller than the snapshot size "
"%(snap_size)sGB. They must be >= original snapshot size."
msgstr ""
"Velikost svazku'%(size)s'GB nemůže být menší než velikost snímku "
"%(snap_size)sGB. Musí být <= původní velikosti snímku."

msgid "Volume size increased since the last backup. Do a full backup."
msgstr "Velikost svazku se od poslední zálohy zvýšila. Proveďte úplnou zálohu."

msgid "Volume size must multiple of 1 GB."
msgstr "Velikost svazku musí být násobkem 1GB."

msgid "Volume status must be 'available'."
msgstr "Stav svazku musí být 'available'."

msgid "Volume to Initiator Group mapping already exists"
msgstr "Mapování svazku ke skupině zavaděče již existuje"

#, python-format
msgid ""
"Volume to be backed up must be available or in-use, but the current status "
"is \"%s\"."
msgstr ""
"Zálohovaný svazek musí být dostupný nebo používaný, ale jeho stav je nyní "
"\"%s\"."

msgid "Volume to be restored to must be available"
msgstr "Obnovovaná záloha musí být dostupná"

#, python-format
msgid "Volume type %(volume_type_id)s could not be found."
msgstr "Typ svazku %(volume_type_id)s nemohl být nalezen."

#, python-format
msgid "Volume type ID '%s' is invalid."
msgstr "Typ svazku ID '%s' je neplatné."

#, python-format
msgid ""
"Volume type access for %(volume_type_id)s / %(project_id)s combination "
"already exists."
msgstr ""
"Přístup k typu svazku pro kombinaci %(volume_type_id)s / %(project_id)s již "
"existuje."

#, python-format
msgid ""
"Volume type access not found for %(volume_type_id)s / %(project_id)s "
"combination."
msgstr ""
"Přístup k typu svazku nenalezen pro kombinaci %(volume_type_id)s / "
"%(project_id)s."

#, python-format
msgid "Volume type encryption for type %(type_id)s already exists."
msgstr "Šifrování typu svazku pro typ %(type_id)s již existuje."

#, python-format
msgid "Volume type encryption for type %(type_id)s does not exist."
msgstr "Šifrování typu svazku pro typ %(type_id)s neexistuje."

msgid "Volume type name can not be empty."
msgstr "Název typu svazku nemůže být prázdný."

#, python-format
msgid "Volume type with name %(volume_type_name)s could not be found."
msgstr "Typ svazku s názvem %(volume_type_name)s nemohl být nalezen."

#, python-format
msgid ""
"VzStorage config 'vzstorage_used_ratio' invalid. Must be > 0 and <= 1.0: %s."
msgstr ""
"Nastavení VzStorage 'vzstorage_used_ratio' je neplatné. Musí být > 0 a <= "
"1.0: %s."

#, python-format
msgid "VzStorage config file at %(config)s doesn't exist."
msgstr "Soubor s nastavením VzStorage %(config)s nebyl nalezen."

msgid ""
"Waiting for all nodes to join cluster. Ensure all sheep daemons are running."
msgstr ""
"Čekání na připojení uzlů ke clusteru. Ujistěte se, že všichni daemoni sheep "
"jsou spuštěni."

msgid "XtremIO not configured correctly, no iscsi portals found"
msgstr "XtremIO není správně nastaveno, nenalezeny žádné portály iscsi"

msgid "XtremIO not initialized correctly, no clusters found"
msgstr "XtremIO nebyl zaveden správně, žádné clustery nenalezeny"

msgid "You must implement __call__"
msgstr "Musíte zavést __call__"

msgid ""
"You must install hpe3parclient before using 3PAR drivers. Run \"pip install "
"python-3parclient\" to install the hpe3parclient."
msgstr ""
"Před použitím ovladačů 3PAR musíte nainstalovat hpe3parclient. Spusťte \"pip "
"install python-3parclient\" pro instalaci klienta."

#, python-format
msgid "ZeroDivisionError: %s"
msgstr "Chyba dělení nulou: %s"

msgid "Zone"
msgstr "Zóna"

#, python-format
msgid "Zoning Policy: %s, not recognized"
msgstr "Zásada zónování: %s nebylo rozpoznáno"

#, python-format
msgid "_create_and_copy_vdisk_data: Failed to get attributes for vdisk %s."
msgstr ""
"Vytvoření a kopírování dat virtuálního disku: Nelze získat vlastnosti "
"virtuálního disku %s."

msgid "_create_host failed to return the host name."
msgstr "Vytvoření hostitele nevrátilo název hostitele."

msgid ""
"_create_host: Can not translate host name. Host name is not unicode or "
"string."
msgstr ""
"Vytvoření hostitele: Nelze převést název hostitele. Název není unicode nebo "
"řetězec."

msgid "_create_host: No connector ports."
msgstr "Vytvoření hostitele: Žádné porty pro připojení."

#, python-format
msgid ""
"_create_vdisk %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"Vytvoření virtuálního disku %(name)s - ve výstupu příkazového řádku nebyla "
"nalezena zpráva o úspěchu.\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s."

#, python-format
msgid ""
"_get_hdr_dic: attribute headers and values do not match.\n"
" Headers: %(header)s\n"
" Values: %(row)s."
msgstr ""
"Získání slovníku hlavičky: hlavičky vlastnosti a jejich hodnoty se "
"neshodují.\n"
"Hlavičky: %(header)s\n"
"Hodnoty: %(row)s."

msgid "_get_host_from_connector failed to return the host name for connector."
msgstr "Získání hostitele od konektoru nevrátilo název jeho hostitele."

msgid ""
"_get_vdisk_map_properties: Could not get FC connection information for the "
"host-volume connection. Is the host configured properly for FC connections?"
msgstr ""
"Získání vlastností mapy virtuálního disku: Nelze získat informace o "
"připojení FC pro připojení svazek-hostitel. Je hostitel správně nastaven pro "
"připojení FC?"

#, python-format
msgid ""
"_get_vdisk_map_properties: No node found in I/O group %(gid)s for volume "
"%(vol)s."
msgstr ""
"Získání vlastností mapy virtuálního disku: Ve skupině vstupu/výstupu %(gid)s "
"nebyl nalezen žádný uzel pro svazek %(vol)s."

msgid "_update_volume_stats: Could not get storage pool data."
msgstr "Aktualizace statistik svazku: Nelze získat data zásoby úložiště."

#, python-format
msgid ""
"add_vdisk_copy failed: A copy of volume %s exists. Adding another copy would "
"exceed the limit of 2 copies."
msgstr ""
"Přidání kopie virtuálního disku selhalo: Kopie svazku %s již existuje. "
"Přidání další kopie by překročilo omezení 2 kopií."

msgid "add_vdisk_copy started without a vdisk copy in the expected pool."
msgstr ""
"Přidání kopie virtuálního disku bylo spuštěno bez kopie v očekávané zásobě."

#, python-format
msgid "all_tenants must be a boolean, got '%s'."
msgstr "all_tenants musí být boolean, obdrženo %s"

msgid "already created"
msgstr "již vytvořeno"

msgid "already_created"
msgstr "již vytvořeno"

#, python-format
msgid "attribute %s not lazy-loadable"
msgstr "vlastnost %s nelze líně načíst"

#, python-format
msgid ""
"backup: %(vol_id)s failed to create device hardlink from %(vpath)s to "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"záloha: %(vol_id)s nemohl vytvořit pevný odkaz na zařízení v %(vpath)s do "
"%(bpath)s.\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s"

#, python-format
msgid ""
"backup: %(vol_id)s failed to obtain backup success notification from "
"server.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"záloha: %(vol_id)s nemohla získat oznámení o úspěšném dokončení zálohy od "
"serveru.\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s"

#, python-format
msgid ""
"backup: %(vol_id)s failed to run dsmc due to invalid arguments on "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"záloha: %(vol_id)s nemohla spustit dsmc kvůli neplatným argumentům na "
"%(bpath)s.\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s."

#, python-format
msgid ""
"backup: %(vol_id)s failed to run dsmc on %(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"záloha: %(vol_id)s nemohla spustit dsmc na %(bpath)s.\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s."

#, python-format
msgid "backup: %(vol_id)s failed. %(path)s is not a file."
msgstr "záloha: %(vol_id)s selhala. %(path)s není soubor."

#, python-format
msgid ""
"backup: %(vol_id)s failed. %(path)s is unexpected file type. Block or "
"regular files supported, actual file mode is %(vol_mode)s."
msgstr ""
"záloha: %(vol_id)s selhala. %(path)s odkazuej na nečekaný typ souboru. "
"Podporován blok, nebo normální soubory, současný režim souboru je "
"%(vol_mode)s."

#, python-format
msgid ""
"backup: %(vol_id)s failed. Cannot obtain real path to volume at %(path)s."
msgstr ""
"záloha: %(vol_id)s selhala. Nelze získat skutečnou cestu ke svazku na "
"%(path)s."

msgid "being attached by different mode"
msgstr "je připojen v jiném režimu"

#, python-format
msgid "can't find lun-map, ig:%(ig)s vol:%(vol)s"
msgstr "nelze najít lun-map, ig:%(ig)s svazek:%(vol)s"

msgid "can't find the volume to extend"
msgstr "nelze najít svazek pro rozšíření"

msgid "can't handle both name and index in req"
msgstr "v žádosti nelze zpracovat jak název tak index najednou"

msgid "cannot understand JSON"
msgstr "JSON nelze porozumět"

msgid "cgsnapshot assigned"
msgstr "snímek skupiny jednotnosti přidělen"

msgid "cgsnapshot changed"
msgstr "snímek skupiny jednotnosti změněn"

msgid "cgsnapshots assigned"
msgstr "snímky skupiny jednotnosti přiděleny"

msgid "cgsnapshots changed"
msgstr "snímky skupiny jednotnosti změněny"

msgid ""
"check_for_setup_error: Password or SSH private key is required for "
"authentication: set either san_password or san_private_key option."
msgstr ""
"Kontrola chyby v nastavení: Heslo nebo soukromý klíč SSH jsou vyžadovány pro "
"ověření: nastavte volbu san_password nebo san_private_key."

msgid "check_for_setup_error: Unable to determine system id."
msgstr "Kontrola chyby v nastavení: Nelze zjistit id systému."

msgid "check_for_setup_error: Unable to determine system name."
msgstr "Kontrola chyby v nastavení: Nelze zjistit název systému."

msgid "check_hypermetro_exist error."
msgstr "Chyba při kontrole existence hypermetra."

#, python-format
msgid "clone depth exceeds limit of %s"
msgstr "hloubka klonování překračuje omezení %s"

msgid "consistencygroup assigned"
msgstr "skupina jednotnosti přidělena"

msgid "consistencygroup changed"
msgstr "skupina jednotnosti změněna"

#, python-format
msgid "create_copy: Source vdisk %(src)s (%(src_id)s) does not exist."
msgstr ""
"Vytvoření kopie: Zdrojový virtuální disk %(src)s (%(src_id)s) neexistuje."

#, python-format
msgid "create_copy: Source vdisk %(src)s does not exist."
msgstr "Vytvoření kopie: Zdrojový virtuální disk %(src)s neexistuje."

msgid "create_host: Host name is not unicode or string."
msgstr "Vytvoření hostitele: Název není unicode nebo řetězec."

msgid "create_host: No initiators or wwpns supplied."
msgstr "Vytvoření hostitele: Nepředány žádné zavaděče nebo wwpns."

msgid "create_hypermetro_pair error."
msgstr "Chyba při vytváření páru hypermetro."

#, python-format
msgid ""
"create_snapshot: Volume status must be \"available\" or \"in-use\" for "
"snapshot. The invalid status is %s."
msgstr ""
"Vytvoření snímku: Stav svazku musí být pro vytvoření snímku \"available\" "
"nebo \"in-use\". Neplatný stav je %s."

msgid "create_snapshot: get source volume failed."
msgstr "Vytvoření snímku: Získání zdrojového svazku selhalo."

#, python-format
msgid "create_volume_from_snapshot: Snapshot %(name)s does not exist."
msgstr "Vytváření svazku ze snímku: Svazek %(name)s neexistuje."

#, python-format
msgid ""
"create_volume_from_snapshot: Snapshot status must be \"available\" for "
"creating volume. The invalid status is: %s."
msgstr ""
"Vytvoření svazku ze snímku: Pro vytvoření svazku musí být stav snímku "
"\"dostupný\". Neplatný stav je: %s."

#, python-format
msgid ""
"delete: %(vol_id)s failed to run dsmc due to invalid arguments with stdout: "
"%(out)s\n"
" stderr: %(err)s"
msgstr ""
"smazání: %(vol_id)s nemohla spustit dsmc kvůli neplatným argumentům se "
"standardním výstupem: %(out)s.\n"
"chybový výstup: %(err)s."

#, python-format
msgid ""
"delete: %(vol_id)s failed to run dsmc with stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"smazání: %(vol_id)s nemohla spustit dsmc pomocí standardního výstupu: "
"%(out)s.\n"
"chybový výstup: %(err)s."

msgid "delete_hypermetro error."
msgstr "Chyba při mazání hypermetra."

#, python-format
msgid "delete_initiator: %s ACL not found. Continuing."
msgstr "Mazání iniciátora: %s ACL nenalezeno. Pokračování."

#, python-format
msgid "deleting snapshot %(snapshot_name)s that has dependent volumes"
msgstr "mazání snímku %(snapshot_name)s který má nezávislé svazky"

#, python-format
msgid "deleting volume %(volume_name)s that has snapshot"
msgstr "mazání svazku %(volume_name)s který má snímek"

msgid "do_setup: No configured nodes."
msgstr "Zavedení: Nenastaveny žádné uzly."

#, python-format
msgid ""
"error writing object to swift, MD5 of object in swift %(etag)s is not the "
"same as MD5 of object sent to swift %(md5)s"
msgstr ""
"chyba při zápisu objektu do swift, MD5 objektu ve swift %(etag)s se liší od "
"MD5 objektu odeslaného do swift %(md5)s"

msgid "fake"
msgstr "falešný"

msgid "fileno is not supported by SheepdogIOWrapper"
msgstr "fileno nepodporuje SheepdogIOWrapper"

#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr "fmt=%(fmt)s zálohováno: %(backing_file)s"

#, python-format
msgid "fmt=%(fmt)s backed by:%(backing_file)s"
msgstr "fmt=%(fmt)s zálohováno:%(backing_file)s"

msgid "force delete"
msgstr "vynutit smazání"

msgid "get_hyper_domain_id error."
msgstr "chyb při získávání id domény hypermetra."

msgid "get_hypermetro_by_id error."
msgstr "Chyba při získávání hypermetra podle id."

#, python-format
msgid ""
"get_iscsi_params: Failed to get target IP for initiator %(ini)s, please "
"check config file."
msgstr ""
"Získání parametrů iSCSI: Nelze získat cílovou IP adresu pro zavaděč %(ini)s, "
"prosím zkontrolujte  soubor s nastavením."

msgid "glance_metadata changed"
msgstr "popisná data glance změněna"

#, python-format
msgid ""
"gpfs_images_share_mode is set to copy_on_write, but %(vol)s and %(img)s "
"belong to different file systems."
msgstr ""
"gpfs_images_share_mode je nastaven na kopírování při zápisu, ale %(vol)s a "
"%(img)s mají odlišné systémy souborů."

#, python-format
msgid ""
"gpfs_images_share_mode is set to copy_on_write, but %(vol)s and %(img)s "
"belong to different filesets."
msgstr ""
"gpfs_images_share_mode je nastaven na kopírování při zápisu, ale %(vol)s a "
"%(img)s mají odlišné sady souborů."

msgid ""
"http service may have been abruptly disabled or put to maintenance state in "
"the middle of this operation."
msgstr ""
"Služba http mohla být uprostřed operace náhle ukončena, nebo převedena do "
"stavu údržby."

msgid "id cannot be None"
msgstr "id nemůže být None"

#, python-format
msgid "image %s not found"
msgstr "Obraz %s nebyl nalezen"

#, python-format
msgid "initialize_connection: Failed to get attributes for volume %s."
msgstr "Zavedení spojení: Nelze získat vlastnosti svazku %s."

#, python-format
msgid "initialize_connection: Missing volume attribute for volume %s."
msgstr "Zavedení spojení: Svazku %s chybí vlastnost."

#, python-format
msgid ""
"initialize_connection: No node found in I/O group %(gid)s for volume %(vol)s."
msgstr ""
"Zavedení spojení: Ve skupině vstupu/výstupu %(gid)s nebyl nalezen žádný uzel "
"pro svazek %(vol)s."

#, python-format
msgid "initialize_connection: vdisk %s is not defined."
msgstr "Zavedení připojení: Virtuální disk %s není určen."

#, python-format
msgid "invalid user '%s'"
msgstr "Neplatný uživatel '%s'"

#, python-format
msgid "iscsi portal, %s, not found"
msgstr "portál iscsi %s nebyl nalezen"

#, python-format
msgid "key manager error: %(reason)s"
msgstr "chyba správce klíčů: %(reason)s"

msgid "limit param must be an integer"
msgstr "parametr limit musí být celé číslo"

msgid "limit param must be positive"
msgstr "parametr limit musí být kladný"

msgid "manage_existing requires a 'name' key to identify an existing volume."
msgstr ""
"manage_existing vyžaduje klíč 'name' pro identifikaci existujícího svazku."

#, python-format
msgid "mdiskgrp missing quotes %s"
msgstr "mdiskgrp chybí uvozovky %s"

#, python-format
msgid "mkfs failed on volume %(vol)s, error message was: %(err)s."
msgstr "mkfs selhalo u svazku %(vol)s, chybová zpráva byla: %(err)s."

msgid "mock"
msgstr "nepravý"

#, python-format
msgid "multiple resources with name %s found by drbdmanage"
msgstr "drbdmanage nalezl mnoho zdrojů s názvem %s"

#, python-format
msgid "multiple resources with snapshot ID %s found"
msgstr "nalezeno mnoho zdrojů mající ID snímku %s"

msgid "name cannot be None"
msgstr "název nemůže být Žádný"

#, python-format
msgid "no snapshot with id %s found in drbdmanage"
msgstr "v drbdmanage nenalezen žádný snímek s id %s"

#, python-format
msgid "not exactly one snapshot with id %s"
msgstr "více než jeden snímek s id %s"

#, python-format
msgid "not exactly one volume with id %s"
msgstr "id %s nemá právě jeden svazek"

#, python-format
msgid "obj missing quotes %s"
msgstr "objektu chybí uvozovky %s"

msgid "open_access_enabled is not off."
msgstr "open_access_enabled není vypnuto."

msgid "progress must be an integer percentage"
msgstr "postup musí být procento vyjádřené celým číslem"

#, python-format
msgid ""
"qemu-img %(minimum_version)s or later is required by this volume driver. "
"Current qemu-img version: %(current_version)s"
msgstr ""
"Ovladač tohoto svazku vyžaduje qemu-img %(minimum_version)s nebo novější. "
"Současná verze qemu-img: %(current_version)s"

#, python-format
msgid ""
"qemu-img is not installed and image is of type %s.  Only RAW images can be "
"used if qemu-img is not installed."
msgstr ""
"qemu-img není nainstalováno a obraz je typu %s. Pokud qemu-img není "
"nainstalován, lze použít pouze obrazy s typem RAW."

msgid ""
"qemu-img is not installed and the disk format is not specified.  Only RAW "
"images can be used if qemu-img is not installed."
msgstr ""
"qemu-img není nainstalováno a formát disku není zadán. Pokud qemu-img není "
"nainstalován, lze použít pouze obrazy s typem RAW."

msgid "rados and rbd python libraries not found"
msgstr "Python knihovny rados a rbd nebyly nalezeny"

#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr "read_deleted může být buď 'no', 'yes' nebo 'only', ne %r"

#, python-format
msgid ""
"restore: %(vol_id)s failed to run dsmc due to invalid arguments on "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"obnova: %(vol_id)s nemohla spustit dsmc kvůli neplatným argumentům na "
"%(bpath)s.\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s."

#, python-format
msgid ""
"restore: %(vol_id)s failed to run dsmc on %(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"obnova: %(vol_id)s nemohla spustit dsmc na %(bpath)s.\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s."

#, python-format
msgid ""
"restore: %(vol_id)s failed.\n"
"stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"obnova: %(vol_id)s selhala.\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s."

msgid ""
"restore_backup aborted, actual object list does not match object list stored "
"in metadata."
msgstr ""
"obnovení zálohy zrušeno, současný seznam objektů neodpovídá seznamu "
"uloženého v popisných datech."

#, python-format
msgid "rtslib_fb is missing member %s: You may need a newer python-rtslib-fb."
msgstr ""
"rtslib_fb chybí člen %s: Možná budete potřebovat novější python-rtslib-fb."

msgid "san_ip must be set"
msgstr "san_ip musí být nastaveno"

msgid ""
"san_login and/or san_password is not set for Datera driver in the cinder."
"conf. Set this information and start the cinder-volume service again."
msgstr ""
"san_login a /nebo san_password není v cinder.conf nastaveno pro ovladač "
"Datera. Nastavte tyto údaje a spusťte znovu službu cinder-volume."

msgid "serve() can only be called once"
msgstr "serve() může být voláno pouze jednou"

#, python-format
msgid "snapshot-%s"
msgstr "snímek-%s"

msgid "snapshots assigned"
msgstr "snímky přiděleny"

msgid "snapshots changed"
msgstr "snímek změněn"

msgid "status must be available"
msgstr "stav musí být dostupný"

msgid "stop_hypermetro error."
msgstr "Chyba při zastavování hypermetra."

msgid "sync_hypermetro error."
msgstr "Chyba při synchronizaci hypermetra."

#, python-format
msgid ""
"targetcli not installed and could not create default directory "
"(%(default_path)s): %(exc)s"
msgstr ""
"targetcli není nainstalováno a nelze vytvořit výchozí adresář "
"(%(default_path)s): %(exc)s"

msgid "terminate_connection: Failed to get host name from connector."
msgstr "Ukončení spojení: Nelze získat název hostitele z konektoru."

msgid "too many body keys"
msgstr "příliš mnoho klíčů těla"

#, python-format
msgid "unrecognized argument %s"
msgstr "nerozpoznaný argument %s"

#, python-format
msgid "unsupported compression algorithm: %s"
msgstr "nepodporovaný kompresní algoritmus: %s"

msgid "valid iqn needed for show_target"
msgstr "Pro zobrazení cíle je třeba platné iqn"

#, python-format
msgid "vdisk %s is not defined."
msgstr "virtuální disk %s není určen."

#, python-format
msgid "volume %s not found in drbdmanage"
msgstr "svazek %s není nalezen v drbdmanage"

msgid "volume assigned"
msgstr "svazek přidělen"

msgid "volume changed"
msgstr "svazek změněn"

#, python-format
msgid ""
"volume size %(volume_size)d is too small to restore backup of size %(size)d."
msgstr ""
"velikost svazku %(volume_size)d je příliš malá pro obnovení zálohy o "
"velikosti %(size)d."

#, python-format
msgid "volume size %d is invalid."
msgstr "velikost svazku %d je neplatná."

msgid ""
"volume_type must be provided when creating a volume in a consistency group."
msgstr "při vytváření svazku ve skupině jednotnosti musí být zadán jeho typ."

msgid "volume_type_id cannot be None"
msgstr "volume_type_id nemůže být None"

#, python-format
msgid "volume_types must be provided to create consistency group %(name)s."
msgstr ""
"pro vytvoření skupiny jednotnosti %(name)s musí být zadány typy svazků."

msgid "volumes assigned"
msgstr "svazky přiděleny"

msgid "volumes changed"
msgstr "svazky změněny"

#, python-format
msgid "wait_for_condition: %s timed out."
msgstr "Čekání na podmínku: %s vypršel časový limit."
