# Translations template for cinder.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the cinder project.
#
# Translators:
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011
# Kai Zhang <zakir.exe@gmail.com>, 2013
# Kai Zhang <zakir.exe@gmail.com>, 2013
# openstack <malei@cn.fujitsu.com>, 2013
# Shuwen SUN <chris-void@outlook.com>, 2014
# Tom Fifield <tom@openstack.org>, 2013
# 颜海峰 <yanheven@gmail.com>, 2014
# Yu Zhang, 2014
# 颜海峰 <yanheven@gmail.com>, 2014
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
# Eric Lei <1165970798@qq.com>, 2016. #zanata
# howard lee <howard@mail.ustc.edu.cn>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: cinder VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2019-01-11 16:51+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-09-28 06:20+0000\n"
"Last-Translator: Eric Lei <1165970798@qq.com>\n"
"Language: zh_CN\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 4.3.3\n"
"Language-Team: Chinese (China)\n"

#, python-format
msgid "\t%s"
msgstr "\t%s"

#, python-format
msgid ""
"\n"
"OpenStack Cinder version: %(version)s\n"
msgstr ""
"\n"
"OpenStack Cinder 版本：%(version)s\n"

#, python-format
msgid " but size is now %d"
msgstr "但现在大小为 %d"

msgid " or "
msgstr "或者"

#, python-format
msgid ""
"%(driver)s manage_existing cannot manage a volume connected to hosts. Please "
"disconnect this volume from existing hosts before importing"
msgstr ""
"%(driver)s manage_existing 无法管理已连接至主机的卷。在进行导入之前，请从现有"
"主机断开与此卷的连接"

#, python-format
msgid ""
"%(err)s\n"
"result: %(res)s."
msgstr ""
"%(err)s\n"
"结果：%(res)s。"

#, python-format
msgid "%(exception)s: %(explanation)s"
msgstr "发生异常 %(exception)s：原因 %(explanation)s"

#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"%(fun)s：失败，产生了意外 CLI 输出。\n"
"命令：%(cmd)s\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s"

#, python-format
msgid "%(host)-25s\t%(availability_zone)-15s"
msgstr "%(host)-25s\t%(availability_zone)-15s"

#, python-format
msgid "%(host)-25s\t%(zone)-15s"
msgstr "%(host)-25s\t%(zone)-15s"

#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""
"%(message)s\n"
"状态码: %(_status)s\n"
"主体: %(_body)s"

#, python-format
msgid "%(msg)s And %(num)s services from the cluster were also removed."
msgstr "源于集群的 %(msg)s 和 %(num)s 服务也被删除。"

#, python-format
msgid ""
"%(msg_type)s: creating NetworkPortal: ensure port %(port)d on ip %(ip)s is "
"not in use by another service."
msgstr ""
"%(msg_type)s：创建 NetworkPortal：请确保 IP %(ip)s 上的端口 %(port)d未被另一"
"项服务使用。"

#, python-format
msgid "%(name)s cannot be all spaces."
msgstr "%(name)s不能是所有空间"

#, python-format
msgid "%(new_size)s < current size %(size)s"
msgstr "%(new_size)s < 当前大小 %(size)s"

#, python-format
msgid ""
"%(op)s: backup %(bck_id)s, volume %(vol_id)s failed. Backup object has "
"unexpected mode. Image or file backups supported, actual mode is "
"%(vol_mode)s."
msgstr ""
"%(op)s：备份 %(bck_id)s（针对卷 %(vol_id)s）失败。备份对象具有意外方式。支持"
"映像或文件备份，实际方式为 %(vol_mode)s。"

#, python-format
msgid "%(service)s Service is not %(status)s on storage appliance: %(host)s"
msgstr "在以下存储设备上，%(service)s 服务并非处于 %(status)s 状态：%(host)s"

#, python-format
msgid ""
"%(worker_name)s value of %(workers)d is invalid, must be greater than 0."
msgstr "%(workers)d 的 %(worker_name)s 值无效，必须大于 0。"

#, python-format
msgid "%s \"data\" is not in result."
msgstr "结果中没有 %s “数据”。"

#, python-format
msgid "%s assigned"
msgstr "%s 已分配"

#, python-format
msgid ""
"%s cannot be accessed. Verify that GPFS is active and file system is mounted."
msgstr "%s 无法访问。请验证 GPFS 是否处于活动状态并且文件系统是否已安装。"

#, python-format
msgid "%s cannot be resized using clone operation as it contains no blocks."
msgstr "%s 无法使用克隆操作来调整大小，因为它未包含任何块。"

#, python-format
msgid ""
"%s cannot be resized using clone operation as it is hosted on compressed "
"volume"
msgstr "%s 无法使用克隆操作来调整大小，因为它托管于压缩卷上"

#, python-format
msgid "%s changed"
msgstr "%s 已更改"

#, python-format
msgid "%s configuration option is not set."
msgstr "未设置 %s 配置选项。"

#, python-format
msgid "%s does not exist."
msgstr "%s 不存在。"

#, python-format
msgid "%s is not a directory."
msgstr "%s 不是一个目录。"

#, python-format
msgid "%s is not installed"
msgstr "未安装 %s"

#, python-format
msgid "%s is not installed."
msgstr "未安装 %s。"

#, python-format
msgid "%s is not set"
msgstr "未设置 %s "

#, python-format
msgid "%s is not set and is required for the replication device to be valid."
msgstr "未设置 %s，它是使复制设备生效所必需的。"

#, python-format
msgid "%s is not set."
msgstr "未设置 %s。"

#, python-format
msgid "%s must be a valid raw or qcow2 image."
msgstr "%s 必须为有效的 raw 映像或 qcow2 映像。"

#, python-format
msgid "%s must be an absolute path."
msgstr "%s 必须为绝对路径。"

#, python-format
msgid "%s not set in cinder.conf"
msgstr "cinder.conf 中未设置 %s"

#, python-format
msgid "%s not set."
msgstr "未设置 %s。"

#, python-format
msgid "'%(key)s = %(value)s'"
msgstr "'%(key)s = %(value)s'"

#, python-format
msgid ""
"'%(prot)s' is invalid for flashsystem_connection_protocol in config file. "
"valid value(s) are %(enabled)s."
msgstr ""
"对于配置文件中的 flashsystem_connection_protocol，“%(prot)s”无效。有效值为 "
"%(enabled)s。"

msgid "'active' must be present when writing snap_info."
msgstr "写入 snap_info 时，状态必须为“活动”。"

msgid "'consistencygroup_id' must be specified"
msgstr "必须指定“consistencygroup_id”"

msgid "'qemu-img info' parsing failed."
msgstr "'qemu-img info'解析失败"

#, python-format
msgid ""
"(Command: %(cmd)s) (Return Code: %(exit_code)s) (Stdout: %(stdout)s) "
"(Stderr: %(stderr)s)"
msgstr ""
"（命令：%(cmd)s）（返回码：%(exit_code)s）（标准输出：%(stdout)s）（标准错"
"误：%(stderr)s）"

msgid "400 Bad Request"
msgstr "400 错误请求"

msgid "401 Unauthorized Error"
msgstr "401 未授权错误"

msgid "404 Not Found Error"
msgstr "404 资源未找到错误"

msgid "413 Request entity too large"
msgstr "413 请求实体过大"

msgid "A concurrent, possibly contradictory, request has been made."
msgstr "发出了并行的可能对立的请求。"

msgid "A readonly volume must be attached as readonly."
msgstr "只读卷必须以只读方式进行挂载。"

msgid "A valid secondary target MUST be specified in order to failover."
msgstr "必须指定有效辅助以进行故障转移。"

msgid "A volume ID or share was not specified."
msgstr "未指定卷标识或者共享。"

#, python-format
msgid ""
"API Version String %(version)s is of invalid format. Must be of format "
"MajorNum.MinorNum."
msgstr ""
"API 版本字符串 %(version)s 为无效格式。必须为以下格式：MajorNum.MinorNum。"

#, python-format
msgid "API response: %s"
msgstr "API 响应：%s"

#, python-format
msgid "API version %(version)s is not supported on this method."
msgstr "API 版本 %(version)s 在此方法上不受支持。"

msgid ""
"About to delete child projects having non-zero quota. This should not be "
"performed"
msgstr "将删除具有非零配额的子项目。不应执行此操作"

msgid "Access list not available for public volume types."
msgstr "对于公用卷类型，未提供访问列表。"

msgid "Activate or deactivate QoS error."
msgstr "激活或者取消激活 QoS 时发生错误。"

msgid "Activate snapshot error."
msgstr "激活快照时发生错误。"

#, python-format
msgid "Activating zone set failed: (Zone set=%(cfg_name)s error=%(err)s)."
msgstr "激活区域集失败（区域集为 %(cfg_name)s，发生的错误为 %(err)s）。"

msgid "Add FC port to host error."
msgstr "将 FC 端口添加至主机时发生错误。"

msgid "Add fc initiator to array error."
msgstr "将 FC 启动程序添加至阵列时发生错误。"

msgid "Add initiator to array error."
msgstr "将启动程序添加至阵列时发生错误。"

msgid "Add lun to cache error."
msgstr "将 LUN 添加至高速缓存时发生错误。"

msgid "Add lun to partition error."
msgstr "将 LUN 添加至分区时发生错误。"

msgid "Add mapping view error."
msgstr "添加映射视图时发生错误。"

msgid "Add new host error."
msgstr "添加新主机时发生错误。"

msgid "Add port to port group error."
msgstr "向端口组添加端口时出错。"

#, python-format
msgid ""
"All the specified storage pools to be managed do not exist. Please check "
"your configuration. Non-existent pools: %s"
msgstr "所指定的要管理的所有存储池都不存在。请检查配置。不存在的池：%s"

msgid "An API version request must be compared to a VersionedMethod object."
msgstr "必须将 API 版本请求与 VersionedMethod 对象进行比较。"

msgid "An error has occurred during backup operation"
msgstr "在备份过程中出现一个错误"

#, python-format
msgid "An error has occurred in SheepdogDriver. (Reason: %(reason)s)"
msgstr "SheepdogDriver中发生了错误。（原因:%(reason)s）"

#, python-format
msgid ""
"An error occurred during the LUNcopy operation. LUNcopy name: "
"%(luncopyname)s. LUNcopy status: %(luncopystatus)s. LUNcopy state: "
"%(luncopystate)s."
msgstr ""
"在 LUNcopy 操作期间发生错误。LUNcopy 名称为 %(luncopyname)s。LUNcopy 状态为 "
"%(luncopystatus)s。LUNcopy 状态为 %(luncopystate)s。"

#, python-format
msgid "An error occurred while reading volume \"%s\"."
msgstr "读取卷“%s”时发生错误。"

#, python-format
msgid "An error occurred while seeking for volume \"%s\"."
msgstr "查找卷“%s”时发生错误。"

#, python-format
msgid "An error occurred while writing to volume \"%s\"."
msgstr "写入卷“%s”时发生错误。"

msgid "An unknown error occurred."
msgstr "发生未知错误。"

msgid "An unknown exception occurred."
msgstr "发生未知异常。"

msgid ""
"An user with a token scoped to a subproject is not allowed to see the quota "
"of its parents."
msgstr "不允许令牌作用域仅限于子项目的用户查看其父代的配额。"

msgid "Append port group description error."
msgstr "附加端口组描述时出错。"

#, python-format
msgid ""
"Applying the zones and cfgs to the switch failed (error code=%(err_code)s "
"error msg=%(err_msg)s."
msgstr ""
"对交换机应用 zones 和 cfgs 失败（错误代码为 %(err_code)s，错误消息为 "
"%(err_msg)s）。"

#, python-format
msgid "Array does not exist or is offline. Current status of array is %s."
msgstr "阵列不存在或者处于脱机状态。阵列的当前状态为 %s。"

msgid "Associate host to hostgroup error."
msgstr "使主机与主机组关联时发生错误。"

msgid "Associate host to mapping view error."
msgstr "使主机与映射视图关联时发生错误。"

msgid "Associate initiator to host error."
msgstr "使启动程序与主机相关联时发生错误。"

msgid "Associate lun to QoS error."
msgstr "将 LUN 关联至 QoS 时出错。"

msgid "Associate lun to lungroup error."
msgstr "使 LUN 与 LUN 组关联时发生错误。"

msgid "Associate lungroup to mapping view error."
msgstr "使 LUN 组与映射视图关联时发生错误。"

msgid "Associate portgroup to mapping view error."
msgstr "使端口组与映射视图关联时发生错误。"

msgid "At least one valid iSCSI IP address must be set."
msgstr "必须至少设置一个有效 iSCSI IP 地址。"

#, python-format
msgid "Attempt to transfer %s with invalid auth key."
msgstr "请尝试使用有效的认证密钥传输 %s。"

#, python-format
msgid "Attribute: %s not found."
msgstr "属性： %s 未找到"

#, python-format
msgid "Authentication failed, verify the switch credentials, error code %s."
msgstr "认证失败，请验证交换机凭证，错误代码：%s。"

#, python-format
msgid "Availability zone '%(s_az)s' is invalid."
msgstr "可用性区域“%(s_az)s”无效。"

msgid "Available categories:"
msgstr "可用的类别："

#, python-format
msgid "Backend doesn't exist (%(backend)s)"
msgstr "后端不存在 (%(backend)s)"

msgid "Backend storage did not configure fiber channel target."
msgstr "后端存储器未配置光纤通道目标。"

msgid "Backing up an in-use volume must use the force flag."
msgstr "备份一个正在使用的卷时必须使用强制标志。"

#, python-format
msgid "Backup %(backup_id)s could not be found."
msgstr "找不到备份 %(backup_id)s。"

msgid "Backup RBD operation failed"
msgstr "备份RBD操作失败"

msgid "Backup already exists in database."
msgstr "数据库中已存在备份。"

msgid "Backup id required"
msgstr "需要备份标识"

msgid "Backup operation of an encrypted volume failed."
msgstr "已加密卷的备份操作失败。"

#, python-format
msgid ""
"Backup service %(configured_service)s does not support verify. Backup id "
"%(id)s is not verified. Skipping verify."
msgstr ""
"备份服务 %(configured_service)s 不支持验证。未验证备份标识 %(id)s。正在跳过验"
"证。"

#, python-format
msgid ""
"Backup service %(service)s does not support verify. Backup id %(id)s is not "
"verified. Skipping reset."
msgstr "备份服务 %(service)s 不支持验证。未验证备份标识 %(id)s。正在跳过重置。"

#, python-format
msgid "Backup should only have one snapshot but instead has %s"
msgstr "备份应该仅具有一个快照，但是具有 %s 个快照"

msgid "Backup status must be available"
msgstr "备份状态必须为“可用”"

#, python-format
msgid "Backup status must be available and not %s."
msgstr "备份状态必须为“可用”，不能是 %s。"

msgid "Backup status must be available or error"
msgstr "备份状态必须为“可用”或“错误”"

msgid "Backup to be restored has invalid size"
msgstr "要复原的备份具有无效大小"

#, python-format
msgid "Bad HTTP response status %(status)s"
msgstr "错误的HTTP响应状态 %(status)s"

#, python-format
msgid "Bad key(s) in quota set: %s"
msgstr "配额集中的键不正确：%s"

#, python-format
msgid ""
"Bad or unexpected response from the storage volume backend API: %(data)s"
msgstr "从存储卷后端 API 返回了不正确或意外的响应：%(data)s"

msgid "Bad response from Datera API"
msgstr "来自 Datera API 的响应不正确"

msgid "Bad response from SolidFire API"
msgstr "来自SolidFire API的错误响应"

#, python-format
msgid "Bad response from XMS, %s"
msgstr "来自 XMS 的响应不正确，%s"

msgid "Binary"
msgstr "二进制"

msgid "Blank components"
msgstr "空组件"

#, python-format
msgid "Brocade Fibre Channel Zoning CLI error: %(reason)s"
msgstr "Brocade 光纤通道分区 CLI 错误：%(reason)s"

#, python-format
msgid "Brocade Fibre Channel Zoning HTTP error: %(reason)s"
msgstr "Brocade 光纤通道分区 HTTP 错误：%(reason)s"

msgid "CHAP secret should be 12-16 bytes."
msgstr "CHAP 密钥应为 12 到 16 个字节。"

#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"CLI 异常输出：\n"
"命令：%(cmd)s\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s"

#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"CLI 异常输出：\n"
"命令：%(cmd)s\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s。"

msgid ""
"CMMVC6071E The VDisk-to-host mapping was not created because the VDisk is "
"already mapped to a host.\n"
"\""
msgstr ""
"CMMVC6071E 未创建 VDisk 至主机的映射，因为该 VDisk 已映射至主机。\n"
"\""

#, python-format
msgid "CPG (%s) doesn't exist on array"
msgstr "数组中不存在 CPG (%s)"

msgid "Cache name is None, please set smartcache:cachename in key."
msgstr "高速缓存名称为 None，请在键中设置 smartcache:cachename。"

#, python-format
msgid "Cache volume %s does not have required properties"
msgstr "高速缓存卷 %s 没有必需属性。"

msgid "Can not add FC port to host."
msgstr "无法将 FC 端口添加至主机。"

#, python-format
msgid "Can not find cache id by cache name %(name)s."
msgstr "按高速缓存名称 %(name)s 找不到高速缓存标识。"

#, python-format
msgid "Can not find partition id by name %(name)s."
msgstr "按名称 %(name)s 找不到分区标识。"

#, python-format
msgid "Can not get pool info. pool: %s"
msgstr "无法获取池信息。池：%s"

#, python-format
msgid "Can not translate %s to integer."
msgstr "无法把 %s 转换成整数"

msgid "Can't decode backup record."
msgstr "无法将备份记录解码。"

#, python-format
msgid "Can't extend replication volume, volume: %(id)s"
msgstr "无法扩展复制卷，卷：%(id)s"

msgid "Can't find LUN on the array, please check the source-name or source-id."
msgstr "在阵列上找不到 LUN，请检查 source-name 或 source-id。"

#, python-format
msgid "Can't find cache name on the array, cache name is: %(name)s."
msgstr "在阵列上找不到高速缓存名称，高速缓存名称为 %(name)s。"

#, python-format
msgid "Can't find partition name on the array, partition name is: %(name)s."
msgstr "在阵列上找不到分区名称，分区名称为 %(name)s。"

#, python-format
msgid "Can't find service: %s"
msgstr "找不到以下服务：%s"

msgid ""
"Can't find snapshot on array, please check the source-name or source-id."
msgstr "在阵列上找不到快照，请检查 source-name 或 source-id。"

msgid "Can't find the same host id from arrays."
msgstr "在阵列中找不到同一主机标识。"

#, python-format
msgid "Can't get volume id from snapshot, snapshot: %(id)s"
msgstr "无法通过快照获取卷，快照：%(id)s"

#, python-format
msgid "Can't get volume id. Volume name: %s."
msgstr "无法获取卷标识，卷名：%s。"

#, python-format
msgid "Can't import LUN %(lun_id)s to Cinder. LUN type mismatched."
msgstr "无法将 LUN %(lun_id)s 导入至 Cinder。LUN 类型不匹配。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a HyperMetroPair."
msgstr "无法将 LUN %s 导入至 Cinder。它在 HyperMetroPair 中已存在。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a LUN copy task."
msgstr "无法将 LUN %s 导入至 Cinder。它在 LUN 复制任务中已存在。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a LUN group."
msgstr "无法将 LUN %s 导入至 Cinder。它在 LUN 组中已存在。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a LUN mirror."
msgstr "无法将 LUN %s 导入至 Cinder。它在 LUN 镜像中已存在。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a SplitMirror."
msgstr "无法将 LUN %s 导入至 Cinder。它在 SplitMirror 中已存在。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a migration task."
msgstr "无法将 LUN %s 导入至 Cinder。它在迁移任务中已存在。"

#, python-format
msgid ""
"Can't import LUN %s to Cinder. Already exists in a remote replication task."
msgstr "无法将 LUN %s 导入至 Cinder。它在远程复制任务中已存在。"

#, python-format
msgid "Can't import LUN %s to Cinder. LUN status is not normal."
msgstr "无法将 LUN %s 导入至 Cinder。LUN 状态异常。"

#, python-format
msgid "Can't import snapshot %s to Cinder. Snapshot doesn't belong to volume."
msgstr "无法将快照 %s 导入至 Cinder。快照不属于卷。"

#, python-format
msgid "Can't import snapshot %s to Cinder. Snapshot is exposed to initiator."
msgstr "无法将快照 %s 导入至 Cinder。快照已展示给启动程序。"

#, python-format
msgid ""
"Can't import snapshot %s to Cinder. Snapshot status is not normal or running "
"status is not online."
msgstr "无法将 LUN %s 导入至 Cinder。快照状态异常或运行状态并非“在线”。"

msgid "Can't parse backup record."
msgstr "无法解析备份记录。"

#, python-format
msgid ""
"Cannot add volume %(volume_id)s to group %(group_id)s because it has no "
"volume type."
msgstr "无法将卷 %(volume_id)s 添加至组 %(group_id)s，因为它没有任何卷类型。"

#, python-format
msgid ""
"Cannot add volume %(volume_id)s to group %(group_id)s because it is already "
"in group %(orig_group)s."
msgstr ""
"无法将卷 %(volume_id)s 添加至组 %(group_id)s，因为它已经存在于组 "
"%(orig_group)s 中。"

#, python-format
msgid ""
"Cannot add volume %(volume_id)s to group %(group_id)s because volume cannot "
"be found."
msgstr "无法将卷 %(volume_id)s 添加至组 %(group_id)s，因为找不到该卷。"

#, python-format
msgid ""
"Cannot add volume %(volume_id)s to group %(group_id)s because volume does "
"not exist."
msgstr "无法将卷 %(volume_id)s 添加至组 %(group_id)s，因为该卷不存在。"

#, python-format
msgid ""
"Cannot add volume %(volume_id)s to group %(group_id)s because volume is in "
"an invalid state: %(status)s. Valid states are: %(valid)s."
msgstr ""
"无法将卷 %(volume_id)s 添加至组 %(group_id)s，因为该卷处于无效状态："
"%(status)s。以下是有效状态：%(valid)s。"

#, python-format
msgid ""
"Cannot add volume %(volume_id)s to group %(group_id)s because volume type "
"%(volume_type)s is not supported by the group."
msgstr ""
"无法将卷 %(volume_id)s 添加至组 %(group_id)s，因为该组不支持卷类型 "
"%(volume_type)s。"

msgid "Cannot change VF context in the session."
msgstr "无法更改会话中的 VF 上下文。"

#, python-format
msgid ""
"Cannot change VF context, specified VF is not available in the manageable VF "
"list %(vf_list)s."
msgstr "无法更改 VF 上下文，指定的 VF 在管理 VF 列表 %(vf_list)s 中不可用。"

#, python-format
msgid "Cannot create directory %s."
msgstr "无法创建目录 %s。"

msgid "Cannot create encryption specs. Volume type in use."
msgstr "无法创建加密规范。卷类型在使用中。"

#, python-format
msgid ""
"Cannot create group %(group)s because snapshot %(snap)s is not in a valid "
"state. Valid states are: %(valid)s."
msgstr ""
"无法创建组 %(group)s，因为快照 %(snap)s 未处于有效状态。以下是有效状态："
"%(valid)s。"

#, python-format
msgid ""
"Cannot create group %(group)s because source volume %(source_vol)s is not in "
"a valid state. Valid states are: %(valid)s."
msgstr ""
"无法创建组 %(group)s，因为源卷 %(source_vol)s 未处于有效状态。有效状态为 "
"%(valid)s。"

#, python-format
msgid "Cannot create group_type with name %(name)s and specs %(group_specs)s"
msgstr "无法创建名称为 %(name)s 且规格为 %(group_specs)s 的组类型。"

#, python-format
msgid ""
"Cannot create image of disk format: %s. Only vmdk disk format is accepted."
msgstr "无法创建磁盘格式为 %s 映像。仅接受 vmdk 磁盘格式。"

#, python-format
msgid "Cannot create volume of size %s: not multiple of 8GB."
msgstr "无法创建大小为 %s 的卷：该大小不是 8GB 的倍数。"

#, python-format
msgid "Cannot create volume_type with name %(name)s and specs %(extra_specs)s"
msgstr "无法创建名称为 %(name)s 规格为 %(extra_specs)s 的卷类型。"

#, python-format
msgid ""
"Cannot delete cache volume: %(cachevol_name)s. It was updated at "
"%(updated_at)s and currently has %(numclones)d volume instances."
msgstr ""
"无法删除高速缓存卷：%(cachevol_name)s。在 %(updated_at)s 对其进行了更新，它当"
"前具有 %(numclones)d 卷实例。"

#, python-format
msgid ""
"Cannot delete cache volume: %(cachevol_name)s. It was updated at "
"%(updated_at)s and currently has %(numclones)s volume instances."
msgstr ""
"无法删除高速缓存卷：%(cachevol_name)s。在 %(updated_at)s 对其进行了更新，它当"
"前具有 %(numclones)s 卷实例。"

msgid "Cannot delete encryption specs. Volume type in use."
msgstr "无法删除加密规范。卷类型在使用中。"

msgid "Cannot find migration task."
msgstr "找不到迁移任务。"

msgid "Cannot ping DRBDmanage backend"
msgstr "无法对 DRBDmanage 后端执行 ping 操作"

#, python-format
msgid ""
"Cannot provide both 'cgsnapshot_id' and 'source_cgid' to create consistency "
"group %(name)s from source."
msgstr ""
"无法同时提供“cgsnapshot_id”和“source_cgid”以从源创建一致性组 %(name)s。"

msgid "Cannot register resource"
msgstr "无法注册资源"

msgid "Cannot register resources"
msgstr "无法注册多个资源"

#, python-format
msgid ""
"Cannot remove volume %(volume_id)s from group %(group_id)s because it is not "
"in the group."
msgstr "无法从组 %(group_id)s 移除卷 %(volume_id)s，因为它不在该组中。"

#, python-format
msgid ""
"Cannot remove volume %(volume_id)s from group %(group_id)s because volume is "
"in an invalid state: %(status)s. Valid states are: %(valid)s."
msgstr ""
"无法从组 %(group_id)s 移除卷 %(volume_id)s，因为该卷处于无效状态："
"%(status)s。以下是有效状态：%(valid)s。"

#, python-format
msgid "Cannot retype from HPE3PARDriver to %s."
msgstr "无法将 HPE3PARDriver 转型为 %s。"

msgid "Cannot retype from one 3PAR array to another."
msgstr "一个 3PAR 阵列无法通过 retype 操作变为另一个阵列。"

msgid "Cannot retype to a CPG in a different domain."
msgstr "无法执行 retype 操作，以变为另一个域中的 CPG。"

msgid "Cannot retype to a snap CPG in a different domain."
msgstr "无法执行 retype 操作，以变为另一个域中的 SNAP CPG。"

msgid "Cannot save group_snapshots changes in group object update."
msgstr "组对象更新时无法保存组快照变更。"

msgid "Cannot save volume_types changes in group object update."
msgstr "组对象更新时无法保存卷类型变更。"

msgid "Cannot save volumes changes in group object update."
msgstr "组对象更新时无法保存卷变更。"

msgid "Cannot specify both protection domain name and protection domain id."
msgstr "无法同时指定保护域名和保护域标识。"

msgid "Cannot specify both storage pool name and storage pool id."
msgstr "无法同时指定存储池名称和存储池标识。"

msgid "Cannot update encryption specs. Volume type in use."
msgstr "无法更新加密规范。卷类型在使用中。"

#, python-format
msgid ""
"Cannot update group %(group_id)s because no valid name, description, "
"add_volumes, or remove_volumes were provided."
msgstr ""
"无法更新组 %(group_id)s，因为未提供任何有效名称、描述、add_volumes 或 "
"remove_volumes。"

#, python-format
msgid "Cannot update group_type %(id)s"
msgstr "无法更新组类型 %(id)s。"

#, python-format
msgid "Cannot update volume_type %(id)s"
msgstr "无法更新 volume_type %(id)s"

#, python-format
msgid "CgSnapshot %(cgsnapshot_id)s could not be found."
msgstr "找不到 Cg 快照 %(cgsnapshot_id)s。"

msgid "Change hostlun id error."
msgstr "更改 hostlun 标识时出错。"

msgid "Change lun priority error."
msgstr "更改 LUN 优先级时发生错误。"

msgid "Change lun smarttier policy error."
msgstr "更改 LUN smarttier 策略时发生错误。"

#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: %(unders)s"
msgstr "对于下列资源，更改将导致使用量小于 0：%(unders)s"

msgid "Check access permissions for the ZFS share assigned to this driver."
msgstr "请检查分配给此驱动程序的 ZFS 共享项的访问许可权。"

msgid "Check hostgroup associate error."
msgstr "检查主机组关联时发生错误。"

msgid "Check initiator added to array error."
msgstr "检查已添加至阵列的启动程序时发生错误。"

msgid "Check initiator associated to host error."
msgstr "检查与主机相关联的启动程序时发生错误。"

msgid "Check lungroup associate error."
msgstr "检查 LUN 组关联时发生错误。"

msgid "Check portgroup associate error."
msgstr "检查端口组关联时发生错误。"

msgid ""
"Check the state of the http service. Also ensure that the https port number "
"is the same as the one specified in cinder.conf."
msgstr ""
"请检查 HTTP 服务的状态。另外，请确保 HTTPS 端口号与 cinder.conf 中指定的 "
"HTTPS 端口号相同。"

msgid "Chunk size is not multiple of block size for creating hash."
msgstr "区块大小不是用于创建散列的块大小的倍数。"

#, python-format
msgid "Cisco Fibre Channel Zoning CLI error: %(reason)s"
msgstr "Cisco 光纤通道分区 CLI 错误：%(reason)s"

#, python-format
msgid ""
"Clone type '%(clone_type)s' is invalid; valid values are: '%(full_clone)s' "
"and '%(linked_clone)s'."
msgstr ""
"克隆“%(clone_type)s”无效；有效值为：“%(full_clone)s”和“%(linked_clone)s”。"

msgid "Cluster"
msgstr "集群"

#, python-format
msgid "Cluster %(id)s could not be found."
msgstr "无法找到标识为 %(id)s 的集群。"

#, python-format
msgid "Cluster %(id)s still has hosts."
msgstr "集群 %(id)s 仍存在主机。"

#, python-format
msgid "Cluster %(name)s already exists."
msgstr "集群 %(name)s 已存在。"

#, python-format
msgid "Cluster %s successfully removed."
msgstr "成功删除集群 %s。"

msgid ""
"Cluster is not formatted. You should probably perform \"dog cluster format\"."
msgstr "集群未格式化。您可能应该执行“dog cluster format”。"

#, python-format
msgid "CommandLineHelper._wait_for_condition: %s timeout."
msgstr "CommandLineHelper._wait_for_condition：%s 超时。"

msgid "Compression Enabler is not installed. Can not create compressed volume."
msgstr "未安装压缩启用程序。无法创建压缩卷。"

#, python-format
msgid "Compute cluster: %(cluster)s not found."
msgstr "找不到计算集群 %(cluster)s。"

msgid "Condition has no field."
msgstr "条件没有任何字段。"

#, python-format
msgid "Config 'max_over_subscription_ratio' invalid. Must be > 0: %s"
msgstr "配置“max_over_subscription_ratio”无效。必须大于 0：%s"

msgid "Configuration error: dell_sc_ssn not set."
msgstr "配置错误：未设置 dell_sc_ssn。"

msgid "Configuration is not found."
msgstr "找不到配置。"

#, python-format
msgid "Configuration value %s is not set."
msgstr "未设置配置值 %s。"

#, python-format
msgid ""
"Conflicting QoS specifications in volume type %s: when QoS spec is "
"associated to volume type, legacy \"netapp:qos_policy_group\" is not allowed "
"in the volume type extra specs."
msgstr ""
"卷类型 %s 中存在冲突的 QoS 规范：当 QoS 规范与卷类型相关联时，不允许卷类型额"
"外规范中存在旧的“netapp:qos_policy_group”。"

#, python-format
msgid "Connection to glance failed: %(reason)s"
msgstr "连接glance失败: %(reason)s"

#, python-format
msgid "Connection to swift failed: %(reason)s"
msgstr "连接 Swift 失败：%(reason)s"

#, python-format
msgid "Connector does not provide: %s"
msgstr "连接器未提供：%s"

#, python-format
msgid "Connector doesn't have required information: %(missing)s"
msgstr "连接器没有必需信息：%(missing)s"

#, python-format
msgid "ConsistencyGroup %(consistencygroup_id)s could not be found."
msgstr "找不到一致性组 %(consistencygroup_id)s。"

msgid "Container"
msgstr "容器"

msgid "Container size smaller than required file size."
msgstr "容器大小小于所需文件大小。"

#, python-format
msgid "Converted to %(f1)s, but format is now %(f2)s"
msgstr "已转换为 %(f1)s，但现在格式为 %(f2)s"

#, python-format
msgid "Converted to %(vol_format)s, but format is now %(file_format)s"
msgstr "已转换为 %(vol_format)s，但现在格式为 %(file_format)s"

#, python-format
msgid "Converted to raw, but format is now %s"
msgstr "转化为裸格式，但目前格式是 %s"

#, python-format
msgid "Converted to raw, but format is now %s."
msgstr "已转换为原始文件，但现在格式为 %s。"

msgid "Coordinator uninitialized."
msgstr "协调程序未初始化。"

#, python-format
msgid ""
"Copy volume task failed: convert_to_base_volume: id=%(id)s, status="
"%(status)s."
msgstr ""
"“复制卷”任务失败：convert_to_base_volume：id=%(id)s，status=%(status)s。"

#, python-format
msgid ""
"Copy volume task failed: create_cloned_volume id=%(id)s, status=%(status)s."
msgstr "复制卷任务失败：create_cloned_volume id=%(id)s，status=%(status)s。"

#, python-format
msgid "Copying metadata from %(src_type)s %(src_id)s to %(vol_id)s."
msgstr "正在将元数据从 %(src_type)s %(src_id)s 复制到 %(vol_id)s。"

msgid ""
"Could not determine which Keystone endpoint to use. This can either be set "
"in the service catalog or with the cinder.conf config option "
"'backup_swift_auth_url'."
msgstr ""
"无法确定要使用的 Keystone 端点。可在服务目录中设置此项，也可使用 cinder.conf "
"配置选项 “backup_swift_auth_url”设置此项。"

msgid ""
"Could not determine which Swift endpoint to use. This can either be set in "
"the service catalog or with the cinder.conf config option 'backup_swift_url'."
msgstr ""
"无法确定要使用的 Swift 端点。可在服务目录中设置此项，也可使用 cinder.conf 配"
"置选项 “backup_swift_url”设置此项。"

#, python-format
msgid "Could not find GPFS cluster id: %s."
msgstr "找不到 GPFS 集群标识：%s。"

#, python-format
msgid "Could not find GPFS file system device: %s."
msgstr "找不到 GPFS 文件系统设备：%s。"

#, python-format
msgid "Could not find config at %(path)s"
msgstr "在 %(path)s 找不到配置文件。"

#, python-format
msgid "Could not find iSCSI export for volume %s"
msgstr "对于卷 %s，找不到 iSCSI 导出"

#, python-format
msgid "Could not find key in output of command %(cmd)s: %(out)s."
msgstr "在命令 %(cmd)s 的输出 %(out)s 中找不到键。"

#, python-format
msgid "Could not find parameter %(param)s"
msgstr "找不到参数 %(param)s"

#, python-format
msgid "Could not find target %s"
msgstr "找不到目标 %s"

#, python-format
msgid "Could not find the parent volume for Snapshot '%s' on array."
msgstr "在阵列上找不到快照“%s”的父卷。"

#, python-format
msgid "Could not find unique snapshot %(snap)s on volume %(vol)s."
msgstr "在卷 %(vol)s 上找不到唯一快照 %(snap)s。"

msgid "Could not get system name."
msgstr "未能获取系统名称。"

#, python-format
msgid ""
"Could not read information for snapshot %(name)s. Code: %(code)s. Reason: "
"%(reason)s"
msgstr "无法读取快照 %(name)s 的信息。代码：%(code)s。原因：%(reason)s"

#, python-format
msgid "Could not restore configuration file %(file_path)s: %(exc)s"
msgstr "无法复原配置文件 %(file_path)s：%(exc)s"

#, python-format
msgid "Could not save configuration to %(file_path)s: %(exc)s"
msgstr "未能将配置保存到 %(file_path)s：%(exc)s"

#, python-format
msgid "Could not start consistency group snapshot %s."
msgstr "无法启动一致性组快照 %s。"

#, python-format
msgid "Couldn't find ORM model for Persistent Versioned Object %s."
msgstr "无法为持久版本对象%s找到ORM模型。"

#, python-format
msgid "Couldn't remove cluster %s because it doesn't exist."
msgstr "无法删除集群 %s，因为它不存在。"

#, python-format
msgid "Couldn't remove cluster %s because it still has hosts."
msgstr "无法删除集群 %s，因为它仍存在主机。"

#, python-format
msgid "Counter %s not found"
msgstr "找不到计数器 %s"

msgid "Create QoS policy error."
msgstr "创建 QoS 策略时发生错误。"

#, python-format
msgid ""
"Create backup aborted, expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"备份创建已异常中止，需要的备份状态为 %(expected_status)s，但实际为 "
"%(actual_status)s。"

#, python-format
msgid ""
"Create backup aborted, expected volume status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"备份创建已异常中止，需要的卷状态为 %(expected_status)s，但实际为 "
"%(actual_status)s。"

msgid "Create group failed."
msgstr "创建组失败。"

msgid "Create hostgroup error."
msgstr "创建主机组时发生错误。"

#, python-format
msgid "Create hypermetro error. %s."
msgstr "创建 hypermetro 错误。%s。"

msgid "Create lun error."
msgstr "创建 LUN 时出错。"

msgid "Create lun migration error."
msgstr "创建 LUN 迁移时发生错误。"

msgid "Create luncopy error."
msgstr "创建 LUNcopy 时发生错误。"

msgid "Create lungroup error."
msgstr "创建 LUN 组时发生错误。"

msgid "Create manager volume flow failed."
msgstr "创建管理器卷流失败。"

msgid "Create port group error."
msgstr "创建端口组时出错。"

msgid "Create replication error."
msgstr "创建复制错误。"

#, python-format
msgid "Create replication pair failed. Error: %s."
msgstr "创建复制对失败。错误：%s。"

msgid "Create snapshot error."
msgstr "创建快照时发生错误。"

#, python-format
msgid "Create volume error. Because %s."
msgstr "创建卷错误。因为 %s。"

msgid "Create volume failed."
msgstr "创建卷失败。"

#, python-format
msgid ""
"Creating and activating zone set failed: (Zone set=%(cfg_name)s error="
"%(err)s)."
msgstr "创建并激活区域集失败（区域集为 %(cfg_name)s，发生的错误为 %(err)s）。"

#, python-format
msgid ""
"Creating and activating zone set failed: (Zone set=%(zoneset)s error="
"%(err)s)."
msgstr "创建并激活区域集失败（区域集为 %(zoneset)s，发生的错误为 %(err)s）。"

#, python-format
msgid ""
"DRBDmanage driver error: expected key \"%s\" not in answer, wrong DRBDmanage "
"version?"
msgstr ""
"DRBDmanage 驱动程序错误：回复中没有预期关键字“%s”，DRBDmanage 版本是否正确？"

msgid ""
"DRBDmanage driver setup error: some required libraries (dbus, drbdmanage.*) "
"not found."
msgstr ""
"DRBDmanage 驱动程序设置错误：找不到某些必需的库（dbus 和 drbdmanage.*）。"

#, python-format
msgid "DRBDmanage expected one resource (\"%(res)s\"), got %(n)d"
msgstr "DRBDmanage 期望一个资源 (\"%(res)s\")，但是获得了 %(n)d"

#, python-format
msgid ""
"DRBDmanage timeout waiting for new volume after snapshot restore; resource "
"\"%(res)s\", volume \"%(vol)s\""
msgstr "快照复原后 DRBDmanage 等待新卷时超时；资源“%(res)s”，卷“%(vol)s”"

#, python-format
msgid ""
"DRBDmanage timeout waiting for snapshot creation; resource \"%(res)s\", "
"snapshot \"%(sn)s\""
msgstr "DRBDmanage 等待创建快照时超时；资源“%(res)s”，快照“%(sn)s”"

#, python-format
msgid ""
"DRBDmanage timeout waiting for volume creation; resource \"%(res)s\", volume "
"\"%(vol)s\""
msgstr "DRBDmanage 等待创建卷时超时；资源“%(res)s”，卷“%(vol)s”"

#, python-format
msgid ""
"DRBDmanage timeout waiting for volume size; volume ID \"%(id)s\" (res "
"\"%(res)s\", vnr %(vnr)d)"
msgstr ""
"DRBDmanage 等待卷大小时超时；卷标识“%(id)s”（res \"%(res)s\"，vnr %(vnr)d）"

#, python-format
msgid "Dataset %s is not shared in Nexenta Store appliance"
msgstr "数据集 %s 在 Nexenta 存储设备中未共享"

#, python-format
msgid "Dataset group %s not found at Nexenta SA"
msgstr "在 Nexenta SA 中找不到数据库组 %s"

#, python-format
msgid ""
"Dedup is a valid provisioning type, but requires WSAPI version "
"'%(dedup_version)s' version '%(version)s' is installed."
msgstr ""
"去重是有效的供应类型，但是要求安装了 WSAPI 版本“%(dedup_version)s”版"
"本“%(version)s”。"

msgid "Default group type can not be found."
msgstr "找不到缺省组类型。"

#, python-format
msgid ""
"Default quota for resource: %(res)s is set by the default quota flag: quota_"
"%(res)s, it is now deprecated. Please use the default quota class for "
"default quota."
msgstr ""
"资源 %(res)s 的缺省配额由缺省配额标记 quota_%(res)s 设置，现在不推荐使用。请"
"对缺省配额使用缺省配额类。 "

msgid "Default volume type can not be found."
msgstr "找不到缺省卷类型。"

msgid "Delete LUNcopy error."
msgstr "删除 LUNcopy 时发生错误。"

msgid "Delete QoS policy error."
msgstr "删除 QoS 策略时发生错误。"

msgid "Delete associated lun from lungroup error."
msgstr "从 LUN 组中删除相关联的 LUN 时发生错误。"

#, python-format
msgid ""
"Delete backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"备份删除已异常中止，当前配置的备份服务 [%(configured_service)s] 不是已用来创"
"建此备份的备份服务 [%(backup_service)s]。"

msgid "Delete group failed."
msgstr "删除组失败。"

msgid "Delete hostgroup error."
msgstr "删除主机组时发生错误。"

msgid "Delete hostgroup from mapping view error."
msgstr "从映射视图删除主机组时发生错误。"

msgid "Delete lun error."
msgstr "删除 LUN 时发生错误。"

msgid "Delete lun migration error."
msgstr "删除 LUN 迁移时发生错误。"

msgid "Delete lungroup error."
msgstr "删除 LUN 组时发生错误。"

msgid "Delete lungroup from mapping view error."
msgstr "从映射视图删除 LUN 组时发生错误。"

msgid "Delete mapping view error."
msgstr "删除映射视图时发生错误。"

msgid "Delete port group error."
msgstr "删除端口组时出错。"

msgid "Delete portgroup from mapping view error."
msgstr "从映射视图删除端口组时发生错误。"

msgid "Delete snapshot error."
msgstr "删除快照时发生错误。"

#, python-format
msgid "Delete snapshot of volume not supported in state: %s."
msgstr "不支持对处于以下状态的卷删除快照：%s。"

#, python-format
msgid ""
"Delete_backup aborted, expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"Delete_backup 已异常中止，需要的备份状态为 %(expected_status)s，但实际为 "
"%(actual_status)s。"

msgid "Deleting volume from database and skipping rpc."
msgstr "正在从数据库删除卷并跳过 RPC。"

#, python-format
msgid "Deleting volume metadata is not allowed for volumes in %s status."
msgstr "当卷状态为 %s 时，不允许删除该卷的元数据。"

#, python-format
msgid "Deleting zones failed: (command=%(cmd)s error=%(err)s)."
msgstr "删除区域失败：（命令为 %(cmd)s，发生的错误为 %(err)s）。"

msgid "Dell API 2.1 or later required for Consistency Group support"
msgstr "要提供“一致性组”支持，需要 Dell API 2.1 或更高版本"

msgid ""
"Dell Cinder driver configuration error replication not supported with direct "
"connect."
msgstr "直接连接不支持 Dell Cinder 驱动程序配置错误复制。"

#, python-format
msgid "Dell Cinder driver configuration error replication_device %s not found"
msgstr "找不到 Dell Cinder 驱动程序配置错误 replication_device %s"

#, python-format
msgid "Destination has migration_status %(stat)s, expected %(exp)s."
msgstr "目标具有 migration_status %(stat)s，原应为 %(exp)s。"

msgid "Destination volume not mid-migration."
msgstr "目标卷未在迁移中。"

msgid ""
"Detach volume failed: More than one attachment, but no attachment_id "
"provided."
msgstr "拆离卷失败：存在多个连接，但是未提供 attachment_id。"

msgid "Detach volume from instance and then try again."
msgstr "请断开卷与实例的连接，然后再次进行尝试。"

#, python-format
msgid "Detected more than one volume with name %(vol_name)s"
msgstr "检测到多个具有名称 %(vol_name)s 的卷"

#, python-format
msgid "Did not find expected column in %(fun)s: %(hdr)s."
msgstr "%(fun)s 中找不到需要的列：%(hdr)s。"

#, python-format
msgid "Did not find the expected key %(key)s in %(fun)s: %(raw)s."
msgstr "在 %(fun)s 中找不到期望的键 %(key)s：%(raw)s。"

#, python-format
msgid "Domain with name %s wasn't found."
msgstr "找不到名称为 %s 的域。"

msgid "Down Hosts"
msgstr "关闭主机"

#, python-format
msgid ""
"Downlevel GPFS Cluster Detected.  GPFS Clone feature not enabled in cluster "
"daemon level %(cur)s - must be at least at level %(min)s."
msgstr ""
"检测到下层 GPFS 集群。在集群守护程序级别 %(cur)s 中未启用“GPFS 克隆”功能 - 必"
"须至少处于级别 %(min)s。"

#, python-format
msgid "Driver initialize connection failed (error: %(err)s)."
msgstr "驱动程序初始化连接失败（错误：%(err)s）。"

msgid "Driver must implement initialize_connection"
msgstr "驱动程序必须实现 initialize_connection"

#, python-format
msgid ""
"Driver successfully decoded imported backup data, but there are missing "
"fields (%s)."
msgstr "驱动程序已成功将所导入的备份数据解码，但是缺少字段 (%s)。"

#, python-format
msgid ""
"EMC VNX Cinder Driver CLI exception: %(cmd)s (Return Code: %(rc)s) (Output: "
"%(out)s)."
msgstr ""
"发生 EMC VNX Cinder 驱动程序 CLI 异常：%(cmd)s（返回码为 %(rc)s）（输出为 "
"%(out)s）。"

#, python-format
msgid ""
"EMC VNX Cinder Driver SPUnavailableException: %(cmd)s (Return Code: %(rc)s) "
"(Output: %(out)s)."
msgstr ""
"EMC VNX Cinder 驱动程序 SPUnavailableException：%(cmd)s（返回码：%(rc)s）（输"
"出：%(out)s）。"

#, python-format
msgid ""
"Either 'cgsnapshot_id' or 'source_cgid' must be provided to create "
"consistency group %(name)s from source."
msgstr ""
"必须提供“cgsnapshot_id”或者“source_cgid”，以从源创建一致性组 %(name)s。"

#, python-format
msgid ""
"Either SLO: %(slo)s or workload %(workload)s is invalid. Examine previous "
"error statement for valid values."
msgstr ""
"SLO %(slo)s 或工作负载 %(workload)s 无效。请查看先前的错误说明以了解有效值。"

msgid "Enables QoS."
msgstr "启用 QoS。"

msgid "Enables compression."
msgstr "启用压缩。"

msgid "Enables replication."
msgstr "启用复制。"

msgid "Ensure that configfs is mounted at /sys/kernel/config."
msgstr "请确保 configfs 安装在 /sys/kernel/config 处。"

#, python-format
msgid ""
"Error Adding Initiator: %(initiator)s on groupInitiatorGroup: "
"%(initiatorgroup)s Return code: %(ret.status)d Message: %(ret.data)s ."
msgstr ""
"在 groupInitiatorGroup %(initiatorgroup)s 上添加启动程序 %(initiator)s 时出"
"错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Adding to TargetGroup: %(targetgroup)s withIQN: %(iqn)sReturn code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"添加至带有 IQN %(iqn)s 的目标组 %(targetgroup)s 时出错。返回码："
"%(ret.status)d，消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Cloning Snapshot: %(snapshot)s on Volume: %(lun)s of Pool: %(pool)s "
"Project: %(project)s  Clone project: %(clone_proj)s Return code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"在池 %(pool)s 的卷 %(lun)s 上克隆快照 %(snapshot)s 时出错。项目：%(project)s "
"克隆项目：%(clone_proj)s返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Initiator: %(initiator)s on Alias: %(alias)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"对别名 %(alias)s 创建发起方 %(initiator)s 时出错。返回码：%(ret.status)d 消"
"息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Project: %(project)s on Pool: %(pool)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"在池 %(pool)s 上创建项目 %(project)s 时出错。返回码：%(ret.status)d 消息："
"%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Property: %(property)s Type: %(type)s Description: "
"%(description)s Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"创建属性 %(property)s、类型 %(type)s 和描述 %(description)s 时出错。返回码："
"%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Share: %(name)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"创建共享项 %(name)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Snapshot: %(snapshot)s onVolume: %(lun)s to Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在卷 %(lun)s 上对池 %(pool)s 创建快照 %(snapshot)s 时出错。项目：%(project)s "
"返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Snapshot: %(snapshot)s onshare: %(share)s to Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在共享项 %(share)s 上对池 %(pool)s 创建快照 %(snapshot)s 时出错。项目："
"%(project)s 返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Target: %(alias)sReturn code: %(ret.status)d Message: "
"%(ret.data)s ."
msgstr "创建目标 %(alias)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating TargetGroup: %(targetgroup)s withIQN: %(iqn)sReturn code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"创建带有 IQN %(iqn)s 的目标组 %(targetgroup)s 时出错。返回码："
"%(ret.status)d，消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Volume: %(lun)s Size: %(size)s Return code: %(ret.status)d "
"Message: %(ret.data)s."
msgstr ""
"创建大小为 %(size)s 的卷 %(lun)s 时出错。返回码：%(ret.status)d消息："
"%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting Snapshot: %(snapshot)s on Share: %(share)s to Pool: %(pool)s "
"Project: %(project)s Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在共享项 %(share)s 上对池 %(pool)s 删除快照 %(snapshot)s 时出错。项目："
"%(project)s 返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting Snapshot: %(snapshot)s on Volume: %(lun)s to Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在卷 %(lun)s 上对池 %(pool)s 删除快照 %(snapshot)s 时出错。项目：%(project)s "
"返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting Volume: %(lun)s from Pool: %(pool)s, Project: %(project)s. "
"Return code: %(ret.status)d, Message: %(ret.data)s."
msgstr ""
"从池 %(pool)s 中删除卷 %(lun)s 时出错，项目：%(project)s。返回码："
"%(ret.status)d，消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting project: %(project)s on pool: %(pool)s Return code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"删除池 %(pool)s 上的项目 %(project)s 时出错。返回码：%(ret.status)d 消息："
"%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting replication action: %(id)s Return code: %(ret.status)d "
"Message: %(ret.data)s."
msgstr ""
"删除复制操作 %(id)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Initiators: InitiatorGroup: %(initiatorgroup)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"获取发起方时出错：发起方组为 %(initiatorgroup)s，返回码为 %(ret.status)d 消"
"息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Pool Stats: Pool: %(pool)s Return code: %(status)d Message: "
"%(data)s."
msgstr "获取池统计信息时出错：池：%(pool)s 返回码：%(status)d 消息：%(data)s。"

#, python-format
msgid ""
"Error Getting Project Stats: Pool: %(pool)s Project: %(project)s Return "
"code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"获取项目状态时出错：池：%(pool)s 项目：%(project)s返回码：%(ret.status)d 消"
"息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Share: %(share)s on Pool: %(pool)s Project: %(project)s Return "
"code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在池 %(pool)s 上获取共享项 %(share)s 时出错。项目：%(project)s 返回码："
"%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Target: %(alias)sReturn code: %(ret.status)d Message: "
"%(ret.data)s ."
msgstr "获取目标 %(alias)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Volume: %(lun)s on Pool: %(pool)s Project: %(project)s Return "
"code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在池 %(pool)s 上获取卷 %(lun)s 时出错。项目：%(project)s 返回码："
"%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid "Error Pool ownership: Pool %(pool)s is not owned by %(host)s."
msgstr "池所有权出错：池 %(pool)s 并非归 %(host)s 所有。"

#, python-format
msgid ""
"Error Setting props Props: %(props)s on Volume: %(lun)s of Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在池 %(pool)s 的卷 %(lun)s 上设置属性 Props %(props)s 时出错。项目："
"%(project)s 返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Initiator: %(iqn)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"验证启动程序 %(iqn)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Pool: %(pool)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr "验证池 %(pool)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Project: %(project)s on Pool: %(pool)s Return code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"在池 %(pool)s 上验证项目 %(project)s 时出错。返回码：%(ret.status)d，消息："
"%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Service: %(service)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"验证服务 %(service)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Target: %(alias)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr "验证目标 %(alias)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying share: %(share)s on Project: %(project)s and Pool: %(pool)s "
"Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在项目 %(project)s 和池 %(pool)s 上验证共享项 %(share)s 时出错。返回码为 "
"%(ret.status)d，消息为 %(ret.data)s。"

msgid "Error connecting to ceph cluster."
msgstr "连接至 ceph 集群时出错。"

#, python-format
msgid "Error connecting via ssh: %s"
msgstr "通过 ssh 进行连接时出错：%s"

#, python-format
msgid "Error creating volume: %s."
msgstr "创建卷时出错：%s。"

msgid "Error deleting replay profile."
msgstr "删除重放概要文件时出错。"

#, python-format
msgid "Error deleting volume %(ssn)s: %(volume)s"
msgstr "删除卷 %(ssn)s 时出错：%(volume)s "

#, python-format
msgid "Error deleting volume %(vol)s: %(err)s."
msgstr "删除卷 %(vol)s 时出错：%(err)s。"

#, python-format
msgid "Error during evaluator parsing: %(reason)s"
msgstr "在评估程序解析期间，发生错误：%(reason)s"

#, python-format
msgid ""
"Error editing share: %(share)s on Pool: %(pool)s Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"在池 %(pool)s 上编辑共享项 %(share)s 时出错。返回码：%(ret.status)d，消息："
"%(ret.data)s。"

#, python-format
msgid ""
"Error enabling iSER for NetworkPortal: please ensure that RDMA is supported "
"on your iSCSI port %(port)d on ip %(ip)s."
msgstr ""
"为 NetworkPortal 启用 iSER 时出错：请确保 RDMA 在 IP %(ip)s 上的 iSCSI 端口 "
"%(port)d 中受支持。"

#, python-format
msgid "Error encountered during cleanup of a failed attach: %(ex)s"
msgstr "在清除失败的连接期间遇到错误：%(ex)s"

#, python-format
msgid "Error executing command via ssh: %s"
msgstr "通过 ssh 执行命令时发生错误：%s"

#, python-format
msgid "Error extending volume %(vol)s: %(err)s."
msgstr "扩展卷 %(vol)s 时出错：%(err)s。"

#, python-format
msgid "Error extending volume: %(reason)s"
msgstr "扩展卷时出错：%(reason)s"

#, python-format
msgid "Error finding %(name)s."
msgstr "查找 %(name)s 时出错。"

msgid ""
"Error getting appliance version details. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"获取设备版本详细信息时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid "Error getting domain id from name %(name)s: %(id)s."
msgstr "从名称 %(name)s 中获取域标识 %(id)s 时出错。"

msgid "Error getting initiator groups."
msgstr "获取发起方组时，发生错误。"

#, python-format
msgid "Error getting pool id from name %(pool_name)s: %(err_msg)s."
msgstr "从名称 %(pool_name)s 中获取池标识时出错：%(err_msg)s。"

#, python-format
msgid ""
"Error getting replication action: %(id)s. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"获取复制操作 %(id)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

msgid ""
"Error getting replication source details. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr "获取复制源详细信息时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

msgid ""
"Error getting replication target details. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"获取复制目标详细信息时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error getting version: svc: %(svc)s.Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"获取版本时出错：svc：%(svc)s。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid "Error in SolidFire API response: data=%(data)s"
msgstr "SolidFire API响应里发生错误：data=%(data)s"

#, python-format
msgid "Error managing volume: %s."
msgstr "管理卷 %s 时出错。"

#, python-format
msgid ""
"Error modifying Service: %(service)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"修改服务 %(service)s 时出错。返回码：%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error moving volume: %(vol)s from source project: %(src)s to target project: "
"%(tgt)s Return code: %(ret.status)d Message: %(ret.data)s ."
msgstr ""
"将卷 %(vol)s 从源项目 %(src)s 移至目标项目 %(tgt)s 时出错。返回码："
"%(ret.status)d 消息：%(ret.data)s。"

msgid "Error not a KeyError."
msgstr "错误并非 KeyError。"

msgid "Error not a TypeError."
msgstr "错误并非 TypeError。"

#, python-format
msgid "Error occurred when creating group_snapshot %s."
msgstr "创建 group_snapshot %s 时发生了错误。"

#, python-format
msgid "Error occurred when deleting group snapshot %s."
msgstr "删除组快照%s 时出现错误。"

#, python-format
msgid "Error occurred when deleting group_snapshot %s."
msgstr "删除 group_snapshot %s 时发生了错误。"

#, python-format
msgid "Error occurred when updating group %s."
msgstr "更新组 %s 时发生了错误。"

#, python-format
msgid "Error renaming volume %(vol)s: %(err)s."
msgstr "重命名卷 %(vol)s 时出错：%(err)s。"

#, python-format
msgid "Error response: %s"
msgstr "错误响应：%s"

msgid "Error retrieving volume size"
msgstr "检索卷大小时出错"

#, python-format
msgid ""
"Error sending replication update for action id: %(id)s . Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"为操作标识 %(id)s 发送复制更新时出错。返回码：%(ret.status)d 消息："
"%(ret.data)s。"

#, python-format
msgid ""
"Error sending replication update. Returned error: %(err)s. Action: %(id)s."
msgstr "发送复制更新时出错。所返回的错误：%(err)s。操作：%(id)s。"

#, python-format
msgid ""
"Error setting replication inheritance to %(set)s for volume: %(vol)s project "
"%(project)s Return code: %(ret.status)d Message: %(ret.data)s ."
msgstr ""
"对于卷 %(vol)s，将复制继承设置为 %(set)s 时出错。项目：%(project)s 返回码："
"%(ret.status)d 消息：%(ret.data)s。"

#, python-format
msgid ""
"Error severing the package: %(package)s from source: %(src)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"从源 %(src)s 分割软件包 %(package)s 时出错。返回码：%(ret.status)d 消息："
"%(ret.data)s。"

#, python-format
msgid "Error while authenticating with switch: %s."
msgstr "向交换机认证时出错：%s。"

#, python-format
msgid "Error while changing VF context %s."
msgstr "更改 VF 上下文 %s 时出错。"

#, python-format
msgid "Error while checking the firmware version %s."
msgstr "检查固件版本 %s 时出错。"

#, python-format
msgid "Error while checking transaction status: %s"
msgstr "检查事务状态时发生错误：%s"

#, python-format
msgid "Error while checking whether VF is available for management %s."
msgstr "检查 VF 对管理 %s 是否可用时出错。"

#, python-format
msgid ""
"Error while connecting the switch %(switch_id)s with protocol %(protocol)s. "
"Error: %(error)s."
msgstr ""
"连接带有协议 %(protocol)s 的交换机 %(switch_id)s 时出错。错误：%(error)s。"

#, python-format
msgid "Error while creating authentication token: %s"
msgstr "创建认证令牌时出错：%s"

#, python-format
msgid "Error while getting data via ssh: (command=%(cmd)s error=%(err)s)."
msgstr ""
"通过 ssh 获取数据时发生错误：（命令为 %(cmd)s，发生的错误为 %(err)s）。"

#, python-format
msgid "Error while getting nvp value: %s."
msgstr "获取 nvp 值时出错：%s。"

#, python-format
msgid "Error while getting session information %s."
msgstr "获取会话信息 %s 时出错。"

#, python-format
msgid "Error while parsing the data: %s."
msgstr "解析数据时出错：%s。"

#, python-format
msgid "Error while querying page %(url)s on the switch, reason %(error)s."
msgstr "在交换机上查询页面 %(url)s 时出错，原因：%(error)s。"

#, python-format
msgid ""
"Error while removing the zones and cfgs in the zone string: %(description)s."
msgstr "移除区域字符串中的 zones 和 cgfs 时出错：%(description)s。"

#, python-format
msgid "Error while requesting %(service)s API."
msgstr "请求 %(service)s API 时出错。"

#, python-format
msgid "Error while running zoning CLI: (command=%(cmd)s error=%(err)s)."
msgstr "运行分区 CLI 时发生错误：（命令为 %(cmd)s，发生的错误为 %(err)s）。"

#, python-format
msgid ""
"Error while updating the new zones and cfgs in the zone string. Error "
"%(description)s."
msgstr "更新区域字符串中的新 zones 和 cgfs 时出错。错误：%(description)s。"

#, python-format
msgid ""
"Error while updating the zones in the zone string. Error %(description)s."
msgstr "更新区域字符串中的 zones 时出错。错误：%(description)s。"

msgid "Error writing field to database"
msgstr "将字段写至数据库时出错。"

msgid "Exceeded the limit of snapshots per volume"
msgstr "超出每个卷的快照数限制"

#, python-format
msgid "Exception in _select_ds_for_volume: %s."
msgstr "_select_ds_for_volume %s 中发生异常。"

#, python-format
msgid "Exception while forming the zone string: %s."
msgstr "构建区域字符串时发生异常：%s。"

#, python-format
msgid "Exception: %s"
msgstr "异常：%s"

#, python-format
msgid "Expected exactly one node called \"%s\""
msgstr "刚好需要一个名为“%s”的节点"

#, python-format
msgid "Expected integer for node_count, svcinfo lsiogrp returned: %(node)s."
msgstr "期望 node_count 的值为整数，已返回 svcinfo lsiogrp：%(node)s。"

#, python-format
msgid "Expected no output from CLI command %(cmd)s, got %(out)s."
msgstr "期望 CLI 命令 %(cmd)s 没有任何输出，但是获得了 %(out)s。"

#, python-format
msgid ""
"Expected single vdisk returned from lsvdisk when filtering on vdisk_UID.  "
"%(count)s were returned."
msgstr ""
"在 vdisk_UID 上进行过滤时，从 lsvdisk 返回了所需的单个 vdisk。返回了 "
"%(count)s。"

#, python-format
msgid "Expected volume size was %d"
msgstr "需要的卷大小为 %d"

#, python-format
msgid ""
"Export backup aborted, expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"备份导出已异常中止，需要的备份状态为 %(expected_status)s，但实际为 "
"%(actual_status)s。"

#, python-format
msgid ""
"Export record aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"记录导出已异常中止，当前配置的备份服务 [%(configured_service)s] 不是已用来创"
"建此备份的备份服务 [%(backup_service)s]。"

msgid "Extend volume error."
msgstr "扩展卷时发生错误。"

msgid "Extend volume not implemented"
msgstr "扩展卷未实现"

msgid "FC is the protocol but wwpns are not supplied by OpenStack."
msgstr "FC 为协议，但 OpenStack 未提供 wwpns。"

#, python-format
msgid "Faield to unassign %(volume)s"
msgstr "无法取消分配 %(volume)s"

#, python-format
msgid "Fail to create cache volume %(volume)s. Error: %(err)s"
msgstr "未能创建高速缓存卷 %(volume)s。错误：%(err)s"

#, python-format
msgid "Failed adding connection for fabric=%(fabric)s: Error: %(err)s"
msgstr "对于光纤网 %(fabric)s，未能添加连接：发生错误：%(err)s"

#, python-format
msgid "Failed creating snapshot for group: %(response)s."
msgstr "为组创建快照失败：%(response)s。"

#, python-format
msgid "Failed creating snapshot for volume %(volname)s: %(response)s."
msgstr "为卷 %(volname)s 创建快照失败：%(response)s。"

#, python-format
msgid "Failed getting active zone set from fabric %s."
msgstr "通过光纤网络 %s 获取活动区域集失败。"

#, python-format
msgid "Failed getting details for pool %s."
msgstr "获取池 %s 的详细信息失败。"

#, python-format
msgid "Failed removing connection for fabric=%(fabric)s: Error: %(err)s"
msgstr "对于光纤网 %(fabric)s，未能移除连接：发生错误：%(err)s"

#, python-format
msgid "Failed to Extend Volume %(volname)s"
msgstr "未能扩展卷 %(volname)s"

#, python-format
msgid "Failed to Login to 3PAR (%(url)s) because %(err)s"
msgstr "未能登录到 3PAR (%(url)s)，因为存在 %(err)s"

msgid "Failed to access active zoning configuration."
msgstr "未能访问活动分区配置。"

#, python-format
msgid "Failed to access zoneset status:%s"
msgstr "未能访问区域集状态：%s"

msgid "Failed to add or update zoning configuration."
msgstr "未能添加或更新分区配置。"

msgid "Failed to add zoning configuration."
msgstr "未能添加分区配置。"

#, python-format
msgid "Failed to associate qos_specs: %(specs_id)s with type %(type_id)s."
msgstr "未能使 qos_specs %(specs_id)s 与类型 %(type_id)s 关联。"

#, python-format
msgid "Failed to attach iSCSI target for volume %(volume_id)s."
msgstr "未能针对卷 %(volume_id)s 连接 iSCSI 目标。"

#, python-format
msgid "Failed to backup volume metadata - %s"
msgstr "未能备份卷元数据 - %s"

#, python-format
msgid ""
"Failed to backup volume metadata - Metadata backup object 'backup.%s.meta' "
"already exists"
msgstr "未能备份卷元数据 - 元数据备份对象“backup.%s.meta”已存在"

#, python-format
msgid "Failed to clone volume from snapshot %s."
msgstr "未能从快照 %s 克隆卷。"

#, python-format
msgid "Failed to connect to %(vendor_name)s Array %(host)s: %(err)s"
msgstr "未能连接至 %(vendor_name)s 阵列 %(host)s：%(err)s"

msgid "Failed to connect to Dell REST API"
msgstr "无法连接至 Dell REST API"

#, python-format
msgid "Failed to connect to sheep daemon. addr: %(addr)s, port: %(port)s"
msgstr "未能连接至 sheep 守护程序。地址：%(addr)s，端口：%(port)s"

#, python-format
msgid "Failed to copy image to volume: %(reason)s"
msgstr "未能将映像复制到卷：%(reason)s"

#, python-format
msgid "Failed to copy metadata to volume: %(reason)s"
msgstr "未能复制元数据到卷：%(reason)s"

msgid ""
"Failed to copy volume to image as image quota has been met. Please delete "
"images or have your limit increased, then try again."
msgstr ""
"由于镜像配额限制，将卷拷贝到镜像中的操作失败。请删除镜像或增加镜像配额，然后"
"再尝试。"

msgid "Failed to copy volume, destination device unavailable."
msgstr "未能复制卷，目标设备不可用。"

msgid "Failed to copy volume, source device unavailable."
msgstr "未能复制卷，源设备不可用。"

#, python-format
msgid "Failed to create IG, %s"
msgstr "未能创建映像 %s"

#, python-format
msgid "Failed to create Volume Group: %(vg_name)s"
msgstr "未能创建卷组: %(vg_name)s"

msgid "Failed to create api volume flow."
msgstr "未能创建 api 卷流。"

#, python-format
msgid "Failed to create cg snapshot %(id)s due to %(reason)s."
msgstr "由于 %(reason)s，未能创建 cg 快照 %(id)s。"

#, python-format
msgid "Failed to create consistency group %(id)s due to %(reason)s."
msgstr "由于 %(reason)s，未能创建一致性组 %(id)s。"

#, python-format
msgid "Failed to create consistency group %(id)s:%(ret)s."
msgstr "未能创建一致性组 %(id)s：%(ret)s。"

#, python-format
msgid "Failed to create consistency group: %(cgid)s. Error: %(excmsg)s."
msgstr "未能创建一致性组：%(cgid)s。错误为 %(excmsg)s。"

#, python-format
msgid ""
"Failed to create host: %(name)s. Please check if it exists on the array."
msgstr "未能创建主机：%(name)s。请检查它在阵列上是否存在。"

#, python-format
msgid "Failed to create hostgroup: %(name)s. Check if it exists on the array."
msgstr "未能创建主机组：%(name)s。请检查它在阵列上是否存在。"

#, python-format
msgid "Failed to create iscsi target for volume %(volume_id)s."
msgstr "未能针对卷 %(volume_id)s 创建 iscsi 目标。"

msgid "Failed to create manage existing flow."
msgstr "未能创建 manage_existing 流。"

msgid "Failed to create manage_existing flow."
msgstr "未能创建 manage_existing 流。"

#, python-format
msgid "Failed to create metadata for volume: %(reason)s"
msgstr "未能为卷创建元数据：%(reason)s"

#, python-format
msgid "Failed to create qos_specs: %(name)s with specs %(qos_specs)s."
msgstr "未能通过规范 %(qos_specs)s 创建 qos_specs：%(name)s。"

msgid "Failed to create scheduler manager volume flow"
msgstr "未能创建调度程序管理器卷流"

#, python-format
msgid "Failed to create snapshot %s"
msgstr "未能创建快照 %s"

#, python-format
msgid "Failed to create snapshot for volume %s."
msgstr "未能为卷 %s 创建快照。"

#, python-format
msgid "Failed to create south bound connector for %s."
msgstr "无法为 %s 创建南向连接器。"

#, python-format
msgid "Failed to create thin pool, error message was: %s"
msgstr "未能创建瘦池，错误消息如下：%s"

#, python-format
msgid "Failed to create volume %s"
msgstr "未能创建卷 %s"

#, python-format
msgid "Failed to delete cgsnapshot %(id)s due to %(reason)s."
msgstr "由于 %(reason)s，未能删除 cg 快照 %(id)s。"

#, python-format
msgid "Failed to delete consistency group %(id)s due to %(reason)s."
msgstr "由于 %(reason)s，未能删除一致性组 %(id)s。"

#, python-format
msgid ""
"Failed to delete fileset for consistency group %(cgname)s. Error: %(excmsg)s."
msgstr "未能针对一致性组 %(cgname)s 删除文件集。错误为 %(excmsg)s。"

#, python-format
msgid "Failed to delete snapshot %s"
msgstr "未能删除快照 %s"

#, python-format
msgid "Failed to detach iSCSI target for volume %(volume_id)s."
msgstr "未能针对卷 %(volume_id)s 与 iSCSI 目标断开连接。"

msgid "Failed to disassociate qos specs."
msgstr "未能取消关联 Qos 规范。"

#, python-format
msgid "Failed to disassociate qos_specs: %(specs_id)s with type %(type_id)s."
msgstr "未能使 qos_specs %(specs_id)s 与类型 %(type_id)s 取消关联。"

#, python-format
msgid "Failed to export for volume: %(reason)s"
msgstr "输出卷失败：%(reason)s"

#, python-format
msgid "Failed to extend volume %(name)s, Error msg: %(msg)s."
msgstr "无法扩展卷 %(name)s，错误消息：%(msg)s。"

msgid "Failed to find QoSnode"
msgstr "找不到 QoSnode"

msgid "Failed to find Storage Center"
msgstr "找不到存储中心"

msgid "Failed to find a vdisk copy in the expected pool."
msgstr "在所需池中找不到 vdisk 副本。"

msgid "Failed to find account for volume."
msgstr "未能查找卷的帐户。"

#, python-format
msgid "Failed to find fileset for path %(path)s, command output: %(cmdout)s."
msgstr "对于路径 %(path)s，未能找到文件集，命令输出：%(cmdout)s。"

#, python-format
msgid "Failed to find group snapshot named: %s"
msgstr "找不到名为 %s 的组快照"

#, python-format
msgid "Failed to find host %s."
msgstr "未能找到主机 %s。"

#, python-format
msgid "Failed to find iSCSI initiator group containing %(initiator)s."
msgstr "找不到包含 %(initiator)s 的 iSCSI 启动程序组。"

#, python-format
msgid "Failed to get LUN target details for the LUN %s"
msgstr "未能获取 LUN %s 的 LUN 目标详细信息"

#, python-format
msgid "Failed to get LUN target list for the LUN %s"
msgstr "未能获取 LUN %s 的 LUN 目标列表"

msgid "Failed to get SplitMirror."
msgstr "无法获取 SplitMirror。"

#, python-format
msgid "Failed to get all associations of qos specs %s"
msgstr "未能获取 qos 规范 %s 的所有关联"

#, python-format
msgid "Failed to get code level (%s)."
msgstr "未能获取代码级别 (%s)。"

#, python-format
msgid "Failed to get domain because CPG (%s) doesn't exist on array."
msgstr "未能获取域，因为阵列上不存在 CPG (%s)。"

msgid "Failed to get image snapshots."
msgstr "无法获取映像快照。"

msgid "Failed to get migration task."
msgstr "无法获取迁移任务。"

msgid "Failed to get model update from clone"
msgstr "未能从克隆获取模型更新"

msgid "Failed to get name server info."
msgstr "未能获取名称服务器信息。"

msgid "Failed to get show fcns database info."
msgstr "未能获取显示 fcns 数据库信息。"

#, python-format
msgid "Failed to get size of volume %s"
msgstr "未能获取卷 %s 的大小"

#, python-format
msgid "Failed to get snapshot for volume %s."
msgstr "未能获取卷 %s 的快照。"

#, python-format
msgid "Failed to get target IQN for the LUN %s"
msgstr "未能获取 LUN %s 的目标 IQN"

msgid "Failed to get target LUN of SplitMirror."
msgstr "无法获取 SplitMirror 的目标 LUN。"

#, python-format
msgid "Failed to get target portal for the LUN %s"
msgstr "未能获取 LUN %s 的目标门户网站"

msgid "Failed to get targets"
msgstr "未能获取目标"

msgid "Failed to identify volume backend."
msgstr "未能识别卷后端。"

#, python-format
msgid "Failed to link fileset for the share %(cgname)s. Error: %(excmsg)s."
msgstr "未能针对共享项 %(cgname)s 链接文件集。错误为 %(excmsg)s。"

#, python-format
msgid "Failed to log on %s Array (invalid login?)."
msgstr "未能登录到 %s 阵列（无效登录？）。"

#, python-format
msgid "Failed to login for user %s."
msgstr "未能让用户 %s 登录。"

msgid "Failed to login with all rest URLs."
msgstr "未能使用所有 REST URL 进行登录。"

#, python-format
msgid ""
"Failed to make a request to Datera cluster endpoint due to the following "
"reason: %s"
msgstr "由于以下原因，未能对 Datera 集群端点进行请求：%s"

msgid "Failed to manage api volume flow."
msgstr "未能管理 API 卷流。"

#, python-format
msgid ""
"Failed to manage existing %(type)s %(name)s, because reported size %(size)s "
"was not a floating-point number."
msgstr "未能管理现有 %(type)s %(name)s，因为所报告的大小 %(size)s不是浮点数。"

#, python-format
msgid ""
"Failed to manage existing volume %(name)s, because of error in getting "
"volume size."
msgstr "未能管理现有卷 %(name)s，因为获取卷大小时出错。"

#, python-format
msgid ""
"Failed to manage existing volume %(name)s, because rename operation failed: "
"Error msg: %(msg)s."
msgstr "未能管理现有卷 %(name)s，因为重命名操作失败：错误消息为 %(msg)s。"

#, python-format
msgid ""
"Failed to manage existing volume %(name)s, because reported size %(size)s "
"was not a floating-point number."
msgstr "未能管理现有卷 %(name)s，因为已报告的大小 %(size)s 不是浮点数。"

#, python-format
msgid ""
"Failed to manage existing volume due to the pool of the volume to be managed "
"does not match the backend pool. Pool of the volume to be managed is "
"%(vdisk_pool)s. Pool of the backend is %(backend_pool)s."
msgstr ""
"无法管理现有卷，因为要管理的卷的池与后端池不匹配。要管理的卷的池为 "
"%(vdisk_pool)s。后端的池为 %(backend_pool)s。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is "
"compress, but the volume type chosen is not compress."
msgstr "无法管理现有卷，要管理的卷为压缩卷，但所选卷类型并非压缩卷。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is not "
"compress, but the volume type chosen is compress."
msgstr "无法管理现有卷，要管理的卷并非压缩卷，但所选卷类型为压缩卷。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is not in a "
"valid I/O group."
msgstr "无法管理现有卷，因为要管理的卷未包含在有效 I/O 组中。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is thick, "
"but the volume type chosen is thin."
msgstr "无法管理现有卷，因为要管理的卷为厚卷，但所选卷类型为薄卷。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is thin, "
"but the volume type chosen is thick."
msgstr "无法管理现有卷，要管理的卷为薄卷，但所选卷类型为厚卷。"

#, python-format
msgid "Failed to manage volume %s."
msgstr "未能管理卷 %s。"

#, python-format
msgid "Failed to move volume %s."
msgstr "未能移动卷 %s。"

#, python-format
msgid ""
"Failed to parse CLI output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"未能解析 CLI 输出：\n"
"命令：%(cmd)s\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s。"

msgid ""
"Failed to parse the configuration option 'glance_catalog_info', must be in "
"the form <service_type>:<service_name>:<endpoint_type>"
msgstr ""
"解析配置选项“glance_catalog_info”失败，必须为以下格式：<service_type>:"
"<service_name>:<endpoint_type>"

msgid ""
"Failed to parse the configuration option 'keystone_catalog_info', must be in "
"the form <service_type>:<service_name>:<endpoint_type>"
msgstr ""
"解析配置选项“swift_catalog_info”失败，必须为以下格式：<service_type>:"
"<service_name>:<endpoint_type>"

msgid ""
"Failed to parse the configuration option 'swift_catalog_info', must be in "
"the form <service_type>:<service_name>:<endpoint_type>"
msgstr ""
"解析配置选项“swift_catalog_info”失败，必须为以下格式：<service_type>:"
"<service_name>:<endpoint_type>"

#, python-format
msgid "Failed to remove export for volume %(volume)s: %(reason)s"
msgstr "未能针对卷 %(volume)s 移除导出：%(reason)s"

#, python-format
msgid "Failed to remove iscsi target for volume %(volume_id)s."
msgstr "未能针对卷 %(volume_id)s 除去 iscsi 目标。"

#, python-format
msgid ""
"Failed to rename logical volume %(name)s, error message was: %(err_msg)s"
msgstr "未能重命名逻辑卷 %(name)s，错误消息如下：%(err_msg)s"

#, python-format
msgid "Failed to retrieve active zoning configuration %s"
msgstr "无法检索处于活动状态的分区配置 %s"

#, python-format
msgid "Failed to retrieve attachments for volume %(name)s"
msgstr "获取卷 %(name)s 的挂载信息失败。"

#, python-format
msgid ""
"Failed to set CHAP authentication for target IQN %(iqn)s. Details: %(ex)s"
msgstr "无法为目标 IQN %(iqn)s 设置 CHAP 认证。详细信息：%(ex)s"

#, python-format
msgid "Failed to set QoS for existing volume %(name)s, Error msg: %(msg)s."
msgstr "未能对现有卷 %(name)s 设置 QoS，错误消息：%(msg)s。"

msgid "Failed to set attribute 'Incoming user' for SCST target."
msgstr "未能对 SCST 目标设置属性“新用户”。"

#, python-format
msgid ""
"Failed to set permissions for the consistency group %(cgname)s. Error: "
"%(excmsg)s."
msgstr "未能针对一致性组 %(cgname)s 设置许可权。错误为 %(excmsg)s。"

#, python-format
msgid ""
"Failed to unlink fileset for consistency group %(cgname)s. Error: %(excmsg)s."
msgstr "未能针对一致性组 %(cgname)s 取消链接文件集。错误为 %(excmsg)s。"

#, python-format
msgid "Failed to update metadata for volume: %(reason)s"
msgstr "未能更新卷的元数据：%(reason)s"

msgid "Failed to update or delete zoning configuration"
msgstr "未能更新或删除分区配置"

msgid "Failed to update or delete zoning configuration."
msgstr "无法更新或删除分区配置。"

#, python-format
msgid "Failed to update qos_specs: %(specs_id)s with specs %(qos_specs)s."
msgstr "未能通过规范 %(qos_specs)s 更新 qos_specs：%(specs_id)s。"

msgid "Failed to update quota usage while retyping volume."
msgstr "对卷进行转型时，更新配额使用率失败"

msgid "Failed to update snapshot."
msgstr "无法更新快照。"

#, python-format
msgid ""
"Failed updating volume %(vol_id)s metadata using the provided %(src_type)s "
"%(src_id)s metadata"
msgstr "未能使用提供的 %(src_type)s %(src_id)s 元数据更新卷 %(vol_id)s 元数据"

#, python-format
msgid "Failure getting LUN info for %s."
msgstr "针对 %s 获取 LUN 信息时发生故障。"

#, python-format
msgid "Failure moving new cloned LUN to %s."
msgstr "将新克隆的 LUN 移至 %s 时发生故障。"

#, python-format
msgid "Failure staging LUN %s to tmp."
msgstr "将 LUN %s 登台至临时文件夹时发生故障。"

#, python-format
msgid "Fexvisor failed to add volume %(id)s due to %(reason)s."
msgstr "由于 %(reason)s，Fexvisor 未能添加卷 %(id)s。"

#, python-format
msgid ""
"Fexvisor failed to join the volume %(vol)s in the group %(group)s due to "
"%(ret)s."
msgstr "由于 %(ret)s，Fexvisor 未能将卷 %(vol)s加入组 %(group)s。"

#, python-format
msgid ""
"Fexvisor failed to remove the volume %(vol)s in the group %(group)s due to "
"%(ret)s."
msgstr "由于 %(ret)s，Fexvisor 未能移除组 %(group)s中的卷 %(vol)s。"

#, python-format
msgid "Fexvisor failed to remove volume %(id)s due to %(reason)s."
msgstr "由于 %(reason)s，Fexvisor 未能移除卷 %(id)s。"

#, python-format
msgid "Fibre Channel SAN Lookup failure: %(reason)s"
msgstr "光纤通道 SAN 查找失败：%(reason)s"

msgid "Fibre Channel Zone Manager not initialized"
msgstr "光纤通道区域管理器未初始化。"

#, python-format
msgid "Fibre Channel Zone operation failed: %(reason)s"
msgstr "“光纤通道区域”操作失败：%(reason)s"

#, python-format
msgid "Fibre Channel connection control failure: %(reason)s"
msgstr "光纤通道连接控制失败：%(reason)s"

#, python-format
msgid "File %(file_path)s could not be found."
msgstr "找不到文件 %(file_path)s。"

#, python-format
msgid "File already exists at %s."
msgstr "%s 处已存在文件。"

#, python-format
msgid "File already exists at: %s"
msgstr "在以下位置处，已存在文件：%s"

msgid "Find host in hostgroup error."
msgstr "在主机组中查找主机时发生错误。"

msgid "Find host lun id error."
msgstr "查找主机 LUN 标识时发生错误。"

msgid "Find lun group from mapping view error."
msgstr "从映射视图查找 LUN 组时发生错误。"

msgid "Find mapping view error."
msgstr "查找映射视图时发生错误。"

msgid "Find portgroup error."
msgstr "查找端口组时发生错误。"

msgid "Find portgroup from mapping view error."
msgstr "从映射视图查找端口组时发生错误。"

#, python-format
msgid ""
"Flash Cache Policy requires WSAPI version '%(fcache_version)s' version "
"'%(version)s' is installed."
msgstr ""
"闪存高速缓存策略要求安装了 WSAPI 版本“%(fcache_version)s”版本“%(version)s”。"

#, python-format
msgid "Flexvisor assign volume failed.:%(id)s:%(status)s."
msgstr "Flexvisor 分配卷失败：%(id)s：%(status)s。"

#, python-format
msgid "Flexvisor assign volume failed:%(id)s:%(status)s."
msgstr "Flexvisor 分配卷失败：%(id)s：%(status)s。"

#, python-format
msgid ""
"Flexvisor could not find volume %(id)s snapshot in the group %(vgid)s "
"snapshot %(vgsid)s."
msgstr "Flexvisor 在组 %(vgid)s 快照 %(vgsid)s 中找不到卷 %(id)s 快照。"

#, python-format
msgid "Flexvisor create volume failed.:%(volumeid)s:%(status)s."
msgstr "Flexvisor 创建卷失败：%(volumeid)s：%(status)s。"

#, python-format
msgid "Flexvisor failed deleting volume %(id)s: %(status)s."
msgstr "Flexvisor 无法删除卷 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to add volume %(id)s to group %(cgid)s."
msgstr "Flexvisor 未能将卷 %(id)s 添加至组 %(cgid)s。"

#, python-format
msgid ""
"Flexvisor failed to assign volume %(id)s due to unable to query status by "
"event id."
msgstr "Flexvisor 无法分配卷 %(id)s，因为无法按事件标识查询状态。 "

#, python-format
msgid "Flexvisor failed to assign volume %(id)s: %(status)s."
msgstr "Flexvisor 无法分配卷 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to assign volume %(volume)s iqn %(iqn)s."
msgstr "Flexvisor 未能分配卷 %(volume)s iqn %(iqn)s。"

#, python-format
msgid "Flexvisor failed to clone volume %(id)s: %(status)s."
msgstr "Flexvisor 无法克隆卷 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to clone volume (failed to get event) %(id)s."
msgstr "Flexvisor 无法克隆卷（无法获取事件）%(id)s。"

#, python-format
msgid "Flexvisor failed to create snapshot for volume %(id)s: %(status)s."
msgstr "Flexvisor 无法对卷 %(id)s 创建快照：%(status)s。"

#, python-format
msgid ""
"Flexvisor failed to create snapshot for volume (failed to get event) %(id)s."
msgstr "Flexvisor 无法对卷 %(id)s 创建快照（无法获取事件）。  "

#, python-format
msgid "Flexvisor failed to create volume %(id)s in the group %(vgid)s."
msgstr "Flexvisor 未能在组 %(vgid)s 中创建卷 %(id)s。"

#, python-format
msgid "Flexvisor failed to create volume %(volume)s: %(status)s."
msgstr "Flexvisor 无法创建卷 %(volume)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to create volume (get event) %s."
msgstr "Flexvisor 无法创建卷（获取事件）%s。"

#, python-format
msgid "Flexvisor failed to create volume from snapshot %(id)s: %(status)s."
msgstr "Flexvisor 未能从快照 %(id)s 创建卷：%(status)s。"

#, python-format
msgid "Flexvisor failed to create volume from snapshot %(id)s:%(status)s."
msgstr "Flexvisor 无法从快照 %(id)s 创建卷：%(status)s。"

#, python-format
msgid ""
"Flexvisor failed to create volume from snapshot (failed to get event) %(id)s."
msgstr "Flexvisor 无法从快照创建卷（无法获取事件）%(id)s。  "

#, python-format
msgid "Flexvisor failed to delete snapshot %(id)s: %(status)s."
msgstr "Flexvisor 无法删除快照 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to delete snapshot (failed to get event) %(id)s."
msgstr "Flexvisor 无法删除快照（无法获取事件）%(id)s。"

#, python-format
msgid "Flexvisor failed to delete volume %(id)s: %(status)s."
msgstr "Flexvisor 无法删除卷 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to extend volume %(id)s: %(status)s."
msgstr "Flexvisor 未能扩展卷 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to extend volume %(id)s:%(status)s."
msgstr "Flexvisor 无法扩展卷 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to extend volume (failed to get event) %(id)s."
msgstr "Flexvisor 无法扩展卷（无法获取事件）%(id)s。"

#, python-format
msgid "Flexvisor failed to get pool info %(id)s: %(status)s."
msgstr "Flexvisor 无法获取池信息 %(id)s：%(status)s。"

#, python-format
msgid ""
"Flexvisor failed to get snapshot id of volume %(id)s from group %(vgid)s."
msgstr "Flexvisor 未能从组 %(vgid)s 获取卷 %(id)s 的快照标识。"

#, python-format
msgid "Flexvisor failed to remove volume %(id)s from group %(cgid)s."
msgstr "Flexvisor 未能从组 %(cgid)s 中移除卷 %(id)s。"

#, python-format
msgid "Flexvisor failed to spawn volume from snapshot %(id)s:%(status)s."
msgstr "Flexvisor 无法从快照 %(id)s 衍生卷：%(status)s。"

#, python-format
msgid ""
"Flexvisor failed to spawn volume from snapshot (failed to get event) %(id)s."
msgstr "Flexvisor 无法从快照衍生卷（无法获取事件）%(id)s。  "

#, python-format
msgid "Flexvisor failed to unassign volume %(id)s: %(status)s."
msgstr "Flexvisor 无法取消分配卷 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to unassign volume (get event) %(id)s."
msgstr "Flexvisor 无法取消分配卷（获取事件）%(id)s。"

#, python-format
msgid "Flexvisor failed to unassign volume:%(id)s:%(status)s."
msgstr "Flexvisor 未能取消分配卷 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor unable to find the source volume %(id)s info."
msgstr "Flexvisor 找不到源卷 %(id)s 信息。"

#, python-format
msgid "Flexvisor unassign volume failed:%(id)s:%(status)s."
msgstr "Flexvisor 取消分配卷失败：%(id)s：%(status)s。"

#, python-format
msgid "Flexvisor volume %(id)s failed to join group %(vgid)s."
msgstr "Flexvisor 卷 %(id)s 未能加入组 %(vgid)s。"

#, python-format
msgid "Folder %s does not exist in Nexenta Store appliance"
msgstr "文件夹 %s 在 Nexenta 存储设备中不存在"

#, python-format
msgid "GPFS is not running, state: %s."
msgstr "GPFS 没有在运行，状态：%s。"

msgid "Get FC ports by port group error."
msgstr "按端口组获取 FC 端口时出错。"

msgid "Get FC ports from array error."
msgstr "从阵列中获取 FC 端口时发生错误。"

msgid "Get FC target wwpn error."
msgstr "获取 FC 目标 WWPN 时发生错误。"

msgid "Get HyperMetroPair error."
msgstr "获取 HyperMetroPair 时出错。"

msgid "Get LUN group by view error."
msgstr "按视图获取 LUN 组时出错。"

msgid "Get LUNcopy information error."
msgstr "获取 LUNcopy 信息时发生错误。"

msgid "Get QoS id by lun id error."
msgstr "通过 LUN 标识获取 QoS 标识时发生错误。"

msgid "Get QoS information error."
msgstr "获取 QoS 信息时发生错误。"

msgid "Get QoS policy error."
msgstr "获取 QoS 策略时发生错误。"

msgid "Get SplitMirror error."
msgstr "获取 SplitMirror 时出错。"

msgid "Get active client failed."
msgstr "获取活动客户机失败。"

msgid "Get array info error."
msgstr "获取阵列信息时出错。"

msgid "Get cache by name error."
msgstr "按名称获取高速缓存时发生错误。"

msgid "Get connected free FC wwn error."
msgstr "获取已连接的空闲 FC wwn 时发生错误。"

msgid "Get engines error."
msgstr "获取引擎时出错。"

msgid "Get host initiators info failed."
msgstr "获取主机启动程序信息失败。"

msgid "Get hostgroup information error."
msgstr "获取主机组信息时发生错误。"

msgid ""
"Get iSCSI port info error, please check the target IP configured in huawei "
"conf file."
msgstr ""
"获取 iSCSI 端口信息时发生错误，请检查 huawei conf 文件中所配置的目标 IP。"

msgid "Get iSCSI port information error."
msgstr "获取 iSCSI 端口信息时发生错误。"

msgid "Get iSCSI target port error."
msgstr "获取 iSCSI 目标端口时发生错误。"

msgid "Get lun id by name error."
msgstr "通过名称获取 LUN 标识时出错。"

msgid "Get lun migration task error."
msgstr "获取 LUN 迁移任务时发生错误。"

msgid "Get lungroup id by lun id error."
msgstr "通过 LUN 标识获取 LUN 组标识时发生错误。"

msgid "Get lungroup information error."
msgstr "获取 LUN 组信息时发生错误。"

msgid "Get manageable snapshots not implemented."
msgstr "获取易管理快照的功能未实现。"

msgid "Get manageable volumes not implemented."
msgstr "获取易管理卷的功能未实现。"

msgid "Get migration task error."
msgstr "获取迁移任务时出错。"

msgid "Get pair failed."
msgstr "获取对失败。"

msgid "Get partition by name error."
msgstr "按名称获取分区时发生错误。"

msgid "Get partition by partition id error."
msgstr "按分区标识获取分区时发生错误。"

msgid "Get port group by view error."
msgstr "按视图获取端口组时出错。"

msgid "Get port group error."
msgstr "获取端口组时出错。"

msgid "Get port groups by port error."
msgstr "按端口获取端口组时出错。"

msgid "Get ports by port group error."
msgstr "按端口组获取端口时出错。"

msgid "Get remote device info failed."
msgstr "获取远程设备信息失败。"

msgid "Get remote devices error."
msgstr "获取远程设备时出错。"

msgid "Get smartcache by cache id error."
msgstr "按高速缓存标识获取 smartcache 时发生错误。"

msgid "Get snapshot error."
msgstr "获取快照时出错。"

msgid "Get snapshot id error."
msgstr "获取快照标识时发生错误。"

msgid "Get target IP error."
msgstr "获取目标 IP 时发生错误。"

msgid "Get target LUN of SplitMirror error."
msgstr "获取 SplitMirror 的目标 LUN 时出错。"

msgid "Get views by port group error."
msgstr "按端口组获取视图时出错。"

msgid "Get volume by name error."
msgstr "按名称获取卷时发生错误。"

msgid "Get volume error."
msgstr "获取卷时发生错误。"

#, python-format
msgid ""
"Glance metadata cannot be updated, key %(key)s exists for volume id "
"%(volume_id)s"
msgstr "无法更新 Glance 元数据，对于卷标识 %(volume_id)s，键 %(key)s 存在"

#, python-format
msgid "Glance metadata for volume/snapshot %(id)s cannot be found."
msgstr "Glance中无法找到卷/镜像 %(id)s 的元数据"

#, python-format
msgid "Google Cloud Storage api failure: %(reason)s"
msgstr "Google 云存储器 API 故障：%(reason)s"

#, python-format
msgid "Google Cloud Storage connection failure: %(reason)s"
msgstr "Google 云存储器连接故障：%(reason)s"

#, python-format
msgid "Google Cloud Storage oauth2 failure: %(reason)s"
msgstr "Google 云存储器 oauth2 故障：%(reason)s"

#, python-format
msgid "Got bad path information from DRBDmanage! (%s)"
msgstr "从 DRBDmanage 中获得了错误路径信息！(%s)"

#, python-format
msgid "Group %(group_id)s could not be found."
msgstr "无法找到名为 %(group_id)s 的组。"

#, python-format
msgid ""
"Group %s still contains volumes. The delete-volumes flag is required to "
"delete it."
msgstr "组 %s 仍然包含卷。需要 delete-volumes 标记，以将其删除。"

#, python-format
msgid ""
"Group Type %(group_type_id)s deletion is not allowed with groups present "
"with the type."
msgstr "当存在类型为 %(group_type_id)s 的组时，不允许删除该组类型。"

#, python-format
msgid "Group Type %(group_type_id)s has no specs with key %(group_specs_key)s."
msgstr "组类型 %(group_type_id)s 没有键 %(group_specs_key)s 对应的规格说明。"

#, python-format
msgid "Group Type %(id)s already exists."
msgstr "组类型 %(id)s 已存在。"

#, python-format
msgid "Group Type %(type_id)s has no extra spec with key %(id)s."
msgstr "组类型%(type_id)s没有与键%(id)s对应的额外规格。"

msgid "Group snapshot is empty. No group will be created."
msgstr "组快照为空。将不会创建任何组。"

#, python-format
msgid "Group status must be available or error, but current status is: %s"
msgstr "组状态必须为“available”或“error”，但当前状态为：%s"

#, python-format
msgid "Group type %(group_type_id)s could not be found."
msgstr "组类型 %(group_type_id)s 无法找到。"

#, python-format
msgid ""
"Group type access for %(group_type_id)s / %(project_id)s combination already "
"exists."
msgstr "已存在针对 %(group_type_id)s / %(project_id)s 组合的组类型权限。"

#, python-format
msgid ""
"Group type access not found for %(group_type_id)s / %(project_id)s "
"combination."
msgstr "使用 %(group_type_id)s / %(project_id)s 组合无法访问组类型。"

#, python-format
msgid "Group type encryption for type %(type_id)s already exists."
msgstr "针对类型为 %(type_id)s 的组类型加密方式已存在。"

#, python-format
msgid "Group type encryption for type %(type_id)s does not exist."
msgstr "针对组类型 %(type_id)s 加密方式不存在。"

msgid "Group type name can not be empty."
msgstr "组类型名称不能为空。"

#, python-format
msgid "Group type with name %(group_type_name)s could not be found."
msgstr "名为 %(group_type_name)s 的组类型无法找到。"

#, python-format
msgid ""
"Group volume type mapping for %(group_id)s / %(volume_type_id)s combination "
"already exists."
msgstr "已存在映射 %(group_id)s / %(volume_type_id)s 组合的卷组类型。"

#, python-format
msgid "GroupSnapshot %(group_snapshot_id)s could not be found."
msgstr "无法找到组快照 %(group_snapshot_id)s。"

msgid ""
"GroupSnapshot status must be available or error, and no Group can be "
"currently using it as source for its creation."
msgstr ""
"组快照状态必须为“avaliable”或“error”，而且当前没有任何组可以使用该快照作为源"
"来创建。"

msgid "HPELeftHand url not found"
msgstr "找不到 HPELeftHand URL"

#, python-format
msgid "HTTP exit code: [%(code)s]"
msgstr "HTTP退出码:[%(code)s]"

#, python-format
msgid ""
"Hash block size has changed since the last backup. New hash block size: "
"%(new)s. Old hash block size: %(old)s. Do a full backup."
msgstr ""
"自从最近一次备份以来，散列块大小已更改。新的散列块大小：%(new)s。旧的散列块大"
"小：%(old)s。请执行完全备份。"

msgid "Heartbeat"
msgstr "心跳"

#, python-format
msgid "Hint \"%s\" not supported."
msgstr "提示“%s”不受支持。"

msgid "Host"
msgstr "主机"

#, python-format
msgid "Host %(host)s could not be found."
msgstr "主机 %(host)s 没有找到。"

#, python-format
msgid "Host %s has no FC initiators"
msgstr "主机 %s 没有 FC 启动程序"

#, python-format
msgid "Host not found. Failed to remove %(service)s on %(host)s."
msgstr "找不到主机。未能在 %(host)s 上移除 %(service)s。"

msgid "Hosts"
msgstr "主机"

msgid "Hypermetro and Replication can not be used in the same volume_type."
msgstr "Hypermetro 和复制不能用于同一 volume_type。"

msgid "ID"
msgstr "ID"

msgid ""
"If compression is set to True, rsize must also be set (not equal to -1)."
msgstr "如果 compression 设置为 True，那么还必须设置 rsize（不等于 -1）。"

msgid "If nofmtdisk is set to True, rsize must also be set to -1."
msgstr "如果 nofmtdisk 设置为 True，rsize 必须也设置为 -1。"

#, python-format
msgid ""
"Illegal value '%(prot)s' specified for flashsystem_connection_protocol: "
"valid value(s) are %(enabled)s."
msgstr ""
"为 flashsystem_connection_protocol 指定的值“%(prot)s”非法：有效值为 "
"%(enabled)s。"

msgid "Illegal value specified for IOTYPE: 0, 1, or 2."
msgstr "对 IOTYPE 指定了非法值：0、1 或 2。"

msgid "Illegal value specified for smarttier: set to either 0, 1, 2, or 3."
msgstr "为 smarttier 指定了非法值：请将值设置为 0、1、2 或者 3。"

msgid ""
"Illegal value specified for storwize_svc_vol_grainsize: set to either 32, "
"64, 128, or 256."
msgstr ""
"为 storwize_svc_vol_grainsize 指定了非法值：请将值设置为 32、64、128 或 256。"

msgid ""
"Illegal value specified for thin: Can not set thin and thick at the same "
"time."
msgstr "为 thin 指定了非法值：不能同时设置 thin 和 thick。"

#, python-format
msgid "Image %(image_id)s could not be found."
msgstr "找不到映像 %(image_id)s。"

#, python-format
msgid "Image %(image_id)s is not active."
msgstr "映像 %(image_id)s 处于不活动状态。"

#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr "映像 %(image_id)s 无法接受，原因是： %(reason)s"

msgid "Image location not present."
msgstr "映像位置不存在。"

msgid "Image quota exceeded"
msgstr "镜像超出配额。"

#, python-format
msgid ""
"Image virtual size is %(image_size)dGB and doesn't fit in a volume of size "
"%(volume_size)dGB."
msgstr ""
"映像虚拟大小为 %(image_size)dGB，在大小为 %(volume_size)dGB 的卷中将无法容"
"纳。"

msgid ""
"ImageBusy error raised while deleting rbd volume. This may have been caused "
"by a connection from a client that has crashed and, if so, may be resolved "
"by retrying the delete after 30 seconds has elapsed."
msgstr ""
"删除 rbd 卷时，发生 ImageBusy 错误。这可能是由于客户机的已崩溃连接导致，如果"
"是这样，那么可通过在 30 秒之后重试该删除来解决问题。"

msgid "Incremental backups exist for this backup."
msgstr "对于此备份，存在增量备份。"

msgid "Input volumes or snapshots are invalid."
msgstr "输入卷或快照无效。"

msgid "Input volumes or source volumes are invalid."
msgstr "输入卷或源卷无效。"

#, python-format
msgid "Instance %(uuid)s could not be found."
msgstr "找不到实例 %(uuid)s。"

#, python-format
msgid "Invalid 3PAR Domain: %(err)s"
msgstr "3PAR 域无效：%(err)s"

msgid "Invalid ALUA value. ALUA value must be 1 or 0."
msgstr "ALUA 值无效。ALUA 值必须为 1 或 0。"

msgid "Invalid Ceph args provided for backup rbd operation"
msgstr "为备份rbd操作提供的Ceph参数无效"

#, python-format
msgid "Invalid CgSnapshot: %(reason)s"
msgstr "Cg 快照无效：%(reason)s"

#, python-format
msgid "Invalid ConsistencyGroup: %(reason)s"
msgstr "一致性组无效：%(reason)s"

#, python-format
msgid "Invalid Group: %(reason)s"
msgstr "无效的组: %(reason)s"

#, python-format
msgid "Invalid GroupSnapshot: %(reason)s"
msgstr "无效的组快照: %(reason)s"

#, python-format
msgid ""
"Invalid HPELeftHand API version found: %(found)s. Version %(minimum)s or "
"greater required for manage/unmanage support."
msgstr ""
"发现无效 HPELeftHand API 版本 (%(found)s)。需要版本 %(minimum)s 或更高版本以"
"获取管理/取消管理支持。"

#, python-format
msgid "Invalid IP address format: '%s'"
msgstr "IP 地址格式“%s”无效"

#, python-format
msgid ""
"Invalid QoS specification detected while getting QoS policy for volume %s"
msgstr "获取卷 %s 的 QoS 策略时，检测到无效 QoS 规范"

#, python-format
msgid "Invalid Replication Target: %(reason)s"
msgstr "无效复制目标：%(reason)s"

#, python-format
msgid ""
"Invalid Virtuozzo Storage share specification: %r. Must be: [MDS1[,"
"MDS2],...:/]<CLUSTER NAME>[:PASSWORD]."
msgstr ""
"无效 Virtuozzo 存储器共享规范：%r。必须为 [MDS1[,MDS2],...:/]<CLUSTER NAME>[:"
"PASSWORD]。"

#, python-format
msgid "Invalid XtremIO version %(cur)s, version %(min)s or up is required"
msgstr "XtremIO V%(cur)s 无效，需要 V%(min)s 或更高版本"

#, python-format
msgid "Invalid allocated quotas defined for the following project quotas: %s"
msgstr "对以下项目配额定义的已分配配额无效：%s"

msgid "Invalid argument - negative seek offset."
msgstr "无效参数 - 查找偏移量为负数。"

#, python-format
msgid "Invalid argument - whence=%s not supported."
msgstr "无效参数 - whence=%s 不受支持。"

#, python-format
msgid "Invalid attaching mode '%(mode)s' for volume %(volume_id)s."
msgstr "加载模式 '%(mode)s' 对于卷 %(volume_id)s 无效。"

#, python-format
msgid "Invalid attachment info for volume %(name)s: %(reason)s"
msgstr "卷 %(name)s 的无效挂载信息: %(reason)s"

#, python-format
msgid "Invalid auth key: %(reason)s"
msgstr "认证密钥无效：%(reason)s"

#, python-format
msgid "Invalid backup: %(reason)s"
msgstr "备份无效：%(reason)s"

#, python-format
msgid "Invalid connection initialization response of volume %(name)s"
msgstr "卷 %(name)s 的连接初始化响应无效"

#, python-format
msgid ""
"Invalid connection initialization response of volume %(name)s: %(output)s"
msgstr "卷 %(name)s 的连接初始化响应无效：%(output)s"

#, python-format
msgid "Invalid content type %(content_type)s."
msgstr "无效的内容类型 %(content_type)s。"

#, python-format
msgid "Invalid directory: %s"
msgstr "无效目录：%s"

#, python-format
msgid "Invalid disk adapter type: %(invalid_type)s."
msgstr "无效磁盘适配器类型：%(invalid_type)s。"

#, python-format
msgid "Invalid disk backing: %s."
msgstr "无效磁盘备份：%s。"

#, python-format
msgid "Invalid disk type: %(disk_type)s."
msgstr "无效磁盘类型：%(disk_type)s。"

#, python-format
msgid "Invalid disk type: %s."
msgstr "无效磁盘类型：%s。"

#, python-format
msgid "Invalid filter keys: %s"
msgstr "无效的筛选键:%s"

#, python-format
msgid "Invalid group type: %(reason)s"
msgstr "无效的组类型:%(reason)s"

#, python-format
msgid "Invalid host: %(reason)s"
msgstr "主机无效：%(reason)s"

#, python-format
msgid ""
"Invalid hpe3parclient version found (%(found)s). Version %(minimum)s or "
"greater required. Run \"pip install --upgrade python-3parclient\" to upgrade "
"the hpe3parclient."
msgstr ""
"发现无效 hpe3parclient 版本 (%(found)s)。需要版本 %(minimum)s 或更高版本。请"
"运行“pip install --upgrade python-3parclient”以升级 hpe3parclient。"

#, python-format
msgid ""
"Invalid hpelefthandclient version found (%(found)s). Version %(minimum)s or "
"greater required. Run 'pip install --upgrade python-lefthandclient' to "
"upgrade the hpelefthandclient."
msgstr ""
"发现无效 hpelefthandclient 版本 (%(found)s)。需要版本 %(minimum)s 或更高版"
"本。请运行“pip install --upgrade python-lefthandclient”以升级 "
"hpelefthandclient。"

#, python-format
msgid "Invalid image href %(image_href)s."
msgstr "无效映像 href %(image_href)s。"

msgid "Invalid image identifier or unable to access requested image."
msgstr "映像标识无效，或无法访问所请求映像。"

msgid "Invalid imageRef provided."
msgstr "提供了无效的imageRef。"

msgid "Invalid input"
msgstr "输入无效"

#, python-format
msgid "Invalid input received: %(reason)s"
msgstr "输入无效： %(reason)s"

#, python-format
msgid "Invalid is_public filter [%s]"
msgstr "is_public 过滤器 [%s] 无效"

#, python-format
msgid "Invalid lun type %s is configured."
msgstr "配置了无效 LUN 类型 %s。"

#, python-format
msgid "Invalid metadata size: %(reason)s"
msgstr "元数据大小无效：  %(reason)s"

#, python-format
msgid "Invalid metadata: %(reason)s"
msgstr "元数据无效：  %(reason)s"

#, python-format
msgid "Invalid mount point base: %s"
msgstr "安装点基准无效：%s"

#, python-format
msgid "Invalid mount point base: %s."
msgstr "安装点基准无效：%s。"

#, python-format
msgid "Invalid new snapCPG name for retype.  new_snap_cpg='%s'."
msgstr "新 snapCPG 名称对执行 retype 操作无效。new_snap_cpg='%s'。"

#, python-format
msgid ""
"Invalid prefetch type '%s' is configured. PrefetchType must be in 0,1,2,3."
msgstr "配置了无效预取类型“%s”。PrefetchType 必须为 0、1、2 和 3 的其中之一。"

#, python-format
msgid "Invalid qos specs: %(reason)s"
msgstr "qos 规范无效：%(reason)s"

#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr "预留到期 %(expire)s 无效。"

#, python-format
msgid "Invalid secondary id %s."
msgstr "无效辅助标识 %s。"

msgid "Invalid service catalog json."
msgstr "服务目录 json 无效。"

msgid "Invalid sheepdog cluster status."
msgstr "sheepdog 集群状态无效。"

#, python-format
msgid "Invalid snapshot: %(reason)s"
msgstr "快照无效: %(reason)s"

#, python-format
msgid "Invalid sort dirs passed: %s"
msgstr "传递的无效排序目录:%s"

#, python-format
msgid "Invalid sort keys passed: %s"
msgstr "传递的无效排序码:%s"

#, python-format
msgid "Invalid status: '%s'"
msgstr "无效的状态：'%s'"

#, python-format
msgid "Invalid storage pool %s requested.  Retype failed."
msgstr "请求的存储池 %s 无效。转型失败。"

#, python-format
msgid "Invalid storage pool %s specificed."
msgstr "指定的存储池 %s 无效。"

msgid "Invalid storage pool is configured."
msgstr "配置了无效存储池。"

#, python-format
msgid "Invalid update setting: '%s'"
msgstr "无效的更新设置：'%s'"

#, python-format
msgid "Invalid value '%s' for force."
msgstr "值“%s”对于 force 无效。"

msgid "Invalid value for 'scheduler_max_attempts', must be >=1"
msgstr "值对于“scheduler_max_attempts”无效，必须 >= 1"

msgid "Invalid value for NetApp configuration option netapp_host_type."
msgstr "NetApp 配置选项 netapp_host_type 的值无效。"

msgid "Invalid value for NetApp configuration option netapp_lun_ostype."
msgstr "NetApp 配置选项 netapp_lun_ostype 的值无效。"

#, python-format
msgid "Invalid value for age, %(age)s"
msgstr "age 的值 %(age)s 无效"

#, python-format
msgid "Invalid value: \"%s\""
msgstr "无效值：“%s”"

#, python-format
msgid ""
"Invalid volume size provided for create request: %s (size argument must be "
"an integer (or string representation of an integer) and greater than zero)."
msgstr ""
"针对创建请求提供的以下卷大小无效：%s（自变量 size 必须是整数（也可以是整数的"
"字符串表示法）并且大于零）。"

#, python-format
msgid "Invalid volume type: %(reason)s"
msgstr "卷类型无效：%(reason)s"

#, python-format
msgid "Invalid volume: %(reason)s"
msgstr "卷无效：  %(reason)s"

#, python-format
msgid "Invalid volume_type passed: %s."
msgstr "已传递的 volume_type 无效：%s。"

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type is not compatible; either "
"match source volume, or omit type argument)."
msgstr ""
"所提供的以下 volume_type 无效：%s（所请求的类型不兼容；要么与源卷相匹配，要么"
"省略类型参数）。"

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type is not compatible; "
"recommend omitting the type argument)."
msgstr "所提供的 volume_type %s 无效（所请求的类型不兼容；建议省略类型参数）。"

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type must be supported by this "
"consistency group)."
msgstr "提供的以下 volume_type 无效：%s（所请求类型必须受此一致性组支持）。"

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type must be supported by this "
"group)."
msgstr "提供的以下 volume_type 无效：%s（所请求类型必须被该组支持）。"

#, python-format
msgid "Invalid wwpns format %(wwpns)s"
msgstr "无效 WWPN 格式 %(wwpns)s"

msgid "Issue encountered waiting for job."
msgstr "等待作业时遇到问题。"

msgid "Issue encountered waiting for synchronization."
msgstr "等待同步时遇到问题。"

msgid ""
"Issuing a fail-over failed because replication is not properly configured."
msgstr "发出故障转移失败，因为未正确配置复制。"

#, python-format
msgid "Kaminario retryable exception: %(reason)s"
msgstr "Kaminario可重试异常:%(reason)s"

#, python-format
msgid "KaminarioCinderDriver failure: %(reason)s"
msgstr "Kaminario Cinder 驱动程序故障:%(reason)s"

#, python-format
msgid "KeyError: %s"
msgstr "KeyError：%s"

msgid "Keystone version 3 or greater must be used to get nested quota support."
msgstr "必须使用 Keystone 版本 3 或更高版本来获取嵌套配额支持。"

#, python-format
msgid "LUN not found by UUID: %(uuid)s."
msgstr "无法通过UUID:%(uuid)s找到LUN。"

#, python-format
msgid "LUN not found with given ref %s."
msgstr "找不到具有给定引用 %s 的 LUN。"

msgid "LeftHand cluster not found"
msgstr "找不到 LeftHand 集群"

msgid "License is unavailable."
msgstr "许可证不可用。"

#, python-format
msgid "Linked clone of source volume not supported in state: %s."
msgstr "不支持处于以下状态的源卷的已链接克隆：%s。"

msgid "Lock acquisition failed."
msgstr "锁定获取失败。"

msgid "Logout session error."
msgstr "注销会话错误。"

msgid ""
"Lookup service not configured. Config option for fc_san_lookup_service needs "
"to specify a concrete implementation of the lookup service."
msgstr ""
"未配置查找服务。fc_san_lookup_service 的配置选项需要指定查找服务的具体实现。"

msgid "Lun migration error."
msgstr "Lun 迁移错误。"

#, python-format
msgid ""
"MD5 of object: %(object_name)s before: %(md5)s and after: %(etag)s is not "
"same."
msgstr "对象 %(object_name)s 的 MD5 在 %(md5)s 之前和 %(etag)s 之后不相同。"

#, python-format
msgid "Malformed fcns output string: %s"
msgstr "以下 fcns 输出字符串的格式不正确：%s"

#, python-format
msgid "Malformed message body: %(reason)s"
msgstr "错误格式的消息体： %(reason)s"

#, python-format
msgid "Malformed nameserver string: %s"
msgstr "以下名称服务器字符串的格式不正确：%s"

msgid "Malformed request body"
msgstr "错误格式的请求主体"

msgid "Malformed request body."
msgstr "请求主体的格式不正确。"

msgid "Malformed request url"
msgstr "错误格式的请求url"

#, python-format
msgid "Malformed response to command %(cmd)s: %(reason)s"
msgstr "对命令 %(cmd)s 的响应的格式不正确：%(reason)s"

#, python-format
msgid "Malformed show fcns database string: %s"
msgstr "以下显示 fcns 数据库字符串的格式不正确：%s"

#, python-format
msgid ""
"Malformed zone configuration: (switch=%(switch)s zone_config="
"%(zone_config)s)."
msgstr ""
"区域配置的格式不正确：(switch=%(switch)s zone_config=%(zone_config)s)。"

#, python-format
msgid "Malformed zone status: (switch=%(switch)s zone_config=%(zone_config)s)."
msgstr ""
"区域状态的格式不正确：（交换机为 %(switch)s，zone_config 为 "
"%(zone_config)s）。"

msgid "Manage existing get size requires 'id'."
msgstr "管理现有 get 大小需要“id”。"

msgid "Manage existing snapshot not implemented."
msgstr "未实现对现有快照的管理。"

#, python-format
msgid ""
"Manage existing volume failed due to invalid backend reference "
"%(existing_ref)s: %(reason)s"
msgstr "由于后端引用 %(existing_ref)s 无效，管理现有卷失败：%(reason)s"

#, python-format
msgid "Manage existing volume failed due to volume type mismatch: %(reason)s"
msgstr "由于卷类型不匹配，管理现有卷失败：%(reason)s"

msgid "Manage existing volume not implemented."
msgstr "未实现对现有卷的管理。"

msgid "Manage existing volume requires 'source-id'."
msgstr "管理现有卷将需要“source-id”。"

msgid "Managing of snapshots to failed-over volumes is not allowed."
msgstr "不允许管理到达已故障转移的卷的快照。"

msgid "Map info is None due to array version not supporting hypermetro."
msgstr "无映射信息，因为阵列版本不支持 hypermetro。"

msgid "Max read iops setting for volume qos, use 0 for unlimited"
msgstr "为卷的qos设置最大读iops，0表示无限制。"

msgid "Max total iops setting for volume qos, use 0 for unlimited"
msgstr "为卷的qos设置最大总量iops，0表示无限制。"

msgid "Max write iops setting for volume qos, use 0 for unlimited"
msgstr "为卷的qos设置最大写iops，0表示无限制。"

msgid "Maximum age is count of days since epoch."
msgstr "最大年龄是自新纪元开始计算的天数。"

#, python-format
msgid "Maximum number of backups allowed (%(allowed)d) exceeded"
msgstr "已超过允许的最大备份数 (%(allowed)d)"

#, python-format
msgid "Maximum number of snapshots allowed (%(allowed)d) exceeded"
msgstr "已超过允许的最大快照数 (%(allowed)d)"

#, python-format
msgid ""
"Maximum number of volumes allowed (%(allowed)d) exceeded for quota "
"'%(name)s'."
msgstr "对于定额“%(name)s”，超过了允许的最大卷数 (%(allowed)d)。"

#, python-format
msgid "May specify only one of %s"
msgstr "只能指定 %s 中的一个"

#, python-format
msgid "Message %(message_id)s could not be found."
msgstr "信息 %(message_id)s 无法找到。"

msgid "Metadata backup already exists for this volume"
msgstr "对于此卷，已存在元数据备份"

#, python-format
msgid "Metadata backup object '%s' already exists"
msgstr "元数据备份对象“%s”已存在"

#, python-format
msgid "Metadata property key %s greater than 255 characters."
msgstr "元数据属性关键字%s超过255个字符。"

#, python-format
msgid "Metadata property key %s value greater than 255 characters."
msgstr "元数据属性关键字%s值超过255个字符。"

msgid "Metadata restore failed due to incompatible version"
msgstr "由于版本不兼容，元数据复原失败"

msgid "Metadata restore failed due to incompatible version."
msgstr "由于版本不兼容，元数据复原失败。"

#, python-format
msgid "Method %(method)s is not defined"
msgstr "方法 %(method)s 未被定义"

msgid ""
"Missing 'purestorage' python module, ensure the library is installed and "
"available."
msgstr "缺少“purestorage”python 模块，请确保库已安装并且可用。"

msgid "Missing Fibre Channel SAN configuration param - fc_fabric_names"
msgstr "缺少光纤通道 SAN 配置参数 - fc_fabric_names"

msgid "Missing request body."
msgstr "缺少请求主体。"

#, python-format
msgid "Missing required element '%(element)s' in request body."
msgstr "请求主体中缺少必要的元素'%(element)s'"

#, python-format
msgid "Missing required element '%s' in request body."
msgstr "请求主体中缺少必需元素“%s”。"

#, python-format
msgid "Multiple copies of volume %s found."
msgstr "找到了卷 %s 的多个副本。"

#, python-format
msgid "Multiple matches found for '%s', use an ID to be more specific."
msgstr "对于“%s”，找到多个匹配项，请使用标识以更具体地进行查找。"

msgid "Multiple profiles found."
msgstr "找到了多个概要文件。"

msgid "Must implement a fallback schedule"
msgstr "必须实现一个回滚 schedule"

msgid "Must implement schedule_create_group"
msgstr "必须实现 schedule_create_group"

msgid "Must implement schedule_create_volume"
msgstr "必须实现 schedule_create_volume"

msgid "Must implement schedule_get_pools"
msgstr "必须实现 schedule_get_pools"

msgid "Must pass wwpn or host to lsfabric."
msgstr "必须将 wwpn 或 host 传递给 lsfabric。"

msgid ""
"Must run this command as cloud admin using a Keystone policy.json which "
"allows cloud admin to list and get any project."
msgstr ""
"必须以云管理员身份使用 Keystone policy.json（它允许云管理员列示和获取任何项"
"目）运行此命令。"

msgid ""
"Must specify 'status', 'attach_status' or 'migration_status' for update."
msgstr "必须指定“status”、“attach_status”或“migration_status”以进行更新。"

#, python-format
msgid "Must specify a valid persona %(valid)s,value '%(persona)s' is invalid."
msgstr "必须指定有效角色 %(valid)s，值“%(persona)s”无效。"

#, python-format
msgid ""
"Must specify a valid provisioning type %(valid)s, value '%(prov)s' is "
"invalid."
msgstr "指定有效供应类型 %(valid)s，值“%(prov)s”无效。"

msgid "Must specify an ExtensionManager class"
msgstr "必须明确一个ExtensionManager类"

msgid ""
"Must specify one or more of the following keys to update: name, description, "
"add_volumes, remove_volumes."
msgstr "更新时必须指定如下的一个或多个键:名称，描述，添加卷，删除卷。"

msgid "Must specify snapshot source-name or source-id."
msgstr "必须指定快照 source-name 或 source-id。"

msgid "Must specify source-name or source-id."
msgstr "必须指定 source-name 或 source-id。"

msgid "Must specify storage pools. Option: sio_storage_pools."
msgstr "必须指定存储库。选项：sio_storage_pools。"

msgid "Must supply a positive value for age"
msgstr "必须为 age 提供正值"

#, python-format
msgid ""
"NAS config '%(name)s=%(value)s' invalid. Must be 'auto', 'true', or 'false'"
msgstr "NAS 配置“%(name)s=%(value)s”无效。必须为“auto”、“true”或“false”"

#, python-format
msgid "NFS config file at %(config)s doesn't exist"
msgstr " %(config)s 处不存在 NFS 配置文件"

#, python-format
msgid "NFS file %s not discovered."
msgstr "未发现 NFS 文件 %s。"

msgid "NFS file could not be discovered."
msgstr "未能发现 NFS 文件。"

msgid "NaElement name cannot be null."
msgstr "NaElement 名称不能为空。"

msgid "Name"
msgstr "名称"

msgid ""
"Name, description, add_volumes, and remove_volumes can not be all empty in "
"the request body."
msgstr "在请求主体中，名称、描述、add_volumes 和 remove_volumes 不能全部为空。"

msgid "Need non-zero volume size"
msgstr "需要非零卷大小"

msgid "NetApp Cinder Driver exception."
msgstr "发生“NetApp Cinder 驱动程序”异常。"

#, python-format
msgid ""
"New size for extend must be greater than current size. (current: %(size)s, "
"extended: %(new_size)s)."
msgstr ""
"用于扩展的新大小必须大于当前大小。（当前：%(size)s，已扩展：%(new_size)s）。"

#, python-format
msgid ""
"New size should be bigger than the real size from backend storage. realsize: "
"%(oldsize)s, newsize: %(newsize)s."
msgstr ""
"新大小应该大于后端存储器中的实际大小。realsize：%(oldsize)s，newsize："
"%(newsize)s。"

msgid "New volume type not specified in request_spec."
msgstr "在 request_spec 中，未指定新的卷类型。"

msgid "Nimble Cinder Driver exception"
msgstr "Nimble Cinder 驱动程序异常"

msgid "No FC initiator can be added to host."
msgstr "无法将任何 FC 启动程序添加至主机。"

msgid "No FC port connected to fabric."
msgstr "没有任何 FC 端口连接至光纤网络。"

msgid "No VF ID is defined in the configuration file."
msgstr "未在配置文件中定义 VF 标识。"

msgid "No active iSCSI portals with supplied iSCSI IPs"
msgstr "不存在具有所提供 iSCSI IP 的活动 iSCSI 门户网站"

msgid "No backups available to do an incremental backup."
msgstr "没有任何备份可用于执行增量备份。"

#, python-format
msgid "No cloned LUN named %s found on the filer"
msgstr "在文件管理器上，找不到名为 %s 的已克隆 LUN"

msgid "No config node found."
msgstr "找不到配置节点。"

#, python-format
msgid "No element by given name %s."
msgstr "没有具备给定名称 %s 的元素。"

#, python-format
msgid "No file found with %s as backing file."
msgstr "在将 %s 作为支持文件的情况下，找不到任何文件。"

#, python-format
msgid "No group snapshot with id %s"
msgstr "不存在任何具有标识 %s 的组快照"

msgid "No iSCSI-enabled ports on target array."
msgstr "目标阵列上没有可支持 iSCSI 的端口。"

msgid "No initiator connected to fabric."
msgstr "没有任何启动程序连接至光纤网络。"

#, python-format
msgid "No initiator group found for initiator %s"
msgstr "找不到对应启动程序 %s 的启动程序组"

#, python-format
msgid "No interface found on cluster for ip %s"
msgstr "集群中找不到 IP %s 的接口"

msgid "No ip address found."
msgstr "找不到 IP 地址。"

msgid "No mounted NFS shares found"
msgstr "找不到任何已安装的 NFS 共享项"

msgid "No mounted SMBFS shares found."
msgstr "找不到任何已安装的 SMBFS 共享项。"

msgid "No mounted Virtuozzo Storage shares found"
msgstr "找不到任何已安装的 Virtuozzo 存储器共享项"

msgid "No mounted shares found"
msgstr "找不到任何已安装的共享项"

#, python-format
msgid "No node found in I/O group %(gid)s for volume %(vol)s."
msgstr "在卷 %(vol)s 的 I/O 组 %(gid)s 中找不到节点。"

msgid ""
"No pools are available for provisioning volumes. Ensure that the "
"configuration option netapp_pool_name_search_pattern is set correctly."
msgstr ""
"没有池可用于提供卷。请确保正确设置了 netapp_pool_name_search_pattern 配置选"
"项。"

#, python-format
msgid "No snap found with %s as backing file."
msgstr "在将 %s 作为支持文件的情况下，找不到任何 snap。"

msgid ""
"No storage could be allocated for this volume request. You may be able to "
"try another size or volume type."
msgstr "无法为该卷请求分配存储。可以尝试其他大小或卷类型。"

#, python-format
msgid "No such QoS spec %(specs_id)s."
msgstr "不存在任何此类 QoS 规范 %(specs_id)s。"

msgid "No suitable discovery ip found"
msgstr "找不到合适的发现 IP"

#, python-format
msgid "No support to restore backup version %s"
msgstr "不支持复原备份版本 %s"

#, python-format
msgid "No target id found for volume %(volume_id)s."
msgstr "没有为卷 %(volume_id)s 找到目标id。"

#, python-format
msgid "No vdisk with the UID specified by ref %s."
msgstr "没有具备引用 %s 指定的 UID 的 vdisk。"

#, python-format
msgid ""
"No volume on cluster with vserver %(vserver)s and junction path %(junction)s "
msgstr "集群上不存在任何具有 vserver %(vserver)s 和结点路径 %(junction)s 的卷"

#, python-format
msgid "No volumes or consistency groups exist in cluster %(current)s."
msgstr "集群 %(current)s 中不存在卷或者一致性组。"

msgid "Not a valid value for NaElement."
msgstr "此值对 NaElement 无效。"

msgid "Not an rbd snapshot"
msgstr "不是 rbd 快照"

#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr "未针对映像 %(image_id)s 授权。"

msgid "Not authorized."
msgstr "未授权。"

#, python-format
msgid "Not enough space on backend (%(backend)s)"
msgstr "后端 (%(backend)s) 上没有足够的空间"

msgid "Not enough storage space in the ZFS share to perform this operation."
msgstr "ZFS 共享项中的存储空间不足，无法执行此操作。"

msgid "Not stored in rbd"
msgstr "未存储在 rbd 中"

msgid "Nova returned \"error\" status while creating snapshot."
msgstr "在创建快照时，Nova 返回了“错误”状态。"

msgid "Object Count"
msgstr "对象计数"

msgid "Object Version"
msgstr "对象版本"

msgid "Object is not a NetApp LUN."
msgstr "对象不是 NetApp LUN。"

#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""
"只能有 %(value)s 个 %(verb)s 请求发送给 %(uri)s 限定是每一个 "
"%(unit_string)s。"

msgid "Only one limit can be set in a QoS spec."
msgstr "在 QoS 规范中只能设置一个限制。"

msgid ""
"Only users with token scoped to immediate parents or root projects are "
"allowed to see its children quotas."
msgstr "只允许令牌作用域仅限于直系父代或者根项目的用户查看其子代配额。"

msgid "Only volumes managed by OpenStack can be unmanaged."
msgstr "只有 OpenStack 管理的卷才能为非受管卷。"

#, python-format
msgid "Operation failed with status=%(status)s. Full dump: %(data)s"
msgstr "操作失败，并且 status=%(status)s。完全转储：%(data)s"

#, python-format
msgid "Operation not supported: %(operation)s."
msgstr "操作 %(operation)s 不受支持。"

msgid "Option gpfs_images_dir is not set correctly."
msgstr "选项 gpfs_images_dir 未正确设置。"

msgid "Option gpfs_mount_point_base is not set correctly."
msgstr "选项 gpfs_mount_point_base 未正确设置。"

#, python-format
msgid "Originating %(res)s %(prop)s must be one of '%(vals)s' values"
msgstr "始发 %(res)s %(prop)s 必须为其中一个“%(vals)s”值"

#, python-format
msgid "ParseException: %s"
msgstr "ParseException：%s"

msgid "Partition name is None, please set smartpartition:partitionname in key."
msgstr "分区名称为 None，请在键中设置 smartpartition:partitionname。"

msgid ""
"Password or SSH private key is required for authentication: set either "
"san_password or san_private_key option."
msgstr ""
"进行认证需要密码或 SSH 专用密钥：请设置 san_password 或 san_private_key 选"
"项。"

msgid "Path to REST server's certificate must be specified."
msgstr "必须指定 REST 服务器的证书的路径。"

#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr "政策不允许 %(action)s 被执行。"

msgid "Pool is not available in the volume host field."
msgstr "在卷主机字段中，未提供池。"

msgid "Pool is not available in the volume host fields."
msgstr "在卷主机字段中，未提供池。"

#, python-format
msgid "Pool with name %(pool_name)s wasn't found in domain %(domain_id)s."
msgstr "在域 %(domain_id)s 中找不到名称为 %(pool_name)s 的池。"

#, python-format
msgid "Programming error in Cinder: %(reason)s"
msgstr "Cinder程序错误:%(reason)s"

msgid "Project ID"
msgstr "项目ID"

#, python-format
msgid "Project quotas are not properly setup for nested quotas: %(reason)s."
msgstr "未正确设置要用作嵌套配额的项目配额：%(reason)s。"

msgid "Protection Group not ready."
msgstr "保护组未就绪。"

#, python-format
msgid ""
"Protocol %(storage_protocol)s is not supported for storage family "
"%(storage_family)s."
msgstr "存储器系列 %(storage_family)s 不支持协议 %(storage_protocol)s。"

msgid "Provided backup record is missing an id"
msgstr "所提供的备份记录缺少标识"

#, python-format
msgid ""
"Provided snapshot status %(provided)s not allowed for snapshot with status "
"%(current)s."
msgstr "对于状态为 %(current)s 的快照，不允许提供的快照状态 %(provided)s。"

#, python-format
msgid "Pure Storage Cinder driver failure: %(reason)s"
msgstr "Pure Storage Cinder 驱动程序故障：%(reason)s"

msgid "Purge command failed, check cinder-manage logs for more details."
msgstr "Pure命令执行失败，更多详细信息请查看cinder-manage日志。"

#, python-format
msgid "QoS Specs %(specs_id)s already exists."
msgstr "QoS 规范 %(specs_id)s 已存在。"

#, python-format
msgid "QoS Specs %(specs_id)s is still associated with entities."
msgstr "QoS 规范 %(specs_id)s 仍然与实体关联。"

#, python-format
msgid "QoS config is wrong. %s must > 0."
msgstr "QoS 配置不正确。%s 必须大于 0。"

#, python-format
msgid ""
"QoS policy must specify for IOTYPE and another qos_specs, QoS policy: "
"%(qos_policy)s."
msgstr "QoS 策略必须指定 IOTYPE 和另一 qos_specs，QoS 策略：%(qos_policy)s。"

#, python-format
msgid ""
"QoS policy must specify for IOTYPE: 0, 1, or 2, QoS policy: %(qos_policy)s "
msgstr "QoS 策略必须指定 IOTYPE：0、1 或 2。QoS 策略：%(qos_policy)s "

#, python-format
msgid ""
"QoS policy upper_limit and lower_limit conflict, QoS policy: %(qos_policy)s."
msgstr ""
"QoS 策略 upper_limit 和 lower_limit 存在冲突，QoS 策略：%(qos_policy)s。"

#, python-format
msgid "QoS spec %(specs_id)s has no spec with key %(specs_key)s."
msgstr "QoS 规范 %(specs_id)s 没有任何具有键 %(specs_key)s 的规范。"

msgid "Qos specs still in use."
msgstr "Qos 规范仍在使用中。"

msgid "Query resource pool error."
msgstr "查询资源池时发生错误。"

#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr "找不到配额类 %(class_name)s。"

msgid "Quota could not be found"
msgstr "配额没有找到。"

#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr "对于资源，已超过配额：%(overs)s"

#, python-format
msgid "Quota exceeded: code=%(code)s"
msgstr "配额用尽：code=%(code)s"

#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr "没有为项目 %(project_id)s 找到配额。"

#, python-format
msgid ""
"Quota limit invalid for project '%(proj)s' for resource '%(res)s': limit of "
"%(limit)d is less than in-use value of %(used)d"
msgstr ""
"资源“%(res)s”的项目“%(proj)s”的配合限制无效：限制 %(limit)d 小于“in-use”值 "
"%(used)d"

#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr "找不到配额预留 %(uuid)s。"

#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr "找不到项目 %(project_id)s 的配额使用量。"

#, python-format
msgid "RBD diff op failed - (ret=%(ret)s stderr=%(stderr)s)"
msgstr "RBD 差集操作失败 - (ret=%(ret)s stderr=%(stderr)s)"

#, python-format
msgid "REST %(proxy_ver)s hpelefthandclient %(rest_ver)s"
msgstr "REST %(proxy_ver)s hpelefthandclient %(rest_ver)s"

msgid "RPC Version"
msgstr "RPC 版本"

#, python-format
msgid "Received error string: %s"
msgstr "接收到错误字符串：%s"

msgid "Reference must be for an unmanaged snapshot."
msgstr "引用必须针对非受管快照。"

msgid "Reference must be for an unmanaged virtual volume."
msgstr "引用必须对应非受管虚拟卷。"

msgid "Reference must be the name of an unmanaged snapshot."
msgstr "引用必须是非受管快照的名称。"

msgid "Reference must be the volume name of an unmanaged virtual volume."
msgstr "引用必须是非受管虚拟卷的卷名称。"

msgid "Reference must contain source-id or source-name element."
msgstr "引用必须包含 source-id 或 source-name 元素。"

msgid "Reference must contain source-id or source-name key."
msgstr "引用必须包含 source-id 或 source-name 键。"

msgid "Reference must contain source-id or source-name."
msgstr "引用必须包含 source-id 或 source-name。"

msgid "Reference must contain source-id."
msgstr "引用必须包含 source-id。"

msgid "Reference must contain source-name element."
msgstr "引用必须包含 source-name 元素。"

msgid "Reference must contain source-name or source-id."
msgstr "引用必须包含 source-name 或 source-id。"

msgid "Reference must contain source-name."
msgstr "引用必须包含源名称。"

msgid "Reference to volume to be managed must contain source-name."
msgstr "对要管理的卷的引用必须包含 source-name。"

#, python-format
msgid "Reference to volume: %s to be managed must contain source-name."
msgstr "对要管理的卷 %s 的引用必须包含 source-name。"

#, python-format
msgid ""
"Refusing to migrate volume ID: %(id)s. Please check your configuration "
"because source and destination are the same Volume Group: %(name)s."
msgstr ""
"正在拒绝迁移卷标识：%(id)s。请检查配置因为源和目标是同一卷组：%(name)s。"

msgid "Remote pool cannot be found."
msgstr "找不到远程池。"

msgid "Remove CHAP error."
msgstr "移除 CHAP 时发生错误。"

msgid "Remove fc from host error."
msgstr "从主机中移除 FC 时发生错误。"

msgid "Remove host from array error."
msgstr "从阵列中移除主机时发生错误。"

msgid "Remove host from hostgroup error."
msgstr "从主机组中移除主机时发生错误。"

msgid "Remove iscsi from host error."
msgstr "从主机中移除 iSCSI 时发生错误。"

msgid "Remove lun from QoS error."
msgstr "从 QoS 移除 LUN 时出错。"

msgid "Remove lun from cache error."
msgstr "从高速缓存移除 LUN 时发生错误。"

msgid "Remove lun from partition error."
msgstr "从分区移除 LUN 时发生错误。"

msgid "Remove port from port group error."
msgstr "从端口组移除端口时出错。"

msgid "Remove volume export failed."
msgstr "除去卷导出失败。"

msgid "Rename lun on array error."
msgstr "在阵列上重命名 LUN 时发生错误。"

msgid "Rename snapshot on array error."
msgstr "在阵列上重命名快照时出错。"

#, python-format
msgid "Replication %(name)s to %(ssn)s failed."
msgstr "将 %(name)s 复制到 %(ssn)s 失败。"

msgid "Replication not allowed yet."
msgstr "尚不允许复制。"

msgid "Request body and URI mismatch"
msgstr "请求主体和URI不匹配"

msgid "Request body contains too many items"
msgstr "请求主体包含太多items"

#, python-format
msgid "Request to Datera cluster returned bad status: %(status)s | %(reason)s"
msgstr "针对 Datera 集群的请求返回了不正确的状态：%(status)s | %(reason)s"

#, python-format
msgid ""
"Requested backup exceeds allowed Backup gigabytes quota. Requested "
"%(requested)sG, quota is %(quota)sG and %(consumed)sG has been consumed."
msgstr ""
"所请求备份超过允许的备份千兆字节配额。已请求 %(requested)sG，配额为 "
"%(quota)sG，并且已耗用 %(consumed)sG。"

#, python-format
msgid ""
"Requested volume or snapshot exceeds allowed %(name)s quota. Requested "
"%(requested)sG, quota is %(quota)sG and %(consumed)sG has been consumed."
msgstr ""
"所请求的卷或快照超过允许的 %(name)s 配额。已请求 %(requested)sG，配额为 "
"%(quota)sG，已耗用 %(consumed)sG。"

msgid "Required configuration not found"
msgstr "找不到必需的配置选项"

#, python-format
msgid ""
"Reset backup status aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"重置备份状态已异常中止，当前配置的备份服务 [%(configured_service)s] 不是已用"
"来创建此备份的备份服务 [%(backup_service)s]。"

#, python-format
msgid "Resizing clone %s failed."
msgstr "调整克隆 %s 的大小失败。"

msgid "Resizing image file failed."
msgstr "对映像文件调整大小失败。"

msgid "Resource could not be found."
msgstr "资源没有找到。"

msgid "Resource not ready."
msgstr "资源未就绪。"

msgid "RestURL is not configured."
msgstr "未配置 RestURL。"

#, python-format
msgid ""
"Restore backup aborted, expected volume status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"备份复原已异常中止，需要的卷状态为 %(expected_status)s，但获得的是 "
"%(actual_status)s。"

#, python-format
msgid ""
"Restore backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"备份复原已异常中止，当前配置的备份服务 [%(configured_service)s] 不是已用来创"
"建此备份的备份服务 [%(backup_service)s]。"

#, python-format
msgid ""
"Restore backup aborted: expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"备份复原已异常中止：需要的备份状态为 %(expected_status)s，但获得的是 "
"%(actual_status)s。"

#, python-format
msgid ""
"Retrieved a different amount of SolidFire volumes for the provided Cinder "
"snapshots. Retrieved: %(ret)s Desired: %(des)s"
msgstr ""
"检索到所提供 Cinder  快照的不同 SolidFire 卷量。已检索到：%(ret)s 期望："
"%(des)s"

#, python-format
msgid ""
"Retrieved a different amount of SolidFire volumes for the provided Cinder "
"volumes. Retrieved: %(ret)s Desired: %(des)s"
msgstr ""
"检索到所提供 Cinder  卷的不同 SolidFire 卷量。已检索到：%(ret)s 期望：%(des)s"

#, python-format
msgid "Retry count exceeded for command: %s"
msgstr "对于命令，超过重试次数：%s"

msgid "Retryable Dell Exception encountered"
msgstr "遇到可重试的Dell异常。"

msgid "Retryable Pure Storage Exception encountered"
msgstr "遇到可重试的Pure Storage异常。"

msgid "Retryable SolidFire Exception encountered"
msgstr "遇到可重试的 SolidFire 异常"

msgid "Retype requires migration but is not allowed."
msgstr "转型需要迁移，但是不允许。"

#, python-format
msgid ""
"Running Cinder with a VMware vCenter version less than %s is not allowed."
msgstr "不允许运行 VMware vCenter 版本低于 %s 的 Cinder。"

msgid "SAN product is not configured."
msgstr "未配置 SAN 产品。"

msgid "SAN protocol is not configured."
msgstr "未配置 SAN 协议。"

#, python-format
msgid "SMBFS config file at %(config)s doesn't exist."
msgstr "%(config)s 处不存在 SMBFS 配置文件。"

msgid "SMBFS config file not set (smbfs_shares_config)."
msgstr "SMBFS 配置文件未设置 (smbfs_shares_config)。"

#, python-format
msgid "SSH Command failed after '%(total_attempts)r' attempts : '%(command)s'"
msgstr "SSH 命令在“%(total_attempts)r”之后失败，尝试次数：“%(command)s”"

#, python-format
msgid "SSH command injection detected: %(command)s"
msgstr "检测到 SSH 命令注入：%(command)s"

#, python-format
msgid "SSH connection failed for %(fabric)s with error: %(err)s"
msgstr "对于 %(fabric)s，SSH 连接失败，发生错误：%(err)s"

#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr "调度器主机过滤器 %(filter_name)s 没有找到。"

#, python-format
msgid "Scheduler Host Weigher %(weigher_name)s could not be found."
msgstr "找不到调度程序主机衡量器 %(weigher_name)s。"

#, python-format
msgid ""
"Secondary id can not be the same as primary array, backend_id = "
"%(secondary)s."
msgstr "辅助标识不能与主阵列相同，backend_id = %(secondary)s。"

#, python-format
msgid "Service %(service)s on host %(host)s removed."
msgstr "已移除主机 %(host)s 上的服务 %(service)s。"

#, python-format
msgid "Service %(service_id)s could not be found on host %(host)s."
msgstr "在主机 %(host)s 上找不到服务 %(service_id)s。"

#, python-format
msgid "Service %(service_id)s could not be found."
msgstr "服务 %(service_id)s 没有找到。"

msgid "Service is too old to fulfil this request."
msgstr "服务太旧，无法实现此请求。"

msgid "Service is unavailable at this time."
msgstr "该时刻服务无法使用。"

msgid "Set pair secondary access error."
msgstr "设置对辅助访问时出错。"

msgid "Sets thin provisioning."
msgstr "设置自动精简配置。"

#, python-format
msgid ""
"Share %s ignored due to invalid format. Must be of form address:/export. "
"Please check the nas_host and nas_share_path settings."
msgstr ""
"由于格式无效，已忽略共享项 %s。格式必须为 address:/export。请检查 nas_host "
"和 nas_share_path 设置。"

#, python-format
msgid "Sheepdog I/O Error, command was: \"%s\"."
msgstr "Sheepdog I/O 错误，命令为：\"%s\"。"

msgid ""
"Show operations can only be made to projects in the same hierarchy of the "
"project in which users are scoped to."
msgstr "只能对与用户作用域仅限于的项目位于同一层次结构中的项目执行显示操作。"

msgid "Size"
msgstr "配置"

#, python-format
msgid "Size for volume: %s not found, cannot secure delete."
msgstr "找不到卷 %s 的大小，无法进行安全删除。"

#, python-format
msgid ""
"Size of specified image %(image_size)sGB is larger than volume size "
"%(volume_size)sGB."
msgstr "所指定映像的大小 %(image_size)sGB 大于卷大小 %(volume_size)sGB。"

#, python-format
msgid ""
"Snapshot %(id)s has been asked to be deleted while waiting for it to become "
"available. Perhaps a concurrent request was made."
msgstr "在等待快照 %(id)s 变为可用时请求删除该快照。可能发出了并行请求。"

#, python-format
msgid ""
"Snapshot %(id)s was found in state %(state)s rather than 'deleting' during "
"cascade delete."
msgstr ""
"级联删除期间，发现快照 %(id)s 处于 %(state)s 状态而不是“deleting”状态。"

#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr "快照 %(snapshot_id)s 没有找到。"

#, python-format
msgid "Snapshot %(snapshot_id)s has no metadata with key %(metadata_key)s."
msgstr "快照 %(snapshot_id)s 没有任何具有键 %(metadata_key)s 的元数据。"

#, python-format
msgid "Snapshot %s must not be part of a group."
msgstr "快照 %s 不能属于某个组。"

#, python-format
msgid "Snapshot '%s' doesn't exist on array."
msgstr "快照“%s”在阵列上不存在。"

msgid "Snapshot already managed."
msgstr "快照已管理。"

msgid "Snapshot cannot be created while volume is migrating."
msgstr "无法在迁移卷时创建快照。"

msgid "Snapshot of secondary replica is not allowed."
msgstr "不允许获取辅助副本的快照。"

#, python-format
msgid "Snapshot of volume not supported in state: %s."
msgstr "不支持对处于以下状态的卷生成快照：%s。"

#, python-format
msgid "Snapshot res \"%s\" that is not deployed anywhere?"
msgstr "未在任何位置部署的快照资源“%s”？"

#, python-format
msgid "Snapshot status %(cur)s not allowed for update_snapshot_status"
msgstr "对于 update_snapshot_status，不允许快照状态 %(cur)s"

#, python-format
msgid ""
"Snapshot to be backed up must be available, but the current status is \"%s\"."
msgstr "要备份的快照必须可用，但当前状态为“%s”。"

msgid "SolidFire Cinder Driver exception"
msgstr "发生“SolidFire Cinder 驱动程序”异常"

msgid "Sort direction array size exceeds sort key array size."
msgstr "排序方向阵列大小超过排序键阵列大小。"

msgid ""
"Source CG cannot be empty or in 'creating' or 'updating' state. No "
"cgsnapshot will be created."
msgstr ""
"源CG不能为空，也不能是“creating”或“updating”状态。将不会创建cgsnapshot。"

msgid "Source Group is empty. No group will be created."
msgstr "源组为空。将不会创建任何组。"

msgid ""
"Source group cannot be empty or in 'creating' or 'updating' state. No group "
"snapshot will be created."
msgstr "源组不能为空，也不能是“creating”或“updating”状态。将不会创建组快照。"

msgid "Source host details not found."
msgstr "找不到源主机详细信息。"

msgid "Source volume device ID is required."
msgstr "需要源卷设备标识。"

msgid "Source volume not mid-migration."
msgstr "源卷未在迁移中。"

msgid "Specifies IP pool to use for volume"
msgstr "为使用卷指定IP池。"

msgid ""
"Specifies number of replicas for each volume. Can only be increased once "
"volume is created"
msgstr "为每一个卷指定副本的数量。一旦卷被创建，其副本数量只能被增加。"

msgid "Specify a password or private_key"
msgstr "请指定密码或 private_key"

msgid "Specify group type name, description or a combination thereof."
msgstr "在其中指定组类型的名称、描述或者两者的组合。"

msgid "Specify san_password or san_private_key"
msgstr "指定san_password或者san_private_key"

msgid ""
"Specify volume type name, description, is_public or a combination thereof."
msgstr "指定卷类型名称、描述、is_public 或它们的组合。"

msgid "Split pair error."
msgstr "拆分对时出错。"

msgid "Split replication failed."
msgstr "拆分复制失败。"

msgid "Start LUNcopy error."
msgstr "启动 LUNcopy 时发生错误。"

msgid "State"
msgstr "状态"

#, python-format
msgid "State of node is wrong. Current state is %s."
msgstr "节点的状态错误。当前状态为 %s。"

msgid "Status"
msgstr "状态"

msgid "Stop snapshot error."
msgstr "停止快照时发生错误。"

#, python-format
msgid "Storage family %s is not supported."
msgstr "不支持存储器系列 %s。"

msgid "Storage pool is not configured."
msgstr "未配置存储池。"

#, python-format
msgid "Storage profile: %(storage_profile)s not found."
msgstr "找不到存储器概要文件 %(storage_profile)s。"

#, python-format
msgid ""
"Successfully renamed %(num_vols)s volumes and %(num_cgs)s consistency groups "
"from cluster %(current)s to %(new)s"
msgstr ""
"成功重命名%(num_vols)s卷和 %(num_cgs)s一致性组从集群%(current)s到%(new)s"

#, python-format
msgid ""
"Sum of child usage '%(sum)s' is greater than free quota of '%(free)s' for "
"project '%(proj)s' for resource '%(res)s'. Please lower the limit or usage "
"for one or more of the following projects: '%(child_ids)s'"
msgstr ""
"子代使用率之和“%(sum)s”大于资源“%(res)s”的项目“%(proj)s”的可用配"
"额“%(free)s”。请降低以下一个或多个项目的限制或使用率“%(child_ids)s”"

msgid "Switch over pair error."
msgstr "切换对时出错。"

msgid "Sync pair error."
msgstr "同步对时出错。"

#, python-format
msgid "Synology driver authentication failed: %(reason)s."
msgstr "Synology驱动认证失败:%(reason)s。"

msgid "System does not support compression."
msgstr "系统不支持压缩。"

msgid "System is busy, retry operation."
msgstr "系统繁忙，请重试操作。"

msgid "Target group type is still in use."
msgstr "目标组类型仍在使用中。"

msgid "Target volume type is still in use."
msgstr "目标卷类型仍在使用中。"

msgid "Terminate connection failed"
msgstr "终止连接发生故障"

msgid "Terminate connection unable to connect to backend."
msgstr "终止连接无法连接至后端。"

#, python-format
msgid "Terminate volume connection failed: %(err)s"
msgstr "终止卷连接失败：%(err)s"

msgid ""
"The 'sort_key' and 'sort_dir' parameters are deprecated and cannot be used "
"with the 'sort' parameter."
msgstr ""
"“sort_key”和“sort_dir”参数已建议不要使用，并且不能与“sort”参数配合使用。"

#, python-format
msgid ""
"The GPFS filesystem %(fs)s is not at the required release level.  Current "
"level is %(cur)s, must be at least %(min)s."
msgstr ""
"GPFS 文件系统 %(fs)s 未处于所要求的发行版级别。当前级别为 %(cur)s，而要求的级"
"别必须至少为 %(min)s。"

#, python-format
msgid ""
"The WebDAV request failed. Reason: %(msg)s, Return code/reason: %(code)s, "
"Source Volume: %(src)s, Destination Volume: %(dst)s, Method: %(method)s."
msgstr ""
"WebDAV 请求失败。原因为 %(msg)s，返回码/原因码为 %(code)s，源卷为 %(src)s，目"
"标卷为 %(dst)s，方法为 %(method)s。"

msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using 'cinder-manage db sync' before running this "
"command."
msgstr ""
"上面的错误可能指示尚未创建数据库。\n"
"在运行此命令之前，请使用“cinder-manage db sync”来创建数据库。"

msgid "The copy should be primary or secondary"
msgstr "副本应为主副本或者辅助副本"

msgid "The decorated method must accept either a volume or a snapshot object"
msgstr "已装饰的方法必须接受卷或快照对象"

msgid "The decorated method must accept image_meta."
msgstr "已装饰的方法必须接受 image_meta。"

#, python-format
msgid "The device in the path %(path)s is unavailable: %(reason)s"
msgstr "路径%(path)s 指向的设备不可用：%(reason)s"

#, python-format
msgid "The end time (%(end)s) must be after the start time (%(start)s)."
msgstr "结束时间 (%(end)s) 必须在开始时间 (%(start)s) 之后。"

#, python-format
msgid "The failed-over volume could not be deleted: %s"
msgstr "无法删除已故障转移的卷：%s"

msgid ""
"The host is not ready to be failed back. Please resynchronize the volumes "
"and resume replication on the 3PAR backends."
msgstr "主机未准备好故障返回。请重新同步卷并在 3PAR 后端上继续进行复制。"

msgid ""
"The host is not ready to be failed back. Please resynchronize the volumes "
"and resume replication on the LeftHand backends."
msgstr "主机未准备好故障返回。请重新同步卷并在 LeftHand 后端上继续进行复制。"

msgid "The method update_migrated_volume is not implemented."
msgstr "未实现方法 update_migrated_volume。"

msgid "The name to use for storage instances created"
msgstr "存储实例使用的名称已创建。"

msgid "The name to use for volumes created"
msgstr "卷使用的名称已创建。"

msgid "The parent backup must be available for incremental backup."
msgstr "父备份必须可用于增量备份。"

#, python-format
msgid "The provided snapshot '%s' is not a snapshot of the provided volume."
msgstr "所提供快照“%s”并非所提供卷的快照。"

#, python-format
msgid "The remote retention count must be %s or less."
msgstr "远程保留计数不得高于 %s。"

msgid ""
"The replication mode was not configured correctly in the volume type "
"extra_specs. If replication:mode is periodic, replication:sync_period must "
"also be specified and be between 300 and 31622400 seconds."
msgstr ""
"未在卷类型 extra_specs 中正确配置复制方式。如果 replication:mode 为 "
"periodic，那么必须同时指定 replication:sync_period 并且周期必须介于 300 秒到 "
"31622400 秒之间。"

#, python-format
msgid "The replication sync period must be at least %s seconds."
msgstr "同步复制周期必须至少为 %s 秒。"

msgid "The results are invalid."
msgstr "结果无效。"

#, python-format
msgid "The retention count must be %s or less."
msgstr "保留计数不得高于 %s。"

msgid "The snapshot cannot be created when the volume is in error status."
msgstr "当卷处于错误状态时，无法创建快照。"

msgid "The snapshot cannot be created when the volume is in maintenance mode."
msgstr "当卷处于维护方式时，无法创建快照。"

#, python-format
msgid "The snapshot is unavailable: %(data)s"
msgstr "快照不可用:%(data)s"

msgid "The source volume for this WebDAV operation not found."
msgstr "找不到此 WebDAV 操作的源卷。"

#, python-format
msgid ""
"The source volume type '%(src)s' is different than the destination volume "
"type '%(dest)s'."
msgstr "原卷类型'%(src)s'与目标卷'%(dest)s'不一致。"

#, python-format
msgid "The source volume type '%s' is not available."
msgstr "原卷类型'%s'不可用。"

#, python-format
msgid "The specified LUN does not belong to the given pool: %s."
msgstr "指定的 LUN 不属于给定池：%s。"

msgid "The specified vdisk is mapped to a host."
msgstr "指定的 vdisk 已映射到主机。"

#, python-format
msgid ""
"The storage device does not support %(prot)s. Please configure the device to "
"support %(prot)s or switch to a driver using a different protocol."
msgstr ""
"存储器设备不支持 %(prot)s。请配置该设备以支持 %(prot)s 或切换至使用另一协议的"
"驱动程序。"

#, python-format
msgid ""
"The type of metadata: %(metadata_type)s for volume/snapshot %(id)s is "
"invalid."
msgstr "卷/快照 %(id)s 的元数据类型 %(metadata_type)s无效。"

msgid "The volume cannot accept transfer in maintenance mode."
msgstr "在维护方式下卷无法接受传输。"

msgid "The volume cannot be attached in maintenance mode."
msgstr "在维护方式下无法连接卷。"

msgid "The volume cannot be detached in maintenance mode."
msgstr "在维护方式下无法拆离卷。"

msgid "The volume cannot be updated during maintenance."
msgstr "维护期间无法更新卷。"

msgid "The volume connection cannot be initialized in maintenance mode."
msgstr "在维护方式下无法初始化卷连接。"

msgid "The volume driver requires the iSCSI initiator name in the connector."
msgstr "卷驱动程序在连接器中需要 iSCSI 发起方名称。"

msgid ""
"The volume is currently busy on the 3PAR and cannot be deleted at this time. "
"You can try again later."
msgstr "该卷当前在 3PAR 上繁忙，此时无法删除。可稍后重试。"

msgid "There are no valid ESX hosts."
msgstr "不存在有效的 ESX 主机。"

msgid "There are no valid datastores."
msgstr "不存在任何有效数据存储器。"

msgid "There is no metadata in DB object."
msgstr "数据库对象中没有元数据。"

#, python-format
msgid "There is no share which can host %(volume_size)sG"
msgstr "不存在任何可主管 %(volume_size)sG 的共享项"

#, python-format
msgid "There is no share which can host %(volume_size)sG."
msgstr "不存在任何可托管 %(volume_size)sG 的共享项。"

msgid "There is no virtual disk device."
msgstr "不存在任何虚拟盘设备。"

#, python-format
msgid "There was an error adding the volume to the remote copy group: %s."
msgstr "将该卷添加至远程复制组时发生了错误：%s。"

#, python-format
msgid "There was an error creating the cgsnapshot: %s"
msgstr "创建 cgsnapshot 时发生错误：%s"

#, python-format
msgid "There was an error creating the remote copy group: %s."
msgstr "创建远程复制组时发生了错误：%s。"

#, python-format
msgid ""
"There was an error setting the sync period for the remote copy group: %s."
msgstr "为远程复制组设置同步周期时发生了错误：%s。"

#, python-format
msgid ""
"There was an error setting up a remote copy group on the 3PAR arrays: "
"('%s'). The volume will not be recognized as replication type."
msgstr ""
"在 3PAR 阵列上设置远程复制组时发生了错误：（“%s”）。该卷未被识别为复制类型。"

#, python-format
msgid ""
"There was an error setting up a remote schedule on the LeftHand arrays: "
"('%s'). The volume will not be recognized as replication type."
msgstr ""
"在 LeftHand 阵列上设置远程调度时发生了错误：（“%s”）。该卷未被识别为复制类"
"型。"

#, python-format
msgid "There was an error starting remote copy: %s."
msgstr "启动远程复制时发生了错误：%s。"

#, python-format
msgid "There's no NFS config file configured (%s)"
msgstr "未配置 NFS 配置文件 (%s)"

#, python-format
msgid ""
"There's no Quobyte volume configured (%s). Example: quobyte://<DIR host>/"
"<volume name>"
msgstr "未配置 Quobyte 卷 (%s)。示例：quobyte://<DIR host>/<volume name>"

msgid "Thin provisioning not supported on this version of LVM."
msgstr "在此版本的 LVM 上，不支持瘦供应。"

msgid "This request was rate-limited."
msgstr "这个请求受到频率限制。"

#, python-format
msgid ""
"This system platform (%s) is not supported. This driver supports only Win32 "
"platforms."
msgstr "此系统平台 (%s) 不受支持。此驱动程序仅支持 Win32 平台。"

#, python-format
msgid "Timed out while waiting for Nova update for creation of snapshot %s."
msgstr "等待 Nova 更新（以便创建快照 %s）时超时。"

#, python-format
msgid ""
"Timed out while waiting for Nova update for deletion of snapshot %(id)s."
msgstr "等待 Nova 更新（以便删除快照 %(id)s）时超时。"

#, python-format
msgid "Timeout while requesting %(service)s API."
msgstr "请求 %(service)s API 时超时。"

#, python-format
msgid "Timeout while requesting capabilities from backend %(service)s."
msgstr "从后端请求 %(service)s 功能时超时。"

#, python-format
msgid "Transfer %(transfer_id)s could not be found."
msgstr "无法找到转换器%(transfer_id)s"

#, python-format
msgid ""
"Trying to import backup metadata from id %(meta_id)s into backup %(id)s."
msgstr "正在尝试将备份元数据从标识 %(meta_id)s 导入到备份 %(id)s。"

#, python-format
msgid ""
"Tune volume task stopped before it was done: volume_name=%(volume_name)s, "
"task-status=%(status)s."
msgstr ""
"调整卷任务未完成就已停止：volume_name=%(volume_name)s， task-status="
"%(status)s。"

#, python-format
msgid ""
"Type %(type_id)s is already associated with another qos specs: "
"%(qos_specs_id)s"
msgstr "已使类型 %(type_id)s 与另一 qos 规范 %(qos_specs_id)s 关联"

msgid "Type access modification is not applicable to public group type."
msgstr "类型访问修改不适用于公共组类型。"

msgid "Type access modification is not applicable to public volume type."
msgstr "类型访问修改不适用于公共卷类型。"

msgid "Type cannot be converted into NaElement."
msgstr "此类型不能转换为 NaElement。"

#, python-format
msgid "TypeError: %s"
msgstr "TypeError：%s"

#, python-format
msgid "UUIDs %s are in both add and remove volume list."
msgstr "UUID %s 同时位于“添加卷”和“移除卷”列表中。"

msgid "Unable to access the backend storage via file handle."
msgstr "通过文件句柄无法访问后端存储器。"

#, python-format
msgid "Unable to access the backend storage via the path %(path)s."
msgstr "无法通过路径 %(path)s 访问后端存储器。"

#, python-format
msgid "Unable to complete failover of %s."
msgstr "无法完成 %s 的故障转移。"

msgid "Unable to connect or find connection to host"
msgstr "无法连接至主机，或找不到与主机的连接"

msgid "Unable to create lock. Coordination backend not started."
msgstr "无法创建锁定。协调后端未启动。"

#, python-format
msgid "Unable to create server object for initiator %(name)s"
msgstr "无法为发起者 %(name)s 创建服务器对象"

#, python-format
msgid "Unable to create volume %(name)s from %(snap)s."
msgstr "无法通过 %(snap)s 创建卷 %(name)s。"

#, python-format
msgid "Unable to create volume %(name)s from %(vol)s."
msgstr "无法通过 %(vol)s 创建卷 %(name)s。"

#, python-format
msgid "Unable to create volume %s"
msgstr "无法创建卷 %s"

msgid "Unable to create volume. Backend down."
msgstr "无法创建卷。后端已关闭。"

#, python-format
msgid "Unable to delete snapshot %(id)s, status: %(status)s."
msgstr "无法删除快照 %(id)s，状态：%(status)s。"

msgid ""
"Unable to detach volume. Volume status must be 'in-use' and attach_status "
"must be 'attached' to detach."
msgstr ""
"无法拆离卷。卷状态必须为“in-use”，并且 attach_status 必须为“attached”才能拆"
"离。"

#, python-format
msgid ""
"Unable to determine secondary_array from supplied secondary: %(secondary)s."
msgstr "无法根据所提供辅助项来确定 secondary_array：%(secondary)s。"

#, python-format
msgid "Unable to determine snapshot name in Purity for snapshot %(id)s."
msgstr "在快照 %(id)s 的 Purity 中无法确定快照名称。"

msgid "Unable to determine system id."
msgstr "无法确定系统标识。"

msgid "Unable to determine system name."
msgstr "无法确定系统名称。"

#, python-format
msgid ""
"Unable to do manage snapshot operations with Purity REST API version "
"%(api_version)s, requires %(required_versions)s."
msgstr ""
"无法对 Purity REST API 版本%(api_version)s 执行“管理快照”操作，需要版本 "
"%(required_versions)s。"

#, python-format
msgid ""
"Unable to do replication with Purity REST API version %(api_version)s, "
"requires one of %(required_versions)s."
msgstr ""
"无法使用 Purity REST API 版本 %(api_version)s 执行复制，需要 "
"%(required_versions)s 的其中之一。"

#, python-format
msgid "Unable to establish the partnership with the Storwize cluster %s."
msgstr "无法建立与 Storwize 集群 %s 的伙伴关系。"

#, python-format
msgid "Unable to extend volume %s"
msgstr "无法扩展卷 %s"

msgid ""
"Unable to failback to \"default\", this can only be done after a failover "
"has completed."
msgstr "无法故障返回至“default”，此操作只能在故障转换完成后进行。"

msgid "Unable to fetch connection information from backend."
msgstr "无法从后端访存连接信息。"

#, python-format
msgid "Unable to fetch connection information from backend: %(err)s"
msgstr "无法从后端访存连接信息：%(err)s"

#, python-format
msgid "Unable to find Purity ref with name=%s"
msgstr "找不到名称为 %s 的 Purity ref"

#, python-format
msgid "Unable to find Volume Group: %(vg_name)s"
msgstr "找不到卷组: %(vg_name)s"

msgid "Unable to find any active VPSA controller"
msgstr "无法找到任何活跃的VPSA控制器。"

msgid "Unable to find failover target, no secondary targets configured."
msgstr "找不到故障转移目标，未配置辅助目标。"

msgid "Unable to find iSCSI mappings."
msgstr "找不到 iSCSI 映射。"

#, python-format
msgid "Unable to find server object for initiator %(name)s"
msgstr "无法找到发起者为 %(name)s 的服务器对象。"

#, python-format
msgid "Unable to find ssh_hosts_key_file: %s"
msgstr "找不到 ssh_hosts_key_file：%s"

#, python-format
msgid "Unable to find volume %s"
msgstr "找不到卷 %s"

#, python-format
msgid "Unable to get a block device for file '%s'"
msgstr "无法获取对应文件“%s”的块设备"

#, python-format
msgid ""
"Unable to get configuration information necessary to create a volume: "
"%(errorMessage)s."
msgstr "无法获取创建卷所需要的配置信息：%(errorMessage)s。"

#, python-format
msgid "Unable to get stats for backend_name: %s"
msgstr "无法获取 backend_name %s 的统计信息"

#, python-format
msgid "Unable to locate account %(account_name)s on Solidfire device"
msgstr "无法在 Solidfire 设备上找到帐户 %(account_name)s"

#, python-format
msgid "Unable to locate an SVM that is managing the IP address '%s'"
msgstr "无法找到正在管理 IP 地址“%s”的 SVM"

#, python-format
msgid "Unable to locate specified replay profiles %s "
msgstr "找不到指定重放概要文件 %s "

#, python-format
msgid ""
"Unable to manage existing volume. Volume %(volume_ref)s already managed."
msgstr "无法管理现有卷。已管理卷 %(volume_ref)s。"

#, python-format
msgid "Unable to manage volume %s"
msgstr "无法管理卷 %s"

msgid "Unable to map volume"
msgstr "无法映射卷"

msgid "Unable to map volume."
msgstr "无法映射卷。"

msgid "Unable to parse attributes."
msgstr "无法解析属性。"

msgid ""
"Unable to re-use a host that is not managed by Cinder with "
"use_chap_auth=True,"
msgstr "无法在 use_chap_auth=True 的情况下复用并非由 Cinder 管理的主机，"

msgid "Unable to re-use host with unknown CHAP credentials configured."
msgstr "无法在配置了未知 CHAP 凭证的情况下复用主机。"

#, python-format
msgid "Unable to rename volume %(existing)s to %(newname)s"
msgstr "无法将卷 %(existing)s 重命名为 %(newname)s"

#, python-format
msgid ""
"Unable to retype %(specname)s, expected to receive current and requested "
"%(spectype)s values. Value received: %(spec)s"
msgstr ""
"无法对 %(specname)s 进行转型，需要接收当前的和请求的 %(spectype)s 值。接收到"
"的值：%(spec)s"

#, python-format
msgid ""
"Unable to retype:  A copy of volume %s exists. Retyping would exceed the "
"limit of 2 copies."
msgstr ""
"无法执行 retype：卷 %s 的副本已存在。执行 retype 将超过2 个副本的限制。"

#, python-format
msgid ""
"Unable to retype: Current action needs volume-copy, it is not allowed when "
"new type is replication. Volume = %s"
msgstr "无法转型：当前操作需要卷拷贝，当新类型为复制时，不允许卷拷贝。卷为 %s"

#, python-format
msgid ""
"Unable to set up mirror mode replication for %(vol)s. Exception: %(err)s."
msgstr "无法对 %(vol)s 设置镜像方式复制。异常：%(err)s。"

msgid "Unable to terminate volume connection from backend."
msgstr "无法从后端终止卷连接。"

#, python-format
msgid "Unable to terminate volume connection: %(err)s"
msgstr "无法终止卷连接：%(err)s"

msgid "Unacceptable parameters."
msgstr "无法接受的参数。"

#, python-format
msgid ""
"Unexecpted mapping status %(status)s for mapping %(id)s. Attributes: "
"%(attr)s."
msgstr "映射 %(id)s 的意外映射状态 %(status)s。属性：%(attr)s。"

#, python-format
msgid ""
"Unexpected CLI response: header/row mismatch. header: %(header)s, row: "
"%(row)s."
msgstr "出现意外 CLI 响应：头/行不匹配。头：%(header)s，行：%(row)s。"

#, python-format
msgid "Unexpected output. Expected [%(expected)s] but received [%(output)s]"
msgstr "意外输出。需要 [%(expected)s]，但接收到 [%(output)s]"

#, python-format
msgid "Unexpected over quota on %(name)s."
msgstr "%(name)s 超过预期配额。"

msgid "Unexpected response from Nimble API"
msgstr "来自 Nimble API 的意外响应"

msgid "Unexpected status code"
msgstr "意外的状态码"

#, python-format
msgid ""
"Unexpected status code from the switch %(switch_id)s with protocol "
"%(protocol)s for url %(page)s. Error: %(error)s"
msgstr ""
"对于 url %(page)s，带有协议 %(protocol)s 的交换机 %(switch_id)s 发出意外状态"
"码。错误：%(error)s"

msgid "Unknown NFS exception"
msgstr "NFS 异常未知"

msgid "Unknown RemoteFS exception"
msgstr "RemoteFS 异常未知"

msgid "Unknown SMBFS exception."
msgstr "SMBFS 异常未知。"

msgid "Unknown Virtuozzo Storage exception"
msgstr "未知 Virtuozzo 存储器异常"

msgid "Unknown action"
msgstr "操作未知"

#, python-format
msgid ""
"Unknown if the volume: %s to be managed is already being managed by Cinder. "
"Aborting manage volume. Please add 'cinder_managed' custom schema property "
"to the volume and set its value to False. Alternatively, Set the value of "
"cinder config policy 'zfssa_manage_policy' to 'loose' to remove this "
"restriction."
msgstr ""
"不知道要管理的卷 %s 是否已由 Cinder 管理。正在异常中止管理卷。请"
"将“cinder_managed”定制模式属性添加至该卷，并将其值设置为 False。或者，将 "
"Cinder 配置策略“zfssa_manage_policy”的值设置为“loose”以移除此限制。"

#, python-format
msgid ""
"Unknown if the volume: %s to be managed is already being managed by Cinder. "
"Aborting manage volume. Please add 'cinder_managed' custom schema property "
"to the volume and set its value to False. Alternatively, set the value of "
"cinder config policy 'zfssa_manage_policy' to 'loose' to remove this "
"restriction."
msgstr ""
"不知道要管理的卷 %s 是否已由 Cinder 管理。正在异常中止管理卷。请"
"将“cinder_managed”定制模式属性添加至该卷，并将其值设置为 False。或者，将 "
"Cinder 配置策略“zfssa_manage_policy”的值设置为“loose”以移除此限制。"

#, python-format
msgid "Unknown or unsupported command %(cmd)s"
msgstr "命令 %(cmd)s 未知或不受支持"

#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr "配额资源 %(unknown)s 未知。"

msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "排序方向未知，必须为“降序”或“升序”"

msgid "Unknown sort direction, must be 'desc' or 'asc'."
msgstr "排序方向未知，必须为“降序”或“升序”。"

msgid "Unmanage and cascade delete options are mutually exclusive."
msgstr "非管理选项与级联删除选项互斥。"

msgid "Unmanage volume not implemented."
msgstr "未实现非管理卷。"

msgid "Unmanaging of snapshots from 'failed-over' volumes is not allowed."
msgstr "不允许取消管理来自“已故障转移”的卷的快照。"

msgid "Unmanaging of snapshots from failed-over volumes is not allowed."
msgstr "不允许取消管理来自已故障转移的卷的快照。"

#, python-format
msgid "Unrecognized QOS keyword: \"%s\""
msgstr "不识别 QOS 关键字：“%s”"

#, python-format
msgid "Unrecognized backing format: %s"
msgstr "无法识别支持格式：%s"

#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr "无法识别的 read_deleted 取值”%s“"

msgid "Unsupported Content-Type"
msgstr "不支持的Content-Type"

#, python-format
msgid "Unsupported backup metadata version (%s)"
msgstr "不支持备份元数据版本 (%s)"

msgid "Unsupported backup metadata version requested"
msgstr "不支持请求的备份元数据版本"

msgid "Unsupported backup verify driver"
msgstr "不支持备份验证驱动程序"

#, python-format
msgid ""
"Unsupported firmware on switch %s. Make sure switch is running firmware v6.4 "
"or higher"
msgstr ""
"在交换机 %s 上存在不受支持的固件。请确保交换机正在运行固件 V6.4 或更高版本"

#, python-format
msgid "Unsupported volume format %s"
msgstr "不支持的卷格式：%s"

#, python-format
msgid "Unsupported volume format: %s "
msgstr "以下卷格式不受支持：%s "

msgid "Update QoS policy error."
msgstr "更新 QoS 策略时发生错误。"

msgid ""
"Update and delete quota operations can only be made by an admin of immediate "
"parent or by the CLOUD admin."
msgstr "只能由直系父代的管理员或者云管理员执行更新和删除配额操作。"

msgid ""
"Update and delete quota operations can only be made to projects in the same "
"hierarchy of the project in which users are scoped to."
msgstr ""
"只能对与用户作用域仅限于的项目位于同一层次结构中的项目执行更新和删除配额操"
"作。"

msgid "Updated At"
msgstr "已更新于"

#, python-format
msgid "Updating volume metadata is not allowed for volumes in %s status."
msgstr "当卷状态为 %s 时，不允许更新该卷的元数据。"

msgid "Upload to glance of attached volume is not supported."
msgstr "不支持上载至所连接卷的 Glance。"

msgid "Use ALUA to associate initiator to host error."
msgstr "使用 ALUA 使启动程序与主机相关联时发生错误。"

msgid ""
"Use CHAP to associate initiator to host error. Please check the CHAP "
"username and password."
msgstr "使用 CHAP 使启动程序与主机相关联时发生错误。请检查 CHAP 用户名和密码。"

msgid "User ID"
msgstr "用户ID"

msgid "User does not have admin privileges"
msgstr "用户没有管理员权限"

msgid "User not authorized to perform WebDAV operations."
msgstr "用户无权执行 WebDAV 操作。"

msgid "UserName is not configured."
msgstr "未配置 UserName。"

msgid "UserPassword is not configured."
msgstr "未配置 UserPassword。"

msgid "VF is not enabled."
msgstr "未启用 VF。"

#, python-format
msgid "VV Set %s does not exist."
msgstr "VV 集 %s 不存在。"

#, python-format
msgid "Valid consumer of QoS specs are: %s"
msgstr "以下是 QoS 规范的有效使用者：%s"

#, python-format
msgid "Validate volume connection failed (error: %(err)s)."
msgstr "验证卷连接失败（错误：%(err)s）。"

#, python-format
msgid ""
"Value \"%(value)s\" is not valid for configuration option \"%(option)s\""
msgstr "值“%(value)s”对于配置选项“%(option)s”无效"

#, python-format
msgid "ValueError: %s"
msgstr "ValueError：%s"

#, python-format
msgid "Vdisk %(name)s not involved in mapping %(src)s -> %(tgt)s."
msgstr "从 %(src)s 到 %(tgt)s 的映射中未涉及到 Vdisk %(name)s。"

#, python-format
msgid ""
"Version %(req_ver)s is not supported by the API. Minimum is %(min_ver)s and "
"maximum is %(max_ver)s."
msgstr ""
"此 API 不支持版本 %(req_ver)s。最低版本为 %(min_ver)s，最高版本为 "
"%(max_ver)s。"

#, python-format
msgid "VersionedObject %s cannot retrieve object by id."
msgstr "VersionedObject %s 无法按标识检索对象。"

#, python-format
msgid "VersionedObject %s does not support conditional update."
msgstr "VersionedObject %s 不支持带条件更新。"

#, python-format
msgid "Virtual volume '%s' doesn't exist on array."
msgstr "虚拟卷“%s”在阵列上不存在。"

#, python-format
msgid "Volume %(deviceID)s not found."
msgstr "找不到卷 %(deviceID)s。"

#, python-format
msgid "Volume %(name)s could not be found. It might be already deleted"
msgstr "找不到卷 %(name)s。该卷可能已被删除"

#, python-format
msgid "Volume %(name)s not found"
msgstr "找不到卷 %(name)s"

#, python-format
msgid "Volume %(name)s was created in VNX, but in %(state)s state."
msgstr "在 VNX 中创建了卷 %(name)s，但此卷处于 %(state)s 状态。"

#, python-format
msgid "Volume %(name)s was not deactivated in time."
msgstr "卷 %(name)s 没有被及时释放。"

#, python-format
msgid "Volume %(vol)s could not be created in pool %(pool)s."
msgstr "未能在池 %(pool)s 中创建卷 %(vol)s。"

#, python-format
msgid "Volume %(vol1)s does not match with snapshot.volume_id %(vol2)s."
msgstr "卷 %(vol1)s 与 snapshot.volume_id %(vol2)s 不匹配。"

#, python-format
msgid "Volume %(vol_id)s status must be %(statuses)s"
msgstr "卷 %(vol_id)s 的状态必须为 %(statuses)s"

#, python-format
msgid ""
"Volume %(vol_id)s status must be available to update readonly flag, but "
"current status is: %(vol_status)s."
msgstr ""
"卷 %(vol_id)s 状态必须为“可用”，才能更新只读标记，但当前状态为："
"%(vol_status)s。"

#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr "卷 %(volume_id)s 没有找到。"

#, python-format
msgid ""
"Volume %(volume_id)s has no administration metadata with key "
"%(metadata_key)s."
msgstr "卷 %(volume_id)s 没有任何具有键 %(metadata_key)s 的元数据。"

#, python-format
msgid "Volume %(volume_id)s has no metadata with key %(metadata_key)s."
msgstr "卷 %(volume_id)s 没有含键 %(metadata_key)s 的元数据。"

#, python-format
msgid "Volume %(volume_id)s is still attached, detach volume first."
msgstr "卷 %(volume_id)s 仍然处于连接状态，请先从卷断开连接。"

#, python-format
msgid "Volume %(volume_id)s replication error: %(reason)s"
msgstr "卷 %(volume_id)s 复制错误：%(reason)s"

#, python-format
msgid "Volume %s could not be created from source volume."
msgstr "未能从源卷创建卷 %s。"

#, python-format
msgid "Volume %s could not be created on shares."
msgstr "在共享项上，未能创建卷 %s。"

#, python-format
msgid "Volume %s could not be created."
msgstr "未能创建卷 %s。"

#, python-format
msgid "Volume %s does not exist in Nexenta SA"
msgstr "卷 %s 在 Nexenta SA 中不存在"

#, python-format
msgid "Volume %s does not exist in Nexenta Store appliance"
msgstr "卷 %s 在 Nexenta 存储设备中不存在"

#, python-format
msgid "Volume %s does not exist on the array."
msgstr "卷 %s 在阵列上不存在。"

#, python-format
msgid "Volume %s does not have provider_location specified, skipping."
msgstr "卷 %s 没有指定 provider_location，正在跳过。"

#, python-format
msgid "Volume %s doesn't exist on array."
msgstr "卷 %s 在阵列上不存在。"

#, python-format
msgid "Volume %s doesn't exist on the ZFSSA backend."
msgstr "卷 %s 在 ZFSSA 后端上不存在。"

#, python-format
msgid ""
"Volume %s is online. Set volume to offline for managing using OpenStack."
msgstr "卷 %s 已联机。将该卷设置为脱机以便使用 OpenStack 进行管理。"

#, python-format
msgid "Volume %s must not be part of a consistency group."
msgstr "卷 %s 不得是一致性组的一部分。"

#, python-format
msgid "Volume %s not found."
msgstr "找不到卷 %s。"

#, python-format
msgid "Volume %s: Error trying to extend volume"
msgstr "卷 %s：尝试扩展卷时出错"

#, python-format
msgid "Volume (%s) already exists on array"
msgstr "数组中已存在卷 (%s)"

#, python-format
msgid "Volume (%s) already exists on array."
msgstr "阵列上已存在卷 (%s)。"

#, python-format
msgid "Volume Group %s does not exist"
msgstr "卷组 %s 不存在"

#, python-format
msgid "Volume Type %(id)s already exists."
msgstr "卷类型 %(id)s 已存在。"

#, python-format
msgid ""
"Volume Type %(volume_type_id)s deletion is not allowed with volumes present "
"with the type."
msgstr "当存在类型为 %(volume_type_id)s 的卷时，不允许删除该卷类型。"

#, python-format
msgid ""
"Volume Type %(volume_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr "卷类型 %(volume_type_id)s 没有额外说明键 %(extra_specs_key)s 。"

msgid "Volume Type id must not be None."
msgstr "卷类型不能为空。"

msgid "Volume already managed."
msgstr "卷已管理。"

msgid "Volume by this name already exists"
msgstr "使用此名称的卷已存在"

msgid "Volume create failed while extracting volume ref."
msgstr "抽取卷引用时创建卷失败。"

#, python-format
msgid "Volume device file path %s does not exist."
msgstr "卷设备文件路径 %s 不存在。"

#, python-format
msgid "Volume device not found at %(device)s."
msgstr "在 %(device)s 上找不到卷设备。"

#, python-format
msgid "Volume driver %s not initialized."
msgstr "卷驱动程序 %s 未初始化。"

msgid "Volume driver not ready."
msgstr "卷驱动未准备好。"

#, python-format
msgid "Volume driver reported an error: %(message)s"
msgstr "卷驱动程序已报告错误：%(message)s"

msgid "Volume has a temporary snapshot that can't be deleted at this time."
msgstr "卷具有此时不能删除的临时快照。"

msgid "Volume has children and cannot be deleted!"
msgstr "卷具有子代，不能删除！"

#, python-format
msgid "Volume in group %s is attached. Need to detach first."
msgstr "已连接组 %s 中的卷。需要先拆离。"

msgid "Volume in group still has dependent snapshots."
msgstr "组中的卷仍然具有从属快照。"

#, python-format
msgid "Volume is attached to a server.  (%s)"
msgstr "卷已连接至服务器。(%s)"

msgid "Volume is in-use."
msgstr "卷在使用中。"

msgid "Volume is not available."
msgstr "卷不可用。"

msgid "Volume is not local to this node."
msgstr "该卷不是此节点的本地卷。"

msgid "Volume manage failed."
msgstr "管理卷失败。"

msgid ""
"Volume metadata backup requested but this driver does not yet support this "
"feature."
msgstr "已请求卷元数据备份，但此驱动程序尚不支持此功能。"

#, python-format
msgid "Volume migration failed: %(reason)s"
msgstr "卷迁移失败：%(reason)s"

msgid "Volume must be in the same availability zone as the snapshot"
msgstr "卷必须与快照位于同一可用性区域中"

msgid "Volume must be in the same availability zone as the source volume"
msgstr "卷必须与源卷位于同一可用性区域中"

msgid "Volume must have a volume type"
msgstr "卷必须具有卷类型"

msgid "Volume must not be replicated."
msgstr "不得复制卷。"

msgid "Volume must not have snapshots."
msgstr "卷不能具有快照。"

#, python-format
msgid "Volume not found for instance %(instance_id)s."
msgstr "没有为实例 %(instance_id)s 找到卷。"

msgid "Volume not found on configured storage backend."
msgstr "在已配置的存储器后端上找不到卷。"

msgid "Volume not found."
msgstr "找不到卷。"

msgid "Volume not unique."
msgstr "卷并非唯一。"

msgid "Volume not yet assigned to host."
msgstr "卷尚未分配给主机。"

msgid "Volume reference must contain source-name element."
msgstr "卷引用必须包含 source-name 元素。"

#, python-format
msgid "Volume replication for %(volume_id)s could not be found."
msgstr "找不到 %(volume_id)s 的卷复制。"

msgid "Volume should have agent-type set as None."
msgstr "卷应该将 agent-type 设置为“无”。"

#, python-format
msgid ""
"Volume size %(volume_size)sGB cannot be smaller than the image minDisk size "
"%(min_disk)sGB."
msgstr "卷大小 %(volume_size)sGB 不能小于映像 minDisk 大小 %(min_disk)sGB。"

#, python-format
msgid "Volume size '%(size)s' must be an integer and greater than 0"
msgstr "卷大小“%(size)s”必须为正整数"

#, python-format
msgid ""
"Volume size '%(size)s'GB cannot be smaller than original volume size  "
"%(source_size)sGB. They must be >= original volume size."
msgstr ""
"卷大小“%(size)s”GB 不能小于原始卷大小 %(source_size)sGB。它们必须不小于原始卷"
"大小。"

#, python-format
msgid ""
"Volume size '%(size)s'GB cannot be smaller than the snapshot size "
"%(snap_size)sGB. They must be >= original snapshot size."
msgstr ""
"卷大小“%(size)s”GB 不能小于快照大小 %(snap_size)sGB。它们必须不小于原始快照大"
"小。"

msgid "Volume size increased since the last backup. Do a full backup."
msgstr "自从最近一次备份以来，卷大小已增加。请执行完全备份。"

msgid "Volume size must be a multiple of 1 GB."
msgstr "卷大小必须为 1 GB 的倍数。"

msgid "Volume size must multiple of 1 GB."
msgstr "卷大小必须是 1 GB 的倍数。"

msgid "Volume status must be 'available'."
msgstr "卷状态必须为“可用”。"

#, python-format
msgid "Volume status must be available for snapshot %(id)s. (is %(status)s)"
msgstr "对于快照 %(id)s，卷状态必须为“available”。（卷状态现在为 %(status)s）"

msgid "Volume to Initiator Group mapping already exists"
msgstr "卷至发起方组的映射已存在"

#, python-format
msgid ""
"Volume to be backed up must be available or in-use, but the current status "
"is \"%s\"."
msgstr "要备份的卷必须可用或者正在使用，但是当前状态为“%s”。"

msgid "Volume to be restored to must be available"
msgstr "要复原至的卷必须可用"

#, python-format
msgid "Volume type %(volume_type_id)s could not be found."
msgstr "卷类型 %(volume_type_id)s 没有找到。"

#, python-format
msgid "Volume type ID '%s' is invalid."
msgstr "卷类型标识“%s”无效。"

#, python-format
msgid ""
"Volume type access for %(volume_type_id)s / %(project_id)s combination "
"already exists."
msgstr "已存在针对 %(volume_type_id)s / %(project_id)s 组合的卷类型访问权限。"

#, python-format
msgid ""
"Volume type access not found for %(volume_type_id)s / %(project_id)s "
"combination."
msgstr "对于 %(volume_type_id)s / %(project_id)s 组合，找不到卷类型访问权限。"

#, python-format
msgid "Volume type encryption for type %(type_id)s already exists."
msgstr "类型 %(type_id)s 的卷类型加密已存在。"

#, python-format
msgid "Volume type encryption for type %(type_id)s does not exist."
msgstr "类型 %(type_id)s 的卷类型加密不存在。"

msgid "Volume type name can not be empty."
msgstr "卷类型名称不能为 空."

#, python-format
msgid "Volume type with name %(volume_type_name)s could not be found."
msgstr "名为 %(volume_type_name)s 的卷类型没有找到。"

#, python-format
msgid "Volume: %s is already being managed by Cinder."
msgstr "卷 %s 已由 Cinder 管理。"

msgid ""
"Volumes/account exceeded on both primary and secondary SolidFire accounts."
msgstr "卷/帐户同时超出主 SolidFire 帐户和辅助 SolidFire 帐户的限制。"

#, python-format
msgid ""
"VzStorage config 'vzstorage_used_ratio' invalid. Must be > 0 and <= 1.0: %s."
msgstr ""
"VzStorage 配置“vzstorage_used_ratio”无效。必须大于 0 并且小于或等于 1.0：%s。"

#, python-format
msgid "VzStorage config file at %(config)s doesn't exist."
msgstr "%(config)s 处不存在 VzStorage 配置文件。"

#, python-format
msgid "Wait synchronize failed. Running status: %s."
msgstr "等待同步失败。运行状态：%s。"

msgid ""
"Waiting for all nodes to join cluster. Ensure all sheep daemons are running."
msgstr "正在等待所有节点加入集群。请确保所有 sheep 守护程序都在运行。"

msgid "We should not do switch over on primary array."
msgstr "不应在主阵列上切换。"

#, python-format
msgid "Worker for %(type)s %(id)s already exists."
msgstr "标识为%(type)s %(id)s的生产者已经存在。"

#, python-format
msgid "Worker with %s could not be found."
msgstr "无法找到标识为 %s 的生产者。"

msgid "XtremIO not configured correctly, no iscsi portals found"
msgstr "未正确配置 XtremIO，找不到任何 iSCSI 门户网站"

msgid "XtremIO not initialized correctly, no clusters found"
msgstr "XtremIO 未正确初始化，找不到任何集群"

msgid "You must implement __call__"
msgstr "你必须执行 __call__"

msgid ""
"You must install hpe3parclient before using 3PAR drivers. Run \"pip install "
"python-3parclient\" to install the hpe3parclient."
msgstr ""
"使用 3PAR 驱动程序之前，必须安装 hpe3parclient。运行“pip install "
"python-3parclient”以安装 hpe3parclient。"

#, python-format
msgid "ZeroDivisionError: %s"
msgstr "ZeroDivisionError：%s"

msgid "Zone"
msgstr "域"

#, python-format
msgid "Zoning Policy: %s, not recognized"
msgstr "分区策略：%s，无法识别"

#, python-format
msgid "_create_and_copy_vdisk_data: Failed to get attributes for vdisk %s."
msgstr "_create_and_copy_vdisk_data：未能获取 vdisk %s 的属性。"

msgid "_create_host failed to return the host name."
msgstr "_create_host 未能返回主机名。"

msgid ""
"_create_host: Can not translate host name. Host name is not unicode or "
"string."
msgstr "_create_host：无法翻译主机名。主机名不是 Unicode或字符串。"

msgid "_create_host: No connector ports."
msgstr "_create_host：不存在任何连接器端口。"

msgid "_create_local_cloned_volume, Replication Service not found."
msgstr "_create_local_cloned_volume，找不到复制服务。"

#, python-format
msgid ""
"_create_local_cloned_volume, volumename: %(volumename)s, sourcevolumename: "
"%(sourcevolumename)s, source volume instance: %(source_volume)s, target "
"volume instance: %(target_volume)s, Return code: %(rc)lu, Error: "
"%(errordesc)s."
msgstr ""
"_create_local_cloned_volume，volumenam：%(volumename)s，sourcevolumename："
"%(sourcevolumename)s，源卷实例：%(source_volume)s，目标卷实例："
"%(target_volume)s，返回码：%(rc)lu，错误：%(errordesc)s。"

#, python-format
msgid ""
"_create_vdisk %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"_create_vdisk %(name)s - 找不到 CLI 输出形式的成功消息。\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s"

msgid "_create_volume_name, id_code is None."
msgstr "_create_volume_name，id_code 为 None。"

msgid "_delete_copysession, Cannot find Replication Service"
msgstr "_delete_copysession，找不到复制服务"

#, python-format
msgid ""
"_delete_copysession, copy session type is undefined! copy session: "
"%(cpsession)s, copy type: %(copytype)s."
msgstr ""
"_delete_copysession，未定义复制会话类型！复制会话：%(cpsession)s，复制类型："
"%(copytype)s。"

#, python-format
msgid ""
"_delete_copysession, copysession: %(cpsession)s, operation: %(operation)s, "
"Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""
"_delete_copysession，copysession：%(cpsession)s，操作：%(operation)s，返回"
"码：%(rc)lu，错误：%(errordesc)s。"

#, python-format
msgid ""
"_delete_volume, volumename: %(volumename)s, Return code: %(rc)lu, Error: "
"%(errordesc)s."
msgstr ""
"_delete_volume，volumename：%(volumename)s，返回码：%(rc)lu，错误："
"%(errordesc)s。"

#, python-format
msgid ""
"_delete_volume, volumename: %(volumename)s, Storage Configuration Service "
"not found."
msgstr "_delete_volume，volumename：%(volumename)s，找不到存储器配置服务。"

#, python-format
msgid ""
"_exec_eternus_service, classname: %(classname)s, InvokeMethod, cannot "
"connect to ETERNUS."
msgstr ""
"_exec_eternus_service，classname：%(classname)s，InvokeMethod，无法连接至 "
"ETERNUS。"

msgid "_extend_volume_op: Extending a volume with snapshots is not supported."
msgstr "_extend_volume_op：不支持扩展带有快照的卷。"

#, python-format
msgid ""
"_find_affinity_group, connector: %(connector)s, Associators: "
"FUJITSU_AuthorizedTarget, cannot connect to ETERNUS."
msgstr ""
"_find_affinity_group，连接器：%(connector)s，关联者："
"FUJITSU_AuthorizedTarget，无法连接至 ETERNUS。"

#, python-format
msgid ""
"_find_affinity_group, connector: %(connector)s, EnumerateInstanceNames, "
"cannot connect to ETERNUS."
msgstr ""
"_find_affinity_group，连接器：%(connector)s，EnumerateInstanceNames，无法连接"
"至 ETERNUS。"

#, python-format
msgid ""
"_find_affinity_group,connector: %(connector)s,AssocNames: "
"FUJITSU_ProtocolControllerForUnit, cannot connect to ETERNUS."
msgstr ""
"_find_affinity_group，连接器：%(connector)s，AssocNames： "
"FUJITSU_ProtocolControllerForUnit，无法连接至 ETERNUS。"

#, python-format
msgid ""
"_find_copysession, ReferenceNames, vol_instance: %(vol_instance_path)s, "
"Cannot connect to ETERNUS."
msgstr ""
"_find_copysession，ReferenceNames，vol_instance：%(vol_instance_path)s，无法"
"连接至 ETERNUS。"

#, python-format
msgid ""
"_find_eternus_service, classname: %(classname)s, EnumerateInstanceNames, "
"cannot connect to ETERNUS."
msgstr ""
"_find_eternus_service，classname：%(classname)s，EnumerateInstanceNames，无法"
"连接至 ETERNUS。"

#, python-format
msgid "_find_initiator_names, connector: %(connector)s, initiator not found."
msgstr "_find_initiator_names，连接器：%(connector)s，找不到启动程序。"

#, python-format
msgid ""
"_find_lun, volumename: %(volumename)s, EnumerateInstanceNames, cannot "
"connect to ETERNUS."
msgstr ""
"_find_lun，volumename：%(volumename)s，EnumerateInstanceNames，无法连接至 "
"ETERNUS。"

#, python-format
msgid ""
"_find_pool, eternus_pool:%(eternus_pool)s, EnumerateInstances, cannot "
"connect to ETERNUS."
msgstr ""
"_find_pool，eternus_pool：%(eternus_pool)s，EnumerateInstances，无法连接至 "
"ETERNUS。"

msgid "_get_async_url: Invalid URL."
msgstr "_get_async_url: 无效的 URL."

#, python-format
msgid ""
"_get_drvcfg, filename: %(filename)s, tagname: %(tagname)s, data is None!! "
"Please edit driver configuration file and correct."
msgstr ""
"_get_drvcfg，filename：%(filename)s，tagname：%(tagname)s，没有数据！请编辑驱"
"动配置文件并更正。"

#, python-format
msgid ""
"_get_eternus_connection, filename: %(filename)s, ip: %(ip)s, port: %(port)s, "
"user: %(user)s, passwd: ****, url: %(url)s, FAILED!!."
msgstr ""
"_get_eternus_connection，filename：%(filename)s，ip：%(ip)s，端口：%(port)s，"
"用户：%(user)s，密码：****，URL：%(url)s，失败！"

#, python-format
msgid ""
"_get_eternus_iscsi_properties, iscsiip list: %(iscsiip_list)s, iqn not found."
msgstr ""
"_get_eternus_iscsi_properties，iscsiip 列表：%(iscsiip_list)s，找不到 iqn。"

#, python-format
msgid ""
"_get_eternus_iscsi_properties, iscsiip: %(iscsiip)s, AssociatorNames: "
"CIM_BindsTo, cannot connect to ETERNUS."
msgstr ""
"_get_eternus_iscsi_properties，iscsiip：%(iscsiip)s，AssociatorName："
"CIM_BindsTo，无法连接至 ETERNUS。"

#, python-format
msgid ""
"_get_eternus_iscsi_properties, iscsiip: %(iscsiip)s, EnumerateInstanceNames, "
"cannot connect to ETERNUS."
msgstr ""
"_get_eternus_iscsi_properties，iscsiip：%(iscsiip)s，EnumerateInstanceNames，"
"无法连接至 ETERNUS。"

#, python-format
msgid ""
"_get_eternus_iscsi_properties, iscsiip: %(iscsiip)s, GetInstance, cannot "
"connect to ETERNUS."
msgstr ""
"_get_eternus_iscsi_properties，iscsiip：%(iscsiip)s，GetInstance，无法连接至 "
"ETERNUS。"

#, python-format
msgid ""
"_get_hdr_dic: attribute headers and values do not match.\n"
" Headers: %(header)s\n"
" Values: %(row)s."
msgstr ""
"_get_hdr_dic：属性头和值不匹配。\n"
"头为 %(header)s\n"
"值为 %(row)s。"

msgid "_get_host_from_connector failed to return the host name for connector."
msgstr "_get_host_from_connector 未能返回连接器的主机名。"

#, python-format
msgid ""
"_get_mapdata_fc, getting host-affinity from aglist/vol_instance failed, "
"affinitygroup: %(ag)s, ReferenceNames, cannot connect to ETERNUS."
msgstr ""
"_get_mapdata_fc，从 aglist/vol_instance 获取主机亲缘关系失败，affinitygroup："
"%(ag)s，ReferenceNames，无法连接至 ETERNUS。"

#, python-format
msgid ""
"_get_mapdata_fc, getting host-affinity instance failed, volmap: %(volmap)s, "
"GetInstance, cannot connect to ETERNUS."
msgstr ""
"_get_mapdata_fc，获取主机亲缘关系实例失败，volmap：%(volmap)s，GetInstance，"
"无法连接至 ETERNUS。"

msgid ""
"_get_mapdata_iscsi, Associators: FUJITSU_SAPAvailableForElement, cannot "
"connect to ETERNUS."
msgstr ""
"_get_mapdata_iscsi，关联者：FUJITSU_SAPAvailableForElement，无法连接至 "
"ETERNUS。"

#, python-format
msgid ""
"_get_mapdata_iscsi, affinitygroup: %(ag)s, ReferenceNames, cannot connect to "
"ETERNUS."
msgstr ""
"_get_mapdata_iscsi，affinitygroup：%(ag)s，ReferenceNames，无法连接至 "
"ETERNUS。"

#, python-format
msgid ""
"_get_mapdata_iscsi, vol_instance: %(vol_instance)s, ReferenceNames: "
"CIM_ProtocolControllerForUnit, cannot connect to ETERNUS."
msgstr ""
"_get_mapdata_iscsi，vol_instance：%(vol_instance)s，ReferenceNames： "
"CIM_ProtocolControllerForUnit，无法连接至 ETERNUS。"

#, python-format
msgid ""
"_get_mapdata_iscsi, volmap: %(volmap)s, GetInstance, cannot connect to "
"ETERNUS."
msgstr ""
"_get_mapdata_iscsi，volmap：%(volmap)s，GetInstance，无法连接至 ETERNUS。"

msgid "_get_target_port, EnumerateInstances, cannot connect to ETERNUS."
msgstr "_get_target_port，EnumerateInstances，无法连接至 ETERNUS。"

#, python-format
msgid "_get_target_port, protcol: %(protocol)s, target_port not found."
msgstr "_get_target_port，协议：%(protocol)s，找不到 target_port。"

#, python-format
msgid "_get_unmanaged_replay: Cannot find snapshot named %s"
msgstr "_get_unmanaged_replay：找不到名为 %s 的快照"

#, python-format
msgid "_get_unmanaged_replay: Cannot find volume id %s"
msgstr "_get_unmanaged_replay：找不到卷标识 %s"

msgid "_get_unmanaged_replay: Must specify source-name."
msgstr "_get_unmanaged_replay：必须指定 source-name。"

msgid ""
"_get_vdisk_map_properties: Could not get FC connection information for the "
"host-volume connection. Is the host configured properly for FC connections?"
msgstr ""
"_get_vdisk_map_properties：对于主机/卷连接，未能获取 FC 连接信息。已针对 FC "
"连接正确配置主机吗？"

#, python-format
msgid ""
"_get_vdisk_map_properties: No node found in I/O group %(gid)s for volume "
"%(vol)s."
msgstr ""
"_get_vdisk_map_properties：在卷 %(vol)s 的 I/O 组 %(gid)s 中找不到任何节点。"

#, python-format
msgid ""
"_map_lun, vol_instance.path:%(vol)s, volumename: %(volumename)s, volume_uid: "
"%(uid)s, initiator: %(initiator)s, target: %(tgt)s, aglist: %(aglist)s, "
"Storage Configuration Service not found."
msgstr ""
"_map_lun，vol_instance.path：%(vol)s，volumename：%(volumename)s，"
"volume_uid：%(uid)s，启动程序：%(initiator)s，目标：%(tgt)s，aglist："
"%(aglist)s，找不到存储器配置服务。"

#, python-format
msgid ""
"_unmap_lun, vol_instance.path: %(volume)s, volumename: %(volumename)s, "
"volume_uid: %(uid)s, aglist: %(aglist)s, Controller Configuration Service "
"not found."
msgstr ""
"_unmap_lun，vol_instance.path：%(volume)s，volumename：%(volumename)s，"
"volume_uid：%(uid)s，aglist：%(aglist)s，找不到控制器配置服务。"

#, python-format
msgid ""
"_unmap_lun, volumename: %(volumename)s, volume_uid: %(volume_uid)s, "
"AffinityGroup: %(ag)s, Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""
"_unmap_lun，volumename：%(volumename)s，volume_uid：%(volume_uid)s，"
"AffinityGroup：%(ag)s，返回码：%(rc)lu，错误：%(errordesc)s。"

#, python-format
msgid ""
"_unmap_lun,vol_instance.path: %(volume)s, AssociatorNames: "
"CIM_ProtocolControllerForUnit, cannot connect to ETERNUS."
msgstr ""
"_unmap_lun，vol_instance.path：%(volume)s，AssociatorName："
"CIM_ProtocolControllerForUnit，无法连接至 ETERNUS。"

msgid "_update_volume_stats: Could not get storage pool data."
msgstr "_update_volume_stats：未能获取存储池数据。"

#, python-format
msgid ""
"_wait_for_copy_complete, cpsession: %(cpsession)s, copysession state is "
"BROKEN."
msgstr ""
"_wait_for_copy_complete，cpsession：%(cpsession)s，copysession 状态为 "
"BROKEN。"

#, python-format
msgid ""
"add_vdisk_copy failed: A copy of volume %s exists. Adding another copy would "
"exceed the limit of 2 copies."
msgstr ""
"add_vdisk_copy 失败：卷 %s 的副本已存在。添加另一个副本将超过 2 个副本的限"
"制。"

msgid "add_vdisk_copy started without a vdisk copy in the expected pool."
msgstr "在所需池中没有 vdisk 副本的情况下，add_vdisk_copy 已开始。"

#, python-format
msgid "all_tenants must be a boolean, got '%s'."
msgstr "all_tenants 必须为布尔值，但是获得了“%s”。"

msgid "already created"
msgstr "已创建"

msgid "already_created"
msgstr "already_created"

#, python-format
msgid "attribute %s not lazy-loadable"
msgstr "属性 %s 不可延迟装入"

#, python-format
msgid ""
"backup: %(vol_id)s failed to create device hardlink from %(vpath)s to "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"备份：%(vol_id)s 未能创建从 %(vpath)s 至 %(bpath)s 的设备硬链接。\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s"

#, python-format
msgid ""
"backup: %(vol_id)s failed to obtain backup success notification from "
"server.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"备份：%(vol_id)s 未能从服务器获取“备份成功”通知。\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s"

#, python-format
msgid ""
"backup: %(vol_id)s failed to run dsmc due to invalid arguments on "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"备份：由于 %(bpath)s 上的自变量无效，使得 %(vol_id)s 未能运行 dsmc。\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s"

#, python-format
msgid ""
"backup: %(vol_id)s failed to run dsmc on %(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"备份：%(vol_id)s 未能对 %(bpath)s 运行 dsmc。\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s"

#, python-format
msgid "backup: %(vol_id)s failed. %(path)s is not a file."
msgstr "备份：%(vol_id)s 失败。%(path)s 不是文件。"

#, python-format
msgid ""
"backup: %(vol_id)s failed. %(path)s is unexpected file type. Block or "
"regular files supported, actual file mode is %(vol_mode)s."
msgstr ""
"备份：%(vol_id)s 失败。%(path)s 是意外的文件类型。支持块文件或常规文件，实际"
"文件方式为 %(vol_mode)s。"

#, python-format
msgid ""
"backup: %(vol_id)s failed. Cannot obtain real path to volume at %(path)s."
msgstr "备份：%(vol_id)s 失败。无法获取 %(path)s 处卷的实际路径。"

msgid "being attached by different mode"
msgstr "正在通过另一方式连接"

#, python-format
msgid "can't find lun-map, ig:%(ig)s vol:%(vol)s"
msgstr "找不到 LUN 映射，ig：%(ig)s 卷：%(vol)s"

msgid "can't find the volume to extend"
msgstr "找不到要扩展的卷"

msgid "can't handle both name and index in req"
msgstr "无法同时处理请求中的名称和索引"

msgid "cannot understand JSON"
msgstr "无法理解JSON"

msgid ""
"cg_creating_from_src must be called with cg_id or cgsnapshot_id parameter."
msgstr "cg_creating_from_src必须通过cg_id or cgsnapshot_id参数调用。"

msgid "cgsnapshot assigned"
msgstr "已分配 cgsnapshot"

msgid "cgsnapshot changed"
msgstr "已更改 cgsnapshot"

msgid "cgsnapshots assigned"
msgstr "已分配 cgsnapshot"

msgid "cgsnapshots changed"
msgstr "已更改 cgsnapshot"

msgid ""
"check_for_setup_error: Password or SSH private key is required for "
"authentication: set either san_password or san_private_key option."
msgstr ""
"check_for_setup_error：认证需要密码或 SSH 专用密钥：请设置 san_password 或 "
"san_private_key 选项。"

msgid "check_for_setup_error: Unable to determine system id."
msgstr "check_for_setup_error：无法确定系统标识。"

msgid "check_for_setup_error: Unable to determine system name."
msgstr "check_for_setup_error：无法确定系统名称。"

msgid "check_hypermetro_exist error."
msgstr "check_hypermetro_exist 错误。"

#, python-format
msgid "clone depth exceeds limit of %s"
msgstr "克隆深度超过 %s 的限制"

msgid "cluster assigned"
msgstr "已分配集群"

msgid "cluster changed"
msgstr "已更改集群"

msgid "config option key_manager.fixed_key is not defined"
msgstr "配置选项 key_manager.fixed_key 为定义。"

msgid "consistencygroup assigned"
msgstr "已分配 consistencygroup"

msgid "consistencygroup changed"
msgstr "已更改 consistencygroup"

msgid "create_cloned_volume, Source Volume does not exist in ETERNUS."
msgstr "create_cloned_volume，源卷在 ETERNUS 中不存在。"

#, python-format
msgid ""
"create_cloned_volume, target volume instancename: %(volume_instancename)s, "
"Get Instance Failed."
msgstr ""
"create_cloned_volume，目标卷实例名：%(volume_instancename)s，获取实例失败。"

#, python-format
msgid ""
"create_cloned_volume: source volume %(src_vol)s size is %(src_size)dGB and "
"doesn't fit in target volume %(tgt_vol)s of size %(tgt_size)dGB."
msgstr ""
"create_cloned_volume：源卷 %(src_vol)s 大小为 %(src_size)dGB，无法拟合大小为 "
"%(tgt_size)dGB 的目标卷 %(tgt_vol)s。"

msgid ""
"create_consistencygroup_from_src only supports a cgsnapshot source or a "
"consistency group source. Multiple sources cannot be used."
msgstr ""
"create_consistencygroup_from_src 仅支持 cgsnapshot 源或一致性组源。不能使用多"
"个源。"

#, python-format
msgid "create_copy: Source vdisk %(src)s (%(src_id)s) does not exist."
msgstr "create_copy：源 vdisk %(src)s (%(src_id)s) 不存在。"

#, python-format
msgid "create_copy: Source vdisk %(src)s does not exist."
msgstr "create_copy：源 vdisk %(src)s 不存在。"

msgid "create_host: Host name is not unicode or string."
msgstr "create_host：主机名不是 Unicode 或字符串。"

msgid "create_host: No initiators or wwpns supplied."
msgstr "create_host：未提供任何发起方或 wwpn。"

msgid "create_hypermetro_pair error."
msgstr "create_hypermetro_pair 错误。"

#, python-format
msgid "create_snapshot, eternus_pool: %(eternus_pool)s, pool not found."
msgstr "create_snapshot，eternus_pool：%(eternus_pool)s，找不到池。"

#, python-format
msgid ""
"create_snapshot, snapshotname: %(snapshotname)s, source volume name: "
"%(volumename)s, vol_instance.path: %(vol_instance)s, dest volume name: "
"%(d_volumename)s, pool: %(pool)s, Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""
"create_snapshot，snapshotname：%(snapshotname)s，源卷名：%(volumename)s，"
"vol_instance.path: %(vol_instance)s，目标卷名：%(d_volumename)s，池："
"%(pool)s，返回码：%(rc)lu，错误：%(errordesc)s。"

#, python-format
msgid ""
"create_snapshot, volumename: %(s_volumename)s, source volume not found on "
"ETERNUS."
msgstr ""
"create_snapshot，volumename：%(s_volumename)s，在 ETERNUS 上找不到源卷。"

#, python-format
msgid ""
"create_snapshot, volumename: %(volumename)s, Replication Service not found."
msgstr "create_snapshot，volumename：%(volumename)s，找不到复制服务。"

#, python-format
msgid ""
"create_snapshot: Volume status must be \"available\" or \"in-use\" for "
"snapshot. The invalid status is %s."
msgstr ""
"create_snapshot：对于快照，卷状态必须为“available”或“in-use”。无效状态为 %s。"

msgid "create_snapshot: get source volume failed."
msgstr "create_snapshot：获取源卷失败。"

#, python-format
msgid ""
"create_volume, volume: %(volume)s, EnumerateInstances, cannot connect to "
"ETERNUS."
msgstr ""
"create_volume，卷：%(volume)s，EnumerateInstances，无法连接至 ETERNUS。"

#, python-format
msgid ""
"create_volume, volume: %(volume)s, volumename: %(volumename)s, eternus_pool: "
"%(eternus_pool)s, Storage Configuration Service not found."
msgstr ""
"create_volume，卷：%(volume)s，卷名：%(volumename)s，eternus_pool："
"%(eternus_pool)s，找不到存储器配置服务。"

#, python-format
msgid ""
"create_volume, volumename: %(volumename)s, poolname: %(eternus_pool)s, "
"Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""
"create_volume，volumename：%(volumename)s，poolname：%(eternus_pool)s，返回"
"码：%(rc)lu，错误：%(errordesc)s。"

msgid "create_volume_from_snapshot, Source Volume does not exist in ETERNUS."
msgstr "create_volume_from_snapshot，源卷在 ETERNUS 中不存在。"

#, python-format
msgid ""
"create_volume_from_snapshot, target volume instancename: "
"%(volume_instancename)s, Get Instance Failed."
msgstr ""
"create_volume_from_snapshot，目标卷实例名：%(volume_instancename)s，获取实例"
"失败。"

#, python-format
msgid "create_volume_from_snapshot: Snapshot %(name)s does not exist."
msgstr "create_volume_from_snapshot：快照 %(name)s 不存在。"

#, python-format
msgid ""
"create_volume_from_snapshot: Snapshot status must be \"available\" for "
"creating volume. The invalid status is: %s."
msgstr ""
"create_volume_from_snapshot：快照状态必须为“可用”，以便创建卷。无效状态为 "
"%s。"

#, python-format
msgid ""
"delete: %(vol_id)s failed to run dsmc due to invalid arguments with stdout: "
"%(out)s\n"
" stderr: %(err)s"
msgstr ""
"删除：%(vol_id)s 由于自变量无效而未能运行 dsmc，标准输出：%(out)s\n"
"标准错误：%(err)s"

#, python-format
msgid ""
"delete: %(vol_id)s failed to run dsmc with stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"删除：%(vol_id)s 未能运行 dsmc，标准输出：%(out)s\n"
"标准错误：%(err)s"

msgid "delete_hypermetro error."
msgstr "delete_hypermetro 错误。"

#, python-format
msgid "delete_initiator: %s ACL not found. Continuing."
msgstr "找不到 delete_initiator: %s ACL。正在继续。"

msgid "delete_replication error."
msgstr "delete_replication 错误。"

#, python-format
msgid "deleting snapshot %(snapshot_name)s that has dependent volumes"
msgstr "正在删除具有从属卷的快照 %(snapshot_name)s"

#, python-format
msgid "deleting volume %(volume_name)s that has snapshot"
msgstr "正在删除有快照的卷  %(volume_name)s"

msgid "do_setup: No configured nodes."
msgstr "do_setup：不存在任何已配置的节点。"

#, python-format
msgid ""
"error writing object to swift, MD5 of object in swift %(etag)s is not the "
"same as MD5 of object sent to swift %(md5)s"
msgstr ""
"将对象写入 swift 时出错，swift %(etag)s 中对象的 MD5 与发送至 swift %(md5)s "
"的对象的 MD5 不同"

msgid ""
"existing_ref argument must be of this format:app_inst_name:storage_inst_name:"
"vol_name"
msgstr ""
"参数 existing_ref 的格式必须为：app_inst_name:storage_inst_name:vol_name。"

#, python-format
msgid "extend_volume, eternus_pool: %(eternus_pool)s, pool not found."
msgstr "extend_volume，eternus_pool：%(eternus_pool)s，找不到池。"

#, python-format
msgid ""
"extend_volume, volume: %(volume)s, volumename: %(volumename)s, eternus_pool: "
"%(eternus_pool)s, Storage Configuration Service not found."
msgstr ""
"extend_volume，卷：%(volume)s， volumename：%(volumename)s，eternus_pool："
"%(eternus_pool)s，找不到存储器配置服务。"

#, python-format
msgid ""
"extend_volume, volumename: %(volumename)s, Return code: %(rc)lu, Error: "
"%(errordesc)s, PoolType: %(pooltype)s."
msgstr ""
"extend_volume，volumename：%(volumename)s，返回码：%(rc)lu，错误："
"%(errordesc)s，池类型：%(pooltype)s。"

#, python-format
msgid "extend_volume, volumename: %(volumename)s, volume not found."
msgstr "extend_volume，volumename：%(volumename)s，找不到卷。"

msgid "fake"
msgstr "fake"

msgid "fileno is not supported by SheepdogIOWrapper"
msgstr "SheepdogIOWrapper 不支持 fileno"

#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr "fmt=%(fmt)s 由 %(backing_file)s 支持"

#, python-format
msgid "fmt=%(fmt)s backed by:%(backing_file)s"
msgstr "fmt=%(fmt)s 受以下项支持：%(backing_file)s"

msgid "force delete"
msgstr "强制删除"

msgid "get_hyper_domain_id error."
msgstr "get_hyper_domain_id 错误。"

msgid "get_hypermetro_by_id error."
msgstr "get_hypermetro_by_id 错误。"

#, python-format
msgid ""
"get_iscsi_params: Failed to get target IP for initiator %(ini)s, please "
"check config file."
msgstr "get_iscsi_params：未能获取发起方 %(ini)s 的目标 IP，请检查配置文件。"

#, python-format
msgid "get_pool: Failed to get attributes for volume %s"
msgstr "get_pool：无法获取卷 %s 的属性"

msgid "glance_metadata changed"
msgstr "已更改 glance_metadata"

#, python-format
msgid ""
"gpfs_images_share_mode is set to copy_on_write, but %(vol)s and %(img)s "
"belong to different file systems."
msgstr ""
"gpfs_images_share_mode 已设置为 copy_on_write，但 %(vol)s 和 %(img)s 属于不同"
"文件系统。"

#, python-format
msgid ""
"gpfs_images_share_mode is set to copy_on_write, but %(vol)s and %(img)s "
"belong to different filesets."
msgstr ""
"gpfs_images_share_mode 已设置为 copy_on_write，但 %(vol)s 和 %(img)s 属于不同"
"文件集。"

msgid "group assigned"
msgstr "已分配组"

msgid "group changed"
msgstr "已更改组"

#, python-format
msgid "group-%s"
msgstr "组 %s"

msgid ""
"group_creating_from_src must be called with group_id or group_snapshot_id "
"parameter."
msgstr ""
"group_creating_from_src必须被调用，参数为group_id或者group_snapshot_id。"

msgid "group_snapshot assigned"
msgstr "已分配组快照"

msgid "group_snapshot changed"
msgstr "已更改组快照"

msgid "group_snapshots assigned"
msgstr "已分配组快照"

msgid "group_type_id cannot be None"
msgstr "group_type_id 不能为None"

msgid ""
"http service may have been abruptly disabled or put to maintenance state in "
"the middle of this operation."
msgstr "HTTP 服务可能已突然禁用，或在此操作的中途进入维护状态。"

msgid "id cannot be None"
msgstr "id不能是None"

#, python-format
msgid "image %s not found"
msgstr "找不到映像 %s "

#, python-format
msgid "initialize_connection, volume: %(volume)s, Volume not found."
msgstr "initialize_connection，卷：%(volume)s，找不到卷。"

#, python-format
msgid "initialize_connection: Failed to get attributes for volume %s."
msgstr "initialize_connection：未能获取卷 %s 的属性。"

#, python-format
msgid "initialize_connection: Missing volume attribute for volume %s."
msgstr "initialize_connection：缺少卷 %s 的卷属性。"

#, python-format
msgid ""
"initialize_connection: No node found in I/O group %(gid)s for volume %(vol)s."
msgstr "initialize_connection：在卷 %(vol)s 的 I/O 组 %(gid)s 中找不到节点。"

#, python-format
msgid "initialize_connection: vdisk %s is not defined."
msgstr "initialize_connection：未定义 vdisk %s。"

#, python-format
msgid "invalid user '%s'"
msgstr "用户 '%s' 无效"

#, python-format
msgid "iscsi portal, %s, not found"
msgstr "找不到 iscsi 门户网站 %s"

#, python-format
msgid "key manager error: %(reason)s"
msgstr "发生密钥管理器错误：%(reason)s"

msgid "limit param must be an integer"
msgstr "limit 参数必须是整数"

msgid "limit param must be positive"
msgstr "limit参数必须是正数"

msgid "manage_existing requires a 'name' key to identify an existing volume."
msgstr "manage_existing 需要“name”键以标识现有卷。"

#, python-format
msgid ""
"manage_existing_snapshot: Error managing existing replay %(ss)s on volume "
"%(vol)s"
msgstr "manage_existing_snapshot：管理卷 %(vol)s 上的现有重放 %(ss)s 时出错"

#, python-format
msgid "marker not found: %s"
msgstr "没有找到标记： %s"

#, python-format
msgid "mdiskgrp missing quotes %s"
msgstr "Mdisk 组缺少引号 %s"

#, python-format
msgid "mkfs failed on volume %(vol)s, error message was: %(err)s."
msgstr "mkfs 在卷 %(vol)s 上发生故障，错误消息如下：%(err)s。"

msgid "mock"
msgstr "mock"

#, python-format
msgid "multiple resources with name %s found by drbdmanage"
msgstr "drbdmanage 找到多个名称为 %s 的资源"

#, python-format
msgid "multiple resources with snapshot ID %s found"
msgstr "找到多个快照标识为 %s 的资源"

msgid "name cannot be None"
msgstr "name不能是None"

msgid "no \"access-key\" field"
msgstr "不存在\"access-key\"域"

msgid "no \"user\" field"
msgstr "不存在“user”域"

#, python-format
msgid "no snapshot with id %s found in drbdmanage"
msgstr "在 drbdmanage 中找不到标识为 %s 的快照"

#, python-format
msgid "not exactly one snapshot with id %s"
msgstr "而不是刚好只有一个标识为 %s 的快照"

#, python-format
msgid "not exactly one volume with id %s"
msgstr "而不是刚好只有一个标识为 %s 的卷"

#, python-format
msgid "obj missing quotes %s"
msgstr "对象缺少引号 %s"

msgid "open_access_enabled is not off."
msgstr "open_access_enabled 未关闭。"

msgid "progress must be an integer percentage"
msgstr "进度必须为整数百分比"

#, python-format
msgid ""
"qemu-img %(minimum_version)s or later is required by this volume driver. "
"Current qemu-img version: %(current_version)s"
msgstr ""
"此卷驱动程序需要 qemu-img %(minimum_version)s 或更高版本。当前 qemu-img 版"
"本：%(current_version)s"

#, python-format
msgid ""
"qemu-img is not installed and image is of type %s.  Only RAW images can be "
"used if qemu-img is not installed."
msgstr ""
"qemu-img 未安装，并且映像的类型为 %s。仅当 qemu-img 未安装时，才能使用原始映"
"像。"

msgid ""
"qemu-img is not installed and the disk format is not specified.  Only RAW "
"images can be used if qemu-img is not installed."
msgstr ""
"qemu-img 未安装，并且磁盘格式未指定。仅当 qemu-img 未安装时，才能使用原始映"
"像。"

msgid "rados and rbd python libraries not found"
msgstr "找不到 rados 和 rbd python 库"

#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr "read_deleted 只能是“no”、“yes”或“only”其中一项，而不能是 %r"

#, python-format
msgid "replication_failover failed. %s not found."
msgstr "replication_failover 失败。找不到 %s。"

msgid "replication_failover failed. Backend not configured for failover"
msgstr "replication_failover 失败。未配置后端，无法进行故障转移"

#, python-format
msgid ""
"restore: %(vol_id)s failed to run dsmc due to invalid arguments on "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"复原：%(vol_id)s 由于 %(bpath)s 上的自变量无效而未能运行 dsmc。\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s"

#, python-format
msgid ""
"restore: %(vol_id)s failed to run dsmc on %(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"复原：%(vol_id)s 未能对 %(bpath)s 运行 dsmc。\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s"

#, python-format
msgid ""
"restore: %(vol_id)s failed.\n"
"stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"复原：%(vol_id)s 失败。\n"
"标准输出：%(out)s\n"
"标准错误：%(err)s。"

msgid ""
"restore_backup aborted, actual object list does not match object list stored "
"in metadata."
msgstr ""
"restore_backup 已异常中止，实际的对象列表与存储在元数据中的对象列表不匹配。"

#, python-format
msgid "rtslib_fb is missing member %s: You may need a newer python-rtslib-fb."
msgstr "rtslib_fb 缺少成员 %s：您可能需要较新的 python-rtslib-fb。"

msgid "san_ip must be set"
msgstr "san_ip必须设置"

msgid ""
"san_login and/or san_password is not set for Datera driver in the cinder."
"conf. Set this information and start the cinder-volume service again."
msgstr ""
"没有在 cinder.conf 中为 Datera 驱动程序设置 san_login 和/或 san_password。请"
"设置此信息并再次启动 cinder-volume服务。"

msgid "serve() can only be called once"
msgstr "serve() 只能调用一次"

#, python-format
msgid "snapshot-%s"
msgstr "快照 - %s"

msgid "snapshots assigned"
msgstr "已更改快照"

msgid "snapshots changed"
msgstr "已更改快照"

msgid "source-name cannot be empty."
msgstr "source-name 不能为空。"

msgid "source-name format should be: 'vmdk_path@vm_inventory_path'."
msgstr "source-name 格式应为“vmdk_path@vm_inventory_path”。"

msgid "specs must be a dictionary."
msgstr "规格说明必须是字典。"

#, python-format
msgid "status must be %s and"
msgstr "状态必须为 %s，并且"

msgid "status must be available"
msgstr "状态必须可用"

msgid "stop_hypermetro error."
msgstr "stop_hypermetro 错误。"

msgid "sync_hypermetro error."
msgstr "sync_hypermetro 错误。"

#, python-format
msgid "target=%(target)s, lun=%(lun)s"
msgstr "目标=%(target)s, lun=%(lun)s"

#, python-format
msgid ""
"targetcli not installed and could not create default directory "
"(%(default_path)s): %(exc)s"
msgstr "未安装 targetcli，并且未能创建缺省目录(%(default_path)s)：%(exc)s"

msgid "terminate_connection: Failed to get host name from connector."
msgstr "terminate_connection：未能从连接器获取主机名。"

msgid "too many body keys"
msgstr "过多主体密钥"

#, python-format
msgid "unmanage_snapshot: Cannot find snapshot named %s"
msgstr "unmanage_snapshot：找不到名为 %s 的快照"

#, python-format
msgid "unmanage_snapshot: Cannot find volume id %s"
msgstr "unmanage_snapshot：找不到卷标识 %s"

#, python-format
msgid "unrecognized argument %s"
msgstr "无法识别自变量 %s"

#, python-format
msgid "unsupported compression algorithm: %s"
msgstr "以下压缩算法不受支持：%s"

msgid "valid iqn needed for show_target"
msgstr "show_target 需要有效 iqn"

#, python-format
msgid "vdisk %s is not defined."
msgstr "未定义 vdisk %s。"

#, python-format
msgid "volume %s not found in drbdmanage"
msgstr "在 drbdmanage 中找不到卷 %s"

msgid "volume assigned"
msgstr "卷已分配"

msgid "volume changed"
msgstr "卷已更改"

#, python-format
msgid ""
"volume size %(volume_size)d is too small to restore backup of size %(size)d."
msgstr "卷大小 %(volume_size)d 太小，无法复原大小为 %(size)d 的备份。"

#, python-format
msgid "volume size %d is invalid."
msgstr "卷大小 %d 无效。"

msgid ""
"volume_type must be provided when creating a volume in a consistency group."
msgstr "在一致性组中创建卷时，必须提供 volume_type。"

msgid "volume_type must be provided when creating a volume in a group."
msgstr "在组中创建卷时，必须提供 volume_type。"

msgid "volume_type_id cannot be None"
msgstr "volume_type_id 不能为“无”"

msgid "volume_types assigned"
msgstr "已分配卷类型"

#, python-format
msgid "volume_types must be provided to create consistency group %(name)s."
msgstr "必须提供 volume_types，才能创建一致性组 %(name)s。"

msgid "volumes assigned"
msgstr "已分配卷"

msgid "volumes changed"
msgstr "已更改卷"

#, python-format
msgid "wait_for_condition: %s timed out."
msgstr "wait_for_condition：%s 已超时。"

#, python-format
msgid ""
"zfssa_manage_policy property needs to be set to 'strict' or 'loose'. Current "
"value is: %s."
msgstr "zfssa_manage_policy 属性需要设置为“strict”或“loose”。当前值为：%s。"
