# Translations template for cinder.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the cinder project.
#
# Translators:
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: cinder VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2019-01-11 16:51+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-04-12 05:04+0000\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language: zh_TW\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 4.3.3\n"
"Language-Team: Chinese (Taiwan)\n"

#, python-format
msgid "\t%s"
msgstr "\t%s"

#, python-format
msgid ""
"\n"
"OpenStack Cinder version: %(version)s\n"
msgstr ""
"\n"
"OpenStack Cinder 版本：%(version)s\n"

#, python-format
msgid " but size is now %d"
msgstr "但大小現在為 %d"

msgid " or "
msgstr "或者"

#, python-format
msgid ""
"%(driver)s manage_existing cannot manage a volume connected to hosts. Please "
"disconnect this volume from existing hosts before importing"
msgstr ""
"%(driver)s manage_existing 無法管理已連接至主機的磁區。請先斷開此磁區與現有主"
"機的連線，然後再匯入"

#, python-format
msgid ""
"%(err)s\n"
"result: %(res)s."
msgstr ""
"%(err)s\n"
"結果：%(res)s。"

#, python-format
msgid "%(exception)s: %(explanation)s"
msgstr "發生 %(exception)s：%(explanation)s"

#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"%(fun)s：失敗，CLI 輸出不符合預期。\n"
"指令：%(cmd)s\n"
" 標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

#, python-format
msgid "%(host)-25s\t%(availability_zone)-15s"
msgstr "%(host)-25s\t%(availability_zone)-15s"

#, python-format
msgid "%(host)-25s\t%(zone)-15s"
msgstr "%(host)-25s\t%(zone)-15s"

#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""
"%(message)s\n"
"狀態碼：%(_status)s\n"
"主體：%(_body)s"

#, python-format
msgid ""
"%(msg_type)s: creating NetworkPortal: ensure port %(port)d on ip %(ip)s is "
"not in use by another service."
msgstr ""
"%(msg_type)s：正在建立 NetworkPortal：確保 IP %(ip)s 上的埠 %(port)d未在由另"
"一個服務使用。"

#, python-format
msgid ""
"%(op)s: backup %(bck_id)s, volume %(vol_id)s failed. Backup object has "
"unexpected mode. Image or file backups supported, actual mode is "
"%(vol_mode)s."
msgstr ""
"%(op)s：備份 %(bck_id)s，磁區 %(vol_id)s 失敗。備份物件具有非預期的模式。支援"
"映像檔或檔案備份，實際模式為%(vol_mode)s。"

#, python-format
msgid "%(service)s Service is not %(status)s on storage appliance: %(host)s"
msgstr "%(service)s 服務在儲存體軟體驅動裝置 %(host)s 上不是處於 %(status)s"

#, python-format
msgid ""
"%(worker_name)s value of %(workers)d is invalid, must be greater than 0."
msgstr "%(workers)d 的 %(worker_name)s 值無效，必須大於 0。"

#, python-format
msgid "%s \"data\" is not in result."
msgstr "結果中沒有 %s \"data\"。"

#, python-format
msgid ""
"%s cannot be accessed. Verify that GPFS is active and file system is mounted."
msgstr "無法存取 %s。請確認 GPFS 在作用中且檔案系統已裝載。"

#, python-format
msgid "%s cannot be resized using clone operation as it contains no blocks."
msgstr "無法使用複製作業來調整 %s 的大小，因為它不包含任何區塊。"

#, python-format
msgid ""
"%s cannot be resized using clone operation as it is hosted on compressed "
"volume"
msgstr "無法使用複製作業來調整 %s 的大小，因為它是在壓縮磁區上進行管理"

#, python-format
msgid "%s configuration option is not set."
msgstr "未設定 %s 配置選項。"

#, python-format
msgid "%s does not exist."
msgstr "%s 不存在。"

#, python-format
msgid "%s is not a directory."
msgstr "%s 不是目錄。"

#, python-format
msgid "%s is not installed"
msgstr "%s 未安裝"

#, python-format
msgid "%s is not installed."
msgstr "未安裝 %s。"

#, python-format
msgid "%s is not set"
msgstr "未設定 %s"

#, python-format
msgid "%s is not set and is required for the replication device to be valid."
msgstr "%s 未設定，並且是抄寫裝置變成有效所必需的。"

#, python-format
msgid "%s is not set."
msgstr "未設定 %s。"

#, python-format
msgid "%s must be a valid raw or qcow2 image."
msgstr "%s 必須是有效的原始映像檔或 qcow2 映像檔。"

#, python-format
msgid "%s must be an absolute path."
msgstr "%s 必須是絕對路徑。"

#, python-format
msgid "%s not set in cinder.conf"
msgstr "%s 未在 cinder.conf 中設定"

#, python-format
msgid "%s not set."
msgstr "未設定 %s。"

#, python-format
msgid ""
"'%(prot)s' is invalid for flashsystem_connection_protocol in config file. "
"valid value(s) are %(enabled)s."
msgstr ""
"在配置檔中，'%(prot)s' 不適用於 flashsystem_connection_protocol。有效值為 "
"%(enabled)s。"

msgid "'active' must be present when writing snap_info."
msgstr "寫入 snap_info 時，狀態必須是「作用中」。"

msgid "'consistencygroup_id' must be specified"
msgstr "必須指定 'consistencygroup_id'"

msgid "'qemu-img info' parsing failed."
msgstr "'qemu-img info' 剖析失敗。"

#, python-format
msgid ""
"(Command: %(cmd)s) (Return Code: %(exit_code)s) (Stdout: %(stdout)s) "
"(Stderr: %(stderr)s)"
msgstr ""
"（指令：%(cmd)s）（回覆碼：%(exit_code)s）（標準輸出：%(stdout)s）（標準錯"
"誤：%(stderr)s）"

msgid "A concurrent, possibly contradictory, request has been made."
msgstr "已發出並行（可能矛盾）的要求。"

msgid "A valid secondary target MUST be specified in order to failover."
msgstr "必須指定有效的次要目標，才能進行失效接手。"

msgid "A volume ID or share was not specified."
msgstr "未指定磁區 ID 或共用項目。"

#, python-format
msgid ""
"API Version String %(version)s is of invalid format. Must be of format "
"MajorNum.MinorNum."
msgstr "API 版本字串 %(version)s 的格式無效。格式必須是 MajorNum.MinorNum。"

#, python-format
msgid "API response: %s"
msgstr "API 回應：%s"

#, python-format
msgid "API version %(version)s is not supported on this method."
msgstr "此方法不支援 API %(version)s 版。"

msgid ""
"About to delete child projects having non-zero quota. This should not be "
"performed"
msgstr "即將刪除具有非零配額的子項專案。不應執行此動作"

msgid "Access list not available for public volume types."
msgstr "存取清單不可用於公用磁區類型。"

msgid "Activate or deactivate QoS error."
msgstr "啟動或關閉服務品質時發生錯誤。"

msgid "Activate snapshot error."
msgstr "啟動 Snapshot 時發生錯誤。"

msgid "Add FC port to host error."
msgstr "將 FC 埠新增至主機時發生錯誤。"

msgid "Add fc initiator to array error."
msgstr "將 FC 起始器新增至陣列時發生錯誤。"

msgid "Add initiator to array error."
msgstr "將起始器新增至陣列時發生錯誤。"

msgid "Add lun to cache error."
msgstr "將 LUN 新增至快取時發生錯誤。"

msgid "Add lun to partition error."
msgstr "將 LUN 新增至分割區時發生錯誤。"

msgid "Add mapping view error."
msgstr "新增對映視圖時發生錯誤。"

msgid "Add new host error."
msgstr "新增主機時發生錯誤。"

msgid "Add port to port group error."
msgstr "將埠新增至埠群組時發生錯誤。"

#, python-format
msgid ""
"All the specified storage pools to be managed do not exist. Please check "
"your configuration. Non-existent pools: %s"
msgstr "要管理的所有指定儲存區都不存在。請檢查配置。不存在的儲存區：%s"

msgid "An API version request must be compared to a VersionedMethod object."
msgstr "API 版本要求必須與 VersionedMethod 物件進行比較。"

msgid "An error has occurred during backup operation"
msgstr "執行備份作業期間發生錯誤"

#, python-format
msgid ""
"An error occurred during the LUNcopy operation. LUNcopy name: "
"%(luncopyname)s. LUNcopy status: %(luncopystatus)s. LUNcopy state: "
"%(luncopystate)s."
msgstr ""
"LUNcopy 作業期間發生錯誤。LUNcopy 名稱：%(luncopyname)s。LUNcopy 狀態 "
"(status)：%(luncopystatus)s。LUNcopy 狀態 (state)：%(luncopystate)s。"

#, python-format
msgid "An error occurred while reading volume \"%s\"."
msgstr "讀取磁區 \"%s\" 時發生錯誤。"

#, python-format
msgid "An error occurred while writing to volume \"%s\"."
msgstr "寫入磁區 \"%s\" 時發生錯誤。"

msgid "An unknown exception occurred."
msgstr "發生一個未知例外"

msgid ""
"An user with a token scoped to a subproject is not allowed to see the quota "
"of its parents."
msgstr "不容許具備已限定為某個子專案之記號的使用者來查看其母項的配額。"

msgid "Append port group description error."
msgstr "附加埠群組說明時發生錯誤。"

#, python-format
msgid ""
"Applying the zones and cfgs to the switch failed (error code=%(err_code)s "
"error msg=%(err_msg)s."
msgstr ""
"將區域和配置套用至交換器失敗（錯誤碼 = %(err_code)s，錯誤訊息 = "
"%(err_msg)s）。"

#, python-format
msgid "Array does not exist or is offline. Current status of array is %s."
msgstr "陣列不存在或者已離線。陣列的現行狀態為 %s。"

msgid "Associate host to hostgroup error."
msgstr "將主機關聯至主機群組時發生錯誤。"

msgid "Associate host to mapping view error."
msgstr "將主機關聯至對映視圖時發生錯誤。"

msgid "Associate initiator to host error."
msgstr "將起始器關聯至主機時發生錯誤。"

msgid "Associate lun to QoS error."
msgstr "將 LUN 與服務品質建立關聯時發生錯誤。"

msgid "Associate lun to lungroup error."
msgstr "將 LUN 關聯至 LUN 群組時發生錯誤。"

msgid "Associate lungroup to mapping view error."
msgstr "將 LUN 群組關聯至對映視圖時發生錯誤。"

msgid "Associate portgroup to mapping view error."
msgstr "將埠群組關聯至對映視圖時發生錯誤。"

msgid "At least one valid iSCSI IP address must be set."
msgstr "必須至少設定一個有效的 iSCSI IP 位址。"

#, python-format
msgid "Attempt to transfer %s with invalid auth key."
msgstr "嘗試傳送 %s，但使用的鑑別金鑰無效。"

#, python-format
msgid "Authentication failed, verify the switch credentials, error code %s."
msgstr "鑑別失敗，請驗證交換器認證，錯誤碼：%s。"

#, python-format
msgid "Availability zone '%(s_az)s' is invalid."
msgstr "可用性區域 '%(s_az)s' 無效。"

msgid "Available categories:"
msgstr "可用的種類："

#, python-format
msgid "Backend doesn't exist (%(backend)s)"
msgstr "後端不存在 (%(backend)s)"

msgid "Backend storage did not configure fiber channel target."
msgstr "後端儲存體未配置光纖通道目標。"

msgid "Backing up an in-use volume must use the force flag."
msgstr "備份使用中的磁區必須使用強制旗標。"

#, python-format
msgid "Backup %(backup_id)s could not be found."
msgstr "找不到備份 %(backup_id)s。"

msgid "Backup RBD operation failed"
msgstr "執行備份 RBD 作業時失敗"

msgid "Backup already exists in database."
msgstr "備份已經存在於資料庫中。"

msgid "Backup id required"
msgstr "需要備份 ID"

msgid "Backup operation of an encrypted volume failed."
msgstr "已加密磁區的備份作業失敗。"

#, python-format
msgid ""
"Backup service %(configured_service)s does not support verify. Backup id "
"%(id)s is not verified. Skipping verify."
msgstr ""
"備份服務 %(configured_service)s 不支援驗證。未驗證備份 ID%(id)s。正在跳過驗"
"證。"

#, python-format
msgid ""
"Backup service %(service)s does not support verify. Backup id %(id)s is not "
"verified. Skipping reset."
msgstr "備份服務 %(service)s 不支援驗證。未驗證備份 ID %(id)s。正在跳過重設。"

#, python-format
msgid "Backup should only have one snapshot but instead has %s"
msgstr "備份應該只有一個 Snapshot，但具有 %s 個"

msgid "Backup status must be available"
msgstr "備份狀態必須為可用"

#, python-format
msgid "Backup status must be available and not %s."
msgstr "備份狀態必須為可用，且不是 %s。"

msgid "Backup status must be available or error"
msgstr "備份狀態必須為可用或者錯誤"

msgid "Backup to be restored has invalid size"
msgstr "要還原的備份大小無效"

#, python-format
msgid "Bad key(s) in quota set: %s"
msgstr "配額集中的索引鍵錯誤：%s"

#, python-format
msgid ""
"Bad or unexpected response from the storage volume backend API: %(data)s"
msgstr "來自儲存磁區後端 API 的回應錯誤或不符合預期：%(data)s"

msgid "Bad response from Datera API"
msgstr "Datera API 傳回錯誤的回應"

msgid "Bad response from SolidFire API"
msgstr "SolidFire API 傳回錯誤的回應"

#, python-format
msgid "Bad response from XMS, %s"
msgstr "XMS 傳回錯誤的回應，%s"

msgid "Binary"
msgstr "二進位"

msgid "Blank components"
msgstr "空白元件"

#, python-format
msgid "Brocade Fibre Channel Zoning CLI error: %(reason)s"
msgstr "Brocade 光纖通道分區 CLI 錯誤：%(reason)s"

#, python-format
msgid "Brocade Fibre Channel Zoning HTTP error: %(reason)s"
msgstr "Brocade 光纖通道分區 HTTP 錯誤：%(reason)s"

msgid "CHAP secret should be 12-16 bytes."
msgstr "CHAP 密碼應該是 12-16 位元組。"

#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"CLI 異常狀況輸出：\n"
" 指令：%(cmd)s\n"
" 標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"CLI 異常狀況輸出：\n"
" 指令：%(cmd)s\n"
" 標準輸出：%(out)s\n"
"標準錯誤：%(err)s。"

msgid ""
"CMMVC6071E The VDisk-to-host mapping was not created because the VDisk is "
"already mapped to a host.\n"
"\""
msgstr ""
"CMMVC6071E 未建立 VDisk 至主機對映，因為該 VDisk 已經對映至某個主機。\n"
"\""

#, python-format
msgid "CPG (%s) doesn't exist on array"
msgstr "陣列上不存在 CPG (%s)"

msgid "Cache name is None, please set smartcache:cachename in key."
msgstr "快取名稱為「無」，請在索引鍵中設定 smartcache:cachename。"

#, python-format
msgid "Cache volume %s does not have required properties"
msgstr "快取磁區 %s 沒有必需的內容"

msgid "Can not add FC port to host."
msgstr "無法將 FC 埠新增至主機。"

#, python-format
msgid "Can not find cache id by cache name %(name)s."
msgstr "依快取名稱 %(name)s 找不到快取 ID。"

#, python-format
msgid "Can not find partition id by name %(name)s."
msgstr "依名稱 %(name)s 找不到分割區 ID。"

#, python-format
msgid "Can not get pool info. pool: %s"
msgstr "無法取得儲存區資訊。儲存區：%s"

#, python-format
msgid "Can not translate %s to integer."
msgstr "無法將 %s 轉換為整數。"

msgid "Can't decode backup record."
msgstr "無法將備份記錄解碼。"

#, python-format
msgid "Can't extend replication volume, volume: %(id)s"
msgstr "無法延伸抄寫磁區，磁區：%(id)s"

msgid "Can't find LUN on the array, please check the source-name or source-id."
msgstr "在陣列上找不到 LUN，請檢查 source-name 或 source-id。"

#, python-format
msgid "Can't find cache name on the array, cache name is: %(name)s."
msgstr "在陣列上找不到快取名稱，快取名稱為：%(name)s。"

#, python-format
msgid "Can't find partition name on the array, partition name is: %(name)s."
msgstr "在陣列上找不到分割區名稱，分割區名稱為：%(name)s。"

#, python-format
msgid "Can't find service: %s"
msgstr "找不到服務：%s"

msgid ""
"Can't find snapshot on array, please check the source-name or source-id."
msgstr "在陣列上找不到 Snapshot，請檢查 source-name 或 source-id。"

msgid "Can't find the same host id from arrays."
msgstr "從陣列中找不到相同的主機 ID。"

#, python-format
msgid "Can't get volume id from snapshot, snapshot: %(id)s"
msgstr "無法從 Snapshot 取得磁區 ID，Snapshot：%(id)s"

#, python-format
msgid "Can't get volume id. Volume name: %s."
msgstr "無法取得磁區 ID。磁區名稱：%s。"

#, python-format
msgid "Can't import LUN %(lun_id)s to Cinder. LUN type mismatched."
msgstr "無法將 LUN %(lun_id)s 匯入 Cinder。LUN 類型不符。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a HyperMetroPair."
msgstr "無法將 LUN %s 匯入 Cinder。它已經存在於 HyperMetroPair 中。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a LUN copy task."
msgstr "無法將 LUN %s 匯入 Cinder。它已經存在於 LUN 複製作業中。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a LUN group."
msgstr "無法將 LUN %s 匯入 Cinder。它已經存在於某個 LUN 群組中。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a LUN mirror."
msgstr "無法將 LUN %s 匯入 Cinder。它已經存在於某個 LUN 鏡映中。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a SplitMirror."
msgstr "無法將 LUN %s 匯入 Cinder。它已經存在於 SplitMirror 中。"

#, python-format
msgid "Can't import LUN %s to Cinder. Already exists in a migration task."
msgstr "無法將 LUN %s 匯入 Cinder。它已經存在於移轉作業中。"

#, python-format
msgid ""
"Can't import LUN %s to Cinder. Already exists in a remote replication task."
msgstr "無法將 LUN %s 匯入 Cinder。它已經存在於遠端抄寫作業中。"

#, python-format
msgid "Can't import LUN %s to Cinder. LUN status is not normal."
msgstr "無法將 LUN %s 匯入 Cinder。LUN 未處於正常狀態。"

#, python-format
msgid "Can't import snapshot %s to Cinder. Snapshot doesn't belong to volume."
msgstr "無法將 Snapshot %s 匯入 Cinder。Snapshot 不屬於磁區。"

#, python-format
msgid "Can't import snapshot %s to Cinder. Snapshot is exposed to initiator."
msgstr "無法將 Snapshot %s 匯入 Cinder。已將 Snapshot 向起始器公開。"

#, python-format
msgid ""
"Can't import snapshot %s to Cinder. Snapshot status is not normal or running "
"status is not online."
msgstr ""
"無法將 Snapshot %s 匯入 Cinder。Snapshot 未處於正常狀態，或者執行中狀態不在線"
"上。"

msgid "Can't parse backup record."
msgstr "無法剖析備份記錄。"

msgid "Cannot change VF context in the session."
msgstr "無法變更階段作業中的 VF 環境定義。"

#, python-format
msgid ""
"Cannot change VF context, specified VF is not available in the manageable VF "
"list %(vf_list)s."
msgstr ""
"無法變更 VF 環境定義，在可管理的 VF 清單 %(vf_list)s 中無法使用指定的 VF。"

#, python-format
msgid "Cannot create directory %s."
msgstr "無法建立目錄 %s。"

msgid "Cannot create encryption specs. Volume type in use."
msgstr "無法建立加密規格。磁區類型在使用中。"

#, python-format
msgid ""
"Cannot create image of disk format: %s. Only vmdk disk format is accepted."
msgstr "無法建立磁碟格式為 %s 的映像檔。僅接受 VMDK 磁碟格式。"

#, python-format
msgid "Cannot create volume of size %s: not multiple of 8GB."
msgstr "無法建立大小為 %s 的磁區：不是 8 GB 的倍數。"

#, python-format
msgid "Cannot create volume_type with name %(name)s and specs %(extra_specs)s"
msgstr "無法使用名稱 %(name)s 及規格 %(extra_specs)s 來建立 volume_type"

#, python-format
msgid ""
"Cannot delete cache volume: %(cachevol_name)s. It was updated at "
"%(updated_at)s and currently has %(numclones)d volume instances."
msgstr ""
"無法刪除快取磁區：%(cachevol_name)s。該快取磁區已在 %(updated_at)s 得到更新，"
"且目前具有 %(numclones)d 個磁區實例。"

#, python-format
msgid ""
"Cannot delete cache volume: %(cachevol_name)s. It was updated at "
"%(updated_at)s and currently has %(numclones)s volume instances."
msgstr ""
"無法刪除快取磁區：%(cachevol_name)s。該快取磁區已在 %(updated_at)s 得到更新，"
"且目前具有 %(numclones)s 個磁區實例。"

msgid "Cannot delete encryption specs. Volume type in use."
msgstr "無法刪除加密規格。磁區類型在使用中。"

msgid "Cannot find migration task."
msgstr "找不到移轉作業。"

msgid "Cannot ping DRBDmanage backend"
msgstr "無法對 DRBDmanage 後端進行連線測試"

#, python-format
msgid ""
"Cannot provide both 'cgsnapshot_id' and 'source_cgid' to create consistency "
"group %(name)s from source."
msgstr ""
"無法同時提供 'cgsnapshot_id' 和 'source_cgid'，以從來源建立一致性群組 "
"%(name)s。"

msgid "Cannot register resource"
msgstr "無法登錄資源"

msgid "Cannot register resources"
msgstr "無法登錄資源"

#, python-format
msgid "Cannot retype from HPE3PARDriver to %s."
msgstr "HPE3PARDriver 無法透過執行 Retype 動作變為 %s。"

msgid "Cannot retype from one 3PAR array to another."
msgstr "一個 3PAR 陣列無法透過執行 Retype 動作變為另一個陣列。"

msgid "Cannot retype to a CPG in a different domain."
msgstr "無法執行 Retype 動作，以變為不同網域中的 CPG。"

msgid "Cannot retype to a snap CPG in a different domain."
msgstr "無法執行 Retype 動作，以變為不同網域中的 snapCPG。"

msgid "Cannot specify both protection domain name and protection domain id."
msgstr "不能同時指定保護網域名稱及保護網域 ID。"

msgid "Cannot specify both storage pool name and storage pool id."
msgstr "不能同時指定儲存區名稱及儲存區 ID。"

msgid "Cannot update encryption specs. Volume type in use."
msgstr "無法更新加密規格。磁區類型在使用中。"

#, python-format
msgid "Cannot update volume_type %(id)s"
msgstr "無法更新 volume_type %(id)s"

#, python-format
msgid "CgSnapshot %(cgsnapshot_id)s could not be found."
msgstr "找不到 CgSnapshot %(cgsnapshot_id)s。"

msgid "Change hostlun id error."
msgstr "變更主機 LUN ID 時發生錯誤。"

msgid "Change lun priority error."
msgstr "變更 LUN 優先順序時發生錯誤。"

msgid "Change lun smarttier policy error."
msgstr "變更 LUN smarttier 原則時發生錯誤。"

#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: %(unders)s"
msgstr "變更會使下列資源的用量小於 0：%(unders)s"

msgid "Check access permissions for the ZFS share assigned to this driver."
msgstr "請檢查指派給此驅動程式之 ZFS 共用的存取權限。"

msgid "Check hostgroup associate error."
msgstr "檢查主機群組關聯時發生錯誤。"

msgid "Check initiator added to array error."
msgstr "檢查已新增至陣列的起始器時發生錯誤。"

msgid "Check initiator associated to host error."
msgstr "檢查與主機相關聯的起始器時發生錯誤。"

msgid "Check lungroup associate error."
msgstr "檢查 LUN 群組關聯時發生錯誤。"

msgid "Check portgroup associate error."
msgstr "檢查埠群組關聯時發生錯誤。"

msgid ""
"Check the state of the http service. Also ensure that the https port number "
"is the same as the one specified in cinder.conf."
msgstr ""
"請檢查 HTTP 服務的狀態。同時確保 HTTPS 埠號與 cinder.conf 中指定的埠號相同。"

msgid "Chunk size is not multiple of block size for creating hash."
msgstr "片段大小不是用於建立雜湊之區塊大小的倍數。"

#, python-format
msgid "Cisco Fibre Channel Zoning CLI error: %(reason)s"
msgstr "Cisco 光纖通道分區 CLI 錯誤：%(reason)s"

#, python-format
msgid ""
"Clone type '%(clone_type)s' is invalid; valid values are: '%(full_clone)s' "
"and '%(linked_clone)s'."
msgstr ""
"複製類型 '%(clone_type)s' 無效；有效值為：'%(full_clone)s' 和 "
"'%(linked_clone)s'。"

msgid ""
"Cluster is not formatted. You should probably perform \"dog cluster format\"."
msgstr "叢集未格式化。您可能應該執行 \"dog cluster format\"。"

#, python-format
msgid "CommandLineHelper._wait_for_condition: %s timeout."
msgstr "CommandLineHelper._wait_for_condition：%s 逾時。"

msgid "Compression Enabler is not installed. Can not create compressed volume."
msgstr "未安裝「壓縮啟用程式」。無法建立已壓縮的磁區。"

#, python-format
msgid "Compute cluster: %(cluster)s not found."
msgstr "找不到計算叢集：%(cluster)s。"

msgid "Condition has no field."
msgstr "條件不含任何欄位。"

#, python-format
msgid "Config 'max_over_subscription_ratio' invalid. Must be > 0: %s"
msgstr "配置 'max_over_subscription_ratio' 無效。必需大於 0：%s"

msgid "Configuration error: dell_sc_ssn not set."
msgstr "配置錯誤：未設定 dell_sc_ssn。"

msgid "Configuration is not found."
msgstr "找不到配置。"

#, python-format
msgid "Configuration value %s is not set."
msgstr "未設定配置值 %s。"

#, python-format
msgid ""
"Conflicting QoS specifications in volume type %s: when QoS spec is "
"associated to volume type, legacy \"netapp:qos_policy_group\" is not allowed "
"in the volume type extra specs."
msgstr ""
"磁區類型 %s 中存在衝突的服務品質規格：將服務品質規格關聯至磁區類型時，不容許"
"在磁區類型額外規格中使用舊式 \"netapp:qos_policy_group\"。"

#, python-format
msgid "Connection to glance failed: %(reason)s"
msgstr "Glance 連線失敗：%(reason)s"

#, python-format
msgid "Connection to swift failed: %(reason)s"
msgstr "Swift 連線失敗：%(reason)s"

#, python-format
msgid "Connector does not provide: %s"
msgstr "連接器未提供：%s"

#, python-format
msgid "Connector doesn't have required information: %(missing)s"
msgstr "連接器沒有必要資訊：%(missing)s"

#, python-format
msgid "ConsistencyGroup %(consistencygroup_id)s could not be found."
msgstr "找不到 ConsistencyGroup %(consistencygroup_id)s。"

msgid "Container"
msgstr "容器"

msgid "Container size smaller than required file size."
msgstr "儲存器大小小於必要的檔案大小。"

#, python-format
msgid "Converted to %(f1)s, but format is now %(f2)s"
msgstr "已轉換為 %(f1)s，但格式現在為 %(f2)s"

#, python-format
msgid "Converted to %(vol_format)s, but format is now %(file_format)s"
msgstr "已轉換為 %(vol_format)s，但格式現在為 %(file_format)s"

#, python-format
msgid "Converted to raw, but format is now %s"
msgstr "已轉換為原始，但格式現在為 %s"

#, python-format
msgid "Converted to raw, but format is now %s."
msgstr "已轉換為原始，但格式現在為 %s。"

msgid "Coordinator uninitialized."
msgstr "協調者未起始設定。"

#, python-format
msgid ""
"Copy volume task failed: convert_to_base_volume: id=%(id)s, status="
"%(status)s."
msgstr ""
"複製磁區作業失敗：convert_to_base_volume：ID = %(id)s、狀態 = %(status)s。"

#, python-format
msgid ""
"Copy volume task failed: create_cloned_volume id=%(id)s, status=%(status)s."
msgstr ""
"複製磁區作業失敗：create_cloned_volume ID = %(id)s，狀態 = %(status)s。"

#, python-format
msgid "Copying metadata from %(src_type)s %(src_id)s to %(vol_id)s."
msgstr "正在將 meta 資料從 %(src_type)s %(src_id)s 複製到 %(vol_id)s。"

msgid ""
"Could not determine which Keystone endpoint to use. This can either be set "
"in the service catalog or with the cinder.conf config option "
"'backup_swift_auth_url'."
msgstr ""
"無法判定要使用的 Keystone 端點。這可以在服務型錄中進行設定，也可以使用 "
"cinder.conf 配置選項 'backup_swift_auth_url' 進行設定。"

msgid ""
"Could not determine which Swift endpoint to use. This can either be set in "
"the service catalog or with the cinder.conf config option 'backup_swift_url'."
msgstr ""
"無法判定要使用的 Swift 端點。這可以在服務型錄中進行設定，也可以使用 cinder."
"conf 配置選項 'backup_swift_url' 進行設定。"

#, python-format
msgid "Could not find GPFS cluster id: %s."
msgstr "找不到 GPFS 叢集 ID：%s。"

#, python-format
msgid "Could not find GPFS file system device: %s."
msgstr "找不到 GPFS 檔案系統裝置：%s。"

#, python-format
msgid "Could not find config at %(path)s"
msgstr "在 %(path)s 處找不到配置"

#, python-format
msgid "Could not find iSCSI export for volume %s"
msgstr "找不到磁區 %s 的 iSCSI 匯出"

#, python-format
msgid "Could not find key in output of command %(cmd)s: %(out)s."
msgstr "在指令 %(cmd)s 的輸出 %(out)s 中找不到索引鍵。"

#, python-format
msgid "Could not find parameter %(param)s"
msgstr "找不到參數 %(param)s"

#, python-format
msgid "Could not find target %s"
msgstr "找不到目標 %s"

#, python-format
msgid "Could not find the parent volume for Snapshot '%s' on array."
msgstr "在陣列上，找不到 Snapshot '%s' 的母項磁區。"

#, python-format
msgid "Could not find unique snapshot %(snap)s on volume %(vol)s."
msgstr "在磁區 %(vol)s 上找不到唯一的 Snapshot %(snap)s。"

msgid "Could not get system name."
msgstr "無法取得系統名稱。"

#, python-format
msgid ""
"Could not read information for snapshot %(name)s. Code: %(code)s. Reason: "
"%(reason)s"
msgstr "無法讀取 Snapshot %(name)s 的資訊。程式碼：%(code)s。原因：%(reason)s"

#, python-format
msgid "Could not restore configuration file %(file_path)s: %(exc)s"
msgstr "無法還原配置檔 %(file_path)s：%(exc)s"

#, python-format
msgid "Could not save configuration to %(file_path)s: %(exc)s"
msgstr "無法將配置儲存至 %(file_path)s：%(exc)s"

#, python-format
msgid "Could not start consistency group snapshot %s."
msgstr "無法啟動一致性群組 Snapshot %s。"

#, python-format
msgid "Counter %s not found"
msgstr "找不到計數器 %s"

msgid "Create QoS policy error."
msgstr "建立服務品質原則時發生錯誤。"

#, python-format
msgid ""
"Create backup aborted, expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"已中止建立備份，預期備份狀態 %(expected_status)s，但取得 %(actual_status)s。"

#, python-format
msgid ""
"Create backup aborted, expected volume status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"已中斷建立備份，預期磁區狀態 %(expected_status)s，但取得 %(actual_status)s。"

msgid "Create hostgroup error."
msgstr "建立主機群組時發生錯誤。"

#, python-format
msgid "Create hypermetro error. %s."
msgstr "建立 hypermetro 時發生錯誤。%s。"

msgid "Create lun error."
msgstr "建立 LUN 時發生錯誤。"

msgid "Create lun migration error."
msgstr "建立 LUN 移轉時發生錯誤。"

msgid "Create luncopy error."
msgstr "建立 LUNcopy 時發生錯誤。"

msgid "Create lungroup error."
msgstr "建立 LUN 群組時發生錯誤。"

msgid "Create manager volume flow failed."
msgstr "建立管理程式磁區流程失敗。"

msgid "Create port group error."
msgstr "建立埠群組時發生錯誤。"

msgid "Create replication error."
msgstr "建立抄寫時發生錯誤。"

#, python-format
msgid "Create replication pair failed. Error: %s."
msgstr "建立抄寫配對失敗。錯誤：%s。"

msgid "Create snapshot error."
msgstr "建立 Snapshot 時發生錯誤。"

#, python-format
msgid "Create volume error. Because %s."
msgstr "建立磁區時發生錯誤。因為 %s。"

msgid "Create volume failed."
msgstr "建立磁區失敗。"

#, python-format
msgid ""
"Creating and activating zone set failed: (Zone set=%(cfg_name)s error="
"%(err)s)."
msgstr "建立及啟動區域集時失敗：（區域集 = %(cfg_name)s 錯誤 = %(err)s）。"

#, python-format
msgid ""
"Creating and activating zone set failed: (Zone set=%(zoneset)s error="
"%(err)s)."
msgstr "建立及啟動區域集時失敗：（區域集 = %(zoneset)s 錯誤 = %(err)s）。"

#, python-format
msgid ""
"DRBDmanage driver error: expected key \"%s\" not in answer, wrong DRBDmanage "
"version?"
msgstr ""
"DRBDmanage 驅動程式錯誤：應答中沒有預期的索引鍵 \"%s\"，DRBDmanage 版本是否錯"
"誤？"

msgid ""
"DRBDmanage driver setup error: some required libraries (dbus, drbdmanage.*) "
"not found."
msgstr ""
"DRBDmanage 驅動程式設定錯誤：找不到部分必要程式庫（dbus、drbdmanage.*）。"

#, python-format
msgid "DRBDmanage expected one resource (\"%(res)s\"), got %(n)d"
msgstr "DRBDmanage 預期一個資源 (\"%(res)s\")，但卻取得 %(n)d"

#, python-format
msgid ""
"DRBDmanage timeout waiting for new volume after snapshot restore; resource "
"\"%(res)s\", volume \"%(vol)s\""
msgstr ""
"在 Snapshot 還原之後等待新磁區時，DRBDmanage 逾時；資源 \"%(res)s\"，磁區 "
"\"%(vol)s\""

#, python-format
msgid ""
"DRBDmanage timeout waiting for snapshot creation; resource \"%(res)s\", "
"snapshot \"%(sn)s\""
msgstr ""
"等待建立 Snapshot 時，DRBDmanage 逾時；資源 \"%(res)s\"，Snapshot \"%(sn)s\""

#, python-format
msgid ""
"DRBDmanage timeout waiting for volume creation; resource \"%(res)s\", volume "
"\"%(vol)s\""
msgstr "等待建立磁區時，DRBDmanage 逾時；資源 \"%(res)s\"，磁區 \"%(vol)s\""

#, python-format
msgid ""
"DRBDmanage timeout waiting for volume size; volume ID \"%(id)s\" (res "
"\"%(res)s\", vnr %(vnr)d)"
msgstr ""
"等待磁區大小時，DRBDmanage 逾時；磁區 ID \"%(id)s\"（資源 \"%(res)s\"，VNR "
"%(vnr)d）"

#, python-format
msgid "Dataset %s is not shared in Nexenta Store appliance"
msgstr "資料集 %s 未在「Nexenta 儲存庫」軟體驅動裝置中共用"

#, python-format
msgid "Dataset group %s not found at Nexenta SA"
msgstr "在 Nexenta SA 中，找不到資料集群組 %s"

#, python-format
msgid ""
"Dedup is a valid provisioning type, but requires WSAPI version "
"'%(dedup_version)s' version '%(version)s' is installed."
msgstr ""
"Dedup 是有效的供應類型，但需要 WSAPI '%(dedup_version)s' 版，已安裝 "
"'%(version)s' 版。"

#, python-format
msgid ""
"Default quota for resource: %(res)s is set by the default quota flag: quota_"
"%(res)s, it is now deprecated. Please use the default quota class for "
"default quota."
msgstr ""
"資源 %(res)s 的預設配額是由預設配額旗標quota_%(res)s 所設定，但它現已淘汰。請"
"將預設配額類別用於預設配額。"

msgid "Default volume type can not be found."
msgstr "找不到預設磁區類型。"

msgid "Delete LUNcopy error."
msgstr "刪除 LUNcopy 時發生錯誤。"

msgid "Delete QoS policy error."
msgstr "刪除服務品質原則時發生錯誤。"

msgid "Delete associated lun from lungroup error."
msgstr "從 LUN 群組中刪除相關聯的 LUN 時發生錯誤。"

#, python-format
msgid ""
"Delete backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"已中止刪除備份，目前配置的備份服務[%(configured_service)s] 不是建立此備份所使"
"用的備份服務 [%(backup_service)s]。"

msgid "Delete hostgroup error."
msgstr "刪除主機群組時發生錯誤。"

msgid "Delete hostgroup from mapping view error."
msgstr "從對映視圖中刪除主機群組時發生錯誤。"

msgid "Delete lun error."
msgstr "刪除 LUN 時發生錯誤。"

msgid "Delete lun migration error."
msgstr "刪除 LUN 移轉時發生錯誤。"

msgid "Delete lungroup error."
msgstr "刪除 LUN 群組時發生錯誤。"

msgid "Delete lungroup from mapping view error."
msgstr "從對映視圖中刪除 LUN 群組時發生錯誤。"

msgid "Delete mapping view error."
msgstr "刪除對映視圖時發生錯誤。"

msgid "Delete port group error."
msgstr "刪除埠群組時發生錯誤。"

msgid "Delete portgroup from mapping view error."
msgstr "從對映視圖中刪除埠群組時發生錯誤。"

msgid "Delete snapshot error."
msgstr "刪除 Snapshot 時發生錯誤。"

#, python-format
msgid "Delete snapshot of volume not supported in state: %s."
msgstr "狀態 %s 不支援刪除磁區的 Snapshot。"

#, python-format
msgid ""
"Delete_backup aborted, expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"Delete_backup 已中止，預期備份狀態 %(expected_status)s，但取得 "
"%(actual_status)s。"

msgid "Deleting volume from database and skipping rpc."
msgstr "正在從資料庫刪除磁區並跳過 RPC。"

#, python-format
msgid "Deleting zones failed: (command=%(cmd)s error=%(err)s)."
msgstr "刪除區域時失敗：（指令 = %(cmd)s 錯誤 = %(err)s）。"

msgid "Dell API 2.1 or later required for Consistency Group support"
msgstr "一致性群組支援需要 Dell API 2.1 或更新版本"

msgid ""
"Dell Cinder driver configuration error replication not supported with direct "
"connect."
msgstr "Dell Cinder 驅動程式配置錯誤，直接連接不支援抄寫。"

#, python-format
msgid "Dell Cinder driver configuration error replication_device %s not found"
msgstr "Dell Cinder 驅動程式配置錯誤，找不到 replication_device %s。"

#, python-format
msgid "Destination has migration_status %(stat)s, expected %(exp)s."
msgstr "目的地具有 migration_status %(stat)s，預期狀態為 %(exp)s。"

msgid "Destination volume not mid-migration."
msgstr "移轉期間找不到目的地磁區。"

msgid ""
"Detach volume failed: More than one attachment, but no attachment_id "
"provided."
msgstr "分離磁區失敗：存在多個連接，但卻未提供attachment_id。"

msgid "Detach volume from instance and then try again."
msgstr "請從實例分離磁區，然後再試一次。"

#, python-format
msgid "Detected more than one volume with name %(vol_name)s"
msgstr "已偵測到多個名稱為 %(vol_name)s 的磁區"

#, python-format
msgid "Did not find expected column in %(fun)s: %(hdr)s."
msgstr "在 %(fun)s 中找不到預期的直欄：%(hdr)s。"

#, python-format
msgid "Did not find the expected key %(key)s in %(fun)s: %(raw)s."
msgstr "在 %(fun)s 中找不到預期的索引鍵 %(key)s：%(raw)s。"

#, python-format
msgid "Domain with name %s wasn't found."
msgstr "找不到名稱為 %s 的網域。"

#, python-format
msgid ""
"Downlevel GPFS Cluster Detected.  GPFS Clone feature not enabled in cluster "
"daemon level %(cur)s - must be at least at level %(min)s."
msgstr ""
"偵測到舊版 GPFS 叢集。「GPFS 副本」特性未在叢集常駐程式層次 %(cur)s 啟用 - 必"
"須至少是層次 %(min)s。"

#, python-format
msgid "Driver initialize connection failed (error: %(err)s)."
msgstr "驅動程式起始設定連線失敗（錯誤：%(err)s）。"

msgid "Driver must implement initialize_connection"
msgstr "驅動程式必須實作 initialize_connection"

#, python-format
msgid ""
"Driver successfully decoded imported backup data, but there are missing "
"fields (%s)."
msgstr "驅動程式已順利將匯入的備份資料解碼，但是有遺漏的欄位 (%s)。"

#, python-format
msgid ""
"EMC VNX Cinder Driver CLI exception: %(cmd)s (Return Code: %(rc)s) (Output: "
"%(out)s)."
msgstr ""
"EMC VNX Cinder 驅動程式 CLI 異常狀況：%(cmd)s（回覆碼：%(rc)s）（輸出："
"%(out)s）。"

#, python-format
msgid ""
"EMC VNX Cinder Driver SPUnavailableException: %(cmd)s (Return Code: %(rc)s) "
"(Output: %(out)s)."
msgstr ""
"EMC VNX Cinder 驅動程式 SPUnavailableException：%(cmd)s（回覆碼：%(rc)s）（輸"
"出：%(out)s）。"

#, python-format
msgid ""
"Either 'cgsnapshot_id' or 'source_cgid' must be provided to create "
"consistency group %(name)s from source."
msgstr ""
"必須提供 'cgsnapshot_id' 或 'source_cgid'，才能從來源建立一致性群組 "
"%(name)s。"

#, python-format
msgid ""
"Either SLO: %(slo)s or workload %(workload)s is invalid. Examine previous "
"error statement for valid values."
msgstr ""
"SLO %(slo)s 或工作量 %(workload)s 無效。請檢查前一個錯誤陳述式以取得有效的"
"值。"

msgid "Enables QoS."
msgstr "啟用服務品質。"

msgid "Enables compression."
msgstr "啟用壓縮。"

msgid "Enables replication."
msgstr "啟用抄寫。"

msgid "Ensure that configfs is mounted at /sys/kernel/config."
msgstr "請確保 configfs 已裝載於 /sys/kernel/config 中。"

#, python-format
msgid ""
"Error Adding Initiator: %(initiator)s on groupInitiatorGroup: "
"%(initiatorgroup)s Return code: %(ret.status)d Message: %(ret.data)s ."
msgstr ""
"在下列 groupInitiatorGroup 上新增起始器 %(initiator)s 時發生錯誤："
"%(initiatorgroup)s。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Adding to TargetGroup: %(targetgroup)s withIQN: %(iqn)sReturn code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"新增至帶 IQN %(iqn)s 的目標群組 %(targetgroup)s 時發生錯誤。回覆碼："
"%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Cloning Snapshot: %(snapshot)s on Volume: %(lun)s of Pool: %(pool)s "
"Project: %(project)s  Clone project: %(clone_proj)s Return code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"在儲存區 %(pool)s 的磁區 %(lun)s 上複製 Snapshot：%(snapshot)s 時發生錯誤專"
"案：%(project)s，副本專案：%(clone_proj)s，回覆碼：%(ret.status)d。訊息："
"%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Initiator: %(initiator)s on Alias: %(alias)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"在別名 %(alias)s 上建立起始器 %(initiator)s 時發生錯誤。回覆碼："
"%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Project: %(project)s on Pool: %(pool)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"在儲存區 %(pool)s 上建立專案 %(project)s 時發生錯誤。回覆碼：%(ret.status)d。"
"訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Property: %(property)s Type: %(type)s Description: "
"%(description)s Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"建立內容 %(property)s 類型 %(type)s 說明%(description)s 時發生錯誤。回覆碼："
"%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Share: %(name)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"建立共用 %(name)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Snapshot: %(snapshot)s onVolume: %(lun)s to Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在儲存區 %(pool)s 的磁區 %(lun)s 上建立 Snapshot：%(snapshot)s 時發生錯誤專"
"案：%(project)s。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Snapshot: %(snapshot)s onshare: %(share)s to Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在下列儲存區的共用 %(share)s 上建立 Snapshot %(snapshot)s 時發生錯誤："
"%(pool)s 專案：%(project)s  回覆碼：%(ret.status)d 訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Target: %(alias)sReturn code: %(ret.status)d Message: "
"%(ret.data)s ."
msgstr ""
"建立目標 %(alias)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating TargetGroup: %(targetgroup)s withIQN: %(iqn)sReturn code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"建立帶 IQN %(iqn)s 的目標群組 %(targetgroup)s 時發生錯誤。回覆碼："
"%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Creating Volume: %(lun)s Size: %(size)s Return code: %(ret.status)d "
"Message: %(ret.data)s."
msgstr ""
"建立磁區 %(lun)s 時發生錯誤。大小：%(size)s。回覆碼：%(ret.status)d。訊息："
"%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting Snapshot: %(snapshot)s on Share: %(share)s to Pool: %(pool)s "
"Project: %(project)s Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在下列儲存區的共用 %(share)s 上刪除 Snapshot %(snapshot)s 時發生錯誤："
"%(pool)s 專案：%(project)s 回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting Snapshot: %(snapshot)s on Volume: %(lun)s to Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在下列儲存區的磁區 %(lun)s 上刪除 Snapshot：%(snapshot)s 時發生錯誤："
"%(pool)s 專案：%(project)s  回覆碼：%(ret.status)d 訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting Volume: %(lun)s from Pool: %(pool)s, Project: %(project)s. "
"Return code: %(ret.status)d, Message: %(ret.data)s."
msgstr ""
"從儲存區 %(pool)s 刪除磁區 %(lun)s 時發生錯誤，專案 %(project)s。回覆碼："
"%(ret.status)d，訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting project: %(project)s on pool: %(pool)s Return code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"刪除儲存區 %(pool)s 上的專案 %(project)s 時發生錯誤。回覆碼：%(ret.status)d。"
"訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Deleting replication action: %(id)s Return code: %(ret.status)d "
"Message: %(ret.data)s."
msgstr ""
"刪除抄寫動作 %(id)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Initiators: InitiatorGroup: %(initiatorgroup)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"取得起始器時發生錯誤：InitiatorGroup：%(initiatorgroup)s 回覆碼："
"%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Pool Stats: Pool: %(pool)s Return code: %(status)d Message: "
"%(data)s."
msgstr ""
"取得儲存區統計資料時發生錯誤：儲存區：%(pool)s，回覆碼：%(status)d，訊息："
"%(data)s。"

#, python-format
msgid ""
"Error Getting Project Stats: Pool: %(pool)s Project: %(project)s Return "
"code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"取得專案統計資料時發生錯誤：儲存區：%(pool)s，專案：%(project)s，回覆碼："
"%(ret.status)d，訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Share: %(share)s on Pool: %(pool)s Project: %(project)s Return "
"code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"取得儲存區 %(pool)s 上的共用 %(share)s 時發生錯誤。專案：%(project)s回覆碼："
"%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Target: %(alias)sReturn code: %(ret.status)d Message: "
"%(ret.data)s ."
msgstr ""
"取得目標 %(alias)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Getting Volume: %(lun)s on Pool: %(pool)s Project: %(project)s Return "
"code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"取得儲存區 %(pool)s 上的磁區 %(lun)s 時發生錯誤。專案：%(project)s。回覆碼："
"%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid "Error Pool ownership: Pool %(pool)s is not owned by %(host)s."
msgstr "錯誤的儲存區所有權：儲存區 %(pool)s 不歸 %(host)s 擁有。"

#, python-format
msgid ""
"Error Setting props Props: %(props)s on Volume: %(lun)s of Pool: %(pool)s "
"Project: %(project)s  Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在儲存區 %(pool)s 的磁區 %(lun)s 上設定內容 Props：%(props)s 時發生錯誤專案："
"%(project)s。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Initiator: %(iqn)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"驗證起始器 %(iqn)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Pool: %(pool)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"驗證儲存區 %(pool)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Project: %(project)s on Pool: %(pool)s Return code: "
"%(ret.status)d Message: %(ret.data)s."
msgstr ""
"在儲存區 %(pool)s 上驗證專案 %(project)s 時發生錯誤。回覆碼：%(ret.status)d。"
"訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Service: %(service)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"驗證服務 %(service)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying Target: %(alias)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"驗證目標 %(alias)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error Verifying share: %(share)s on Project: %(project)s and Pool: %(pool)s "
"Return code: %(ret.status)d Message: %(ret.data)s."
msgstr ""
"在專案 %(project)s 及儲存區 %(pool)s 上驗證共用 %(share)s 時發生錯誤。回覆"
"碼：%(ret.status)d，訊息：%(ret.data)s。"

msgid "Error connecting to ceph cluster."
msgstr "連接至 ceph 叢集時發生錯誤。"

#, python-format
msgid "Error connecting via ssh: %s"
msgstr "透過 SSH 進行連接時發生錯誤：%s"

#, python-format
msgid "Error creating volume: %s."
msgstr "建立磁區時發生錯誤：%s。"

msgid "Error deleting replay profile."
msgstr "刪除重播設定檔時發生錯誤。"

#, python-format
msgid "Error deleting volume %(ssn)s: %(volume)s"
msgstr "刪除磁區 %(ssn)s 時發生錯誤：%(volume)s"

#, python-format
msgid "Error deleting volume %(vol)s: %(err)s."
msgstr "刪除磁區 %(vol)s 時發生錯誤：%(err)s。"

#, python-format
msgid "Error during evaluator parsing: %(reason)s"
msgstr "評估器剖析期間發生錯誤：%(reason)s"

#, python-format
msgid ""
"Error editing share: %(share)s on Pool: %(pool)s Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"編輯儲存區 %(pool)s 上的共用 %(share)s 時發生錯誤。回覆碼：%(ret.status)d。訊"
"息：%(ret.data)s。"

#, python-format
msgid ""
"Error enabling iSER for NetworkPortal: please ensure that RDMA is supported "
"on your iSCSI port %(port)d on ip %(ip)s."
msgstr ""
"對 NetworkPortal 啟用 iSER 時發生錯誤：請確保 RDMA 在 IP %(ip)s 的 iSCSI 埠 "
"%(port)d 上受支援。"

#, python-format
msgid "Error encountered during cleanup of a failed attach: %(ex)s"
msgstr "清除失敗連接期間發生錯誤：%(ex)s"

#, python-format
msgid "Error executing command via ssh: %s"
msgstr "透過 SSH 來執行指令時發生錯誤：%s"

#, python-format
msgid "Error extending volume %(vol)s: %(err)s."
msgstr "延伸磁區 %(vol)s 時發生錯誤：%(err)s。"

#, python-format
msgid "Error extending volume: %(reason)s"
msgstr "延伸磁區時發生錯誤：%(reason)s"

#, python-format
msgid "Error finding %(name)s."
msgstr "尋找 %(name)s 時發生錯誤。"

msgid ""
"Error getting appliance version details. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"取得軟體驅動裝置版本詳細資料時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret."
"data)s。"

#, python-format
msgid "Error getting domain id from name %(name)s: %(id)s."
msgstr "從名稱 %(name)s 取得網域 ID 時發生錯誤：%(id)s。"

msgid "Error getting initiator groups."
msgstr "取得起始器群組時發生錯誤。"

#, python-format
msgid "Error getting pool id from name %(pool_name)s: %(err_msg)s."
msgstr "從名稱 %(pool_name)s 取得儲存區 ID 時發生錯誤：%(err_msg)s。"

#, python-format
msgid ""
"Error getting replication action: %(id)s. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"取得抄寫動作 %(id)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

msgid ""
"Error getting replication source details. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"取得抄寫來源詳細資料時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

msgid ""
"Error getting replication target details. Return code: %(ret.status)d "
"Message: %(ret.data)s ."
msgstr ""
"取得抄寫目標詳細資料時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error getting version: svc: %(svc)s.Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"取得版本時發生錯誤：SVC：%(svc)s。回覆碼：%(ret.status)d 訊息：%(ret.data)s。"

#, python-format
msgid "Error in SolidFire API response: data=%(data)s"
msgstr "SolidFire API 回應發生錯誤：資料 = %(data)s"

#, python-format
msgid "Error managing volume: %s."
msgstr "管理磁區時發生錯誤：%s。"

#, python-format
msgid ""
"Error modifying Service: %(service)s Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"修改服務 %(service)s 時發生錯誤。回覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error moving volume: %(vol)s from source project: %(src)s to target project: "
"%(tgt)s Return code: %(ret.status)d Message: %(ret.data)s ."
msgstr ""
"將磁區 %(vol)s 從來源專案 %(src)s 移至下列目標專案時發生錯誤：%(tgt)s。回覆"
"碼：%(ret.status)d。訊息：%(ret.data)s。"

msgid "Error not a KeyError."
msgstr "此錯誤不是 KeyError。"

msgid "Error not a TypeError."
msgstr "此錯誤不是 TypeError。"

#, python-format
msgid "Error renaming volume %(vol)s: %(err)s."
msgstr "重命名磁區 %(vol)s 時發生錯誤：%(err)s。"

#, python-format
msgid "Error response: %s"
msgstr "錯誤的回應：%s"

msgid "Error retrieving volume size"
msgstr "擷取磁區大小時發生錯誤"

#, python-format
msgid ""
"Error sending replication update for action id: %(id)s . Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"傳送動作識別碼 %(id)s 的抄寫更新時發生錯誤。回覆碼：%(ret.status)d。訊息："
"%(ret.data)s。"

#, python-format
msgid ""
"Error sending replication update. Returned error: %(err)s. Action: %(id)s."
msgstr "傳送抄寫更新時發生錯誤。傳回的錯誤：%(err)s。動作：%(id)s。"

#, python-format
msgid ""
"Error setting replication inheritance to %(set)s for volume: %(vol)s project "
"%(project)s Return code: %(ret.status)d Message: %(ret.data)s ."
msgstr ""
"針對磁區 %(vol)s，將抄寫繼承設定為 %(set)s 時發生錯誤，專案：%(project)s。回"
"覆碼：%(ret.status)d。訊息：%(ret.data)s。"

#, python-format
msgid ""
"Error severing the package: %(package)s from source: %(src)s Return code: "
"%(ret.status)d Message: %(ret.data)s ."
msgstr ""
"將套件 %(package)s 從來源 %(src)s 分離時發生錯誤。回覆碼：%(ret.status)d。訊"
"息：%(ret.data)s。"

#, python-format
msgid "Error while authenticating with switch: %s."
msgstr "對交換器進行鑑別時發生錯誤：%s。"

#, python-format
msgid "Error while changing VF context %s."
msgstr "變更 VF 環境定義 %s 時發生錯誤。"

#, python-format
msgid "Error while checking the firmware version %s."
msgstr "檢查韌體版本 %s 時發生錯誤。"

#, python-format
msgid "Error while checking transaction status: %s"
msgstr "檢查交易狀態時發生錯誤：%s"

#, python-format
msgid "Error while checking whether VF is available for management %s."
msgstr "檢查 VF 是否適用於管理 %s 時發生錯誤。"

#, python-format
msgid ""
"Error while connecting the switch %(switch_id)s with protocol %(protocol)s. "
"Error: %(error)s."
msgstr ""
"連接使用通訊協定 %(protocol)s 的交換器 %(switch_id)s 時發生錯誤。錯誤："
"%(error)s。"

#, python-format
msgid "Error while creating authentication token: %s"
msgstr "建立鑑別記號時發生錯誤：%s"

#, python-format
msgid "Error while getting data via ssh: (command=%(cmd)s error=%(err)s)."
msgstr "透過 SSH 取得資料時發生錯誤：（指令 = %(cmd)s 錯誤 = %(err)s）。"

#, python-format
msgid "Error while getting nvp value: %s."
msgstr "取得 NVP 值時發生錯誤：%s。"

#, python-format
msgid "Error while getting session information %s."
msgstr "取得階段作業資訊 %s 時發生錯誤。"

#, python-format
msgid "Error while parsing the data: %s."
msgstr "剖析資料時發生錯誤：%s。"

#, python-format
msgid "Error while querying page %(url)s on the switch, reason %(error)s."
msgstr "在交換器上查詢頁面 %(url)s 時發生錯誤，原因：%(error)s。"

#, python-format
msgid ""
"Error while removing the zones and cfgs in the zone string: %(description)s."
msgstr "移除區域字串中的區域和配置時發生錯誤：%(description)s。"

#, python-format
msgid "Error while requesting %(service)s API."
msgstr "要求 %(service)s API 時發生錯誤。"

#, python-format
msgid "Error while running zoning CLI: (command=%(cmd)s error=%(err)s)."
msgstr "執行分區 CLI 時發生錯誤：（指令 = %(cmd)s 錯誤 = %(err)s）。"

#, python-format
msgid ""
"Error while updating the new zones and cfgs in the zone string. Error "
"%(description)s."
msgstr "更新區域字串中的新區域和配置時發生錯誤。錯誤：%(description)s。"

msgid "Error writing field to database"
msgstr "將欄位寫入資料庫時發生錯誤"

msgid "Exceeded the limit of snapshots per volume"
msgstr "已超過每個磁區的 Snapshot 數目限制"

#, python-format
msgid "Exception in _select_ds_for_volume: %s."
msgstr "_select_ds_for_volume 發生異常狀況：%s。"

#, python-format
msgid "Exception while forming the zone string: %s."
msgstr "對區域字串進行格式化時發生異常狀況：%s。"

#, python-format
msgid "Exception: %s"
msgstr "異常狀況：%s"

#, python-format
msgid "Expected exactly one node called \"%s\""
msgstr "預期只有一個節點稱為 \"%s\""

#, python-format
msgid "Expected integer for node_count, svcinfo lsiogrp returned: %(node)s."
msgstr "node_count 預期整數，傳回了 svcinfo lsiogrp：%(node)s。"

#, python-format
msgid "Expected no output from CLI command %(cmd)s, got %(out)s."
msgstr "預期 CLI 指令 %(cmd)s 沒有任何輸出，但卻取得 %(out)s。"

#, python-format
msgid ""
"Expected single vdisk returned from lsvdisk when filtering on vdisk_UID.  "
"%(count)s were returned."
msgstr ""
"根據 vdisk_UID 來過濾時，預期從 lsvdisk 傳回單一 vdisk。傳回了 %(count)s 個。"

#, python-format
msgid "Expected volume size was %d"
msgstr "預期磁區大小為 %d"

#, python-format
msgid ""
"Export backup aborted, expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"已中止匯出備份，預期備份狀態 %(expected_status)s，但取得 %(actual_status)s。"

#, python-format
msgid ""
"Export record aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"已中止匯出記錄，目前配置的備份服務[%(configured_service)s] 不是建立此備份所使"
"用的備份服務 [%(backup_service)s]。"

msgid "Extend volume error."
msgstr "延伸磁區時發生錯誤。"

msgid "Extend volume not implemented"
msgstr "未實作延伸磁區"

msgid "FC is the protocol but wwpns are not supplied by OpenStack."
msgstr "FC 是通訊協定，但 OpenStack 未提供 WWPN。"

#, python-format
msgid "Faield to unassign %(volume)s"
msgstr "無法取消指派 %(volume)s"

#, python-format
msgid "Fail to create cache volume %(volume)s. Error: %(err)s"
msgstr "無法建立快取磁區 %(volume)s。錯誤：%(err)s"

#, python-format
msgid "Failed adding connection for fabric=%(fabric)s: Error: %(err)s"
msgstr "無法給架構 %(fabric)s 新增連線：錯誤：%(err)s"

#, python-format
msgid "Failed creating snapshot for group: %(response)s."
msgstr "無法為群組建立 Snapshot：%(response)s。"

#, python-format
msgid "Failed creating snapshot for volume %(volname)s: %(response)s."
msgstr "無法為磁區 %(volname)s 建立 Snapshot：%(response)s。"

#, python-format
msgid "Failed getting active zone set from fabric %s."
msgstr "無法從光纖 %s 取得作用中的區域集。"

#, python-format
msgid "Failed getting details for pool %s."
msgstr "無法取得儲存區 %s 的詳細資料。"

#, python-format
msgid "Failed removing connection for fabric=%(fabric)s: Error: %(err)s"
msgstr "無法移除架構 %(fabric)s 的連線：錯誤：%(err)s"

#, python-format
msgid "Failed to Extend Volume %(volname)s"
msgstr "無法延伸磁區 %(volname)s"

#, python-format
msgid "Failed to Login to 3PAR (%(url)s) because %(err)s"
msgstr "無法登入 3PAR (%(url)s)，原因：%(err)s"

msgid "Failed to access active zoning configuration."
msgstr "無法存取作用中的分區配置。"

#, python-format
msgid "Failed to access zoneset status:%s"
msgstr "無法存取區域集狀態：%s"

msgid "Failed to add zoning configuration."
msgstr "無法新增分區配置。"

#, python-format
msgid "Failed to associate qos_specs: %(specs_id)s with type %(type_id)s."
msgstr "無法使 qos_specs：%(specs_id)s 與類型 %(type_id)s 產生關聯。"

#, python-format
msgid "Failed to attach iSCSI target for volume %(volume_id)s."
msgstr "無法給磁區 %(volume_id)s 連接 iSCSI 目標。"

#, python-format
msgid "Failed to backup volume metadata - %s"
msgstr "無法備份磁區 meta 資料 - %s"

#, python-format
msgid ""
"Failed to backup volume metadata - Metadata backup object 'backup.%s.meta' "
"already exists"
msgstr "無法備份磁區 meta 資料 - meta 資料備份物件'backup.%s.meta' 已存在"

#, python-format
msgid "Failed to clone volume from snapshot %s."
msgstr "無法從 Snapshot %s 複製磁區。"

#, python-format
msgid "Failed to connect to %(vendor_name)s Array %(host)s: %(err)s"
msgstr "無法連接 %(vendor_name)s 陣列 %(host)s：%(err)s"

msgid "Failed to connect to Dell REST API"
msgstr "無法連接至 Dell REST API"

#, python-format
msgid "Failed to connect to sheep daemon. addr: %(addr)s, port: %(port)s"
msgstr "無法連接 sheep 常駐程式。位址：%(addr)s，埠：%(port)s"

#, python-format
msgid "Failed to copy image to volume: %(reason)s"
msgstr "無法將映像檔複製到磁區：%(reason)s"

#, python-format
msgid "Failed to copy metadata to volume: %(reason)s"
msgstr "無法將 meta 資料複製到磁區：%(reason)s"

msgid "Failed to copy volume, destination device unavailable."
msgstr "未能複製磁區，無法使用目的地裝置。"

msgid "Failed to copy volume, source device unavailable."
msgstr "未能複製磁區，無法使用來源裝置。"

#, python-format
msgid "Failed to create IG, %s"
msgstr "無法建立 IG %s"

#, python-format
msgid "Failed to create Volume Group: %(vg_name)s"
msgstr "無法建立磁區群組：%(vg_name)s"

msgid "Failed to create api volume flow."
msgstr "無法建立 API 磁區流程。"

#, python-format
msgid "Failed to create cg snapshot %(id)s due to %(reason)s."
msgstr "由於 %(reason)s，無法建立 cg Snapshot %(id)s。"

#, python-format
msgid "Failed to create consistency group %(id)s due to %(reason)s."
msgstr "由於 %(reason)s，無法建立一致性群組 %(id)s。"

#, python-format
msgid "Failed to create consistency group %(id)s:%(ret)s."
msgstr "無法建立一致性群組 %(id)s：%(ret)s。"

#, python-format
msgid "Failed to create consistency group: %(cgid)s. Error: %(excmsg)s."
msgstr "無法建立一致性群組 %(cgid)s。錯誤：%(excmsg)s。"

#, python-format
msgid ""
"Failed to create host: %(name)s. Please check if it exists on the array."
msgstr "無法建立主機：%(name)s。請檢查該主機在陣列上是否存在。"

#, python-format
msgid "Failed to create hostgroup: %(name)s. Check if it exists on the array."
msgstr "無法建立主機群組：%(name)s。請檢查該主機群組在陣列上是否存在。"

#, python-format
msgid "Failed to create iscsi target for volume %(volume_id)s."
msgstr "無法給磁區 %(volume_id)s 建立 iSCSI 目標。"

msgid "Failed to create manage existing flow."
msgstr "無法建立管理現有流程。"

msgid "Failed to create manage_existing flow."
msgstr "無法建立 manage_existing 流程。"

#, python-format
msgid "Failed to create metadata for volume: %(reason)s"
msgstr "無法給磁區建立 meta 資料：%(reason)s"

#, python-format
msgid "Failed to create qos_specs: %(name)s with specs %(qos_specs)s."
msgstr "無法使用規格 %(qos_specs)s 來建立 qos_specs：%(name)s。"

msgid "Failed to create scheduler manager volume flow"
msgstr "無法建立排定器管理程式磁區流程"

#, python-format
msgid "Failed to create snapshot %s"
msgstr "無法建立 Snapshot %s"

#, python-format
msgid "Failed to create snapshot for volume %s."
msgstr "無法建立磁區 %s 的 Snapshot。"

#, python-format
msgid "Failed to create south bound connector for %s."
msgstr "無法建立 %s 的南行連接器。"

#, python-format
msgid "Failed to create thin pool, error message was: %s"
msgstr "無法建立小型儲存區，錯誤訊息為：%s"

#, python-format
msgid "Failed to create volume %s"
msgstr "無法建立磁區 %s"

#, python-format
msgid "Failed to delete cgsnapshot %(id)s due to %(reason)s."
msgstr "由於 %(reason)s，無法刪除 cg Snapshot %(id)s。"

#, python-format
msgid "Failed to delete consistency group %(id)s due to %(reason)s."
msgstr "由於 %(reason)s，無法刪除一致性群組 %(id)s。"

#, python-format
msgid ""
"Failed to delete fileset for consistency group %(cgname)s. Error: %(excmsg)s."
msgstr "無法刪除一致性群組 %(cgname)s 的檔案集。錯誤：%(excmsg)s。"

#, python-format
msgid "Failed to delete snapshot %s"
msgstr "無法刪除 Snapshot %s"

#, python-format
msgid "Failed to detach iSCSI target for volume %(volume_id)s."
msgstr "無法分離磁區 %(volume_id)s 的 iSCSI 目標。"

msgid "Failed to disassociate qos specs."
msgstr "無法解除與服務品質規格的關聯。"

#, python-format
msgid "Failed to disassociate qos_specs: %(specs_id)s with type %(type_id)s."
msgstr "無法解除 qos_specs：%(specs_id)s 與類型 %(type_id)s 的關聯。"

#, python-format
msgid "Failed to export for volume: %(reason)s"
msgstr "無法針對磁區進行匯出：%(reason)s"

#, python-format
msgid "Failed to extend volume %(name)s, Error msg: %(msg)s."
msgstr "無法延伸現有磁區 %(name)s，錯誤訊息：%(msg)s。"

msgid "Failed to find QoSnode"
msgstr "找不到 QoSnode"

msgid "Failed to find Storage Center"
msgstr "找不到 Storage Center"

msgid "Failed to find a vdisk copy in the expected pool."
msgstr "在預期儲存區中找不到 vdisk 副本。"

msgid "Failed to find account for volume."
msgstr "找不到磁區的帳戶。"

#, python-format
msgid "Failed to find fileset for path %(path)s, command output: %(cmdout)s."
msgstr "找不到路徑 %(path)s 的檔案集，指令輸出：%(cmdout)s。"

#, python-format
msgid "Failed to find group snapshot named: %s"
msgstr "找不到名為 %s 的群組 Snapshot"

#, python-format
msgid "Failed to find host %s."
msgstr "找不到主機 %s。"

#, python-format
msgid "Failed to find iSCSI initiator group containing %(initiator)s."
msgstr "找不到包含 %(initiator)s 的 iSCSI 起始器群組。"

#, python-format
msgid "Failed to get LUN target details for the LUN %s"
msgstr "無法取得 LUN %s 的 LUN 目標詳細資料"

#, python-format
msgid "Failed to get LUN target list for the LUN %s"
msgstr "無法取得 LUN %s 的 LUN 目標清單"

msgid "Failed to get SplitMirror."
msgstr "無法取得 SplitMirror。"

#, python-format
msgid "Failed to get all associations of qos specs %s"
msgstr "無法取得服務品質規格 %s 的所有關聯"

#, python-format
msgid "Failed to get code level (%s)."
msgstr "無法取得程式碼層次 (%s)。"

#, python-format
msgid "Failed to get domain because CPG (%s) doesn't exist on array."
msgstr "無法取得網域，因為 CPG (%s) 不存在於陣列上。"

msgid "Failed to get image snapshots."
msgstr "無法取得映像檔 Snapshot。"

msgid "Failed to get migration task."
msgstr "無法取得移轉作業。"

msgid "Failed to get model update from clone"
msgstr "無法從複本取得模型更新"

msgid "Failed to get name server info."
msgstr "無法取得名稱伺服器資訊。"

msgid "Failed to get show fcns database info."
msgstr "無法取得「顯示 fcns」資料庫資訊。"

#, python-format
msgid "Failed to get size of volume %s"
msgstr "無法取得磁區 %s 的大小"

#, python-format
msgid "Failed to get snapshot for volume %s."
msgstr "無法取得磁區 %s 的 Snapshot。"

#, python-format
msgid "Failed to get target IQN for the LUN %s"
msgstr "無法取得 LUN %s 的目標 IQN"

msgid "Failed to get target LUN of SplitMirror."
msgstr "無法取得 SplitMirror 的目標 LUN。"

#, python-format
msgid "Failed to get target portal for the LUN %s"
msgstr "無法取得 LUN %s 的目標入口網站"

msgid "Failed to get targets"
msgstr "無法取得目標"

msgid "Failed to identify volume backend."
msgstr "無法識別磁區後端。"

#, python-format
msgid "Failed to link fileset for the share %(cgname)s. Error: %(excmsg)s."
msgstr "無法鏈結共用 %(cgname)s 的檔案集。錯誤：%(excmsg)s。"

#, python-format
msgid "Failed to log on %s Array (invalid login?)."
msgstr "無法登入 %s 陣列（無效登入？）。"

#, python-format
msgid "Failed to login for user %s."
msgstr "無法以使用者 %s 身分登入。"

msgid "Failed to login with all rest URLs."
msgstr "無法使用所有其餘 URL 進行登入。"

#, python-format
msgid ""
"Failed to make a request to Datera cluster endpoint due to the following "
"reason: %s"
msgstr "無法對 Datera 叢集端點發出要求，原因如下：%s"

msgid "Failed to manage api volume flow."
msgstr "無法管理 API 磁區流程。"

#, python-format
msgid ""
"Failed to manage existing %(type)s %(name)s, because reported size %(size)s "
"was not a floating-point number."
msgstr "無法管理現有 %(type)s %(name)s，因為報告的大小 %(size)s 不是浮點數字。"

#, python-format
msgid ""
"Failed to manage existing volume %(name)s, because of error in getting "
"volume size."
msgstr "無法管理現有磁區 %(name)s，因為取得磁區大小時發生錯誤。"

#, python-format
msgid ""
"Failed to manage existing volume %(name)s, because rename operation failed: "
"Error msg: %(msg)s."
msgstr "無法管理現有磁區 %(name)s，因為重新命名作業失敗：錯誤訊息：%(msg)s。"

#, python-format
msgid ""
"Failed to manage existing volume %(name)s, because reported size %(size)s "
"was not a floating-point number."
msgstr "無法管理現有磁區 %(name)s，因為所報告的大小 %(size)s不是浮點數字。"

#, python-format
msgid ""
"Failed to manage existing volume due to the pool of the volume to be managed "
"does not match the backend pool. Pool of the volume to be managed is "
"%(vdisk_pool)s. Pool of the backend is %(backend_pool)s."
msgstr ""
"因為要管理之磁區的通訊協定與後端通訊協定不符，所以無法管理現有磁區。要管理之"
"磁區的通訊協定是 %(vdisk_pool)s。後端的通訊協定是 %(backend_pool)s。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is "
"compress, but the volume type chosen is not compress."
msgstr ""
"因為要管理的磁區是壓縮磁區，但所選磁區類型卻是未壓縮磁區，所以無法管理現有磁"
"區。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is not "
"compress, but the volume type chosen is compress."
msgstr ""
"因為要管理的磁區是未壓縮磁區，但所選磁區類型卻是壓縮磁區，所以無法管理現有磁"
"區。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is not in a "
"valid I/O group."
msgstr "因為要管理的磁區不在有效的 I/O 群組中，所以無法管理現有磁區。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is thick, "
"but the volume type chosen is thin."
msgstr ""
"因為要管理的磁區是豐富磁區，但所選磁區類型卻是精簡磁區，所以無法管理現有磁"
"區。"

msgid ""
"Failed to manage existing volume due to the volume to be managed is thin, "
"but the volume type chosen is thick."
msgstr ""
"因為要管理的磁區是精簡磁區，但所選磁區類型卻是豐富磁區，所以無法管理現有磁"
"區。"

#, python-format
msgid "Failed to manage volume %s."
msgstr "無法管理磁區 %s。"

#, python-format
msgid "Failed to move volume %s."
msgstr "無法移動磁區 %s。"

#, python-format
msgid ""
"Failed to parse CLI output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"無法剖析 CLI 輸出：\n"
" 指令：%(cmd)s\n"
" 標準輸出：%(out)s\n"
"標準錯誤：%(err)s。"

msgid ""
"Failed to parse the configuration option 'keystone_catalog_info', must be in "
"the form <service_type>:<service_name>:<endpoint_type>"
msgstr ""
"無法剖析配置選項 'keystone_catalog_info'，必須採用下列格式：<service_type>:"
"<service_name>:<endpoint_type>"

msgid ""
"Failed to parse the configuration option 'swift_catalog_info', must be in "
"the form <service_type>:<service_name>:<endpoint_type>"
msgstr ""
"無法剖析配置選項 'swift_catalog_info'，必須採用下列格式：<service_type>:"
"<service_name>:<endpoint_type>"

#, python-format
msgid "Failed to remove export for volume %(volume)s: %(reason)s"
msgstr "無法移除磁區 %(volume)s 的匯出項目：%(reason)s"

#, python-format
msgid "Failed to remove iscsi target for volume %(volume_id)s."
msgstr "無法移除磁區 %(volume_id)s 的 iSCSI 目標。"

#, python-format
msgid ""
"Failed to rename logical volume %(name)s, error message was: %(err_msg)s"
msgstr "無法重新命名邏輯磁區 %(name)s，錯誤訊息為：%(err_msg)s"

#, python-format
msgid "Failed to retrieve active zoning configuration %s"
msgstr "無法擷取作用中的分區配置 %s"

#, python-format
msgid ""
"Failed to set CHAP authentication for target IQN %(iqn)s. Details: %(ex)s"
msgstr "無法設定目標 IQN %(iqn)s 的 CHAP 鑑別。詳細資料：%(ex)s"

#, python-format
msgid "Failed to set QoS for existing volume %(name)s, Error msg: %(msg)s."
msgstr "無法設定現有磁區 %(name)s 的服務品質，錯誤訊息：%(msg)s。"

msgid "Failed to set attribute 'Incoming user' for SCST target."
msgstr "無法設定 SCST 目標的「送入使用者」屬性。"

#, python-format
msgid ""
"Failed to set permissions for the consistency group %(cgname)s. Error: "
"%(excmsg)s."
msgstr "無法設定一致性群組 %(cgname)s 的許可權。錯誤：%(excmsg)s。"

#, python-format
msgid ""
"Failed to unlink fileset for consistency group %(cgname)s. Error: %(excmsg)s."
msgstr "無法解除鏈結一致性群組 %(cgname)s 的檔案集。錯誤：%(excmsg)s。"

#, python-format
msgid "Failed to update metadata for volume: %(reason)s"
msgstr "無法更新磁區的 meta 資料：%(reason)s"

msgid "Failed to update or delete zoning configuration"
msgstr "無法更新或刪除分區配置"

msgid "Failed to update or delete zoning configuration."
msgstr "無法更新或刪除分區配置。"

#, python-format
msgid "Failed to update qos_specs: %(specs_id)s with specs %(qos_specs)s."
msgstr "無法使用規格 %(qos_specs)s 來更新 qos_specs：%(specs_id)s。"

msgid "Failed to update quota usage while retyping volume."
msgstr "對磁區執行 Retype 作業時，無法更新配額用量。"

msgid "Failed to update snapshot."
msgstr "無法更新 Snapshot。"

#, python-format
msgid ""
"Failed updating volume %(vol_id)s metadata using the provided %(src_type)s "
"%(src_id)s metadata"
msgstr ""
"使用提供的 %(src_type)s %(src_id)s meta 資料來更新磁區 %(vol_id)s meta 資料時"
"失敗"

#, python-format
msgid "Failure getting LUN info for %s."
msgstr "取得 %s 的 LUN 資訊時失敗。"

#, python-format
msgid "Failure moving new cloned LUN to %s."
msgstr "將新複製的 LUN 移至 %s 時失敗。"

#, python-format
msgid "Failure staging LUN %s to tmp."
msgstr "將 LUN %s 暫置到 tmp 時失敗。"

#, python-format
msgid "Fexvisor failed to add volume %(id)s due to %(reason)s."
msgstr "由於 %(reason)s，Fexvisor 無法新增磁區 %(id)s。"

#, python-format
msgid ""
"Fexvisor failed to join the volume %(vol)s in the group %(group)s due to "
"%(ret)s."
msgstr "Fexvisor 無法結合群組 %(group)s 中的磁區 %(vol)s，原因：%(ret)s。"

#, python-format
msgid ""
"Fexvisor failed to remove the volume %(vol)s in the group %(group)s due to "
"%(ret)s."
msgstr "Fexvisor 無法移除群組 %(group)s 中的磁區 %(vol)s，原因：%(ret)s。"

#, python-format
msgid "Fexvisor failed to remove volume %(id)s due to %(reason)s."
msgstr "Fexvisor 無法移除磁區 %(id)s，原因：%(reason)s。"

#, python-format
msgid "Fibre Channel SAN Lookup failure: %(reason)s"
msgstr "「光纖通道」SAN 查閱失敗：%(reason)s"

#, python-format
msgid "Fibre Channel Zone operation failed: %(reason)s"
msgstr "「光纖通道」區域作業失敗：%(reason)s"

#, python-format
msgid "Fibre Channel connection control failure: %(reason)s"
msgstr "「光纖通道」連線控制失敗：%(reason)s"

#, python-format
msgid "File %(file_path)s could not be found."
msgstr "找不到檔案 %(file_path)s。"

#, python-format
msgid "File already exists at %s."
msgstr "%s 處已存在檔案。"

#, python-format
msgid "File already exists at: %s"
msgstr "%s 處已存在檔案"

msgid "Find host in hostgroup error."
msgstr "在主機群組中尋找主機時發生錯誤。"

msgid "Find host lun id error."
msgstr "尋找主機 LUN ID 時發生錯誤。"

msgid "Find lun group from mapping view error."
msgstr "從對映視圖中尋找 LUN 群組時發生錯誤。"

msgid "Find mapping view error."
msgstr "尋找對映視圖時發生錯誤。"

msgid "Find portgroup error."
msgstr "尋找埠群組時發生錯誤。"

msgid "Find portgroup from mapping view error."
msgstr "從對映視圖中尋找埠群組時發生錯誤。"

#, python-format
msgid ""
"Flash Cache Policy requires WSAPI version '%(fcache_version)s' version "
"'%(version)s' is installed."
msgstr ""
"「快閃記憶體快取原則」需要 WSAPI '%(fcache_version)s' 版，已安裝 "
"'%(version)s' 版。"

#, python-format
msgid "Flexvisor assign volume failed.:%(id)s:%(status)s."
msgstr "Flexvisor 指派磁區失敗：%(id)s：%(status)s。"

#, python-format
msgid "Flexvisor assign volume failed:%(id)s:%(status)s."
msgstr "Flexvisor 指派磁區失敗：%(id)s：%(status)s。"

#, python-format
msgid ""
"Flexvisor could not find volume %(id)s snapshot in the group %(vgid)s "
"snapshot %(vgsid)s."
msgstr ""
"Flexvisor 在群組 %(vgid)s Snapshot %(vgsid)s 中找不到磁區 %(id)s Snapshot。"

#, python-format
msgid "Flexvisor create volume failed.:%(volumeid)s:%(status)s."
msgstr "Flexvisor 建立磁區失敗：%(volumeid)s：%(status)s。"

#, python-format
msgid "Flexvisor failed deleting volume %(id)s: %(status)s."
msgstr "Flexvisor 無法刪除磁區 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to add volume %(id)s to group %(cgid)s."
msgstr "Flexvisor 無法將磁區 %(id)s 新增至群組 %(cgid)s。"

#, python-format
msgid ""
"Flexvisor failed to assign volume %(id)s due to unable to query status by "
"event id."
msgstr "Flexvisor 無法指派磁區 %(id)s，原因是無法依事件 ID 來查詢狀態。"

#, python-format
msgid "Flexvisor failed to assign volume %(id)s: %(status)s."
msgstr "Flexvisor 無法指派磁區 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to assign volume %(volume)s iqn %(iqn)s."
msgstr "Flexvisor 無法指派磁區 %(volume)s iqn %(iqn)s。"

#, python-format
msgid "Flexvisor failed to clone volume %(id)s: %(status)s."
msgstr "Flexvisor 無法複製磁區 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to clone volume (failed to get event) %(id)s."
msgstr "Flexvisor 無法複製磁區（無法取得事件）%(id)s。"

#, python-format
msgid "Flexvisor failed to create snapshot for volume %(id)s: %(status)s."
msgstr "Flexvisor 無法建立磁區 %(id)s 的 Snapshot：%(status)s。"

#, python-format
msgid ""
"Flexvisor failed to create snapshot for volume (failed to get event) %(id)s."
msgstr "Flexvisor 無法建立下列磁區的 Snapshot（無法取得事件）：%(id)s。"

#, python-format
msgid "Flexvisor failed to create volume %(id)s in the group %(vgid)s."
msgstr "Flexvisor 無法在群組 %(vgid)s 中建立磁區 %(id)s。"

#, python-format
msgid "Flexvisor failed to create volume %(volume)s: %(status)s."
msgstr "Flexvisor 無法建立磁區 %(volume)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to create volume (get event) %s."
msgstr "Flexvisor 無法建立磁區（取得事件）%s。"

#, python-format
msgid "Flexvisor failed to create volume from snapshot %(id)s: %(status)s."
msgstr "Flexvisor 無法從 Snapshot %(id)s 建立磁區：%(status)s。"

#, python-format
msgid "Flexvisor failed to create volume from snapshot %(id)s:%(status)s."
msgstr "Flexvisor 無法從 Snapshot %(id)s 建立磁區：%(status)s。"

#, python-format
msgid ""
"Flexvisor failed to create volume from snapshot (failed to get event) %(id)s."
msgstr "Flexvisor 無法從下列 Snapshot 建立磁區（無法取得事件）：%(id)s。"

#, python-format
msgid "Flexvisor failed to delete snapshot %(id)s: %(status)s."
msgstr "Flexvisor 無法刪除 Snapshot %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to delete snapshot (failed to get event) %(id)s."
msgstr "Flexvisor 無法刪除 Snapshot（無法取得事件）%(id)s。"

#, python-format
msgid "Flexvisor failed to delete volume %(id)s: %(status)s."
msgstr "Flexvisor 無法刪除磁區 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to extend volume %(id)s: %(status)s."
msgstr "Flexvisor 無法延伸磁區 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to extend volume %(id)s:%(status)s."
msgstr "Flexvisor 無法延伸磁區 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to extend volume (failed to get event) %(id)s."
msgstr "Flexvisor 無法延伸磁區（無法取得事件）%(id)s。"

#, python-format
msgid "Flexvisor failed to get pool info %(id)s: %(status)s."
msgstr "Flexvisor 無法取得儲存區資訊 %(id)s：%(status)s。"

#, python-format
msgid ""
"Flexvisor failed to get snapshot id of volume %(id)s from group %(vgid)s."
msgstr "Flexvisor 無法從群組 %(vgid)s 取得磁區 %(id)s 的 Snapshot ID。"

#, python-format
msgid "Flexvisor failed to remove volume %(id)s from group %(cgid)s."
msgstr "Flexvisor 無法從群組 %(cgid)s 中移除磁區 %(id)s。"

#, python-format
msgid "Flexvisor failed to spawn volume from snapshot %(id)s:%(status)s."
msgstr "Flexvisor 無法從 Snapshot %(id)s 大量產生磁區：%(status)s。"

#, python-format
msgid ""
"Flexvisor failed to spawn volume from snapshot (failed to get event) %(id)s."
msgstr "Flexvisor 無法從下列 Snapshot 大量產生磁區（無法取得事件）：%(id)s。"

#, python-format
msgid "Flexvisor failed to unassign volume %(id)s: %(status)s."
msgstr "Flexvisor 無法取消指派磁區 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor failed to unassign volume (get event) %(id)s."
msgstr "Flexvisor 無法取消指派磁區（取得事件）%(id)s。"

#, python-format
msgid "Flexvisor failed to unassign volume:%(id)s:%(status)s."
msgstr "Flexvisor 無法取消指派磁區 %(id)s：%(status)s。"

#, python-format
msgid "Flexvisor unable to find the source volume %(id)s info."
msgstr "Flexvisor 找不到來源磁區 %(id)s 資訊。"

#, python-format
msgid "Flexvisor unassign volume failed:%(id)s:%(status)s."
msgstr "Flexvisor 取消指派磁區失敗：%(id)s：%(status)s。"

#, python-format
msgid "Flexvisor volume %(id)s failed to join group %(vgid)s."
msgstr "Flexvisor 磁區 %(id)s 無法加入群組 %(vgid)s 中。"

#, python-format
msgid "Folder %s does not exist in Nexenta Store appliance"
msgstr "資料夾 %s 不存在於「Nexenta 儲存庫」軟體驅動裝置中"

#, python-format
msgid "GPFS is not running, state: %s."
msgstr "GPFS 不在執行中，狀態：%s。"

msgid "Get FC ports by port group error."
msgstr "依埠群組取得 FC 埠時發生錯誤。"

msgid "Get FC ports from array error."
msgstr "從陣列中取得 FC 埠時發生錯誤。"

msgid "Get FC target wwpn error."
msgstr "取得 FC 目標 WWPN 時發生錯誤。"

msgid "Get HyperMetroPair error."
msgstr "取得 HyperMetroPair 時發生錯誤。"

msgid "Get LUN group by view error."
msgstr "依視圖取得 LUN 群組時發生錯誤。"

msgid "Get LUNcopy information error."
msgstr "取得 LUNcopy 資訊時發生錯誤。"

msgid "Get QoS id by lun id error."
msgstr "依 LUN ID 取得服務品質 ID 時發生錯誤。"

msgid "Get QoS information error."
msgstr "取得服務品質資訊時發生錯誤。"

msgid "Get QoS policy error."
msgstr "取得服務品質原則時發生錯誤。"

msgid "Get SplitMirror error."
msgstr "取得 SplitMirror 時發生錯誤。"

msgid "Get active client failed."
msgstr "取得作用中的用戶端失敗。"

msgid "Get array info error."
msgstr "取得陣列資訊時發生錯誤。"

msgid "Get cache by name error."
msgstr "依名稱取得快取時發生錯誤。"

msgid "Get connected free FC wwn error."
msgstr "取得已連接的可用 FC WWN 時發生錯誤。"

msgid "Get engines error."
msgstr "取得引擎時發生錯誤。"

msgid "Get host initiators info failed."
msgstr "取得主機起始器資訊時失敗。"

msgid "Get hostgroup information error."
msgstr "取得主機群組資訊時發生錯誤。"

msgid ""
"Get iSCSI port info error, please check the target IP configured in huawei "
"conf file."
msgstr "取得 iSCSI 埠資訊時發生錯誤，請檢查 huawei 配置檔中配置的目標 IP。"

msgid "Get iSCSI port information error."
msgstr "取得 iSCSI 埠資訊時發生錯誤。"

msgid "Get iSCSI target port error."
msgstr "取得 iSCSI 目標埠時發生錯誤。"

msgid "Get lun id by name error."
msgstr "依名稱取得 LUN ID 時發生錯誤。"

msgid "Get lun migration task error."
msgstr "取得 LUN 移轉作業時發生錯誤。"

msgid "Get lungroup id by lun id error."
msgstr "依 LUN ID 取得 LUN 群組 ID 時發生錯誤。"

msgid "Get lungroup information error."
msgstr "取得 LUN 群組資訊時發生錯誤。"

msgid "Get migration task error."
msgstr "取得移轉作業時發生錯誤。"

msgid "Get pair failed."
msgstr "取得配對失敗。"

msgid "Get partition by name error."
msgstr "依名稱取得分割區時發生錯誤。"

msgid "Get partition by partition id error."
msgstr "依分割區 ID 取得分割區時發生錯誤。"

msgid "Get port group by view error."
msgstr "依視圖取得埠群組時發生錯誤。"

msgid "Get port group error."
msgstr "取得埠群組時發生錯誤。"

msgid "Get port groups by port error."
msgstr "依埠取得埠群組時發生錯誤。"

msgid "Get ports by port group error."
msgstr "依埠群組取得埠時發生錯誤。"

msgid "Get remote device info failed."
msgstr "取得遠端裝置資訊失敗。"

msgid "Get remote devices error."
msgstr "取得遠端裝置時發生錯誤。"

msgid "Get smartcache by cache id error."
msgstr "依快取 ID 取得 smartcache 時發生錯誤。"

msgid "Get snapshot error."
msgstr "取得 Snapshot 時發生錯誤。"

msgid "Get snapshot id error."
msgstr "取得 Snapshot ID 時發生錯誤。"

msgid "Get target IP error."
msgstr "取得目標 IP 時發生錯誤。"

msgid "Get target LUN of SplitMirror error."
msgstr "取得 SplitMirror 的目標 LUN 時發生錯誤。"

msgid "Get views by port group error."
msgstr "依埠群組取得視圖時發生錯誤。"

msgid "Get volume by name error."
msgstr "依名稱取得磁區時發生錯誤。"

msgid "Get volume error."
msgstr "取得磁區時發生錯誤。"

#, python-format
msgid ""
"Glance metadata cannot be updated, key %(key)s exists for volume id "
"%(volume_id)s"
msgstr "無法更新 Glance meta 資料，磁區 ID %(volume_id)s 已存在索引鍵 %(key)s"

#, python-format
msgid "Glance metadata for volume/snapshot %(id)s cannot be found."
msgstr "找不到磁區/Snapshot %(id)s 的 Glance meta 資料。"

#, python-format
msgid "Google Cloud Storage api failure: %(reason)s"
msgstr "Google Cloud Storage API 失敗：%(reason)s"

#, python-format
msgid "Google Cloud Storage connection failure: %(reason)s"
msgstr "Google Cloud Storage 連線失敗：%(reason)s"

#, python-format
msgid "Google Cloud Storage oauth2 failure: %(reason)s"
msgstr "Google Cloud Storage oauth2 失敗：%(reason)s"

#, python-format
msgid "Got bad path information from DRBDmanage! (%s)"
msgstr "從 DRBDmanage 取得不正確的路徑資訊！(%s)"

msgid "HPELeftHand url not found"
msgstr "找不到 HPELeftHand URL"

#, python-format
msgid ""
"Hash block size has changed since the last backup. New hash block size: "
"%(new)s. Old hash block size: %(old)s. Do a full backup."
msgstr ""
"雜湊區塊大小自前次備份以來已變更。新的雜湊區塊大小：%(new)s。舊的雜湊區塊大"
"小：%(old)s。請執行完整備份。"

#, python-format
msgid "Hint \"%s\" not supported."
msgstr "不支援提示 \"%s\"。"

msgid "Host"
msgstr "主機"

#, python-format
msgid "Host %(host)s could not be found."
msgstr "找不到主機 %(host)s。"

#, python-format
msgid "Host %s has no FC initiators"
msgstr "主機 %s 沒有 FC 起始器"

#, python-format
msgid "Host not found. Failed to remove %(service)s on %(host)s."
msgstr "找不到主機。無法移除 %(host)s 上的 %(service)s。"

msgid "Hypermetro and Replication can not be used in the same volume_type."
msgstr "不能在同一 volume_type 中使用 Hypermetro 和抄寫。"

msgid "ID"
msgstr "識別號"

msgid ""
"If compression is set to True, rsize must also be set (not equal to -1)."
msgstr "如果壓縮設為 True，則也必須設定調整大小（不等於 -1）。"

msgid "If nofmtdisk is set to True, rsize must also be set to -1."
msgstr "如果 nofmtdisk 設為 True，則 rsize 也必須設為 -1。"

#, python-format
msgid ""
"Illegal value '%(prot)s' specified for flashsystem_connection_protocol: "
"valid value(s) are %(enabled)s."
msgstr ""
"為 flashsystem_connection_protocol 指定的值 '%(prot)s' 不正確：有效值為 "
"%(enabled)s。"

msgid "Illegal value specified for IOTYPE: 0, 1, or 2."
msgstr "為 IOTYPE 指定的值無效：0、1 或 2。"

msgid "Illegal value specified for smarttier: set to either 0, 1, 2, or 3."
msgstr "指定給 smarttier 的值不正確：設定為 0、1、2 或 3。"

msgid ""
"Illegal value specified for storwize_svc_vol_grainsize: set to either 32, "
"64, 128, or 256."
msgstr ""
"指定給 storwize_svc_vol_grainsize 的值不正確：應設為 32、64、128 或 256。"

msgid ""
"Illegal value specified for thin: Can not set thin and thick at the same "
"time."
msgstr "指定給 thin 的值不正確：無法同時設定thin 和 thick。"

#, python-format
msgid "Image %(image_id)s could not be found."
msgstr "找不到映像檔 %(image_id)s。"

#, python-format
msgid "Image %(image_id)s is not active."
msgstr "映像檔 %(image_id)s 不在作用中。"

#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr "無法接受映像檔 %(image_id)s：%(reason)s"

msgid "Image location not present."
msgstr "映像檔位置不存在。"

#, python-format
msgid ""
"Image virtual size is %(image_size)dGB and doesn't fit in a volume of size "
"%(volume_size)dGB."
msgstr ""
"映像檔虛擬大小為 %(image_size)d GB，不適合大小為%(volume_size)d GB 的磁區。"

msgid ""
"ImageBusy error raised while deleting rbd volume. This may have been caused "
"by a connection from a client that has crashed and, if so, may be resolved "
"by retrying the delete after 30 seconds has elapsed."
msgstr ""
"刪除 rbd 磁區時發出 ImageBusy 錯誤。造成此問題的原因可能是從已損毀的用戶端進"
"行連線，如果是這樣，則可以在30 秒後，透過重試刪除來解決。"

msgid "Incremental backups exist for this backup."
msgstr "此備份的增量備份已存在。"

msgid "Input volumes or snapshots are invalid."
msgstr "輸入磁區或 Snapshot 無效。"

msgid "Input volumes or source volumes are invalid."
msgstr "輸入磁區或來源磁區無效。"

#, python-format
msgid "Instance %(uuid)s could not be found."
msgstr "找不到實例 %(uuid)s。"

#, python-format
msgid "Invalid 3PAR Domain: %(err)s"
msgstr "無效的 3PAR 網域：%(err)s"

msgid "Invalid ALUA value. ALUA value must be 1 or 0."
msgstr "無效的 ALUA 值。ALUA 值必須是 1 或 0。"

msgid "Invalid Ceph args provided for backup rbd operation"
msgstr "提供給備份 rbd 作業的 Ceph 引數無效"

#, python-format
msgid "Invalid CgSnapshot: %(reason)s"
msgstr "無效的 CgSnapshot：%(reason)s"

#, python-format
msgid "Invalid ConsistencyGroup: %(reason)s"
msgstr "無效的 ConsistencyGroup：%(reason)s"

#, python-format
msgid ""
"Invalid HPELeftHand API version found: %(found)s. Version %(minimum)s or "
"greater required for manage/unmanage support."
msgstr ""
"找到的 HPELeftHand API 版本 %(found)s 無效。管理/取消管理支援需要 "
"%(minimum)s 版或更高版本。"

#, python-format
msgid "Invalid IP address format: '%s'"
msgstr "無效的 IP 位址格式：'%s'"

#, python-format
msgid ""
"Invalid QoS specification detected while getting QoS policy for volume %s"
msgstr "取得磁區 %s 的服務品質原則時，偵測到無效的服務品質規格"

#, python-format
msgid "Invalid Replication Target: %(reason)s"
msgstr "無效的抄寫目標：%(reason)s"

#, python-format
msgid ""
"Invalid Virtuozzo Storage share specification: %r. Must be: [MDS1[,"
"MDS2],...:/]<CLUSTER NAME>[:PASSWORD]."
msgstr ""
"Virtuozzo 儲存體共用項目規格無效：%r。必須是：[MDS1[,MDS2],...:/]<CLUSTER "
"NAME>[:PASSWORD]。"

#, python-format
msgid "Invalid XtremIO version %(cur)s, version %(min)s or up is required"
msgstr "XtremIO %(cur)s 版無效，需要 %(min)s 版或更高版本"

#, python-format
msgid "Invalid allocated quotas defined for the following project quotas: %s"
msgstr "為下列專案配額定義的已配置配額無效：%s"

msgid "Invalid argument - negative seek offset."
msgstr "無效的引數 - 負數探查偏移。"

#, python-format
msgid "Invalid argument - whence=%s not supported."
msgstr "無效的引數 - 不支援 whence=%s。"

#, python-format
msgid "Invalid attaching mode '%(mode)s' for volume %(volume_id)s."
msgstr "連接模式 '%(mode)s' 不適用於磁區 %(volume_id)s。"

#, python-format
msgid "Invalid auth key: %(reason)s"
msgstr "無效的鑑別金鑰：%(reason)s"

#, python-format
msgid "Invalid backup: %(reason)s"
msgstr "無效的備份：%(reason)s"

#, python-format
msgid "Invalid connection initialization response of volume %(name)s"
msgstr "磁區 %(name)s 的連線起始設定回應無效"

#, python-format
msgid ""
"Invalid connection initialization response of volume %(name)s: %(output)s"
msgstr "磁區 %(name)s 的連線起始設定回應無效：%(output)s"

#, python-format
msgid "Invalid content type %(content_type)s."
msgstr "無效的內容類型 %(content_type)s。"

#, python-format
msgid "Invalid directory: %s"
msgstr "無效的目錄：%s"

#, python-format
msgid "Invalid disk adapter type: %(invalid_type)s."
msgstr "無效的磁碟配接卡類型：%(invalid_type)s。"

#, python-format
msgid "Invalid disk backing: %s."
msgstr "無效的磁碟備用項目：%s。"

#, python-format
msgid "Invalid disk type: %(disk_type)s."
msgstr "無效的磁碟類型：%(disk_type)s。"

#, python-format
msgid "Invalid disk type: %s."
msgstr "無效的磁碟類型：%s。"

#, python-format
msgid "Invalid host: %(reason)s"
msgstr "無效的主機：%(reason)s"

#, python-format
msgid ""
"Invalid hpe3parclient version found (%(found)s). Version %(minimum)s or "
"greater required. Run \"pip install --upgrade python-3parclient\" to upgrade "
"the hpe3parclient."
msgstr ""
"找到的 hpe3parclient 版本 (%(found)s) 無效。需要 %(minimum)s 版或更高版本。請"
"執行 \"pip install --upgrade python-3parclient\" 來升級 hpe3parclient。"

#, python-format
msgid ""
"Invalid hpelefthandclient version found (%(found)s). Version %(minimum)s or "
"greater required. Run 'pip install --upgrade python-lefthandclient' to "
"upgrade the hpelefthandclient."
msgstr ""
"找到的 hpelefthandclient 版本 (%(found)s) 無效。需要 %(minimum)s 版或更高版"
"本。請執行 'pip install --upgrade python-lefthandclient' 來升級 "
"hpelefthandclient。"

#, python-format
msgid "Invalid image href %(image_href)s."
msgstr "無效的映像檔 href %(image_href)s。"

msgid "Invalid image identifier or unable to access requested image."
msgstr "映像檔 ID 無效，或無法存取所要求的映像檔。"

msgid "Invalid imageRef provided."
msgstr "提供的 imageRef 無效。"

msgid "Invalid input"
msgstr "無效的輸入"

#, python-format
msgid "Invalid input received: %(reason)s"
msgstr "收到的輸入無效：%(reason)s"

#, python-format
msgid "Invalid is_public filter [%s]"
msgstr "無效的 is_public 過濾器 [%s]"

#, python-format
msgid "Invalid lun type %s is configured."
msgstr "所配置的 LUN 類型 %s 無效。"

#, python-format
msgid "Invalid metadata size: %(reason)s"
msgstr "無效的 meta 資料大小：%(reason)s"

#, python-format
msgid "Invalid metadata: %(reason)s"
msgstr "無效的 meta 資料：%(reason)s"

#, python-format
msgid "Invalid mount point base: %s"
msgstr "無效的裝載點基本程式：%s"

#, python-format
msgid "Invalid mount point base: %s."
msgstr "無效的裝載點基本程式：%s。"

#, python-format
msgid "Invalid new snapCPG name for retype.  new_snap_cpg='%s'."
msgstr "新 snapCPG 名稱無效，無法執行 Retype 動作。new_snap_cpg='%s'。"

#, python-format
msgid ""
"Invalid prefetch type '%s' is configured. PrefetchType must be in 0,1,2,3."
msgstr "所配置的預先提取類型 %s 無效。PrefetchType 必須位於 0、1、2 和 3 中。"

#, python-format
msgid "Invalid qos specs: %(reason)s"
msgstr "無效的服務品質規格：%(reason)s"

#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr "無效的預約有效期限 %(expire)s。"

#, python-format
msgid "Invalid secondary id %s."
msgstr "次要 ID %s 無效。"

msgid "Invalid service catalog json."
msgstr "無效的服務型錄 JSON。"

msgid "Invalid sheepdog cluster status."
msgstr "sheepdog 叢集狀態無效。"

#, python-format
msgid "Invalid snapshot: %(reason)s"
msgstr "無效的 Snapshot：%(reason)s"

#, python-format
msgid "Invalid status: '%s'"
msgstr "無效的狀態：'%s'"

#, python-format
msgid "Invalid storage pool %s requested.  Retype failed."
msgstr "所要求的儲存區 %s 無效。執行 Retype 動作失敗。"

#, python-format
msgid "Invalid storage pool %s specificed."
msgstr "所指定的儲存區 %s 無效。"

msgid "Invalid storage pool is configured."
msgstr "所配置的儲存區無效。"

#, python-format
msgid "Invalid update setting: '%s'"
msgstr "無效的更新設定：'%s'"

#, python-format
msgid "Invalid value '%s' for force."
msgstr "force 的值 '%s' 無效。"

msgid "Invalid value for 'scheduler_max_attempts', must be >=1"
msgstr "'scheduler_max_attempts' 的值無效，必須 >= 1"

msgid "Invalid value for NetApp configuration option netapp_host_type."
msgstr "NetApp 配置選項 netapp_host_type 的值無效。"

msgid "Invalid value for NetApp configuration option netapp_lun_ostype."
msgstr "NetApp 配置選項 netapp_lun_ostype 的值無效。"

#, python-format
msgid "Invalid value for age, %(age)s"
msgstr "經歷時間的值 %(age)s 無效"

#, python-format
msgid "Invalid value: \"%s\""
msgstr "無效的值：\"%s\""

#, python-format
msgid ""
"Invalid volume size provided for create request: %s (size argument must be "
"an integer (or string representation of an integer) and greater than zero)."
msgstr ""
"提供給建立要求的磁區大小無效：%s（大小引數必須為整數或整數的字串表示法且大於"
"零）。"

#, python-format
msgid "Invalid volume type: %(reason)s"
msgstr "無效的磁區類型：%(reason)s"

#, python-format
msgid "Invalid volume: %(reason)s"
msgstr "無效的磁區：%(reason)s"

#, python-format
msgid "Invalid volume_type passed: %s."
msgstr "傳遞的 volume_type 無效：%s。"

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type is not compatible; either "
"match source volume, or omit type argument)."
msgstr ""
"提供的 volume_type 無效：%s（所要求的類型不相容；符合來源磁區，或省略 type 引"
"數）。"

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type is not compatible; "
"recommend omitting the type argument)."
msgstr ""
"提供的 volume_type 無效：%s（所要求的類型不相容；建議省略該類型引數）。"

#, python-format
msgid ""
"Invalid volume_type provided: %s (requested type must be supported by this "
"consistency group)."
msgstr "提供的 volume_type 無效：%s（所要求的類型必須受此一致性群組支援）。"

#, python-format
msgid "Invalid wwpns format %(wwpns)s"
msgstr "無效的 WWPN 格式 %(wwpns)s"

msgid "Issue encountered waiting for job."
msgstr "等待工作時遇到問題。"

msgid "Issue encountered waiting for synchronization."
msgstr "等待同步時遇到問題。"

msgid ""
"Issuing a fail-over failed because replication is not properly configured."
msgstr "發出失效接手失敗，因為未正確配置抄寫。"

#, python-format
msgid "KeyError: %s"
msgstr "KeyError：%s"

msgid "Keystone version 3 or greater must be used to get nested quota support."
msgstr "Keystone 第 3 版或更高版本必須用於取得巢狀配額支援。"

#, python-format
msgid "LUN not found with given ref %s."
msgstr "找不到具有給定參照 %s 的 LUN。"

msgid "LeftHand cluster not found"
msgstr "找不到 LeftHand 叢集"

msgid "License is unavailable."
msgstr "無法使用授權。"

#, python-format
msgid "Linked clone of source volume not supported in state: %s."
msgstr "狀態 %s 不支援來源磁區的鏈結複本。"

msgid "Lock acquisition failed."
msgstr "鎖定獲得失敗。"

msgid "Logout session error."
msgstr "登出階段作業錯誤。"

msgid ""
"Lookup service not configured. Config option for fc_san_lookup_service needs "
"to specify a concrete implementation of the lookup service."
msgstr ""
"未配置查閱服務。fc_san_lookup_service 的配置選項需要指定查閱服務的具體實作。"

msgid "Lun migration error."
msgstr "Lun 移轉錯誤。"

#, python-format
msgid ""
"MD5 of object: %(object_name)s before: %(md5)s and after: %(etag)s is not "
"same."
msgstr "之前物件 %(object_name)s 的 MD5 %(md5)s 與之後的 %(etag)s 不同。"

#, python-format
msgid "Malformed fcns output string: %s"
msgstr "形態異常的 fcns 輸出字串：%s"

#, python-format
msgid "Malformed message body: %(reason)s"
msgstr "訊息內文的格式不正確：%(reason)s"

#, python-format
msgid "Malformed nameserver string: %s"
msgstr "格式不正確的名稱伺服器字串：%s"

msgid "Malformed request body"
msgstr "要求內文的格式不正確"

msgid "Malformed request body."
msgstr "要求內文形態異常。"

msgid "Malformed request url"
msgstr "要求 URL 的格式不正確"

#, python-format
msgid "Malformed response to command %(cmd)s: %(reason)s"
msgstr "對指令 %(cmd)s 的回應格式不正確：%(reason)s"

#, python-format
msgid "Malformed show fcns database string: %s"
msgstr "形態異常的「顯示 fcns」資料庫字串：%s"

#, python-format
msgid ""
"Malformed zone configuration: (switch=%(switch)s zone_config="
"%(zone_config)s)."
msgstr ""
"格式不正確的區域配置：（交換器 = %(switch)szone_config = %(zone_config)s）。"

#, python-format
msgid "Malformed zone status: (switch=%(switch)s zone_config=%(zone_config)s)."
msgstr ""
"形態異常的區域狀態：（交換器 = %(switch)s，zone_config = %(zone_config)s）。"

msgid "Manage existing get size requires 'id'."
msgstr "管理現有取得大小需要 'id'。"

msgid "Manage existing snapshot not implemented."
msgstr "未實作管理現有 Snapshot。"

#, python-format
msgid ""
"Manage existing volume failed due to invalid backend reference "
"%(existing_ref)s: %(reason)s"
msgstr "管理現有磁區時失敗，因為後端參照%(existing_ref)s 無效：%(reason)s"

#, python-format
msgid "Manage existing volume failed due to volume type mismatch: %(reason)s"
msgstr "管理現有磁區時失敗，因為磁區類型不符：%(reason)s"

msgid "Manage existing volume not implemented."
msgstr "未實作管理現有磁區。"

msgid "Manage existing volume requires 'source-id'."
msgstr "管理現有磁區需要 'source-id'。"

msgid "Managing of snapshots to failed-over volumes is not allowed."
msgstr "不容許對已失效接手之磁區的 Snapshot 進行管理。"

msgid "Map info is None due to array version not supporting hypermetro."
msgstr "由於陣列版本不支援 Hypermetro，對映資訊為「無」。"

#, python-format
msgid "Maximum number of backups allowed (%(allowed)d) exceeded"
msgstr "已超出容許的備份數目上限 (%(allowed)d)"

#, python-format
msgid "Maximum number of snapshots allowed (%(allowed)d) exceeded"
msgstr "已超出容許的 Snapshot 數目上限 (%(allowed)d)"

#, python-format
msgid ""
"Maximum number of volumes allowed (%(allowed)d) exceeded for quota "
"'%(name)s'."
msgstr "已超出下列配額容許的磁區數目上限 (%(allowed)d)：'%(name)s'。"

#, python-format
msgid "May specify only one of %s"
msgstr "只能指定 %s 的其中之一"

msgid "Metadata backup already exists for this volume"
msgstr "此磁區已存在 meta 資料備份"

#, python-format
msgid "Metadata backup object '%s' already exists"
msgstr "meta 資料備份物件 '%s' 已存在"

msgid "Metadata restore failed due to incompatible version"
msgstr "meta 資料還原失敗，因為版本不相容"

msgid "Metadata restore failed due to incompatible version."
msgstr "由於版本不相容，meta 資料還原失敗。"

msgid ""
"Missing 'purestorage' python module, ensure the library is installed and "
"available."
msgstr "遺漏 'purestorage' Python 模組，請確保該程式庫已安裝且可用。"

msgid "Missing Fibre Channel SAN configuration param - fc_fabric_names"
msgstr "遺漏了「光纖通道」SAN 配置參數 - fc_fabric_names"

msgid "Missing request body."
msgstr "遺漏要求內文。"

#, python-format
msgid "Missing required element '%s' in request body."
msgstr "要求內文遺漏了必要元素 '%s'。"

#, python-format
msgid "Multiple copies of volume %s found."
msgstr "找到磁區 %s 的多個副本。"

#, python-format
msgid "Multiple matches found for '%s', use an ID to be more specific."
msgstr "找到 '%s' 的多個相符項，請使用 ID 以更具體地進行尋找。"

msgid "Multiple profiles found."
msgstr "找到多個設定檔。"

msgid "Must implement a fallback schedule"
msgstr "必須實作撤回排程"

msgid "Must implement schedule_create_volume"
msgstr "必須實作 schedule_create_volume"

msgid "Must implement schedule_get_pools"
msgstr "必須實作 schedule_get_pools"

msgid "Must pass wwpn or host to lsfabric."
msgstr "必須將 WWPN 或主機傳遞給 lsfabric。"

msgid ""
"Must run this command as cloud admin using a Keystone policy.json which "
"allows cloud admin to list and get any project."
msgstr ""
"必須以雲端管理者身分使用 Keystone policy.json 來執行此指令，此 policy.json 容"
"許雲端管理者列出和取得任何專案。"

msgid ""
"Must specify 'status', 'attach_status' or 'migration_status' for update."
msgstr "必須指定 'status'、'attach_status' 或 'migration_status' 進行更新。"

#, python-format
msgid "Must specify a valid persona %(valid)s,value '%(persona)s' is invalid."
msgstr "必須指定有效的 persona %(valid)s，值 '%(persona)s' 無效。"

#, python-format
msgid ""
"Must specify a valid provisioning type %(valid)s, value '%(prov)s' is "
"invalid."
msgstr "必須指定有效的供應類型 %(valid)s，值 '%(prov)s' 無效。"

msgid "Must specify an ExtensionManager class"
msgstr "必須指定 ExtensionManager 類別"

msgid "Must specify snapshot source-name or source-id."
msgstr "必須指定 Snapshot source-name 或 source-id。"

msgid "Must specify source-name or source-id."
msgstr "必須修改 source-name 或 source-id。"

msgid "Must specify storage pools. Option: sio_storage_pools."
msgstr "必須指定儲存區。選項：sio_storage_pools。"

msgid "Must supply a positive value for age"
msgstr "必須為經歷時間提供正數值"

#, python-format
msgid ""
"NAS config '%(name)s=%(value)s' invalid. Must be 'auto', 'true', or 'false'"
msgstr "NAS 配置 '%(name)s=%(value)s' 無效。必須為 'auto'、'true' 或'false'"

#, python-format
msgid "NFS config file at %(config)s doesn't exist"
msgstr "%(config)s 處不存在 NFS 配置檔"

#, python-format
msgid "NFS file %s not discovered."
msgstr "未探索到 NFS 檔 %s。"

msgid "NFS file could not be discovered."
msgstr "無法探索 NFS 檔案。"

msgid "NaElement name cannot be null."
msgstr "NaElement 名稱不能是空值。"

msgid "Name"
msgstr "名稱"

msgid ""
"Name, description, add_volumes, and remove_volumes can not be all empty in "
"the request body."
msgstr "要求內文中的名稱、說明、add_volumes 和 remove_volumes 不能全部都為空。"

msgid "Need non-zero volume size"
msgstr "需要非零磁區大小"

msgid "NetApp Cinder Driver exception."
msgstr "NetApp Cinder 驅動程式異常狀況。"

#, python-format
msgid ""
"New size for extend must be greater than current size. (current: %(size)s, "
"extended: %(new_size)s)."
msgstr ""
"用於延伸的新大小必須大於現行大小。（現行大小：%(size)s，延伸後大小："
"%(new_size)s）。"

#, python-format
msgid ""
"New size should be bigger than the real size from backend storage. realsize: "
"%(oldsize)s, newsize: %(newsize)s."
msgstr ""
"新大小應該大於後端儲存體中的實際大小。實際大小：%(oldsize)s，新大小："
"%(newsize)s。"

msgid "New volume type not specified in request_spec."
msgstr "request_spec 中沒有指定新的磁區類型。"

msgid "Nimble Cinder Driver exception"
msgstr "Nimble Cinder 驅動程式異常狀況"

msgid "No FC initiator can be added to host."
msgstr "任何 FC 起始器均無法新增至主機。"

msgid "No FC port connected to fabric."
msgstr "沒有 FC 埠已連接至光纖。"

msgid "No VF ID is defined in the configuration file."
msgstr "配置檔中未定以 VF ID。"

msgid "No active iSCSI portals with supplied iSCSI IPs"
msgstr "沒有具備所提供之 iSCSI IP 的作用中 iSCSI 入口網站"

msgid "No backups available to do an incremental backup."
msgstr "沒有可用的備份來執行增量備份。"

#, python-format
msgid "No cloned LUN named %s found on the filer"
msgstr "在編檔器上找不到名稱為 %s 的複製 LUN"

msgid "No config node found."
msgstr "找不到任何配置節點。"

#, python-format
msgid "No element by given name %s."
msgstr "依給定的名稱 %s，找不到元素。"

#, python-format
msgid "No file found with %s as backing file."
msgstr "找不到含有 %s 的檔案來作為備用檔。"

msgid "No iSCSI-enabled ports on target array."
msgstr "目標陣列上沒有支援 iSCSI 的埠。"

msgid "No initiator connected to fabric."
msgstr "沒有起始器已連接至光纖。"

#, python-format
msgid "No initiator group found for initiator %s"
msgstr "找不到起始器 %s 的起始器群組"

#, python-format
msgid "No interface found on cluster for ip %s"
msgstr "在叢集上找不到 IP %s 的介面"

msgid "No ip address found."
msgstr "找不到任何 IP 位址。"

msgid "No mounted NFS shares found"
msgstr "找不到已裝載的 NFS 共用"

msgid "No mounted SMBFS shares found."
msgstr "找不到已裝載的 SMBFS 共用項目。"

msgid "No mounted Virtuozzo Storage shares found"
msgstr "找不到已裝載的 Virtuozzo 儲存體共用項目"

msgid "No mounted shares found"
msgstr "找不到已裝載的共用項目"

#, python-format
msgid "No node found in I/O group %(gid)s for volume %(vol)s."
msgstr "在磁區 %(vol)s 的 I/O 群組 %(gid)s 中找不到任何節點。"

msgid ""
"No pools are available for provisioning volumes. Ensure that the "
"configuration option netapp_pool_name_search_pattern is set correctly."
msgstr ""
"沒有儲存區可用於供應磁區。請確保已正確設定配置選項 "
"netapp_pool_name_search_pattern。"

#, python-format
msgid "No snap found with %s as backing file."
msgstr "找不到含有 %s 的 Snapshot 來作為備用檔。"

#, python-format
msgid "No such QoS spec %(specs_id)s."
msgstr "沒有這類服務品質規格 %(specs_id)s。"

msgid "No suitable discovery ip found"
msgstr "找不到適當的探索 IP"

#, python-format
msgid "No support to restore backup version %s"
msgstr "不支援還原備份版本 %s"

#, python-format
msgid "No target id found for volume %(volume_id)s."
msgstr "找不到磁區 %(volume_id)s 的目標 ID。"

#, python-format
msgid "No vdisk with the UID specified by ref %s."
msgstr "不存在具有由參照 %s 所指定之 UID 的 vdisk。"

#, python-format
msgid ""
"No volume on cluster with vserver %(vserver)s and junction path %(junction)s "
msgstr "叢集上沒有含 vserver %(vserver)s 及接合路徑%(junction)s 的磁區"

msgid "Not a valid value for NaElement."
msgstr "不是 NaElement 的有效值。"

msgid "Not an rbd snapshot"
msgstr "不是 rbd Snapshot"

#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr "未獲映像檔 %(image_id)s 的授權。"

msgid "Not authorized."
msgstr "未被授權"

#, python-format
msgid "Not enough space on backend (%(backend)s)"
msgstr "後端 (%(backend)s) 上空間不足"

msgid "Not enough storage space in the ZFS share to perform this operation."
msgstr "ZFS 共用中的儲存體空間不足，無法執行此作業。"

msgid "Not stored in rbd"
msgstr "未儲存在 rbd 中"

msgid "Nova returned \"error\" status while creating snapshot."
msgstr "建立 Snapshot 時，Nova 傳回了「錯誤」狀態。"

msgid "Object Count"
msgstr "物件計數"

msgid "Object Version"
msgstr "物件版本"

msgid "Object is not a NetApp LUN."
msgstr "物件不是 NetApp LUN。"

#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr "只能每隔 %(unit_string)s 向 %(uri)s 提出 %(value)s 個 %(verb)s 要求。"

msgid "Only one limit can be set in a QoS spec."
msgstr "在一個服務品質規格中，只能設定一個限制。"

msgid ""
"Only users with token scoped to immediate parents or root projects are "
"allowed to see its children quotas."
msgstr ""
"只容許具備已限定為原生母項或 root 專案範圍之記號的使用者來查看其子項配額。"

msgid "Only volumes managed by OpenStack can be unmanaged."
msgstr "只能取消管理由 OpenStack 進行管理的磁區。"

#, python-format
msgid "Operation failed with status=%(status)s. Full dump: %(data)s"
msgstr "作業失敗，狀態 = %(status)s。完整傾出：%(data)s"

#, python-format
msgid "Operation not supported: %(operation)s."
msgstr "不受支援的作業：%(operation)s。"

msgid "Option gpfs_images_dir is not set correctly."
msgstr "未正確設定選項 gpfs_images_dir。"

msgid "Option gpfs_mount_point_base is not set correctly."
msgstr "未正確設定選項 gpfs_mount_point_base。"

#, python-format
msgid "Originating %(res)s %(prop)s must be one of '%(vals)s' values"
msgstr "原始 %(res)s %(prop)s 必須是值 %(vals)s 的其中之一"

#, python-format
msgid "ParseException: %s"
msgstr "ParseException：%s"

msgid "Partition name is None, please set smartpartition:partitionname in key."
msgstr "分割區名稱為「無」，請在索引鍵中設定 smartpartition:partitionname。"

msgid ""
"Password or SSH private key is required for authentication: set either "
"san_password or san_private_key option."
msgstr ""
"鑑別需要密碼或 SSH 私密金鑰：請設定san_password 或 san_private_key 選項。"

msgid "Path to REST server's certificate must be specified."
msgstr "必須指定 REST 伺服器憑證的路徑。"

#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr "原則不容許執行 %(action)s。"

msgid "Pool is not available in the volume host field."
msgstr "在磁區主機欄位中無法使用儲存區。"

msgid "Pool is not available in the volume host fields."
msgstr "在磁區主機欄位中無法使用儲存區。"

#, python-format
msgid "Pool with name %(pool_name)s wasn't found in domain %(domain_id)s."
msgstr "在網域 %(domain_id)s 中找不到名稱為 %(pool_name)s 的儲存區。"

msgid "Project ID"
msgstr "專案識別號"

#, python-format
msgid "Project quotas are not properly setup for nested quotas: %(reason)s."
msgstr "未針對巢狀配額正確設定專案配額：%(reason)s。"

msgid "Protection Group not ready."
msgstr "保護群組尚未備妥。"

#, python-format
msgid ""
"Protocol %(storage_protocol)s is not supported for storage family "
"%(storage_family)s."
msgstr "通訊協定 %(storage_protocol)s 不受儲存體系列 %(storage_family)s 支援。"

msgid "Provided backup record is missing an id"
msgstr "所提供的備份記錄遺漏了 ID"

#, python-format
msgid ""
"Provided snapshot status %(provided)s not allowed for snapshot with status "
"%(current)s."
msgstr ""
"提供的 Snapshot 狀態 %(provided)s，不為 Snapshot（狀態 = %(current)s）所接"
"受。"

#, python-format
msgid "Pure Storage Cinder driver failure: %(reason)s"
msgstr "Pure Storage Cinder 驅動程式失敗：%(reason)s"

#, python-format
msgid "QoS Specs %(specs_id)s already exists."
msgstr "服務品質規格 %(specs_id)s 已存在。"

#, python-format
msgid "QoS Specs %(specs_id)s is still associated with entities."
msgstr "服務品質規格 %(specs_id)s 仍與實體相關聯。"

#, python-format
msgid "QoS config is wrong. %s must > 0."
msgstr "服務品質配置錯誤。%s 必須大於 0。"

#, python-format
msgid ""
"QoS policy must specify for IOTYPE and another qos_specs, QoS policy: "
"%(qos_policy)s."
msgstr ""
"必須為 IOTYPE 指定服務品質原則及另一個 qos_specs，服務品質原則："
"%(qos_policy)s。"

#, python-format
msgid ""
"QoS policy must specify for IOTYPE: 0, 1, or 2, QoS policy: %(qos_policy)s "
msgstr ""
"必須為 IOTYPE 指定服務品質原則：0、1 或 2，服務品質原則：%(qos_policy)s "

#, python-format
msgid ""
"QoS policy upper_limit and lower_limit conflict, QoS policy: %(qos_policy)s."
msgstr ""
"服務品質原則 upper_limit 與 lower_limit 相衝突，服務品質原則："
"%(qos_policy)s。"

#, python-format
msgid "QoS spec %(specs_id)s has no spec with key %(specs_key)s."
msgstr "服務品質規格 %(specs_id)s 沒有索引鍵為 %(specs_key)s 的規格。"

msgid "Qos specs still in use."
msgstr "服務品質規格仍在使用中。"

msgid "Query resource pool error."
msgstr "查詢資源儲存區時發生錯誤。"

#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr "找不到配額類別 %(class_name)s。"

msgid "Quota could not be found"
msgstr "找不到配額"

#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr "資源已超出配額：%(overs)s"

#, python-format
msgid "Quota exceeded: code=%(code)s"
msgstr "已超出配額：錯誤碼 = %(code)s"

#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr "找不到專案 %(project_id)s 的配額。"

#, python-format
msgid ""
"Quota limit invalid for project '%(proj)s' for resource '%(res)s': limit of "
"%(limit)d is less than in-use value of %(used)d"
msgstr ""
"針對資源 '%(res)s'，專案 '%(proj)s' 的配額限制無效：限制 %(limit)d 小於使用中"
"的值 %(used)d"

#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr "找不到配額預約 %(uuid)s。"

#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr "找不到專案 %(project_id)s 的配額用量。"

#, python-format
msgid "RBD diff op failed - (ret=%(ret)s stderr=%(stderr)s)"
msgstr "RBD 差異 op 失敗 -（ret = %(ret)s 標準錯誤 = %(stderr)s）"

#, python-format
msgid "REST %(proxy_ver)s hpelefthandclient %(rest_ver)s"
msgstr "REST %(proxy_ver)s hpelefthandclient %(rest_ver)s"

msgid "RPC Version"
msgstr "RPC 版本"

#, python-format
msgid "Received error string: %s"
msgstr "接收到錯誤字串：%s"

msgid "Reference must be for an unmanaged snapshot."
msgstr "參照必須是針對未受管理的 Snapshot 進行的。"

msgid "Reference must be for an unmanaged virtual volume."
msgstr "參照必須針對未受管理的虛擬磁區。"

msgid "Reference must be the name of an unmanaged snapshot."
msgstr "參照必須是受管理之 Snapshot 的名稱。"

msgid "Reference must be the volume name of an unmanaged virtual volume."
msgstr "參照必須是未受管理虛擬磁區的磁區名稱。"

msgid "Reference must contain source-id or source-name element."
msgstr "參照必須包含 source-id 或 source-name 元素。"

msgid "Reference must contain source-id or source-name key."
msgstr "參照必須包含 source-id 或 source-name 索引鍵。"

msgid "Reference must contain source-id or source-name."
msgstr "參照必須包含 source-id 或 source-name。"

msgid "Reference must contain source-id."
msgstr "參照必須包含 source-id。"

msgid "Reference must contain source-name element."
msgstr "參照必須包含 source-name 元素。"

msgid "Reference must contain source-name or source-id."
msgstr "參照必須包含 source-name 或 source-id。"

msgid "Reference must contain source-name."
msgstr "參照必須包含 source-name。"

msgid "Reference to volume to be managed must contain source-name."
msgstr "對要管理之磁區的參照必需包含 source-name。"

#, python-format
msgid "Reference to volume: %s to be managed must contain source-name."
msgstr "對要管理之磁區 %s 的參照必需包含 source-name。"

#, python-format
msgid ""
"Refusing to migrate volume ID: %(id)s. Please check your configuration "
"because source and destination are the same Volume Group: %(name)s."
msgstr ""
"正在拒絕移轉磁區 ID：%(id)s。請檢查您的配置，因為來源和目的地是相同的磁區群"
"組：%(name)s。"

msgid "Remote pool cannot be found."
msgstr "找不到遠端儲存區。"

msgid "Remove CHAP error."
msgstr "移除 CHAP 時發生錯誤。"

msgid "Remove fc from host error."
msgstr "從主機中移除 FC 時發生錯誤。"

msgid "Remove host from array error."
msgstr "從陣列中移除主機時發生錯誤。"

msgid "Remove host from hostgroup error."
msgstr "從主機群組中移除主機時發生錯誤。"

msgid "Remove iscsi from host error."
msgstr "從主機中移除 iSCSI 時發生錯誤。"

msgid "Remove lun from QoS error."
msgstr "從服務品質中移除 LUN 時發生錯誤。"

msgid "Remove lun from cache error."
msgstr "從快取中移除 LUN 時發生錯誤。"

msgid "Remove lun from partition error."
msgstr "從分割區中移除 LUN 時發生錯誤。"

msgid "Remove port from port group error."
msgstr "從埠群組中移除埠時發生錯誤。"

msgid "Remove volume export failed."
msgstr "移除磁區匯出失敗。"

msgid "Rename lun on array error."
msgstr "重新命名陣列上的 LUN 時發生錯誤。"

msgid "Rename snapshot on array error."
msgstr "重新命名陣列上的 Snapshot 時發生錯誤。"

#, python-format
msgid "Replication %(name)s to %(ssn)s failed."
msgstr "將 %(name)s 抄寫至 %(ssn)s 失敗。"

msgid "Replication not allowed yet."
msgstr "尚未容許抄寫。"

msgid "Request body and URI mismatch"
msgstr "要求內文與 URI 不符"

msgid "Request body contains too many items"
msgstr "要求內文包含太多項目"

#, python-format
msgid "Request to Datera cluster returned bad status: %(status)s | %(reason)s"
msgstr "傳送至 Datera 叢集的要求，傳回了不正確的狀態：%(status)s | %(reason)s"

#, python-format
msgid ""
"Requested backup exceeds allowed Backup gigabytes quota. Requested "
"%(requested)sG, quota is %(quota)sG and %(consumed)sG has been consumed."
msgstr ""
"所要求的備份超出容許的備份 GB 數配額。要求 %(requested)s G，配額為 %(quota)s "
"G，並且已耗用 %(consumed)s G。"

#, python-format
msgid ""
"Requested volume or snapshot exceeds allowed %(name)s quota. Requested "
"%(requested)sG, quota is %(quota)sG and %(consumed)sG has been consumed."
msgstr ""
"所要求的磁區或 Snapshot 超出容許的 %(name)s 配額。要求 %(requested)s G，配額"
"為 %(quota)s G，並且已耗用 %(consumed)s G。"

msgid "Required configuration not found"
msgstr "找不到必要的配置"

#, python-format
msgid ""
"Reset backup status aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"已中止重設備份狀態，目前配置的備份服務[%(configured_service)s] 不是建立此備份"
"所使用的備份服務 [%(backup_service)s]。"

#, python-format
msgid "Resizing clone %s failed."
msgstr "調整副本 %s 的大小失敗。"

msgid "Resizing image file failed."
msgstr "調整映像檔大小時失敗。"

msgid "Resource could not be found."
msgstr "找不到資源。"

msgid "Resource not ready."
msgstr "資源未備妥。"

msgid "RestURL is not configured."
msgstr "未配置 RestURL。"

#, python-format
msgid ""
"Restore backup aborted, expected volume status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"已中止還原備份，預期磁區狀態 %(expected_status)s，但取得 %(actual_status)s。"

#, python-format
msgid ""
"Restore backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to create "
"this backup [%(backup_service)s]."
msgstr ""
"已中止還原備份，目前配置的備份服務[%(configured_service)s] 不是建立此備份所使"
"用的備份服務 [%(backup_service)s]。"

#, python-format
msgid ""
"Restore backup aborted: expected backup status %(expected_status)s but got "
"%(actual_status)s."
msgstr ""
"已中止還原備份：預期備份狀態 %(expected_status)s，但取得 %(actual_status)s。"

#, python-format
msgid ""
"Retrieved a different amount of SolidFire volumes for the provided Cinder "
"snapshots. Retrieved: %(ret)s Desired: %(des)s"
msgstr ""
"針對所提供的 Cinder Snapshot，已擷取不同數量的 SolidFire 磁區。已擷取數目："
"%(ret)s，所需數目：%(des)s"

#, python-format
msgid ""
"Retrieved a different amount of SolidFire volumes for the provided Cinder "
"volumes. Retrieved: %(ret)s Desired: %(des)s"
msgstr ""
"針對所提供的 Cinder 磁區，已擷取不同數量的 SolidFire 磁區。已擷取數目："
"%(ret)s，所需數目：%(des)s"

#, python-format
msgid "Retry count exceeded for command: %s"
msgstr "已超出指令 %s 的重試次數"

msgid "Retryable SolidFire Exception encountered"
msgstr "發生「可重試的 SolidFire 異常狀況」"

msgid "Retype requires migration but is not allowed."
msgstr "Retype 需要移轉，但系統不容許。"

#, python-format
msgid ""
"Running Cinder with a VMware vCenter version less than %s is not allowed."
msgstr "不容許使用低於 %s 的 VMware vCenter 版本來執行 Cinder。"

msgid "SAN product is not configured."
msgstr "未配置 SAN 產品。"

msgid "SAN protocol is not configured."
msgstr "未配置 SAN 通訊協定。"

#, python-format
msgid "SMBFS config file at %(config)s doesn't exist."
msgstr "%(config)s 處的 SMBFS 配置檔不存在。"

msgid "SMBFS config file not set (smbfs_shares_config)."
msgstr "未設定 SMBFS 配置檔 (smbfs_shares_config)。"

#, python-format
msgid "SSH Command failed after '%(total_attempts)r' attempts : '%(command)s'"
msgstr "嘗試 '%(total_attempts)r' 次之後 SSH 指令仍失敗：'%(command)s'"

#, python-format
msgid "SSH command injection detected: %(command)s"
msgstr "偵測到 SSH 指令注入：%(command)s"

#, python-format
msgid "SSH connection failed for %(fabric)s with error: %(err)s"
msgstr "%(fabric)s 進行 SSH 連線失敗，發生錯誤：%(err)s"

#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr "找不到「排程器主機過濾器」%(filter_name)s。"

#, python-format
msgid "Scheduler Host Weigher %(weigher_name)s could not be found."
msgstr "找不到「排程器主機稱量程式」%(weigher_name)s。"

#, python-format
msgid ""
"Secondary id can not be the same as primary array, backend_id = "
"%(secondary)s."
msgstr "次要 ID 不能與主要陣列相同，backend_id = %(secondary)s。"

#, python-format
msgid "Service %(service)s on host %(host)s removed."
msgstr "已移除主機 %(host)s 上的服務 %(service)s。"

#, python-format
msgid "Service %(service_id)s could not be found on host %(host)s."
msgstr "在主機 %(host)s 上找不到服務 %(service_id)s。"

#, python-format
msgid "Service %(service_id)s could not be found."
msgstr "找不到服務 %(service_id)s。"

msgid "Service is too old to fulfil this request."
msgstr "服務太舊，無法滿足此要求。"

msgid "Service is unavailable at this time."
msgstr "此時無法使用服務。"

msgid "Set pair secondary access error."
msgstr "設定配對次要存取時發生錯誤。"

msgid "Sets thin provisioning."
msgstr "設定精簡供應。"

#, python-format
msgid "Sheepdog I/O Error, command was: \"%s\"."
msgstr "Sheepdog I/O 錯誤，指令為：\"%s\"。"

msgid ""
"Show operations can only be made to projects in the same hierarchy of the "
"project in which users are scoped to."
msgstr "顯示作業只能對將使用者限定範圍之相同專案階層中的專案執行。"

msgid "Size"
msgstr "容量"

#, python-format
msgid "Size for volume: %s not found, cannot secure delete."
msgstr "找不到磁區 %s 的大小，無法安全刪除。"

#, python-format
msgid ""
"Size of specified image %(image_size)sGB is larger than volume size "
"%(volume_size)sGB."
msgstr "所指定映像檔的大小 %(image_size)s GB 大於磁區大小%(volume_size)s GB。"

#, python-format
msgid ""
"Snapshot %(id)s has been asked to be deleted while waiting for it to become "
"available. Perhaps a concurrent request was made."
msgstr ""
"在等待 Snapshot %(id)s 變成可用時，已經要求將其刪除。可能發出了並行要求。"

#, python-format
msgid ""
"Snapshot %(id)s was found in state %(state)s rather than 'deleting' during "
"cascade delete."
msgstr ""
"在連鎖刪除期間，發現 Snapshot %(id)s 處於 %(state)s 狀態，而不是「刪除中」狀"
"態。"

#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr "找不到 Snapshot %(snapshot_id)s。"

#, python-format
msgid "Snapshot %(snapshot_id)s has no metadata with key %(metadata_key)s."
msgstr "Snapshot %(snapshot_id)s 沒有索引鍵為 %(metadata_key)s 的 meta 資料。"

#, python-format
msgid "Snapshot '%s' doesn't exist on array."
msgstr "陣列上不存在 Snapshot '%s'。"

msgid "Snapshot cannot be created while volume is migrating."
msgstr "移轉磁區時無法建立 Snapshot。"

msgid "Snapshot of secondary replica is not allowed."
msgstr "不容許使用次要抄本的 Snapshot。"

#, python-format
msgid "Snapshot of volume not supported in state: %s."
msgstr "狀態 %s 不支援取得磁區的 Snapshot。"

#, python-format
msgid "Snapshot res \"%s\" that is not deployed anywhere?"
msgstr "未在任何位置部署 Snapshot 資源 \"%s\"？"

#, python-format
msgid "Snapshot status %(cur)s not allowed for update_snapshot_status"
msgstr "Snapshot 狀態 %(cur)s，不為 update_snapshot_status 所接受"

#, python-format
msgid ""
"Snapshot to be backed up must be available, but the current status is \"%s\"."
msgstr "要備份的 Snapshot 必須可用，但現行狀態卻是 \"%s\"。"

msgid "SolidFire Cinder Driver exception"
msgstr "SolidFire Cinder 驅動程式異常狀況"

msgid "Sort direction array size exceeds sort key array size."
msgstr "排序方向陣列大小超過排序鍵陣列大小。"

msgid "Source host details not found."
msgstr "找不到來源主機詳細資料。"

msgid "Source volume device ID is required."
msgstr "需要來源磁區裝置 ID。"

msgid "Source volume not mid-migration."
msgstr "移轉期間找不到來源磁區。"

msgid "Specify a password or private_key"
msgstr "指定密碼或 private_key"

msgid "Specify san_password or san_private_key"
msgstr "指定 san_password 或 san_private_key"

msgid ""
"Specify volume type name, description, is_public or a combination thereof."
msgstr "指定磁區類型名稱、說明、is_public 或這些的組合。"

msgid "Split pair error."
msgstr "分割配對時發生錯誤。"

msgid "Split replication failed."
msgstr "分割抄寫失敗。"

msgid "Start LUNcopy error."
msgstr "啟動 LUNcopy 時發生錯誤。"

msgid "State"
msgstr "狀態"

#, python-format
msgid "State of node is wrong. Current state is %s."
msgstr "節點的狀態是錯誤的。現行狀態為 %s。"

msgid "Status"
msgstr "狀態"

msgid "Stop snapshot error."
msgstr "停止 Snapshot 時發生錯誤。"

#, python-format
msgid "Storage family %s is not supported."
msgstr "儲存體系列 %s 不受支援。"

msgid "Storage pool is not configured."
msgstr "未配置儲存區。"

#, python-format
msgid "Storage profile: %(storage_profile)s not found."
msgstr "找不到儲存體設定檔 %(storage_profile)s。"

#, python-format
msgid ""
"Sum of child usage '%(sum)s' is greater than free quota of '%(free)s' for "
"project '%(proj)s' for resource '%(res)s'. Please lower the limit or usage "
"for one or more of the following projects: '%(child_ids)s'"
msgstr ""
"針對資源 '%(res)s'，子項總用量 '%(sum)s' 大於專案 '%(proj)s' 的可用配額 "
"'%(free)s'。請降低下列一個以上專案的限制或用量：'%(child_ids)s'"

msgid "Switch over pair error."
msgstr "切換配對時發生錯誤。"

msgid "Sync pair error."
msgstr "同步配對時發生錯誤。"

msgid "System does not support compression."
msgstr "系統不支援壓縮。"

msgid "System is busy, retry operation."
msgstr "系統忙碌中，請重試作業。"

msgid "Target volume type is still in use."
msgstr "目標磁區類型仍在使用中。"

msgid "Terminate connection failed"
msgstr "終止連線失敗"

msgid "Terminate connection unable to connect to backend."
msgstr "終止連線無法連接至後端。"

#, python-format
msgid "Terminate volume connection failed: %(err)s"
msgstr "終止磁區連線失敗：%(err)s"

msgid ""
"The 'sort_key' and 'sort_dir' parameters are deprecated and cannot be used "
"with the 'sort' parameter."
msgstr ""
"'sort_key' 和 'sort_dir' 參數已遭淘汰，因此無法與 'sort' 參數搭配使用。"

#, python-format
msgid ""
"The GPFS filesystem %(fs)s is not at the required release level.  Current "
"level is %(cur)s, must be at least %(min)s."
msgstr ""
"GPFS 檔案系統 %(fs)s 不是必要的版次。現行層次是 %(cur)s，必須至少是 %(min)s。"

#, python-format
msgid ""
"The WebDAV request failed. Reason: %(msg)s, Return code/reason: %(code)s, "
"Source Volume: %(src)s, Destination Volume: %(dst)s, Method: %(method)s."
msgstr ""
"WebDAV 要求失敗。原因：%(msg)s，回覆碼/原因：%(code)s，來源磁區：%(src)s，目"
"的地磁區：%(dst)s，方法：%(method)s。"

msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using 'cinder-manage db sync' before running this "
"command."
msgstr ""
"上述錯誤可能會顯示尚未建立資料庫。\n"
"請使用 'cinder-manage db sync' 來建立資料庫，然後再執行此指令。"

msgid "The copy should be primary or secondary"
msgstr "副本應為主要或次要副本"

msgid "The decorated method must accept either a volume or a snapshot object"
msgstr "裝飾方法必須接受磁區或 Snapshot 物件"

#, python-format
msgid "The device in the path %(path)s is unavailable: %(reason)s"
msgstr "路徑 %(path)s 中的裝置無法使用：%(reason)s"

#, python-format
msgid "The end time (%(end)s) must be after the start time (%(start)s)."
msgstr "結束時間 (%(end)s) 必須晚於開始時間 (%(start)s)。"

#, python-format
msgid "The failed-over volume could not be deleted: %s"
msgstr "無法刪除已失效接手的磁區：%s"

msgid ""
"The host is not ready to be failed back. Please resynchronize the volumes "
"and resume replication on the 3PAR backends."
msgstr "主機尚未備妥以進行失效回復。請重新同步磁區，並回復 3PAR 後端上的抄寫。"

msgid ""
"The host is not ready to be failed back. Please resynchronize the volumes "
"and resume replication on the LeftHand backends."
msgstr ""
"主機尚未備妥以進行失效回復。請重新同步磁區，並回復 LeftHand 後端上的抄寫。"

msgid "The method update_migrated_volume is not implemented."
msgstr "未實作方法 update_migrated_volume。"

msgid "The parent backup must be available for incremental backup."
msgstr "增量備份的母項備份必須可用。"

#, python-format
msgid "The provided snapshot '%s' is not a snapshot of the provided volume."
msgstr "所提供的 Snapshot '%s' 不是所提供之磁區的 Snapshot。"

#, python-format
msgid "The remote retention count must be %s or less."
msgstr "遠端保留計數必須小於或等於 %s。"

msgid ""
"The replication mode was not configured correctly in the volume type "
"extra_specs. If replication:mode is periodic, replication:sync_period must "
"also be specified and be between 300 and 31622400 seconds."
msgstr ""
"在磁區類型 extra_specs 中，未正確配置抄寫模式。如果 replication:mode 是定期"
"的，則 replication:sync_period 也必須予以指定且介於 300 和 31622400 秒之間。"

#, python-format
msgid "The replication sync period must be at least %s seconds."
msgstr "抄寫同步週期必須至少是 %s 秒。"

msgid "The results are invalid."
msgstr "結果無效。"

#, python-format
msgid "The retention count must be %s or less."
msgstr "保留計數必須小於或等於 %s。"

msgid "The snapshot cannot be created when the volume is in maintenance mode."
msgstr "當磁區處於維護模式時，無法建立 Snapshot。"

msgid "The source volume for this WebDAV operation not found."
msgstr "找不到此 WebDAV 作業的來源磁區。"

#, python-format
msgid ""
"The source volume type '%(src)s' is different than the destination volume "
"type '%(dest)s'."
msgstr "來源磁區類型 '%(src)s' 與目的地磁區類型'%(dest)s' 不同。"

#, python-format
msgid "The source volume type '%s' is not available."
msgstr "來源磁區類型 '%s' 無法使用。"

#, python-format
msgid "The specified LUN does not belong to the given pool: %s."
msgstr "指定的 LUN 不屬於給定的儲存區：%s。"

msgid "The specified vdisk is mapped to a host."
msgstr "所指定的 vdisk 已對映至主機。"

#, python-format
msgid ""
"The storage device does not support %(prot)s. Please configure the device to "
"support %(prot)s or switch to a driver using a different protocol."
msgstr ""
"儲存裝置不支援 %(prot)s。請配置該裝置以支援 %(prot)s，或者切換至使用其他通訊"
"協定的驅動程式。"

#, python-format
msgid ""
"The type of metadata: %(metadata_type)s for volume/snapshot %(id)s is "
"invalid."
msgstr "磁區/Snapshot %(id)s 的 meta 資料類型 %(metadata_type)s無效。"

msgid "The volume cannot accept transfer in maintenance mode."
msgstr "磁區無法在維護模式下接受傳送。"

msgid "The volume cannot be attached in maintenance mode."
msgstr "無法在維護模式下連接磁區。"

msgid "The volume cannot be detached in maintenance mode."
msgstr "無法在維護模式下分離磁區。"

msgid "The volume cannot be updated during maintenance."
msgstr "維護期間，無法更新磁區。"

msgid "The volume connection cannot be initialized in maintenance mode."
msgstr "無法在維護模式下起始設定磁區連線。"

msgid "The volume driver requires the iSCSI initiator name in the connector."
msgstr "磁區驅動程式需要連接器中的 iSCSI 起始器名稱。"

msgid ""
"The volume is currently busy on the 3PAR and cannot be deleted at this time. "
"You can try again later."
msgstr "磁區目前在 3PAR 上正忙，因此此時無法將其刪除。您可以稍後重試。"

msgid "There are no valid ESX hosts."
msgstr "沒有有效的 ESX 主機。"

msgid "There are no valid datastores."
msgstr "沒有有效的資料儲存庫。"

msgid "There is no metadata in DB object."
msgstr "資料庫物件中沒有 meta 資料。"

#, python-format
msgid "There is no share which can host %(volume_size)sG"
msgstr "沒有共用可以管理 %(volume_size)sG"

#, python-format
msgid "There is no share which can host %(volume_size)sG."
msgstr "沒有共用項目可以管理 %(volume_size)s G。"

msgid "There is no virtual disk device."
msgstr "沒有虛擬磁碟裝置。"

#, python-format
msgid "There was an error adding the volume to the remote copy group: %s."
msgstr "將磁區新增至遠端複製群組時發生錯誤：%s。"

#, python-format
msgid "There was an error creating the cgsnapshot: %s"
msgstr "建立 cgsnapshot 時發生錯誤：%s"

#, python-format
msgid "There was an error creating the remote copy group: %s."
msgstr "建立遠端複製群組時發生錯誤：%s。"

#, python-format
msgid ""
"There was an error setting the sync period for the remote copy group: %s."
msgstr "設定遠端複製群組的同步週期時發生錯誤：%s。"

#, python-format
msgid ""
"There was an error setting up a remote copy group on the 3PAR arrays: "
"('%s'). The volume will not be recognized as replication type."
msgstr ""
"在 3PAR 陣列上設定遠端複製群組時發生錯誤：('%s')。該磁區將不作為抄寫類型予以"
"辨識。"

#, python-format
msgid ""
"There was an error setting up a remote schedule on the LeftHand arrays: "
"('%s'). The volume will not be recognized as replication type."
msgstr ""
"在 LeftHand 陣列上設定遠端排程時發生錯誤：('%s')。該磁區將不作為抄寫類型予以"
"辨識。"

#, python-format
msgid "There was an error starting remote copy: %s."
msgstr "啟動遠端複製時發生錯誤：%s。"

#, python-format
msgid "There's no NFS config file configured (%s)"
msgstr "未配置任何 NFS 配置檔 (%s)"

#, python-format
msgid ""
"There's no Quobyte volume configured (%s). Example: quobyte://<DIR host>/"
"<volume name>"
msgstr ""
"沒有已配置的 Quobyte 磁區 (%s)。範例：quobyte://<DIR host>/<volume name>"

msgid "Thin provisioning not supported on this version of LVM."
msgstr "此版本的 LVM 不支援精簡供應。"

msgid "This request was rate-limited."
msgstr "此要求存在頻率限制。"

#, python-format
msgid ""
"This system platform (%s) is not supported. This driver supports only Win32 "
"platforms."
msgstr "此系統平台 (%s) 不受支援。此驅動程式僅支援Win32 平台。"

#, python-format
msgid "Timed out while waiting for Nova update for creation of snapshot %s."
msgstr "等待 Nova 更新以建立 Snapshot %s 時發生逾時。"

#, python-format
msgid ""
"Timed out while waiting for Nova update for deletion of snapshot %(id)s."
msgstr "等待 Nova 更新以刪除 Snapshot %(id)s 時發生逾時。"

#, python-format
msgid "Timeout while requesting %(service)s API."
msgstr "要求 %(service)s API 時發生逾時。"

#, python-format
msgid "Timeout while requesting capabilities from backend %(service)s."
msgstr "要求後端 %(service)s 中的功能時逾時。"

#, python-format
msgid "Transfer %(transfer_id)s could not be found."
msgstr "找不到傳送 %(transfer_id)s。"

#, python-format
msgid ""
"Trying to import backup metadata from id %(meta_id)s into backup %(id)s."
msgstr "正在嘗試將備份 meta 資料從 ID %(meta_id)s 匯入到備份 %(id)s 中。"

#, python-format
msgid ""
"Tune volume task stopped before it was done: volume_name=%(volume_name)s, "
"task-status=%(status)s."
msgstr ""
"調整磁區作業已停止，因為該作業已完成：volume_name=%(volume_name)s，task-"
"status=%(status)s。"

#, python-format
msgid ""
"Type %(type_id)s is already associated with another qos specs: "
"%(qos_specs_id)s"
msgstr "類型 %(type_id)s 已經與另一個服務品質規格%(qos_specs_id)s 產生關聯"

msgid "Type access modification is not applicable to public volume type."
msgstr "類型存取修訂不適用公用磁區類型。"

msgid "Type cannot be converted into NaElement."
msgstr "無法將類型轉換為 NaElement。"

#, python-format
msgid "TypeError: %s"
msgstr "TypeError：%s"

#, python-format
msgid "UUIDs %s are in both add and remove volume list."
msgstr "UUID %s 同時位於新增和移除磁區清單中。"

msgid "Unable to access the backend storage via file handle."
msgstr "無法透過檔案控點來存取後端儲存體。"

#, python-format
msgid "Unable to access the backend storage via the path %(path)s."
msgstr "無法透過路徑 %(path)s 來存取後端儲存體。"

#, python-format
msgid "Unable to complete failover of %s."
msgstr "無法完成 %s 的失效接手。"

msgid "Unable to connect or find connection to host"
msgstr "無法連接至主機或找不到與主機的連線"

msgid "Unable to create lock. Coordination backend not started."
msgstr "無法建立鎖定。協調後端未啟動。"

#, python-format
msgid "Unable to create volume %(name)s from %(snap)s."
msgstr "無法從 %(snap)s 建立磁區 %(name)s。"

#, python-format
msgid "Unable to create volume %(name)s from %(vol)s."
msgstr "無法從 %(vol)s 建立磁區 %(name)s。"

#, python-format
msgid "Unable to create volume %s"
msgstr "無法建立磁區 %s"

msgid "Unable to create volume. Backend down."
msgstr "無法建立磁區。後端已關閉。"

#, python-format
msgid "Unable to delete snapshot %(id)s, status: %(status)s."
msgstr "無法刪除 Snapshot %(id)s，狀態：%(status)s。"

msgid ""
"Unable to detach volume. Volume status must be 'in-use' and attach_status "
"must be 'attached' to detach."
msgstr ""
"無法分離磁區。磁區狀態必須是「使用中」，並且 attach_status必須是「已連接」才"
"能進行分離。"

#, python-format
msgid ""
"Unable to determine secondary_array from supplied secondary: %(secondary)s."
msgstr "無法判定來自所提供之次要項目的 secondary_array：%(secondary)s。"

#, python-format
msgid "Unable to determine snapshot name in Purity for snapshot %(id)s."
msgstr "針對 Snapshot %(id)s，無法判定純度中的 Snapshot 名稱。"

msgid "Unable to determine system id."
msgstr "無法判定系統 ID。"

msgid "Unable to determine system name."
msgstr "無法判定系統名稱。"

#, python-format
msgid ""
"Unable to do manage snapshot operations with Purity REST API version "
"%(api_version)s, requires %(required_versions)s."
msgstr ""
"無法使用純度 REST API 版本 %(api_version)s 來執行管理 Snapshot 作業需要 "
"%(required_versions)s。"

#, python-format
msgid ""
"Unable to do replication with Purity REST API version %(api_version)s, "
"requires one of %(required_versions)s."
msgstr ""
"無法使用純度 REST API %(api_version)s 版來執行抄寫作業，需要下列其中一個："
"%(required_versions)s。"

#, python-format
msgid "Unable to establish the partnership with the Storwize cluster %s."
msgstr "無法與 Storwize 叢集 %s 建立夥伴關係。"

#, python-format
msgid "Unable to extend volume %s"
msgstr "無法延伸磁區 %s"

msgid ""
"Unable to failback to \"default\", this can only be done after a failover "
"has completed."
msgstr "無法失效回復至「預設」，只有在失效接手完成之後才能執行此作業。"

msgid "Unable to fetch connection information from backend."
msgstr "無法從後端提取連線資訊。"

#, python-format
msgid "Unable to fetch connection information from backend: %(err)s"
msgstr "無法從後端提取連線資訊：%(err)s"

#, python-format
msgid "Unable to find Purity ref with name=%s"
msgstr "找不到名稱為 %s 的純度參照"

#, python-format
msgid "Unable to find Volume Group: %(vg_name)s"
msgstr "找不到磁區群組：%(vg_name)s"

msgid "Unable to find failover target, no secondary targets configured."
msgstr "找不到失效接手目標，未配置次要目標。"

msgid "Unable to find iSCSI mappings."
msgstr "找不到 iSCSI 對映。"

#, python-format
msgid "Unable to find ssh_hosts_key_file: %s"
msgstr "找不到 ssh_hosts_key_file：%s"

#, python-format
msgid "Unable to find volume %s"
msgstr "找不到磁區 %s"

#, python-format
msgid "Unable to get a block device for file '%s'"
msgstr "無法取得檔案 '%s' 的區塊裝置"

#, python-format
msgid ""
"Unable to get configuration information necessary to create a volume: "
"%(errorMessage)s."
msgstr "無法取得建立磁區所需的配置資訊：%(errorMessage)s。"

#, python-format
msgid "Unable to get stats for backend_name: %s"
msgstr "無法取得 backend_name 的統計資料：%s"

#, python-format
msgid "Unable to locate account %(account_name)s on Solidfire device"
msgstr "在 SolidFire 裝置上找不到帳戶 %(account_name)s"

#, python-format
msgid "Unable to locate an SVM that is managing the IP address '%s'"
msgstr "找不到管理 IP 位址 '%s' 的 SVM"

#, python-format
msgid "Unable to locate specified replay profiles %s "
msgstr "找不到指定的重播設定檔 %s "

#, python-format
msgid ""
"Unable to manage existing volume. Volume %(volume_ref)s already managed."
msgstr "無法管理現有磁區。磁區 %(volume_ref)s 已經受管理。"

#, python-format
msgid "Unable to manage volume %s"
msgstr "無法管理磁區 %s"

msgid "Unable to map volume"
msgstr "無法對映磁區"

msgid "Unable to map volume."
msgstr "無法對映磁區。"

msgid "Unable to parse attributes."
msgstr "無法剖析屬性。"

msgid ""
"Unable to re-use a host that is not managed by Cinder with "
"use_chap_auth=True,"
msgstr "無法重複使用未受 Cinder 管理且use_chap_auth=True 的主機。"

msgid "Unable to re-use host with unknown CHAP credentials configured."
msgstr "無法重複使用配置有不明 CHAP 認證的主機。"

#, python-format
msgid "Unable to rename volume %(existing)s to %(newname)s"
msgstr "無法將磁區 %(existing)s 重新命名為 %(newname)s"

#, python-format
msgid ""
"Unable to retype %(specname)s, expected to receive current and requested "
"%(spectype)s values. Value received: %(spec)s"
msgstr ""
"無法對 %(specname)s 執行 Retype 作業，預期接收現行及要求的 %(spectype)s 值。"
"接收到的值：%(spec)s"

#, python-format
msgid ""
"Unable to retype:  A copy of volume %s exists. Retyping would exceed the "
"limit of 2 copies."
msgstr ""
"無法執行 Retype 動作：存在磁區 %s 的副本。如果執行 Retype 動作，則將超過2 份"
"副本的限制。"

#, python-format
msgid ""
"Unable to retype: Current action needs volume-copy, it is not allowed when "
"new type is replication. Volume = %s"
msgstr ""
"無法執行 Retype 動作：現行動作需要磁區複製，但當新類型為抄寫時，不容許這樣"
"做。磁區為 %s"

#, python-format
msgid ""
"Unable to set up mirror mode replication for %(vol)s. Exception: %(err)s."
msgstr "無法設定 %(vol)s 的鏡映模式抄寫。異常狀況：%(err)s。"

msgid "Unable to terminate volume connection from backend."
msgstr "無法從後端終止磁區連線。"

#, python-format
msgid "Unable to terminate volume connection: %(err)s"
msgstr "無法終止磁區連線：%(err)s"

msgid "Unacceptable parameters."
msgstr "不可接受的參數值"

#, python-format
msgid ""
"Unexecpted mapping status %(status)s for mapping %(id)s. Attributes: "
"%(attr)s."
msgstr "對映 %(id)s 的對映狀態 %(status)s 不符合預期。屬性：%(attr)s。"

#, python-format
msgid ""
"Unexpected CLI response: header/row mismatch. header: %(header)s, row: "
"%(row)s."
msgstr "非預期的 CLI 回應：標頭/列不符。標頭：%(header)s、列：%(row)s。"

#, python-format
msgid "Unexpected output. Expected [%(expected)s] but received [%(output)s]"
msgstr "非預期的輸出。預期 [%(expected)s]，但卻接收到 [%(output)s]"

msgid "Unexpected response from Nimble API"
msgstr "來自 Nimble API 的非預期回應"

msgid "Unexpected status code"
msgstr "非預期的狀態碼"

#, python-format
msgid ""
"Unexpected status code from the switch %(switch_id)s with protocol "
"%(protocol)s for url %(page)s. Error: %(error)s"
msgstr ""
"針對 URL %(page)s，從使用通訊協定 %(protocol)s 的交換器 %(switch_id)s 傳回非"
"預期的狀態碼。錯誤：%(error)s"

msgid "Unknown NFS exception"
msgstr "不明的 NFS 異常狀況"

msgid "Unknown RemoteFS exception"
msgstr "不明的 RemoteFS 異常狀況"

msgid "Unknown SMBFS exception."
msgstr "不明的 SMBFS 異常狀況。"

msgid "Unknown Virtuozzo Storage exception"
msgstr "「不明 Virtuozzo 儲存體」異常狀況"

msgid "Unknown action"
msgstr "不明動作"

#, python-format
msgid ""
"Unknown if the volume: %s to be managed is already being managed by Cinder. "
"Aborting manage volume. Please add 'cinder_managed' custom schema property "
"to the volume and set its value to False. Alternatively, Set the value of "
"cinder config policy 'zfssa_manage_policy' to 'loose' to remove this "
"restriction."
msgstr ""
"如果要管理的磁區 %s 已經由 Cinder 進行管理，則是不明情況。正在終止管理磁區。"
"請將 'cinder_managed' 自訂綱目內容新增至該磁區，並將它的值設為 False。或者，"
"將 Cinder 配置原則 'zfssa_manage_policy' 的值設為 'loose'，以移除此限制。"

#, python-format
msgid ""
"Unknown if the volume: %s to be managed is already being managed by Cinder. "
"Aborting manage volume. Please add 'cinder_managed' custom schema property "
"to the volume and set its value to False. Alternatively, set the value of "
"cinder config policy 'zfssa_manage_policy' to 'loose' to remove this "
"restriction."
msgstr ""
"如果要管理的磁區 %s 已經由 Cinder 進行管理，則是不明情況。正在終止管理磁區。"
"請將 'cinder_managed' 自訂綱目內容新增至該磁區，並將它的值設為 False。或者，"
"將 Cinder 配置原則 'zfssa_manage_policy' 的值設為 'loose'，以移除此限制。"

#, python-format
msgid "Unknown or unsupported command %(cmd)s"
msgstr "不明或不支援的指令 %(cmd)s"

#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr "不明的配額資源 %(unknown)s。"

msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "不明的排序方向，必須為 'desc' 或 'asc'"

msgid "Unknown sort direction, must be 'desc' or 'asc'."
msgstr "不明的排序方向，必須為 'desc' 或 'asc'。"

msgid "Unmanage and cascade delete options are mutually exclusive."
msgstr "取消管理與連鎖刪除選項是互斥的。"

msgid "Unmanage volume not implemented."
msgstr "未實作取消管理磁區。"

msgid "Unmanaging of snapshots from 'failed-over' volumes is not allowed."
msgstr "不容許取消管理「已失效接手」之磁區中的 Snapshot。"

msgid "Unmanaging of snapshots from failed-over volumes is not allowed."
msgstr "不容許取消管理已失效接手之磁區中的 Snapshot。"

#, python-format
msgid "Unrecognized QOS keyword: \"%s\""
msgstr "無法辨識的服務品質關鍵字：\"%s\""

#, python-format
msgid "Unrecognized backing format: %s"
msgstr "無法辨識的備用格式：%s"

#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr "無法辨識 read_deleted 值 '%s'"

msgid "Unsupported Content-Type"
msgstr "不支援的內容類型"

#, python-format
msgid "Unsupported backup metadata version (%s)"
msgstr "不支援的備份 meta 資料版本 (%s)"

msgid "Unsupported backup metadata version requested"
msgstr "所要求的備份 meta 資料版本不受支援"

msgid "Unsupported backup verify driver"
msgstr "不受支援的備份驗證驅動程式"

#, python-format
msgid ""
"Unsupported firmware on switch %s. Make sure switch is running firmware v6.4 "
"or higher"
msgstr "交換器 %s 上的韌體不受支援。請確保交換器正在執行韌體6.4 版或更高版本"

#, python-format
msgid "Unsupported volume format: %s "
msgstr "不受支援的磁區格式：%s"

msgid "Update QoS policy error."
msgstr "更新服務品質原則時發生錯誤。"

msgid ""
"Update and delete quota operations can only be made by an admin of immediate "
"parent or by the CLOUD admin."
msgstr "更新和刪除配額作業只能由原生母項的管理者或CLOUD 管理者來執行。"

msgid ""
"Update and delete quota operations can only be made to projects in the same "
"hierarchy of the project in which users are scoped to."
msgstr "更新和刪除配額作業只能對將使用者限定範圍之相同專案階層中的專案執行。"

msgid "Updated At"
msgstr "已更新"

msgid "Upload to glance of attached volume is not supported."
msgstr "不支援將所連接的磁區上傳至 Glance。"

msgid "Use ALUA to associate initiator to host error."
msgstr "使用 ALUA 將起始器關聯至主機時發生錯誤。"

msgid ""
"Use CHAP to associate initiator to host error. Please check the CHAP "
"username and password."
msgstr "使用 CHAP 將起始器關聯至主機時發生錯誤。請檢查 CHAP 使用者名稱及密碼。"

msgid "User ID"
msgstr "使用者識別號"

msgid "User does not have admin privileges"
msgstr "使用者並沒有管理者權力"

msgid "User not authorized to perform WebDAV operations."
msgstr "使用者未獲授權來執行 WebDAV 作業。"

msgid "UserName is not configured."
msgstr "未配置 UserName。"

msgid "UserPassword is not configured."
msgstr "未配置 UserPassword。"

msgid "VF is not enabled."
msgstr "未啟用 VF。"

#, python-format
msgid "VV Set %s does not exist."
msgstr "「VV 集」%s 不存在。"

#, python-format
msgid "Valid consumer of QoS specs are: %s"
msgstr "服務品質規格的有效消費者為：%s"

#, python-format
msgid "Validate volume connection failed (error: %(err)s)."
msgstr "驗證磁區連線失敗（錯誤：%(err)s）。"

#, python-format
msgid ""
"Value \"%(value)s\" is not valid for configuration option \"%(option)s\""
msgstr "值 \"%(value)s\" 不適用於配置選項 \"%(option)s\""

#, python-format
msgid "ValueError: %s"
msgstr "ValueError：%s"

#, python-format
msgid "Vdisk %(name)s not involved in mapping %(src)s -> %(tgt)s."
msgstr "從 %(src)s 到 %(tgt)s 的對映未涉及到 vdisk %(name)s。"

#, python-format
msgid ""
"Version %(req_ver)s is not supported by the API. Minimum is %(min_ver)s and "
"maximum is %(max_ver)s."
msgstr "API 不支援 %(req_ver)s 版。下限為 %(min_ver)s，上限為 %(max_ver)s。"

#, python-format
msgid "VersionedObject %s cannot retrieve object by id."
msgstr "VersionedObject %s 無法依 ID 擷取物件。"

#, python-format
msgid "VersionedObject %s does not support conditional update."
msgstr "VersionedObject %s 不支援條件式更新。"

#, python-format
msgid "Virtual volume '%s' doesn't exist on array."
msgstr "虛擬磁區 '%s' 不在陣列上。"

#, python-format
msgid "Volume %(deviceID)s not found."
msgstr "找不到磁區 %(deviceID)s。"

#, python-format
msgid "Volume %(name)s was created in VNX, but in %(state)s state."
msgstr "已在 VNX 中建立磁區 %(name)s，但該磁區處於 %(state)s 狀態。"

#, python-format
msgid "Volume %(vol)s could not be created in pool %(pool)s."
msgstr "無法在儲存區 %(pool)s 中建立磁區 %(vol)s。"

#, python-format
msgid "Volume %(vol1)s does not match with snapshot.volume_id %(vol2)s."
msgstr "磁區 %(vol1)s 與 snapshot.volume_id %(vol2)s 不符。"

#, python-format
msgid ""
"Volume %(vol_id)s status must be available to update readonly flag, but "
"current status is: %(vol_status)s."
msgstr ""
"磁區 %(vol_id)s 狀態必須為可用，才能更新唯讀旗標，但現行狀態為："
"%(vol_status)s。"

#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr "找不到磁區 %(volume_id)s。"

#, python-format
msgid ""
"Volume %(volume_id)s has no administration metadata with key "
"%(metadata_key)s."
msgstr "磁區 %(volume_id)s 沒有索引鍵為%(metadata_key)s 的管理 meta 資料。"

#, python-format
msgid "Volume %(volume_id)s has no metadata with key %(metadata_key)s."
msgstr "磁區 %(volume_id)s 沒有索引鍵為 %(metadata_key)s 的 meta 資料。"

#, python-format
msgid "Volume %(volume_id)s is still attached, detach volume first."
msgstr "磁區 %(volume_id)s 仍處於連接狀態，請先將磁區分離。"

#, python-format
msgid "Volume %(volume_id)s replication error: %(reason)s"
msgstr "磁區 %(volume_id)s 抄寫錯誤：%(reason)s"

#, python-format
msgid "Volume %s could not be created from source volume."
msgstr "無法從來源磁區建立磁區 %s。"

#, python-format
msgid "Volume %s could not be created on shares."
msgstr "無法在共用上建立磁區 %s。"

#, python-format
msgid "Volume %s could not be created."
msgstr "無法建立磁區 %s。"

#, python-format
msgid "Volume %s does not exist in Nexenta SA"
msgstr "磁區 %s 不存在於 Nexenta SA 中"

#, python-format
msgid "Volume %s does not exist in Nexenta Store appliance"
msgstr "磁區 %s 不存在於「Nexenta 儲存庫」軟體驅動裝置中"

#, python-format
msgid "Volume %s does not exist on the array."
msgstr "磁區 %s 不在陣列上。"

#, python-format
msgid "Volume %s does not have provider_location specified, skipping."
msgstr "沒有為磁區 %s 指定 provider_location，正在跳過。"

#, python-format
msgid "Volume %s doesn't exist on array."
msgstr "磁區 %s 不在陣列上。"

#, python-format
msgid "Volume %s doesn't exist on the ZFSSA backend."
msgstr "磁區 %s 不存在於 ZFSSA 後端上。"

#, python-format
msgid ""
"Volume %s is online. Set volume to offline for managing using OpenStack."
msgstr "磁區 %s 在線上。請將磁區設為離線，以使用 OpenStack 進行管理。"

#, python-format
msgid "Volume %s must not be part of a consistency group."
msgstr "磁區 %s 不得為一致性群組的一部分。"

#, python-format
msgid "Volume %s not found."
msgstr "找不到磁區 %s。"

#, python-format
msgid "Volume %s: Error trying to extend volume"
msgstr "磁區 %s：嘗試延伸磁區時發生錯誤"

#, python-format
msgid "Volume (%s) already exists on array"
msgstr "陣列上已存在磁區 (%s)"

#, python-format
msgid "Volume (%s) already exists on array."
msgstr "陣列上已存在磁區 (%s)。"

#, python-format
msgid "Volume Group %s does not exist"
msgstr "磁區群組 %s 不存在"

#, python-format
msgid "Volume Type %(id)s already exists."
msgstr "磁區類型 %(id)s 已存在。"

#, python-format
msgid ""
"Volume Type %(volume_type_id)s deletion is not allowed with volumes present "
"with the type."
msgstr "磁區類型 %(volume_type_id)s 刪除作業，不為該類型的磁區所接受。"

#, python-format
msgid ""
"Volume Type %(volume_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""
"磁區類型 %(volume_type_id)s 沒有索引鍵為 %(extra_specs_key)s 的額外規格。"

msgid "Volume Type id must not be None."
msgstr "磁區類型 ID 不得為 None。"

msgid "Volume by this name already exists"
msgstr "具有此名稱的磁區已經存在"

msgid "Volume create failed while extracting volume ref."
msgstr "擷取磁區參照時，磁區建立失敗。"

#, python-format
msgid "Volume device file path %s does not exist."
msgstr "磁區裝置檔案路徑 %s 不存在。"

#, python-format
msgid "Volume device not found at %(device)s."
msgstr "在 %(device)s 處找不到磁區裝置。"

#, python-format
msgid "Volume driver %s not initialized."
msgstr "未起始設定磁區驅動程式 %s。"

msgid "Volume driver not ready."
msgstr "磁區驅動程式未備妥。"

#, python-format
msgid "Volume driver reported an error: %(message)s"
msgstr "磁區驅動程式報告了錯誤：%(message)s"

msgid "Volume has a temporary snapshot that can't be deleted at this time."
msgstr "磁區具有目前無法刪除的暫時 Snapshot。"

msgid "Volume has children and cannot be deleted!"
msgstr "磁區具有子項，且無法予以刪除！"

#, python-format
msgid "Volume is attached to a server.  (%s)"
msgstr "已將磁區連接至伺服器。(%s)"

msgid "Volume is in-use."
msgstr "磁區在使用中。"

msgid "Volume is not available."
msgstr "無法使用磁區。"

msgid "Volume is not local to this node."
msgstr "磁區不是此節點的本端磁區。"

msgid ""
"Volume metadata backup requested but this driver does not yet support this "
"feature."
msgstr "已要求磁區 meta 資料備份，但此驅動程式尚不支援此功能。"

#, python-format
msgid "Volume migration failed: %(reason)s"
msgstr "移轉磁區失敗：%(reason)s"

msgid "Volume must be in the same availability zone as the snapshot"
msgstr "磁區和 Snapshot 必須位在同一個可用性區域中"

msgid "Volume must be in the same availability zone as the source volume"
msgstr "磁區和來源磁區必須位在同一個可用性區域中"

msgid "Volume must have a volume type"
msgstr "磁區必須具有磁區類型"

msgid "Volume must not be replicated."
msgstr "不得抄寫磁區。"

msgid "Volume must not have snapshots."
msgstr "磁區不得具有 Snapshot。"

#, python-format
msgid "Volume not found for instance %(instance_id)s."
msgstr "找不到實例 %(instance_id)s 的磁區。"

msgid "Volume not found on configured storage backend."
msgstr "在所配置的儲存體後端系統上找不到磁區。"

msgid "Volume not found."
msgstr "找不到磁區。"

msgid "Volume not unique."
msgstr "磁區不是唯一的。"

msgid "Volume not yet assigned to host."
msgstr "尚未將磁區指派給主機。"

msgid "Volume reference must contain source-name element."
msgstr "磁區參照必須包含 source-name 元素。"

#, python-format
msgid "Volume replication for %(volume_id)s could not be found."
msgstr "找不到 %(volume_id)s 的磁區抄寫。"

msgid "Volume should have agent-type set as None."
msgstr "磁區應該將代理程式類型設定為「無」。"

#, python-format
msgid ""
"Volume size %(volume_size)sGB cannot be smaller than the image minDisk size "
"%(min_disk)sGB."
msgstr ""
"磁區大小 %(volume_size)s GB 不能小於映像檔 minDisk 大小 %(min_disk)s GB。"

#, python-format
msgid "Volume size '%(size)s' must be an integer and greater than 0"
msgstr "磁區大小 '%(size)s' 必須是大於 0 的整數"

#, python-format
msgid ""
"Volume size '%(size)s'GB cannot be smaller than original volume size  "
"%(source_size)sGB. They must be >= original volume size."
msgstr ""
"磁區大小 '%(size)s' GB 不能小於原始磁區大小%(source_size)s GB。它們必須大於或"
"等於原始磁區大小。"

#, python-format
msgid ""
"Volume size '%(size)s'GB cannot be smaller than the snapshot size "
"%(snap_size)sGB. They must be >= original snapshot size."
msgstr ""
"磁區大小 '%(size)s' GB 不能小於 Snapshot 大小%(snap_size)s GB。它們必須大於或"
"等於原始 Snapshot 大小。"

msgid "Volume size increased since the last backup. Do a full backup."
msgstr "磁區大小自前次備份以來已增加。請執行完整備份。"

msgid "Volume size must be a multiple of 1 GB."
msgstr "磁區大小必須是 1 GB 的倍數。"

msgid "Volume size must multiple of 1 GB."
msgstr "磁區大小必須是 1 GB 的倍數。"

msgid "Volume status must be 'available'."
msgstr "磁區狀態必須為「可用」。"

msgid "Volume to Initiator Group mapping already exists"
msgstr "磁區至起始器群組的對映已存在"

#, python-format
msgid ""
"Volume to be backed up must be available or in-use, but the current status "
"is \"%s\"."
msgstr "要備份的磁區必須處於可用或使用中狀態，但是現行狀態是 \"%s\"。"

msgid "Volume to be restored to must be available"
msgstr "要還原至的磁區必須可用"

#, python-format
msgid "Volume type %(volume_type_id)s could not be found."
msgstr "找不到磁區類型 %(volume_type_id)s。"

#, python-format
msgid "Volume type ID '%s' is invalid."
msgstr "磁區類型 ID '%s' 無效。"

#, python-format
msgid ""
"Volume type access for %(volume_type_id)s / %(project_id)s combination "
"already exists."
msgstr "%(volume_type_id)s / %(project_id)s 組合的磁區類型存取已存在。"

#, python-format
msgid ""
"Volume type access not found for %(volume_type_id)s / %(project_id)s "
"combination."
msgstr "找不到 %(volume_type_id)s / %(project_id)s 組合的磁區類型存取。"

#, python-format
msgid "Volume type encryption for type %(type_id)s already exists."
msgstr "類型 %(type_id)s 的磁區類型加密已存在。"

#, python-format
msgid "Volume type encryption for type %(type_id)s does not exist."
msgstr "類型 %(type_id)s 的磁區類型加密不存在。"

msgid "Volume type name can not be empty."
msgstr "磁區類型名稱不能為空。"

#, python-format
msgid "Volume type with name %(volume_type_name)s could not be found."
msgstr "找不到名稱為 %(volume_type_name)s 的磁區類型。"

#, python-format
msgid "Volume: %s is already being managed by Cinder."
msgstr "磁區 %s 已經由 Cinder 進行管理。"

msgid ""
"Volumes/account exceeded on both primary and secondary SolidFire accounts."
msgstr "超過了主要及次要 SolidFire 帳戶上的磁區/帳戶。"

#, python-format
msgid ""
"VzStorage config 'vzstorage_used_ratio' invalid. Must be > 0 and <= 1.0: %s."
msgstr ""
"VzStorage 配置 'vzstorage_used_ratio' 無效。必須大於 0 且小於或等於 1.0：%s。"

#, python-format
msgid "VzStorage config file at %(config)s doesn't exist."
msgstr "%(config)s 處的 VzStorage 配置檔不存在。"

#, python-format
msgid "Wait synchronize failed. Running status: %s."
msgstr "等待同步失敗。執行中狀態：%s。"

msgid ""
"Waiting for all nodes to join cluster. Ensure all sheep daemons are running."
msgstr "正在等待所有節點結合叢集。請確保所有 sheep 常駐程式都在執行中。"

msgid "We should not do switch over on primary array."
msgstr "我們不應切換到主要陣列上。"

msgid "XtremIO not configured correctly, no iscsi portals found"
msgstr "未正確地配置 XtremIO，找不到 iSCSI 入口網站"

msgid "XtremIO not initialized correctly, no clusters found"
msgstr "未正確地起始設定 XtremIO，找不到叢集"

msgid "You must implement __call__"
msgstr "必須實作 __call__"

msgid ""
"You must install hpe3parclient before using 3PAR drivers. Run \"pip install "
"python-3parclient\" to install the hpe3parclient."
msgstr ""
"在使用 3PAR 驅動程式之前，必須先安裝 hpe3parclient。請執行 \"pip install "
"python-3parclient\" 來安裝 hpe3parclient。"

#, python-format
msgid "ZeroDivisionError: %s"
msgstr "ZeroDivisionError：%s"

msgid "Zone"
msgstr "區域"

#, python-format
msgid "Zoning Policy: %s, not recognized"
msgstr "分區原則：%s，無法辨識"

#, python-format
msgid "_create_and_copy_vdisk_data: Failed to get attributes for vdisk %s."
msgstr "_create_and_copy_vdisk_data：無法取得 vdisk %s 的屬性。"

msgid "_create_host failed to return the host name."
msgstr "_create_host 無法傳回主機名稱。"

msgid ""
"_create_host: Can not translate host name. Host name is not unicode or "
"string."
msgstr "_create_host：無法轉換主機名稱。主機名稱不是 Unicode 或字串。"

msgid "_create_host: No connector ports."
msgstr "_create_host：無連接器埠。"

msgid "_create_local_cloned_volume, Replication Service not found."
msgstr "_create_local_cloned_volume，找不到「抄寫服務」。"

#, python-format
msgid ""
"_create_local_cloned_volume, volumename: %(volumename)s, sourcevolumename: "
"%(sourcevolumename)s, source volume instance: %(source_volume)s, target "
"volume instance: %(target_volume)s, Return code: %(rc)lu, Error: "
"%(errordesc)s."
msgstr ""
"_create_local_cloned_volume，磁區名稱：%(volumename)s，來源磁區名稱："
"%(sourcevolumename)s，來源磁區實例：%(source_volume)s，目標磁區實例："
"%(target_volume)s，回覆碼：%(rc)lu，錯誤：%(errordesc)s。"

#, python-format
msgid ""
"_create_vdisk %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"_create_vdisk %(name)s - 在 CLI 輸出中找不到成功訊息。\n"
" 標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

msgid "_create_volume_name, id_code is None."
msgstr "_create_volume_name，id_code 為「無」。"

msgid "_delete_copysession, Cannot find Replication Service"
msgstr "_delete_copysession，找不到「抄寫服務」"

#, python-format
msgid ""
"_delete_copysession, copy session type is undefined! copy session: "
"%(cpsession)s, copy type: %(copytype)s."
msgstr ""
"_delete_copysession，未定義複製階段作業類型！複製階段作業：%(cpsession)s，複"
"製類型：%(copytype)s。"

#, python-format
msgid ""
"_delete_copysession, copysession: %(cpsession)s, operation: %(operation)s, "
"Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""
"_delete_copysession，複製階段作業：%(cpsession)s，作業：%(operation)s，回覆"
"碼：%(rc)lu，錯誤：%(errordesc)s。"

#, python-format
msgid ""
"_delete_volume, volumename: %(volumename)s, Return code: %(rc)lu, Error: "
"%(errordesc)s."
msgstr ""
"_delete_volume，磁區名稱：%(volumename)s，回覆碼：%(rc)lu，錯誤："
"%(errordesc)s。"

#, python-format
msgid ""
"_delete_volume, volumename: %(volumename)s, Storage Configuration Service "
"not found."
msgstr "_delete_volume，磁區名稱：%(volumename)s，找不到「儲存體配置服務」。"

#, python-format
msgid ""
"_exec_eternus_service, classname: %(classname)s, InvokeMethod, cannot "
"connect to ETERNUS."
msgstr ""
"_exec_eternus_service，類別名稱：%(classname)s，呼叫方法，無法連接至 "
"ETERNUS。"

msgid "_extend_volume_op: Extending a volume with snapshots is not supported."
msgstr "_extend_volume_op：不支援延伸具有 Snapshot 的磁區。"

#, python-format
msgid ""
"_find_affinity_group, connector: %(connector)s, Associators: "
"FUJITSU_AuthorizedTarget, cannot connect to ETERNUS."
msgstr ""
"_find_affinity_group，連接器：%(connector)s，協助程式："
"FUJITSU_AuthorizedTarget，無法連接至 ETERNUS。"

#, python-format
msgid ""
"_find_affinity_group, connector: %(connector)s, EnumerateInstanceNames, "
"cannot connect to ETERNUS."
msgstr ""
"_find_affinity_group，連接器：%(connector)s，列舉實例名稱，無法連接至 "
"ETERNUS。"

#, python-format
msgid ""
"_find_affinity_group,connector: %(connector)s,AssocNames: "
"FUJITSU_ProtocolControllerForUnit, cannot connect to ETERNUS."
msgstr ""
"_find_affinity_group，連接器：%(connector)s，協助程式名稱："
"FUJITSU_ProtocolControllerForUnit，無法連接至 ETERNUS。"

#, python-format
msgid ""
"_find_copysession, ReferenceNames, vol_instance: %(vol_instance_path)s, "
"Cannot connect to ETERNUS."
msgstr ""
"_find_copysession，參照名稱，vol_instance：%(vol_instance_path)s，無法連接至 "
"ETERNUS。"

#, python-format
msgid ""
"_find_eternus_service, classname: %(classname)s, EnumerateInstanceNames, "
"cannot connect to ETERNUS."
msgstr ""
"_find_eternus_service，類別名稱：%(classname)s，列舉實例名稱，無法連接至 "
"ETERNUS。"

#, python-format
msgid "_find_initiator_names, connector: %(connector)s, initiator not found."
msgstr "_find_initiator_names，連接器：%(connector)s，找不到起始器。"

#, python-format
msgid ""
"_find_lun, volumename: %(volumename)s, EnumerateInstanceNames, cannot "
"connect to ETERNUS."
msgstr ""
"_find_lun，磁區名稱：%(volumename)s，列舉實例名稱，無法連接至 ETERNUS。"

#, python-format
msgid ""
"_find_pool, eternus_pool:%(eternus_pool)s, EnumerateInstances, cannot "
"connect to ETERNUS."
msgstr ""
"_find_pool，eternus_pool:%(eternus_pool)s，列舉實例，無法連接至 ETERNUS。"

#, python-format
msgid ""
"_get_drvcfg, filename: %(filename)s, tagname: %(tagname)s, data is None!! "
"Please edit driver configuration file and correct."
msgstr ""
"_get_drvcfg，檔名：%(filename)s，標記名稱：%(tagname)s，資料為「無」！請編輯"
"驅動程式配置檔並更正。"

#, python-format
msgid ""
"_get_eternus_connection, filename: %(filename)s, ip: %(ip)s, port: %(port)s, "
"user: %(user)s, passwd: ****, url: %(url)s, FAILED!!."
msgstr ""
"_get_eternus_connection，檔名：%(filename)s，IP：%(ip)s，埠：%(port)s，使用"
"者：%(user)s，密碼：****，URL：%(url)s，失敗！"

#, python-format
msgid ""
"_get_eternus_iscsi_properties, iscsiip list: %(iscsiip_list)s, iqn not found."
msgstr ""
"_get_eternus_iscsi_properties，ISCSI IP 清單：%(iscsiip_list)s，找不到 IQN。"

#, python-format
msgid ""
"_get_eternus_iscsi_properties, iscsiip: %(iscsiip)s, AssociatorNames: "
"CIM_BindsTo, cannot connect to ETERNUS."
msgstr ""
"_get_eternus_iscsi_properties，ISCSI IP：%(iscsiip)s，協助程式名稱："
"CIM_BindsTo，無法連接至 ETERNUS。"

#, python-format
msgid ""
"_get_eternus_iscsi_properties, iscsiip: %(iscsiip)s, EnumerateInstanceNames, "
"cannot connect to ETERNUS."
msgstr ""
"_get_eternus_iscsi_properties，ISCSI IP：%(iscsiip)s，列舉實例名稱，無法連接"
"至 ETERNUS。"

#, python-format
msgid ""
"_get_eternus_iscsi_properties, iscsiip: %(iscsiip)s, GetInstance, cannot "
"connect to ETERNUS."
msgstr ""
"_get_eternus_iscsi_properties，ISCSI IP：%(iscsiip)s，取得實例，無法連接至 "
"ETERNUS。"

#, python-format
msgid ""
"_get_hdr_dic: attribute headers and values do not match.\n"
" Headers: %(header)s\n"
" Values: %(row)s."
msgstr ""
"_get_hdr_dic：屬性標頭與值不相符。\n"
"標頭：%(header)s\n"
"值：%(row)s。"

msgid "_get_host_from_connector failed to return the host name for connector."
msgstr "_get_host_from_connector 無法傳回連接器的主機名稱。"

#, python-format
msgid ""
"_get_mapdata_fc, getting host-affinity from aglist/vol_instance failed, "
"affinitygroup: %(ag)s, ReferenceNames, cannot connect to ETERNUS."
msgstr ""
"_get_mapdata_fc，從 aglist/vol_instance 取得 host-affinity 失敗，親緣性群組："
"%(ag)s，參照名稱，無法連接至 ETERNUS。"

#, python-format
msgid ""
"_get_mapdata_fc, getting host-affinity instance failed, volmap: %(volmap)s, "
"GetInstance, cannot connect to ETERNUS."
msgstr ""
"_get_mapdata_fc，取得 host-affinity 實例失敗，磁區對映：%(volmap)s，取得實"
"例，無法連接至 ETERNUS。"

msgid ""
"_get_mapdata_iscsi, Associators: FUJITSU_SAPAvailableForElement, cannot "
"connect to ETERNUS."
msgstr ""
"_get_mapdata_iscsi，協助程式：FUJITSU_SAPAvailableForElement，無法連接至 "
"ETERNUS。"

#, python-format
msgid ""
"_get_mapdata_iscsi, affinitygroup: %(ag)s, ReferenceNames, cannot connect to "
"ETERNUS."
msgstr "_get_mapdata_iscsi，親緣性群組：%(ag)s，參照名稱，無法連接至 ETERNUS。"

#, python-format
msgid ""
"_get_mapdata_iscsi, vol_instance: %(vol_instance)s, ReferenceNames: "
"CIM_ProtocolControllerForUnit, cannot connect to ETERNUS."
msgstr ""
"_get_mapdata_iscsi，vol_instance：%(vol_instance)s，參照名稱："
"CIM_ProtocolControllerForUnit，無法連接至 ETERNUS。"

#, python-format
msgid ""
"_get_mapdata_iscsi, volmap: %(volmap)s, GetInstance, cannot connect to "
"ETERNUS."
msgstr ""
"_get_mapdata_iscsi，磁區對映：%(volmap)s，取得實例，無法連接至 ETERNUS。"

msgid "_get_target_port, EnumerateInstances, cannot connect to ETERNUS."
msgstr "_get_target_port，列舉實例，無法連接至 ETERNUS。"

#, python-format
msgid "_get_target_port, protcol: %(protocol)s, target_port not found."
msgstr "_get_target_port，通訊協定：%(protocol)s，找不到 target_port。"

#, python-format
msgid "_get_unmanaged_replay: Cannot find snapshot named %s"
msgstr "_get_unmanaged_replay：找不到名為 %s 的 Snapshot"

#, python-format
msgid "_get_unmanaged_replay: Cannot find volume id %s"
msgstr "_get_unmanaged_replay：找不到磁區 ID %s"

msgid "_get_unmanaged_replay: Must specify source-name."
msgstr "_get_unmanaged_replay：必須指定 source-name。"

msgid ""
"_get_vdisk_map_properties: Could not get FC connection information for the "
"host-volume connection. Is the host configured properly for FC connections?"
msgstr ""
"_get_vdisk_map_properties：無法取得主機-磁區連線的 FC 連線資訊。是否已針對 "
"FC 連線適當地配置主機？"

#, python-format
msgid ""
"_get_vdisk_map_properties: No node found in I/O group %(gid)s for volume "
"%(vol)s."
msgstr ""
"_get_vdisk_map_properties：在下列磁區的 I/O 群組 %(gid)s 中找不到節點："
"%(vol)s。"

#, python-format
msgid ""
"_map_lun, vol_instance.path:%(vol)s, volumename: %(volumename)s, volume_uid: "
"%(uid)s, initiator: %(initiator)s, target: %(tgt)s, aglist: %(aglist)s, "
"Storage Configuration Service not found."
msgstr ""
"_map_lun，vol_instance.path：%(vol)s，磁區名稱：%(volumename)s，volume_uid："
"%(uid)s，起始器：%(initiator)s，目標：%(tgt)s，親緣性群組清單：%(aglist)s，找"
"不到「儲存體配置服務」。"

#, python-format
msgid ""
"_unmap_lun, vol_instance.path: %(volume)s, volumename: %(volumename)s, "
"volume_uid: %(uid)s, aglist: %(aglist)s, Controller Configuration Service "
"not found."
msgstr ""
"_unmap_lun，vol_instance.path：%(volume)s，磁區名稱：%(volumename)s，"
"volume_uid：%(uid)s，親緣性群組清單：%(aglist)s，找不到「控制器配置服務」。"

#, python-format
msgid ""
"_unmap_lun, volumename: %(volumename)s, volume_uid: %(volume_uid)s, "
"AffinityGroup: %(ag)s, Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""
"_unmap_lun，磁區名稱：%(volumename)s，volume_uid：%(volume_uid)s，親緣性群"
"組：%(ag)s，回覆碼：%(rc)lu，錯誤：%(errordesc)s。"

#, python-format
msgid ""
"_unmap_lun,vol_instance.path: %(volume)s, AssociatorNames: "
"CIM_ProtocolControllerForUnit, cannot connect to ETERNUS."
msgstr ""
"_unmap_lun，vol_instance.path: %(volume)s，協助程式名稱："
"CIM_ProtocolControllerForUnit，無法連接至 ETERNUS。"

msgid "_update_volume_stats: Could not get storage pool data."
msgstr "_update_volume_stats：無法取得儲存區資料。"

#, python-format
msgid ""
"_wait_for_copy_complete, cpsession: %(cpsession)s, copysession state is "
"BROKEN."
msgstr ""
"_wait_for_copy_complete，cpsession：%(cpsession)s，copysession 狀態為 "
"BROKEN。"

#, python-format
msgid ""
"add_vdisk_copy failed: A copy of volume %s exists. Adding another copy would "
"exceed the limit of 2 copies."
msgstr ""
"add_vdisk_copy 失敗：存在磁區 %s 的副本。如果新增另一份副本，則將超過 2 份副"
"本的限制。"

msgid "add_vdisk_copy started without a vdisk copy in the expected pool."
msgstr "已開始 add_vdisk_copy，但預期儲存區中沒有 vdisk 副本。"

#, python-format
msgid "all_tenants must be a boolean, got '%s'."
msgstr "all_tenants 必須是布林值，但卻取得 '%s'。"

msgid "already created"
msgstr "已建立"

msgid "already_created"
msgstr "already_created"

#, python-format
msgid "attribute %s not lazy-loadable"
msgstr "屬性 %s 無法延遲載入"

#, python-format
msgid ""
"backup: %(vol_id)s failed to create device hardlink from %(vpath)s to "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"備份：%(vol_id)s 無法建立從 %(vpath)s 到%(bpath)s 的裝置固定鏈結。\n"
" 標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

#, python-format
msgid ""
"backup: %(vol_id)s failed to obtain backup success notification from "
"server.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"備份：%(vol_id)s 無法從伺服器取得備份成功通知。\n"
" 標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

#, python-format
msgid ""
"backup: %(vol_id)s failed to run dsmc due to invalid arguments on "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"備份：%(vol_id)s 無法執行 dsmc，因為%(bpath)s 的裝置固定鏈結。\n"
" 標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

#, python-format
msgid ""
"backup: %(vol_id)s failed to run dsmc on %(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"備份：%(vol_id)s 無法在 %(bpath)s 上執行 dsmc。\n"
" 標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

#, python-format
msgid "backup: %(vol_id)s failed. %(path)s is not a file."
msgstr "備份：%(vol_id)s 失敗。%(path)s 不是檔案。"

#, python-format
msgid ""
"backup: %(vol_id)s failed. %(path)s is unexpected file type. Block or "
"regular files supported, actual file mode is %(vol_mode)s."
msgstr ""
"備份：%(vol_id)s 失敗。%(path)s 為非預期的檔案類型。支援區塊或一般檔案，實際"
"檔案模式為 %(vol_mode)s。"

#, python-format
msgid ""
"backup: %(vol_id)s failed. Cannot obtain real path to volume at %(path)s."
msgstr "備份：%(vol_id)s 失敗。無法取得 %(path)s 處磁區的實際路徑。"

msgid "being attached by different mode"
msgstr "正在以不同的模式進行連接"

#, python-format
msgid "can't find lun-map, ig:%(ig)s vol:%(vol)s"
msgstr "找不到 lun-map，ig：%(ig)s 磁區：%(vol)s"

msgid "can't find the volume to extend"
msgstr "找不到要延伸的磁區"

msgid "can't handle both name and index in req"
msgstr "無法處理要求中的名稱及索引"

msgid "cannot understand JSON"
msgstr "無法理解 JSON"

msgid "cgsnapshot assigned"
msgstr "已指派 cgsnapshot"

msgid "cgsnapshot changed"
msgstr "已變更 cgsnapshot"

msgid "cgsnapshots assigned"
msgstr "已指派 cgsnapshot"

msgid "cgsnapshots changed"
msgstr "已變更 cgsnapshot"

msgid ""
"check_for_setup_error: Password or SSH private key is required for "
"authentication: set either san_password or san_private_key option."
msgstr ""
"check_for_setup_error：需要密碼或 SSH 私密金鑰以進行鑑別：請設定 "
"san_password 或 san_private_key 選項。"

msgid "check_for_setup_error: Unable to determine system id."
msgstr "check_for_setup_error：無法判定系統 ID。"

msgid "check_for_setup_error: Unable to determine system name."
msgstr "check_for_setup_error：無法判定系統名稱。"

msgid "check_hypermetro_exist error."
msgstr "check_hypermetro_exist 錯誤。"

#, python-format
msgid "clone depth exceeds limit of %s"
msgstr "複製深度超出了限制 (%s)"

msgid "consistencygroup assigned"
msgstr "已指派 consistencygroup"

msgid "consistencygroup changed"
msgstr "已變更 consistencygroup"

msgid "create_cloned_volume, Source Volume does not exist in ETERNUS."
msgstr "create_cloned_volume，ETERNUS 中不存在「來源磁區」。"

#, python-format
msgid ""
"create_cloned_volume, target volume instancename: %(volume_instancename)s, "
"Get Instance Failed."
msgstr ""
"create_cloned_volume，目標磁區實例名稱：%(volume_instancename)s，取得實例失"
"敗。"

#, python-format
msgid ""
"create_cloned_volume: source volume %(src_vol)s size is %(src_size)dGB and "
"doesn't fit in target volume %(tgt_vol)s of size %(tgt_size)dGB."
msgstr ""
"create_cloned_volume：來源磁區 %(src_vol)s 大小為 %(src_size)dGB，且不適合大"
"小為 %(tgt_size)dGB 的目標磁區 %(tgt_vol)s。"

msgid ""
"create_consistencygroup_from_src only supports a cgsnapshot source or a "
"consistency group source. Multiple sources cannot be used."
msgstr ""
"create_consistencygroup_from_src 僅支援一個 cgsnapshot 來源或一個一致性群組來"
"源。不能使用多個來源。"

#, python-format
msgid "create_copy: Source vdisk %(src)s (%(src_id)s) does not exist."
msgstr "create_copy：來源 vdisk %(src)s (%(src_id)s) 不存在。"

#, python-format
msgid "create_copy: Source vdisk %(src)s does not exist."
msgstr "create_copy：來源 vdisk %(src)s 不存在。"

msgid "create_host: Host name is not unicode or string."
msgstr "create_host：主機名稱不是 Unicode 或字串。"

msgid "create_host: No initiators or wwpns supplied."
msgstr "create_host：未提供任何起始器或 WWPN。"

msgid "create_hypermetro_pair error."
msgstr "create_hypermetro_pair 錯誤。"

#, python-format
msgid "create_snapshot, eternus_pool: %(eternus_pool)s, pool not found."
msgstr "create_snapshot，eternus_pool：%(eternus_pool)s，找不到儲存區。"

#, python-format
msgid ""
"create_snapshot, snapshotname: %(snapshotname)s, source volume name: "
"%(volumename)s, vol_instance.path: %(vol_instance)s, dest volume name: "
"%(d_volumename)s, pool: %(pool)s, Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""
"create_snapshot，Snapshot 名稱：%(snapshotname)s，來源磁區名稱："
"%(volumename)s，vol_instance.path：%(vol_instance)s，目的地磁區名稱："
"%(d_volumename)s，儲存區：%(pool)s，回覆碼：%(rc)lu，錯誤：%(errordesc)s。"

#, python-format
msgid ""
"create_snapshot, volumename: %(s_volumename)s, source volume not found on "
"ETERNUS."
msgstr ""
"create_snapshot，磁區名稱：%(s_volumename)s，在 ETERNUS 上找不到來源磁區。"

#, python-format
msgid ""
"create_snapshot, volumename: %(volumename)s, Replication Service not found."
msgstr "create_snapshot，磁區名稱：%(volumename)s，找不到「抄寫服務」。"

#, python-format
msgid ""
"create_snapshot: Volume status must be \"available\" or \"in-use\" for "
"snapshot. The invalid status is %s."
msgstr ""
"create_snapshot：Snapshot 的磁區狀態必須為「可用」或「使用中」。無效狀態為 "
"%s。"

msgid "create_snapshot: get source volume failed."
msgstr "create_snapshot：取得來源磁區時失敗。"

#, python-format
msgid ""
"create_volume, volume: %(volume)s, EnumerateInstances, cannot connect to "
"ETERNUS."
msgstr "create_volume，磁區：%(volume)s，列舉實例，無法連接至 ETERNUS。"

#, python-format
msgid ""
"create_volume, volume: %(volume)s, volumename: %(volumename)s, eternus_pool: "
"%(eternus_pool)s, Storage Configuration Service not found."
msgstr ""
"create_volume，磁區：%(volume)s，磁區名稱：%(volumename)s，eternus_pool："
"%(eternus_pool)s，找不到「儲存體配置服務」。"

#, python-format
msgid ""
"create_volume, volumename: %(volumename)s, poolname: %(eternus_pool)s, "
"Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""
"create_volume，磁區名稱：%(volumename)s，儲存區名稱：%(eternus_pool)s，回覆"
"碼：%(rc)lu，錯誤：%(errordesc)s。"

msgid "create_volume_from_snapshot, Source Volume does not exist in ETERNUS."
msgstr "create_volume_from_snapshot，ETERNUS 中不存在「來源磁區」。"

#, python-format
msgid ""
"create_volume_from_snapshot, target volume instancename: "
"%(volume_instancename)s, Get Instance Failed."
msgstr ""
"create_volume_from_snapshot，目標磁區實例名稱：%(volume_instancename)s，取得"
"實例失敗。"

#, python-format
msgid "create_volume_from_snapshot: Snapshot %(name)s does not exist."
msgstr "create_volume_from_snapshot：Snapshot %(name)s 不存在。"

#, python-format
msgid ""
"create_volume_from_snapshot: Snapshot status must be \"available\" for "
"creating volume. The invalid status is: %s."
msgstr ""
"create_volume_from_snapshot：Snapshot 狀態必須為「可用」，才能建立磁區。無效"
"的狀態為：%s。"

#, python-format
msgid ""
"delete: %(vol_id)s failed to run dsmc due to invalid arguments with stdout: "
"%(out)s\n"
" stderr: %(err)s"
msgstr ""
"刪除：%(vol_id)s 無法執行 dsmc，因為引數無效，標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

#, python-format
msgid ""
"delete: %(vol_id)s failed to run dsmc with stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"刪除：%(vol_id)s 無法執行 dsmc，標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

msgid "delete_hypermetro error."
msgstr "delete_hypermetro 錯誤。"

#, python-format
msgid "delete_initiator: %s ACL not found. Continuing."
msgstr "delete_initiator：找不到 %s。將繼續。"

msgid "delete_replication error."
msgstr "delete_replication 錯誤。"

#, python-format
msgid "deleting snapshot %(snapshot_name)s that has dependent volumes"
msgstr "正在刪除具有相依磁區的 Snapshot %(snapshot_name)s"

#, python-format
msgid "deleting volume %(volume_name)s that has snapshot"
msgstr "正在刪除具有 Snapshot 的磁區 %(volume_name)s"

msgid "do_setup: No configured nodes."
msgstr "do_setup：未配置節點。"

#, python-format
msgid ""
"error writing object to swift, MD5 of object in swift %(etag)s is not the "
"same as MD5 of object sent to swift %(md5)s"
msgstr ""
"將物件寫入 Swift 時發生錯誤，Swift 中物件的 MD5 %(etag)s，與傳送至 Swift 的物"
"件 MD5 %(md5)s 不同"

#, python-format
msgid "extend_volume, eternus_pool: %(eternus_pool)s, pool not found."
msgstr "extend_volume，eternus_pool：%(eternus_pool)s，找不到儲存區。"

#, python-format
msgid ""
"extend_volume, volume: %(volume)s, volumename: %(volumename)s, eternus_pool: "
"%(eternus_pool)s, Storage Configuration Service not found."
msgstr ""
"extend_volume，磁區：%(volume)s，磁區名稱：%(volumename)s，eternus_pool："
"%(eternus_pool)s，找不到「儲存體配置服務」。"

#, python-format
msgid ""
"extend_volume, volumename: %(volumename)s, Return code: %(rc)lu, Error: "
"%(errordesc)s, PoolType: %(pooltype)s."
msgstr ""
"extend_volume，磁區名稱：%(volumename)s，回覆碼：%(rc)lu，錯誤："
"%(errordesc)s，儲存區類型：%(pooltype)s。"

#, python-format
msgid "extend_volume, volumename: %(volumename)s, volume not found."
msgstr "extend_volume，磁區名稱：%(volumename)s，找不到磁區。"

msgid "fake"
msgstr "偽造"

msgid "fileno is not supported by SheepdogIOWrapper"
msgstr "SheepdogIOWrapper 不支援 fileno"

#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr "fmt = %(fmt)s 受 %(backing_file)s 支援"

#, python-format
msgid "fmt=%(fmt)s backed by:%(backing_file)s"
msgstr "fmt = %(fmt)s 受 %(backing_file)s 支援"

msgid "force delete"
msgstr "強制刪除"

msgid "get_hyper_domain_id error."
msgstr "get_hyper_domain_id 錯誤。"

msgid "get_hypermetro_by_id error."
msgstr "get_hypermetro_by_id 錯誤。"

#, python-format
msgid ""
"get_iscsi_params: Failed to get target IP for initiator %(ini)s, please "
"check config file."
msgstr "get_iscsi_params：無法取得起始器 %(ini)s 的目標 IP，請檢查配置檔。"

#, python-format
msgid "get_pool: Failed to get attributes for volume %s"
msgstr "get_pool：無法取得磁區 %s 的屬性"

msgid "glance_metadata changed"
msgstr "已變更 glance_metadata"

#, python-format
msgid ""
"gpfs_images_share_mode is set to copy_on_write, but %(vol)s and %(img)s "
"belong to different file systems."
msgstr ""
"gpfs_images_share_mode 已設為 copy_on_write，但 %(vol)s 及 %(img)s 屬於不同的"
"檔案系統。"

#, python-format
msgid ""
"gpfs_images_share_mode is set to copy_on_write, but %(vol)s and %(img)s "
"belong to different filesets."
msgstr ""
"gpfs_images_share_mode 已設為 copy_on_write，但 %(vol)s 及 %(img)s 屬於不同的"
"檔案集。"

msgid ""
"http service may have been abruptly disabled or put to maintenance state in "
"the middle of this operation."
msgstr "HTTP 服務可能已在執行此作業的中途意外停用或置於維護狀態。"

msgid "id cannot be None"
msgstr "ID 不能為 None"

#, python-format
msgid "image %s not found"
msgstr "找不到映像檔 %s"

#, python-format
msgid "initialize_connection, volume: %(volume)s, Volume not found."
msgstr "initialize_connection，磁區：%(volume)s，找不到「磁區」。"

#, python-format
msgid "initialize_connection: Failed to get attributes for volume %s."
msgstr "initialize_connection：無法取得磁區 %s 的屬性。"

#, python-format
msgid "initialize_connection: Missing volume attribute for volume %s."
msgstr "initialize_connection：遺漏磁區 %s 的磁區屬性。"

#, python-format
msgid ""
"initialize_connection: No node found in I/O group %(gid)s for volume %(vol)s."
msgstr ""
"initialize_connection：在磁區 %(vol)s 的 I/O 群組 %(gid)s 中找不到節點。"

#, python-format
msgid "initialize_connection: vdisk %s is not defined."
msgstr "initialize_connection：未定義 vdisk %s。"

#, python-format
msgid "invalid user '%s'"
msgstr "無效的使用者 '%s'"

#, python-format
msgid "iscsi portal, %s, not found"
msgstr "找不到 iSCSI 入口網站 %s"

#, python-format
msgid "key manager error: %(reason)s"
msgstr "金鑰管理程式錯誤：%(reason)s"

msgid "limit param must be an integer"
msgstr "限制參數必須是整數"

msgid "limit param must be positive"
msgstr "限制參數必須是正數"

msgid "manage_existing requires a 'name' key to identify an existing volume."
msgstr "manage_existing 需要 'name' 索引鍵來確認現有磁區。"

#, python-format
msgid ""
"manage_existing_snapshot: Error managing existing replay %(ss)s on volume "
"%(vol)s"
msgstr ""
"manage_existing_snapshot：管理磁區 %(vol)s 上的現有重播 %(ss)s 時發生錯誤"

#, python-format
msgid "mdiskgrp missing quotes %s"
msgstr "mdiskgrp 遺漏引用 %s"

#, python-format
msgid "mkfs failed on volume %(vol)s, error message was: %(err)s."
msgstr "mkfs 在磁區 %(vol)s 上執行時失敗，錯誤訊息為：%(err)s。"

msgid "mock"
msgstr "模擬"

#, python-format
msgid "multiple resources with name %s found by drbdmanage"
msgstr "DRBDmanage 找到多個資源具有名稱 %s"

#, python-format
msgid "multiple resources with snapshot ID %s found"
msgstr "找到多個資源具有 Snapshot ID %s"

msgid "name cannot be None"
msgstr "名稱不能為 None"

#, python-format
msgid "no snapshot with id %s found in drbdmanage"
msgstr "在 DRBDmanage 中找不到 ID 為 %s 的 Snapshot"

#, python-format
msgid "not exactly one snapshot with id %s"
msgstr "不止一個 Snapshot 具有 ID %s"

#, python-format
msgid "not exactly one volume with id %s"
msgstr "不止一個磁區具有 ID %s"

#, python-format
msgid "obj missing quotes %s"
msgstr "obj 遺漏引用 %s"

msgid "open_access_enabled is not off."
msgstr "未關閉 open_access_enabled。"

msgid "progress must be an integer percentage"
msgstr "進度必須是整數百分比"

#, python-format
msgid ""
"qemu-img %(minimum_version)s or later is required by this volume driver. "
"Current qemu-img version: %(current_version)s"
msgstr ""
"此磁區驅動程式需要 qemu-img %(minimum_version)s 或更高版本。現行 qemu-img 版"
"本：%(current_version)s"

#, python-format
msgid ""
"qemu-img is not installed and image is of type %s.  Only RAW images can be "
"used if qemu-img is not installed."
msgstr ""
"未安裝 qemu-img，且映像檔的類型是 %s。如果未安裝 qemu-img，則只能使用原始映像"
"檔。"

msgid ""
"qemu-img is not installed and the disk format is not specified.  Only RAW "
"images can be used if qemu-img is not installed."
msgstr ""
"未安裝 qemu-img，且未指定磁碟格式。如果未安裝qemu-img，則只能使用原始映像檔。"

msgid "rados and rbd python libraries not found"
msgstr "找不到 rados 及 rbd python 程式庫"

#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr "read_deleted 只能是 'no'、'yes' 或 'only' 其中之一，不能是 %r"

#, python-format
msgid "replication_failover failed. %s not found."
msgstr "replication_failover 失敗。找不到 %s。"

msgid "replication_failover failed. Backend not configured for failover"
msgstr "replication_failover 失敗。未配置後端以進行失效接手"

#, python-format
msgid ""
"restore: %(vol_id)s failed to run dsmc due to invalid arguments on "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"還原：%(vol_id)s 無法執行 dsmc，因為%(bpath)s 上的引數無效。\n"
" 標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

#, python-format
msgid ""
"restore: %(vol_id)s failed to run dsmc on %(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"還原：%(vol_id)s 無法在 %(bpath)s 上執行 dsmc。\n"
" 標準輸出：%(out)s\n"
" 標準錯誤：%(err)s"

#, python-format
msgid ""
"restore: %(vol_id)s failed.\n"
"stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"還原：%(vol_id)s 失敗。\n"
" 標準輸出：%(out)s\n"
"標準錯誤：%(err)s。"

msgid ""
"restore_backup aborted, actual object list does not match object list stored "
"in metadata."
msgstr "restore_backup 已中斷，實際物件清單與meta 資料中儲存的物件清單不相符。"

#, python-format
msgid "rtslib_fb is missing member %s: You may need a newer python-rtslib-fb."
msgstr "rtslib_fb 遺漏成員 %s：您可能需要更新的 python-rtslib-fb。"

msgid "san_ip must be set"
msgstr "必須設定 san_ip"

msgid ""
"san_login and/or san_password is not set for Datera driver in the cinder."
"conf. Set this information and start the cinder-volume service again."
msgstr ""
"未在 cinder.conf 中設定 Datera 驅動程式的 san_login 及/或 san_password。請設"
"定此資訊並重新啟動 cinder-volume 服務。"

msgid "serve() can only be called once"
msgstr "只能呼叫 serve() 一次"

#, python-format
msgid "snapshot-%s"
msgstr "snapshot-%s"

msgid "snapshots assigned"
msgstr "已指派 Snapshot"

msgid "snapshots changed"
msgstr "已變更 Snapshot"

msgid "source-name cannot be empty."
msgstr "source-name 不能是空的。"

msgid "source-name format should be: 'vmdk_path@vm_inventory_path'."
msgstr "source-name 格式應該是：'vmdk_path@vm_inventory_path'。"

#, python-format
msgid "status must be %s and"
msgstr " 狀態必須是 %s，並且"

msgid "status must be available"
msgstr "狀態必須可用"

msgid "stop_hypermetro error."
msgstr "stop_hypermetro 錯誤。"

msgid "sync_hypermetro error."
msgstr "sync_hypermetro 錯誤。"

#, python-format
msgid ""
"targetcli not installed and could not create default directory "
"(%(default_path)s): %(exc)s"
msgstr "targetcli 尚未安裝，無法建立預設目錄(%(default_path)s)：%(exc)s"

msgid "terminate_connection: Failed to get host name from connector."
msgstr "terminate_connection：無法從連接器取得主機名稱。"

msgid "too many body keys"
msgstr "主體金鑰太多"

#, python-format
msgid "unmanage_snapshot: Cannot find snapshot named %s"
msgstr "unmanage_snapshot：找不到名為 %s 的 Snapshot"

#, python-format
msgid "unmanage_snapshot: Cannot find volume id %s"
msgstr "unmanage_snapshot：找不到磁區 ID %s"

#, python-format
msgid "unrecognized argument %s"
msgstr "無法辨識的引數 %s"

#, python-format
msgid "unsupported compression algorithm: %s"
msgstr "不支援的壓縮演算法：%s"

msgid "valid iqn needed for show_target"
msgstr "show_target 需要有效的 IQN"

#, python-format
msgid "vdisk %s is not defined."
msgstr "未定義 vdisk %s。"

#, python-format
msgid "volume %s not found in drbdmanage"
msgstr "在 DRBDmanage 中找不到磁區 %s"

msgid "volume assigned"
msgstr "已指派磁區"

msgid "volume changed"
msgstr "已變更磁區"

#, python-format
msgid ""
"volume size %(volume_size)d is too small to restore backup of size %(size)d."
msgstr "磁區大小 %(volume_size)d 太小，無法還原大小為 %(size)d 的備份。"

#, python-format
msgid "volume size %d is invalid."
msgstr "磁區大小 %d 無效。"

msgid ""
"volume_type must be provided when creating a volume in a consistency group."
msgstr "在一致性群組中建立磁區時，必須提供volume_type。"

msgid "volume_type_id cannot be None"
msgstr "volume_type_id 不能為 None"

#, python-format
msgid "volume_types must be provided to create consistency group %(name)s."
msgstr "必須提供 volume_types，才能建立一致性群組 %(name)s。"

msgid "volumes assigned"
msgstr "已指派磁區"

msgid "volumes changed"
msgstr "已變更磁區"

#, python-format
msgid "wait_for_condition: %s timed out."
msgstr "wait_for_condition：%s 已逾時。"

#, python-format
msgid ""
"zfssa_manage_policy property needs to be set to 'strict' or 'loose'. Current "
"value is: %s."
msgstr "zfssa_manage_policy 內容需要設為 'strict' 或 'loose'。現行值為：%s。"
